### ISSUE TITLE
Parallelize cmorization part

### ISSUE THREAD

**Issue by goord** [EC-Earth/ece2cmor3#11]
Create a work queue for the cmorization of tasks (within each table to achieve good performance).

**Comment by goord** [comment]
Since multithreading appears not to speed up things (GIL I presume) we shall have to try multiprocess instead

**Comment by oloapinivad** [comment]
Hi @goord 
could you confirm that parallelization works only on IFS? I am not getting any speedup with multiple cores in NEMO cmorization. 
Thanks

**Comment by goord** [comment]
Yes, there is no multiprocessing for the NEMO part.
