### ISSUE TITLE
Is it possible to add the inverse tool of drq2ppt?

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#115]
This has been asked by Youmin Chen at the last EC-Earth meeting in Reading, and by mail:

We discussed that the "drq2ppt.py " can be used to generate the ppt* files for IFS within EC-EARTH. If for other purposes, the ppt files are given, would it possible to add a python script which can generate the varlist.json from the ppt* files?

**Comment by cym263** [comment]
Thank you, Thomas, for putting the question here! I am looking forward to the solution. //Youmin

**Comment by treerink** [comment]
Unfortunately it is rather complicated to make such a tool: a certain grib code can be used for several cmor variables or several grib codes are used in an expression for one cmor variable. The different used frequencies complicate it further. 

What you can do is having a look into the available list and search on the grib code of your interest to see where it plays a role. In the available file in the comment column the expression for each cmor variable is given.

The available file can be found at the EC-Earth wiki: [here](https://dev.ec-earth.org/projects/cmip6/wiki/Step_by_step_procedure_to_cmorize_EC-EARTH3_per_MIP) under "Update: Step 1 & 2 combined": **[available variables for m=all-ec-earth-mips-e=CMIP](https://docs.google.com/spreadsheets/d/1vGgX0BCCkIAqt1hPU4fwrWgMhehVfVj9jIcwPm_tGhE)** but this link may change.

So closing this issue by rejecting.

**Comment by goord** [comment]
Hi Youmin, another strategy may be to try to cmorize your target data request with whatever you have, the tool will report errors but should continue with whatever variables appear to be supported by your output.
