### ISSUE TITLE
On cca: ImportError: No module named gribapi

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#117]
Since the "Fixed missing import" commit this issue remains on cca (on other linux systems recreating the ece2cmor conda environment will do):
import gribapi
ImportError: No module named gribapi

**Comment by treerink** [comment]
Seems to be the same problem source:
https://dev.ec-earth.org/issues/242#change-5857

**Comment by goord** [comment]
tested on cca, working
