### ISSUE TITLE
Add "template new component" in ece2cmor3

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#163]
Currently ece2cmor3 contains two components:one for NEMO and one for IFS. A next step is to add a component for TM5 and for LPJ-GUESS. It would be convenient if a kind of template can be added to ece2cmor3 for a new component. This template can be based on the assumption that the files to be cmorized are netcdf files and contain cmor variable names (or maybe better: they contain table-cmor-var-name names, as actually the {table - cmor name}-combination is the unique variable description).

Is this feasible Gijs?

**Comment by treerink** [comment]
This template might be just a very clean and simple basic template as discussed in our telecon with the LPJ-GUESS group, just added in **comment** at a logical spot. It will be used for the new NEMO setup, for a new TM5 component and for a clean merge of what has been implemented for a LPJ-GUESS component already.

**Comment by tommibergman** [comment]
Also a list of subroutines that have model specific calls would be nice. Now it is hard to know where one needs to look and therefore addition of a new component easily becomes a trial and error process.

**Comment by treerink** [comment]
@tommibergman @goord you can extend the `how-to-add-a-new-model-component.txt`

**Comment by treerink** [comment]
As discussed: Script `generate-nemopar.json.sh` added to generate the "dummy" nemopar.json file for the new components and for the new coming nemo approach.

**Comment by treerink** [comment]
Issue #179 is solved, and the auto-grid-detection branch is merged into trunk. I.e. for NEMO the nemopar.json is a source-target list where both the source and the target are equal, and equal to the cmor variable name. We keep this list, because it tells ece2cmor3 which variables are available, for the current NEMO case one of both (the source or the target) is superfluous, however for IFS this is needed. In this way the code stays the same for all model components. The grid info is gone from the json file, it is automatically detected from the netcdf files.

During solving #179, the design has been simplified much in order to make it easier to add a new model component. In comment lines have been added marked by "NEWCOMPONENT" or with TM5 or LPJ-GUESS examples. So this makes the template as described/asked for in this issue.  

For other new components like TM5 and LPJ-GUESS the setup will match the case of NEMO quite closely. In #183 the lpjguesspar.json has been added.

So I think the master branch of ece2cmor3 is now ready to continue to add the other components
