### ISSUE TITLE
Replace grib_api by ece-codes in the master branch

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#166]
In the nocdo branch the grib_api has been replaced by ece-codes. However, now the merge of nocdo branch into trunk is not scheduled soon, it would be maybe feasible to implement this replacement in the master branch, so grib_api issues for instance on cca and on Mac OS X can be circumvented (see #117 and #152 - post 9). Or would ece-codes dependencies cause similar issues on those platforms?

**Comment by goord** [comment]
Hi Thomas this has been done right? I only see ec-codes in the environment.yml. Should we test on cca and close this issue?

**Comment by goord** [comment]
Tested on cca, it works.
