### ISSUE TITLE
Meaning of filter option?

### ISSUE THREAD

**Issue by klauswyser** [EC-Earth/ece2cmor3#171]
What's the meaning of the ``--filter`` option in ece2cmor3? The documentation isn't really helpful on that point.

Is ``--filter`` required when we have different 3 hourly and 6 hourly output in the same IFS output files? If so, what happens if ``--filter`` is set but the output in the 3-hourly and 6-hourly output is identical? And what if ``--filter`` is set but there is only 6-hourly output in the IFS output?

**Comment by goord** [comment]
Hi Klaus, the --filter option automatically splits the grib file before the post-processing, for each cmor variable it will create a grib file with the selected messages needed by ece2cmor. This is not necessary if you have a single time step: the cdo commands can then act all on the raw output  with the appropriate selection operator; so in that case you should be able to dismiss the --filter option. If you do include it anyway, ece2cmor3 will start splitting the file, it will give the same answer but I think it may take longer.

**Comment by klauswyser** [comment]
Thanks for the explanation, good to know. So it's safe to always use ``--filter`` but may it take longer time.
