### ISSUE TITLE
only-set-in-job-environment directory?

### ISSUE THREAD

**Issue by klauswyser** [EC-Earth/ece2cmor3#173]
What is the meaning of the only-set-in-job-environment directory?

I seem to have just one of these directories conating temporary(?) files. When I process several months in parallel they seem to all use the same only-set-in-job-environment directory and disturb each other.

**Comment by goord** [comment]
Yes this is a problem I expected, I will fix it asap

**Comment by klauswyser** [comment]
Could you create this directory in the tmp_dir instead? At least I use different tmp_dirs when running parallel jobs so they don't interfere with each other.

**Comment by goord** [comment]
Hi Klaus, now by default ece2cmor3 will create a directory /tmp/ece2cmor, if this does not exist already. Within this directory, ifs2cmor will create a directory ifs-YYYYMM, which is unique to all your jobs I presume, and contains all temporary files. The parent temp dir can be overridden by the eec2cmor command by specifying the --tempdir option. The changes have been committed in rev. 2b4075a2e85aa2961dcc321b1f800852f2a2f594

**Comment by klauswyser** [comment]
Wouldn't it be nice to also have the exp name in the name of the temp directory? It may happen that a user wants to process the same year from two different experiments at the same time, and in that case ifs-YYYYMM will be ambigous.

**Comment by goord** [comment]
Done in rev. 09a09fad2d8fd56da09cef61bd96c4ead35a5e4c
