### ISSUE TITLE
Issues with Mac OSX implementation

### ISSUE THREAD

**Issue by tommibergman** [EC-Earth/ece2cmor3#176]
Here we collect all the issues with using ece2cmor on Mac OSX. So far we know that check_vars works without problems.

**Comment by tommibergman** [comment]
CDO from anaconda does not include netcdf library due to problems in linking with extra options. See: https://github.com/conda-forge/cdo-feedstock/issues/15

**Comment by tommibergman** [comment]
CMOR.write fails on license validation in the CMOR library. I have made an issue on CMOR github:
https://github.com/PCMDI/cmor/issues/354

**Comment by tommibergman** [comment]
No gribapi on OSX see also #117

**Comment by tommibergman** [comment]
License validation error in OSX can be avoided by removing license keyword from CMIP6_CV.json. It is not a fix as you will need the license information in final files, but with this hack you can do development on OSX as well.

**Comment by treerink** [comment]
see further #203

closing this one.
