### ISSUE TITLE
Create basic XIOS file_def files which serve as a basis to generate the CMIP6 ones

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#177]
The goal is first to generate a basic template cmip6 file_def xml file which contains all field elements where each field element contains many attributes storing all the cmip6 data request data, the cmor - nemo code variable identification of the Shaconemo ping files and much of the attribute data from the four nemo field_def files (they can be either taken from the ec-earth3 repository or from the Shaconemo repository).

Secondly, a slightly more compact basic file_def xml is created from this basic template one, in which the fields are grouped on three selection criteria: the model component which produces the field, the output frequency and the grid. For each sub group which is not empty a file element definition will contain the concerned fields.

Third, as mentioned in #167  a `drq2file_def-nemo` script will, based on the CMIP6 data request (i.e. on drq), modify the masking by setting the enable attribute for each requested field to TRUE in the latter basic file_def files in order to generate the proper nemo XIOS file_def file for each CMIP6 MIP experiment. This script will be called by the  `generate-ec-earth-namelists.sh` script.

**Comment by klauswyser** [comment]
A good  strategy!

However, it's probably not enough that ``generate-ec-earth-namelists.sh`` only enables/disables output groups. Take for example a MIP (e.g. OMIP) that requests more variables from NEMO on the T-grid. Then ``generate-ec-earth-namelists.sh`` will somehow have to add these files to file_def.

**Comment by treerink** [comment]
All three tasks as described in this issue are implemented. Therefore closing this issue. For specific additional requests and for errors, please open specific issues.
