### ISSUE TITLE
Add Volume estimate for ec-earth available variables

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#180]
We will try to provide a Volume estimate per MIP experiment, for instance this could be estimated by `generate-ec-earth-namelists.sh`.  One way to make a realistic estimate is to measure the Volume of a single time slice of each spatial 2D grid by examining the output of a run. Then these numbers will simply be used for the 2D and 3D grids to calculate the total Volume per variable as we know the number of layers and the number of records. This method should be applicable to both NEMO and IFS output. (And probably for TM5 and LPJ-GUESS as well.)

Currently we have 15  grid definitions in the NEMO field_def files:
`````scripts
grid_T_2D            (grid_T_3D)  
grid_U_2D            (grid_U_3D)  
grid_V_2D            (grid_V_3D)  
grid_W_2D            (grid_W_3D)  

grid_ptr_T_3basin_2D (grid_ptr_W_3basin_3D)

grid_T_3D_ncatice

grid_T_SFC

grid_1point

grid_transect
grid_transect_lim
`````
The first four 2D grids seem the most important to have an estimate.

**Comment by treerink** [comment]
An estimate for a single NEMO-opa or NEMO-lim 2D field (one record) based on the netcdf output gives: 0.41M with an estimate marge of about 3% (0.012M). A rough upper limit is 0.43M.

**Comment by treerink** [comment]
An estimate for a single IFS SH (spectral harmonics grid) grib record (i.e. a single 2D field for one time step for one vertical layer) is 0.133 MB

An estimate for a single IFS GG (grid point grid) grib record (i.e. a single 2D field for one time step for one vertical layer) is 0.18 MB

**Comment by treerink** [comment]
An estimate for a single NEMO-ORA025 opa or NEMO-lim 2D field (one record) based on the netcdf output gives: 5.76M with an estimate marge of about 3%.

**Comment by treerink** [comment]
The IF & NEMO volume estimates are available now and combined in one `volume-estimate.txt` file, which is for each MIP experiment available in the sub directories with the control output files

**Comment by treerink** [comment]
For TM5 it would be nice to have a Volume estimate as well. In that case we have to add an additional script (because we don't have an `drq2tm5-config` script), which then also checks which TM5 variables of the data request are outputted in EC-Earth, and based on a data Volume of a single 2D data slice we detect based on the number of time records per year and the number of vertical layers for each variable, how large the total Volume for all TM5 variables is.

**Comment by treerink** [comment]
Should this also be done for LPJ-GUESS?

**Comment by treerink** [comment]
In 7cc3083acb97a22da58bf1826e33661265dee9d5 the `estimate-tm5-volume.py` script is added. From this script it would be easy to create also an lpj-guess variant.

@tommibergman The `estimate-tm5-volume.py` script needs still the correct basic data: a volume estimate of a single 2D layer (1 time step, 1 vertical layer), and I have to know the number of vertical layers if there are 3D fields (one vertical dimension or more?). No High  Res with TM5, right?

@nierad Do you want this for lpj-guess as well, then same questions for you for LPJ-GUESS.

**Comment by treerink** [comment]
The TM5 volume estimate is added to the `genecec` chain, and the TM5 numbers have now been inserted. So the TM5 part is solved.

**Comment by nierad** [comment]
Well our current output seems to be something 7-9 GB per simulated year in total, with each Experiment a subset of this.  If it is easy to create, let's do it. But LPJ-GUESS does have output with up to 4 dimensions (e.g. lat,lon, time, vegtype or lat,lon,time, landuse) which have different extents.

**Comment by treerink** [comment]
Hi Lars,

Can you provide the Volume size of 1 2D lon,lat slice of 1 layer for 1 time step  of LPJ-GUESS (In MB)?

Do you have one (lon,lat)- resolution for LPJ-GUESS output? Or low, standard and high resolution, or two of them?

How many layers have the  vegtype dimension?
How many layers have the  landuse dimension?

**Comment by nierad** [comment]
Hi Thomas, 
we currently have a standard and low res, T255 and  T159, which have 25799 and 10407 cells, respectively. I haven't done any cmorisation with the full grid, only singe gridcells, therefore I can't quite tell you the approximate size of a cmorised file yet. 
The dimensions have the lengths:
vegtype = 31
landuse = 4
sdepth = 2

**Comment by treerink** [comment]
The number of MB of one cell? One cell is one lon,lat point?

**Comment by tommibergman** [comment]
On TM5 10800 cells yield ~0.1 Mb.

**Comment by nierad** [comment]
Cmorised annual files including the 25799 cells for T255 have sizes like these:
lat lon, 12 months: between 0.2 and 1.5 MB * 
lat,lon,12 months, 2 depths: 2.9 MB

I think the above gives us an estimate of: 1.4 MB per "layer" for 12 monthly values on T255  + 0.1 MB overhead for dimensions and meta-data. Does that make sense?

* Many output types in LPJG contain lots of zeros, because the are non-zero only in areas where e.g. forest Harvest is applied. The maximum value (1.5MB) would be applicable for state variables. Furthermore, this changes with more complex landscape management in the future, i.e. files for 1850 will be smaller than for 1990, due to less homogenous grid-cells.  

I assume you want to estimate the amount of space needed for the storage of cmorized files.

**Comment by treerink** [comment]
Ok, so 1.4 MB for 12 monthly values, that makes **0.12 MB** per single 2D (lon,lat)-slice of 1 vertical layer for 1 time step of cmorized LPJ-GUESS data.

For the other model components the raw model output Volume and the cmorized Volume do not differ to much, for LPJ-GUESS I am not sure? If there is a difference of course users would be interested to know both numbers.

We estimate for non-compressed data, and we won't claim to be more precise than 20%, however the order of magnitude is what many users are quite interested in.

**Comment by nierad** [comment]
Well, I would have to look into a full set of data which we yet haven't produced. Can't we go with the maximum for now?

**Comment by treerink** [comment]
The script `estimate-lpj-guess-volume.py` is added, and produces an estimate for the T255 grid. The script is added to the `genecec` chain, so the numbers end up in the volume-estimate files.

So, closing this issue.
