### ISSUE TITLE
Add also the ppt0000000000 when generating ppt 

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#200]
As suggested by @aearamos in [#168 in this post](https://github.com/EC-Earth/ece2cmor3/issues/168#issuecomment-389908495), we can generate also the `ppt0000000000` automatically including the **land-sea mask** gib code 172.

**Comment by klauswyser** [comment]
Don't forget parameter 129 in ``ppt0000000000``

**Comment by treerink** [comment]
Done in 278388dc97161e79efcd9270dfa022f4723fe1c9

@klauswyser The Geopotential 129 should already always be in the pptdddddd0600 (see 7bf67fa), if not in 3D then it is added in 2D:
`````scripts
        # Always add the geopotential, recommended by ECMWF
        if cmor_source.grib_code(129) not in mfp3dfs:
            mfp2df.append(cmor_source.grib_code(129))
`````

Close.

**Comment by klauswyser** [comment]
We have to be careful and make sure that the geopotential of the surface (orography) is saved once in ppt0000000000, but the geopotential of the pressure levels is saved every 6 hours. Unfortunately the geopotential of the orography and of the pressure levels both have the same GRIB parameter, so having 129 in the pptdddddd00000 file doesn't mean we have the orography of the surface...

**Comment by treerink** [comment]
@klauswyser I don't fully understand it. 

Do you mean that in practice at any time 129 has to be added to MFPPHY in the ppt0000000000 file?

**Comment by klauswyser** [comment]
Let's put it from the other side: we need parameter 129 for the surface in ICMSH*+000000 and ICMGG*+000000. Do we get that with the present scripts?

**Comment by treerink** [comment]
The ppt0000000000 is now directly produced by drq2ppt. The 129 and 172 are always added in MFPPHY, and NFPPHY is now correctly highered by 2 for ppt0000000000 in 
525b575 and in 5d554f5.
