### ISSUE TITLE
Add version messages for cmor and data request versions.

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#201]
Add messages about the:

- cmor table version
- data request version the cmor tables are based on (see 1st line header resources/tables/CMIP6_*.json files)
- cmor library version (if there is a cmor table and/or dat request version dependency)
- data request version with:
`````scripts
drq -v
`````
or within python by
`````scripts
 from dreqPy import dreq
 dq = dreq.loadDreq()
`````

**Comment by goord** [comment]
rev. 7cc1d41cc8eeb6eee17e65ec55e7a84810fc3ff3
