### ISSUE TITLE
Work around for license validation error on Mac OSX for ece2cmor

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#203]
As mentions in [#176 in this post ](https://github.com/EC-Earth/ece2cmor3/issues/176#issuecomment-404201051) the license validation error in OSX can be avoided by removing license keyword from CMIP6_CV.json. It is not a fix as you will need the license information in final files, but with this hack you can do development on OSX as well.

The following will make it work:
`````scripts
cd ece2cmor3/resources/tables/;
sed -i '/"license":/,+2d' CMIP6_CV.json
`````

**Comment by tommibergman** [comment]
Now with the latest version of the tables (01.00.27) this is not an issue anymore. Even with the license keyword there is no error.
