### ISSUE TITLE
Providing a small LPJ-GUESS test data set for ece2cmor with a performance description

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#219]
A small LPJ-GUESS test dataset can be used by people which are unfamiliar with LPJ-GUESS cmorization to see whether everything works fine on their platform and it allows comparison with the performance description for this test data set.

A link to some test dataset would be nice.

Also for other model components this might be a good idea.

**Comment by treerink** [comment]
Did anyone already made this LPJ-GUESS test data set.

And if so, can we reach it? Some address?

**Comment by janitm** [comment]
I don't know the current status of it but @nierad is creating a test data set.

**Comment by nierad** [comment]
Hi all, I didn't do it yet. 
The question is, do we want ALL variables available or just representative subset? 
A 2-year full dataset would be about 3.8 GB and approximately a similar amount for the cmor-files.

Any thoughts?

**Comment by treerink** [comment]
@nierad Actually I think we need the full dataset so we undoubtedly can test the whole LPJ-GUESS component on every platform  and can compare if there are changes made. But in fact it would be nice to have in addition a small representative subset for quick and frequent tests. So Lars would both be possible?

**Comment by nierad** [comment]
Sure, the subset can be a couple of files with different format. The question remains: Where to put it?

**Comment by treerink** [comment]
If the small representative dataset is really small, say only a few MB, I think we can just add it here at the github. That would be really convenient to work with.

**Comment by nierad** [comment]
I will cut out a couple of gridcells for a couple of years from the overall output. That should not be much more than a few MB. Coming in a few days, when the last output-fixes have been applied.

**Comment by nierad** [comment]
Hi all, 
finally there is a test-dataset  available at 
http://stormbringer.nateko.lu.se/public/lars/ece2cmor3/LPJG_test_data.tgz
It contains data from 20 gridcells for all LPJG variables from 1855-1857.
The file det.out is currently NOT used, but we decided to keep it until the final data request is through. 
There are still 6 variables I haven't been able to test, as I haven't found the appropriate drq-xlsx file. 
Do we want all the cmor output-files I generated for comparison, too?

**Comment by treerink** [comment]
@nierad I think this data set needs an update after all the changes, right? If so, can you provide one once more, so we can close this issue?

**Comment by klauswyser** [comment]
Here is the output from 3 years of our historical simultation: http://exporter.nsc.liu.se/2346554bb6e441a6b12836824d0bc076 rsync://exporter.nsc.liu.se/2346554bb6e441a6b12836824d0bc076 Note that this dataset is not with the latest version of the model, nevertheless I hope it's still useful.

**Comment by treerink** [comment]
@nierad I guess you are now in the situation that providing such a minimal (or less minimal) dataset is easy?

**Comment by nierad** [comment]
@treerink: Indeed, we could simply use an existing years data for a subset of variables of - say - different timescale and type. 
I'd suggest to wait until #733 on the dev-portal is resolved.

**Comment by treerink** [comment]
@nierad  I understand from the CMIP6 telcon this morning that ec-earth portal issue 733 won't be fixed soon. Actually it doesn't matter much for the test dataset because this is about the field values. So I would suggest you can finish this issue with what you have now?

**Comment by nierad** [comment]
@treerink Yip, will do in the next days!

**Comment by nierad** [comment]
Here is a small test dataset of with data from the "deforestGlobal" experiment. 
It contains unmodified output from LPJ-GUESS for a set of variables with different dimensions and/or frequency. 
Please download from:
http://stormbringer.nateko.lu.se/public/lars/ECE/test-data-lpjg.tar.gz

**Comment by treerink** [comment]
In `ece2cmor3/ece2cmor3/resources/test-data-request/varlist-lpjg.json` I added some of the variables which are present in the lpjg test data set:
```
 mrsosLut_monthly.out
 baresoilFrac_monthly.out
 cLand_monthly.out
 mrsll_monthly.out
 fco2nat_monthly.out
 ```
Below a few variables which are in the lpjg test dataset but not in the varlist yet:
```
mrsos_monthly.out
fLulccAtmLut_monthly.out
tsl_daily.out
nwdFracLut_monthly.out
```

**Comment by treerink** [comment]
@goord you bring this lpjg test dataset under gitlfs?

**Comment by treerink** [comment]
The LPJ-GUESS dataset (~0.5 GB)  is now checked at:
```
ece2cmor3/test/test_data/lpjg/
```
