### ISSUE TITLE
Fix the ifsmon examples

### ISSUE THREAD

**Issue by goord** [EC-Earth/ece2cmor3#223]
See pull request #220 . Perhaps convert them to simple shell scripts.

**Comment by janitm** [comment]
Leaving a comment here as the pull request was already merged by the time I saw your comments. Those changes to ifsmon.py were from quite a time back from last March, namely they were present in the commit f0742b0 titled "ifsmon and cdoapi: changes to get it to run on my mac" by Peter. I haven't personally tested ifs data (nor did I have access to a mac), but anthoni-p would probably be able to consult with what the issues there were

**Comment by treerink** [comment]
@goord This was about some Travis test examples right? Are we going to do this, or just close it?

**Comment by goord** [comment]
After removing the examples folder you can close this issue, right now it only confuses people

**Comment by treerink** [comment]
Done, so closing.
