### ISSUE TITLE
IFS variables prhmax and mrfso

### ISSUE THREAD

**Issue by aearamos** [EC-Earth/ece2cmor3#227]
Hi everyone. 

I'm not sure if here is the right place to ask, but I'm having a hard time finding two ifs variables. For the DCPP runs we need prhmax (Daily Maximum Hourly Precipitation Rate) and mrfso (Soil Frozen Water Content) but I just can't find a way to produce them using the ifs output. 

Has anybody ever produced these two variables or know the right grib codes/equations that can produce them? 

Thanks in advance.

**Comment by etiennesky** [comment]
Hi @aearamos can you post here Emanuel Dutra's formula to compute mrfso ?

**Comment by etiennesky** [comment]
for prhmax I think we can approximate this with 228224/mxtpr6 (Maximum total precipitation rate in the last 6 hours) 

Description: The total precipitation is calculated from the combined large-scale and convective rainfall and snowfall rates every time step and the maximum is kept since the last 6 hours

Since the timestep is 45min, doing the daymax(mxtpr6) is close enough to "Daily Maximum Hourly Precipitation Rate", no?

**Comment by aearamos** [comment]
Here's the formula from Emanuel Dutra to calculate mrfso:
Assuming we have from the IFS output: swvl1,swvl2, swvl3, swvl4, (volumetric soil water layers)
stl1, stl2, stl3, stl4 (soil temperature layer): 

mrfso =0.07*swvl1*f(stl1)+ 0.21*swvl2*f(stl2)+ 0.72*swvl3*f(stl3)+ 1.89*swvl4*f(stl4)

Where f(temperature) is the function to diagnose the fraction of
frozen soil.

The value of f depends on some conditions, as seen here (look for ZF):
https://svn.ec-earth.org/ecearth3/tags/3.2.3/sources/ifs-36r4/src/surf/module/vsurf_mod.F90
and here (e.q 8.63):
https://www.ecmwf.int/sites/default/files/elibrary/2010/9233-part-iv-physical-processes.pdf

So, if we know f, then we should be able to calculate mrfso in the ifspar.json file. However, since f is not constant, how can we implement it? Is there a way to implement some conditions in the ifspar.json file? 

Thanks!

**Comment by goord** [comment]
If f can be written as a CDO expression of other grib codes you can compute with ece2cmor3. From the function above this seems possible, provided PTSAM1M is written to the grib files; is this array the soil layer temperature?

**Comment by goord** [comment]
The 228224 grib code is a good one, I will add it asap

**Comment by goord** [comment]
Ok then adding following lines to ifspar.json should do the job:
```
    {
        "source": "131.129",
        "target": "mrfso",
        "expr": "0.07*var39*((var139<=c2)+0.5*(var139<c1)*(1-sin(c4*(var139-c3)))) + 0.21*var40*((var170<=c2)+0.5*(var170<c1)*(1-sin(c4*(var170-c3)))) + 0.72*var41*((var183<=c2)+0.5*(var183<c1)*(1-sin(c4*(var183-c3)))) + 1.89*var42*((var236<=c2)+0.5*(var236<c1)*(1-sin(c4*(var236-c3))))",
        "masked": "land"
    },
```
where I replaced the RTF1,...,RTF4 with c1,...,c4 but you have to insert the numerical values in the expression above. Are you sure about the factor 0.5 though and shouldn't RTF3 be equal to RTF2 to make that expression continuous in temperature?

**Comment by aearamos** [comment]
From [https://github.com/EC-Earth/ece2cmor3/issues/227#issuecomment-418400830](url)

What's the best way to output 228.224 from IFS? I tried adding the 228224 to the ppt files, but it gave me an UNKNOWN CODE error. 

I also tried adding it straight to ifspar.json, when I got the grib_filter error, as expected. 

` ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 228.224, level type 1, level 0. Dismissing task prhmax in table Eday`

I considered the variable to be under 228, which is precipitation flux. So in my ifspar.json I have:

`   {
        "source": "228.224",
        "convert": "vol2flux",
        "target": "prhmax"
    },
`
So, despite being part of the grib code tables from ECMWF, not all variables can be outputed or are yet implemented. 

Is there a way to output it? Some part of the code that should be edited?

**Comment by etiennesky** [comment]
Hi @aearamos most grib codes are not implemented in IFS, these are with a few exceptions only in the ECMWF table (number 128, this number is dropped from the grib codes).  

For 228224 I don't think it would be easy to implement this, and it also isn't such an important variable.

You can cunsult the file sources/ifs-36r4/src/ifs/module/yom_grib_codes.F90 to check which grib codes are supported.

**Comment by aearamos** [comment]
Hi @goord and @treerink,
I ended up not being able to compute prhmax, but it's on the ignored list anyway. However, after some discussion with Etienne and Emanuel Dutra, I was able to compute mrfso with reasonable results. Following the equations discussed above in this issue, we came up with the following expression to compute mrfso:

{
        "source": "85.128",
        "target": "mrfso",
        "expr": "1000 * ( 0.07*var39 * ((var139 < 270.16)+0.5*(var139 < 274.16 && var139 > 270.16)*(1-sin(0.785*(var139-272.16)))) + 0.21*var40 * ((var170 < 270.16)+0.5*(var170 < 274.16 && var170 > 270.16)*(1-sin(0.785*(var170-272.16)))) + 0.72*var41 * ((var183 < 270.16)+0.5*(var183 < 274.16 && var183 > 270.16)*(1-sin(0.785*(var183-272.16)))) + 1.89*var42 * ((var236 < 270.16)+0.5*(var236 < 274.16 && var236 > 270.16)*(1-sin(0.785*(var236-272.16)))))",
        "masked": "land"
},

I believe some of the missing grib codes will have to be added to the drq, but this expression is working properly. 

This variable, if accepted, can move from "ignored" to "available".

Thanks.
Arthur.

**Comment by goord** [comment]
I added the variable to ifspar.json, @treerink can you remove it from the ignored variable list?

**Comment by treerink** [comment]
The variable `mrfso` is in 33566f84853bdac4f1991de621f1cce3a57d1d17 removed. Because the variable is available the ignored file won't be checked. The ignored list itself will be recreated soon, with the remake for data request 01.00.28.

So closing this issue.

**Comment by aearamos** [comment]
Hi @treerink.
I just noticed a typo in the expression for variable mrfso:

Instead of 
"expr": "1000*(0.07*var39*((var139<270.16)+0.5*(var139<274.16 && var139>270.16)*(1-sin(0.785*(var139-272.16)))) + 0.21*var40*((var170<270.16)+0.5*(var170<274.16 && var170>270.16)*(1-sin(0.785*(var170-272.16)))) + 0.72*var41*((var183<270.16)+0.5*(var183<274.16 && var183>270.16)*(1-sin(0.785*(var183-272.16)))) + 1.89*var42*((var236<270.16)+0.5(var236<274.16 && var236>270.16)*(1-sin(0.785*(var236-272.16)))))"

It should be

"1000*(0.07*var39*((var139<270.16)+0.5*(var139<274.16 && var139>270.16)*(1-sin(0.785*(var139-272.16)))) + 0.21*var40*((var170<270.16)+0.5*(var170<274.16 && var170>270.16)*(1-sin(0.785*(var170-272.16)))) + 0.72*var41*((var183<270.16)+0.5*(var183<274.16 && var183>270.16)*(1-sin(0.785*(var183-272.16)))) + 1.89*var42*((var236<270.16)+**0.5***(var236<274.16 && var236>270.16)*(1-sin(0.785*(var236-272.16)))))"

The error is in the multiplication of the last 0.5*... 

For that reason the variable was not being output, at least not for me. I got the following:
syntax error, unexpected '('!
cdo(3) expr (Abort): Syntax error!

**Comment by treerink** [comment]
Almost impossible to make no typo in such expression :)

**Comment by treerink** [comment]
Gijs you update this one?

**Comment by goord** [comment]
Sorry, fixed it in the most recent commit
