### ISSUE TITLE
drq2ppt.py fails with: AttributeError: 'lpjg_source' object has no attribute 'get_root_codes'

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#229]
Error messge after lpj-guess merge or/and later changes:
`````
  File "./drq2ppt.py", line 172, in <module>
    main()
  File "./drq2ppt.py", line 165, in main
    write_ppt_files(ece2cmorlib.tasks)
  File "./drq2ppt.py", line 55, in write_ppt_files
    root_codes = task.source.get_root_codes()
AttributeError: 'lpjg_source' object has no attribute 'get_root_codes'
`````
Maybe applies also to other scripts?

**Comment by treerink** [comment]
Seems to be related to changes in checkvars.py in cb2616e07ee6fda02481c5f513f67ae08939f58b, thus related to the merge with the lpj-guess branch and to #222 I guess.

**Comment by goord** [comment]
Rev. eb97521c7ab0686363b90865a67825ba5fb3ec44
