### ISSUE TITLE
Get rid of LFS

### ISSUE THREAD

**Issue by goord** [EC-Earth/ece2cmor3#234]
Git LFS will be out of bandwidth continuously making all tests fail, and I am not willing to pay for this service. We should put the test data on our own ftp server. @treerink perhaps KNMI can provide us some ftp server space? This would also very much help   to provide examples.

**Comment by treerink** [comment]
Settings -> Billings -> Purchase  more

Each pack costs $5 per month, and provides 50 GB of bandwidth and 50 GB for storage.

**Comment by plesager** [comment]
KNMI does not have persistent ftp server space, only a temporary one.

**Comment by etiennesky** [comment]
At BSC we are thinking about hosting the files required for the ece2cmor3 testing, what are the requirements and approx storage space required?

**Comment by treerink** [comment]
See also discussion in #219. In the end it would be good if there would be test data sets for the LPJ-GUESS, TM5, NEMO and IFS, so the cmorization can be tested on a new platform and by new ece2cmor3 users. The coverage of the tests is up to ourselves. I would say that it would be nice if we have at least quick and lightweight tests, they will need only small test data sets. Beside that we might want to add also more extensive tests with a larger coverage.

One NEMO output file typically is a few hundred MB, containing several variables.

**Comment by treerink** [comment]
The requirement is that everyone can download it. There is no sharing restriction I believe, so open policy. And it would be easy if groups can upload the test data sets, but in this case it concerns a few actions, so not a big deal if this has to be done in a less convenient way.

**Comment by etiennesky** [comment]
Here are the sizes of the output directories for a 1-yer run I did with the c-cycle branch

```
25.0 GiB /ifs
24.3 GiB /nemo
1.8 GiB /lpjg
54.5 MiB  /tm5                                                                                                                                                                                                                  
```

Since raw data for IFS can be quite large, would 2 months be enough? In the case of LPJG we need 1 year I think.

For IFS one month would take around 2GiB.  In this run 14 GiB of the nemo output are for PISCES , so if we keep only normal nemo output 1 month would be around 1GiB.

@treerink what do you mean by "quick and lightweight" tests? Less than a month? This would be much easier to handle.

**Comment by goord** [comment]
LFS behaves again as expected w.r.t. the automatic tests, so closing this issue
