### ISSUE TITLE
Error with clw variable

### ISSUE THREAD

**Issue by KristianJS** [EC-Earth/ece2cmor3#238]
Hi,
Currently the "clw" variable is given as being on "alevel" coordinates, which I believe is model levels? In my older version of ece2cmor3, it tries to process this file in the Amon table with

"cdo -O -f nc -P 4 setgridtype,regular -monmean -selzaxis,hybrid -selmon,4 -selcode,246"

and gives an error because it can't find the hybrid axes. I believe Paolo has tried with the latest version and gets a similar error where it fails to find any vertical levels.

Indeed, I don't believe this is wrong: cloud liquid water should be a single level field! If you just do "cdo selcode 246" on a generic (filtered) ICMGG file, you get a field with no vertical dimension whatsoever. What is going on here? If I remove the "alevel" bit from the clw entry in Amon table I get the correct looking file.

Is this an error in the CMIP table? Or is ece2cmor trying to interpolate the values to model levels and failing for some other reason?

PS: Similar issue with other variables also on "alevel" coordinate, but this was the only one I cared about...

**Comment by KristianJS** [comment]
Sorry, digging a little deeper, I believe I understand this now. Indeed, clw was intended to be output on model levels. But changes in the output made by CNR and us meant it was only output as a single level field instead (averaged over all model levels). That's why ece2cmor was unhappy!

If you agree this is what's going on please feel free to close the issue.

**Comment by goord** [comment]
Hi Kristian, the 3D/2D administration of the atmospheric fields in ece2cmor3 is based upon

https://confluence.ecmwf.int//display/OIFS/How+to+control+OpenIFS+output

If the output does not contain the right level type, ece2cmor3 will not process the variable.
BTW if you were thinking about total column liquid water, that is grib code 78, it is used for the variable "lwp"

**Comment by aearamos** [comment]
Hi, @KristianJS. What's the solution then? I had the same problem as you did and can't cmorize some of the variables with the "alevel" coordinate. Were you able to cmorize it? Thanks

**Comment by oloapinivad** [comment]
Hi all,

From my point of view, I guess there is no solution. If the hybrid levels have not been saved, it does not make sense to try to cmorize variables that would not fit the CV criteria.

**Comment by KristianJS** [comment]
Yes I agree, there is no solution. I didn't write out "clw" on model levels in the raw output, so ece2cmor can't cmor-ize it of course. 

Gijs, thanks for pointing out that! I realize now I was getting mixed up between these two things. Indeed, "clw" (128.246) was always a model level field, while it's "lwp" that is the integrated quantity. The file I was extracting and thought was "clw" was, in fact, grib code 228.246, i.e. U at 100m!

Funnily, by removing the "alevel" coordinate from the "clw" entry in Amon table, ece2cmor happily created a clw_Amon file with the right metadata, even though the field it extracted was in fact U100m. I don't know if that qualifies as a bug given that I tampered with the tables. But thought I would let you know.
