### ISSUE TITLE
Task output disappearing in first leg

### ISSUE THREAD

**Issue by goord** [EC-Earth/ece2cmor3#239]
For my PRIMAVERA stream 2 cmorization the first leg produces no 3D fields in the Amon table, and no errors are reported. However, when I run with only the problematic variables, everything goes fine. I suspect this is a manifestation of the absence of pressure levels in the initial state file, which mess up the timestamps produced by cdo.

**Comment by oloapinivad** [comment]
Hi Gijs, this is strange, my Amon data seems perfectly there. 
Perhaps there is a difference in the initial file?

**Comment by goord** [comment]
Fixed in rev. 5fede6b4237a38e5a7ac69f3dca001f381e19bc7
