### ISSUE TITLE
AMOC in nemo

### ISSUE THREAD

**Issue by aearamos** [EC-Earth/ece2cmor3#244]
Hi everyone,

I'm trying to output and cmorize some diagnostic variables in nemo, such as AMOC. I have discussed with some other colleagues about this variables but we have not yet reached a consensus on which nemo var to use. We do have some candidates, such as zomsflgo, which is defined as "Meridional Stream-Function: Global" and requires a specific basins.nc file and fluxes from other basins. 

Has anyone successfully outputed AMOC in nemo and can give a little help? 

Thank you.

**Comment by aearamos** [comment]
On this issue,  I have variable "zomsf_3bsn" from NEMO that I was trying to cmorize and match it to variable msftyz (Ocean Y Overturning Mass Streamfunction).

For this nemo variable, the coordinates are  "time_centered 3basin olevel nav_lat nav_lon", while for msftyz the dimensions are "latitude olevel basin time". I could do some post-processing with NCO to try to match the dimensions, but I'm still getting some errors. 

@goord can you confirm if it's possible to cmorize this variable or other variables with the "basin" dimension? I don't see this variable in the list of ignored or missing variables so I wanted to make sure. 

Thank you.

**Comment by goord** [comment]
It's not possible yet, I will have a look at it

**Comment by aearamos** [comment]
Thank you for letting me know.

**Comment by goord** [comment]
Can you confirm this basin dimension contains 3 values, corresponding to the atlantic_arctic_ocean, indian_pacific_ocean and global_ocean basins?

**Comment by aearamos** [comment]
According to my file, the order is Global, Atlantic and Indio-Pacific.

Here's the msftyz variable from my output:

`	float msftyz(time_counter, \3basin, olevel, y, x) ;
		msftyz:long_name = "Meridional Stream-Function : All basins" ;
		msftyz:units = "Sv" ;
		msftyz:online_operation = "average" ;
		msftyz:interval_operation = "2700 s" ;
		msftyz:interval_write = "1 month" ;
		msftyz:cell_methods = "time: mean (interval: 2700 s)" ;
		msftyz:_FillValue = 1.e+20f ;
		msftyz:missing_value = 1.e+20f ;
		msftyz:coordinates = "time_centered 3basin olevel nav_lat nav_lon" ;
`

And the basins are:
`float \3basin(\3basin) ;
		\3basin:name = "3basin" ;
		\3basin:long_name = "Sub-basin mask (1=Global 2=Atlantic 3=Indo-Pacific)" ;
		\3basin:units = "1" ;
`

The variable I'm calling in my xml nemo file is:
`<field enabled="True" field_ref="zomsf_3bsn" grid_ref="grid_ptr_W_3basin_3D" id="id_msftyz" name="msftyz">  </field>
`

**Comment by goord** [comment]
Ok, so they're not in the appropriate order but I hope the cmor library can transpose the data if we provide it with the correct axis values.

**Comment by aearamos** [comment]
Hi @goord, the code passed the first error I had before, but now I have the following error:

C Traceback:
! In function: cmor_axis
! 

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: Could not find all axes for this variable. 
! Check that all your axes name matches the ones found in 
! the table Omon. 
!
!
!!!!!!!!!!!!!!!!!!!!!!!!!

Traceback (most recent call last):
  File "./ece2cmor.py", line 114, in <module>
    main()
  File "./ece2cmor.py", line 104, in main
    ece2cmorlib.perform_nemo_tasks(args.datadir, args.exp, startdate, length)
  File "/gpfs/scratch/pr1eel00/pr1eel17/a1bs/auto-ecearth3/ece2cmor/ece2cmor3/ece2cmorlib.py", line 176, in perform_nemo_tasks
    nemo2cmor.execute(nemo_tasks)
  File "/gpfs/scratch/pr1eel00/pr1eel17/a1bs/auto-ecearth3/ece2cmor/ece2cmor3/nemo2cmor.py", line 93, in execute
    execute_netcdf_task(dataset, task)
  File "/gpfs/scratch/pr1eel00/pr1eel17/a1bs/auto-ecearth3/ece2cmor/ece2cmor3/nemo2cmor.py", line 132, in execute_netcdf_task
    varid = create_cmor_variable(task, dataset, axes)
  File "/gpfs/scratch/pr1eel00/pr1eel17/a1bs/auto-ecearth3/ece2cmor/ece2cmor3/nemo2cmor.py", line 180, in create_cmor_variable
    original_name=str(srcvar))
  File "/apps/PYTHON/2.7.14/INTEL/lib/python2.7/site-packages/CMOR-3.3.3-py2.7-linux-x86_64.egg/cmor/pywrapper.py", line 536, in variable
    missing_value, tolerance, positive, original_name, history, comment)
_cmor.CMORError: Problem with 'cmor.variable'. Please check the logfile (if defined).

I believe there's an inconsistency between the file I have and the axes in the CMIP tables because my file has an extra dimension, with longitude. Should I remove longitude before trying?

**Comment by goord** [comment]
I see. I think the zonal averaging should go in the xml averaging if possible...

**Comment by aearamos** [comment]
I'm sorry but what do you mean by zonal averaging? Some pre-processing before cmorization? Does the new fixes count for all the axes (lon, lat, basin, olevel, time)? 

 I tried adding "longitude" to the CMIP6_Omon table but it didn't work.

**Comment by goord** [comment]
I suspect that the streamfunction should only be defined as a function of latitude, and is independent of longitude. Can you post a picture of the values perhaps?

**Comment by aearamos** [comment]
For Longitude I have the axis, but the values are all 0 and for latitude I have values from ~ -90 to 90. If you want I can send you the output file, it's only 315kb.  
My dimensions are:
    dimensions:
	axis_nbounds = 2 ;
	x = 1 ;
	y = 292 ;
	depthw = 75 ;
	\3basin = 3 ;
	time_counter = UNLIMITED ; // (1 currently)

**Comment by goord** [comment]
Ok yes please send me the file, that will be more efficient. g.vandenoord@esciencecenter.nl is my address.

**Comment by goord** [comment]
BTW issue #46 is related to this, and I will try to fix that one too

**Comment by goord** [comment]
Encountered problems: msftyz has an unknown unit Sverdrup (added explicit unit converter in nemopar.json) and the latitude axis has the same 2 last values, which cmor does not like at all...

**Comment by aearamos** [comment]
The first problem can be fixed changing the field-def-opa.xml so the unit is kg s-1, just like the CMIP6_Omon.json table. I didn't know about the same 2 last values. It must be a property of this grid, I'm not sure either. I can change the values and see what happens.

**Comment by goord** [comment]
The latitude axis is tricky, I'm trying to fix it in ece2cmor3 but it is getting a bit hacky...

**Comment by etiennesky** [comment]
> The first problem can be fixed changing the field-def-opa.xml so the unit is kg s-1, just like the CMIP6_Omon.json table. I didn't know about the same 2 last values. It must be a property of this grid, I'm not sure either. I can change the values and see what happens.

If you change the units you might have to multiply the values, are you sure that 1Sv=kg s-1 ?

**Comment by aearamos** [comment]
> > The first problem can be fixed changing the field-def-opa.xml so the unit is kg s-1, just like the CMIP6_Omon.json table. I didn't know about the same 2 last values. It must be a property of this grid, I'm not sure either. I can change the values and see what happens.
> 
> If you change the units you might have to multiply the values, are you sure that 1Sv=kg s-1 ?

It's not. From the drq, they multiply this variable by 10⁶ and density of the water to get the right values in kg/s, so we would have to divide back to get the values in sv. So, the two are different and we should stick with the units from the drq.

**Comment by goord** [comment]
There is a factor 1e+9 between them

**Comment by aearamos** [comment]
I know. The file I sent you is in Sv I think, but that's because we were testing to make sure the values make sense in Sv. But my idea is to modify the field-def to output the values in kg/s, do the calculation in the file-def, and then match the units with the data request. After that, we can simply convert it to Sv if we need it.

**Comment by goord** [comment]
Hi @aearamos the basinaxis branch is ready for testing; it uses the factor 10^9 for converting from Sv to kg/s. This branch is also meant to fix the issue #46 if there are multiple ice categories so you can test as well if you like.

**Comment by aearamos** [comment]
Hi, @goord.
I was able to cmorize the variable. It took me some time because I was having problems with some python libraries from here. However, is it possible the last updates may have changed something with the IFS cmorization? I'm getting some errors such as:

ERROR:ece2cmor3.postproc:Could not retrieve pressure levels for rv850 with axes []
ERROR:ece2cmor3.cdoapi:(returncode:-11) cdo showltype: Started child process "selcode,130 /gpfs/scratch/pr1eel00/pr1eel17/a1bs/auto-ecearth3/ece2cmor/ece2cmor3/atm-fc0-199001/a1bs-ifs-199001-97K_HG/130.128.210.6 (pipe1.1)".
cdo(2) selcode: Processed 73423872 values from 1 variable over 124 timesteps [0.33s]
cdo showltype: Processed 1 variable [0.33s 489MB]

And this goes for other variables as well. 

Other error I get is

ERROR:ece2cmor3.cdoapi:(returncode:-11) cdo setgridtype: Started child process "monmean -selcode,205 /gpfs/scratch/pr1eel00/pr1eel17/a1bs/auto-ecearth3/ece2cmor/ece2cmor3/atm-fc0-199001/a1bs-ifs-199001-97K_HG/205.128.1.6 (pipe1.1)".
cdo(2) monmean: Started child process "selcode,205 /gpfs/scratch/pr1eel00/pr1eel17/a1bs/auto-ecearth3/ece2cmor/ece2cmor3/atm-fc0-199001/a1bs-ifs-199001-97K_HG/205.128.1.6 (pipe2.1)".
cdo(3) selcode: Processed 10927074 values from 1 variable over 123 timesteps [0.08s]
cdo(2) monmean: Processed 10927074 values from 1 variable over 123 timesteps [0.08s]

ERROR:ece2cmor3.postproc:Task prc in table Amon has not produced any output... setting it to failed status.

The script says it completed the cmorization, but there are no files in my output folder. 

The Ocean variables are fine.

**Comment by goord** [comment]
Ehm... the basinaxis branch is the latest and I didn't touch ifs2cmor in there, so the error you see should occur in the most recent main branch revision as well...

**Comment by goord** [comment]
Hi @aearamos I succeeded to do the rv850 cmorization on my laptop with the latest master branch, so can you send me the full output of ece2cmor?

**Comment by aearamos** [comment]
Hi, @goord.

From what I saw, I'm able to generate the files in their right frequencies and have them in an intermediate folder, but the next step, where they should be renamed and moved to my output folder, it's still not happening. I'm not sure if it's a problem with our workflow or with ece2cmor. Here's my output from my last atmospheric cmorization. 
Again, the ocean part works fine. 
[cmor_atm_output.txt](https://github.com/EC-Earth/ece2cmor3/files/2437339/cmor_atm_output.txt)

**Comment by goord** [comment]
This is very awkward... do you see the cdo-generated netcdf files in the temp directory?

**Comment by aearamos** [comment]
Yes. I see them. Some netcdfs and some are just the codes, such as in:

32.128.1.6
33.128.1_141.128.1.6
42.128.111_41.128.111_40.128.111_39.128.111.6
albsn_Emon.nc
clt_Amon.nc
clt_day.nc

I have these and many others. Apparently postprocessing is not able to find the axis information. I'm rechecking my workflow to make sure it's not something missing on my side.

**Comment by goord** [comment]
This is a bit disturbing that we're stuck with an old CDO version...
Can you check whether your ice categories also work, so I can close #46  too?

**Comment by aearamos** [comment]
It is. And I don't know why it happened, since I've been using the same version over the last weeks and now I had to change. About #46, I believe I need those ICE variables for piControl, I'm not sure. I'll try them and update the issue. I believe you can close this one here.
