### ISSUE TITLE
missing last November records in 3hrs fluxes files

### ISSUE THREAD

**Issue by oloapinivad** [EC-Earth/ece2cmor3#245]
Hi,

I am investigating this, not sure if it is a problem from ece2cmor3 or EC-Earth.

In all the November month I found out that the last record of 3hr pr files is not stored: this is evident also from the filename itself, stating 1800 instead of 2100.

````
pr_3hr_EC-Earth3P_Primavera-atm_r1i1p1f1_gr_195011010000-195011301800.nc
pr_3hr_EC-Earth3P_Primavera-atm_r1i1p1f1_gr_195111010000-195111301800.nc
pr_3hr_EC-Earth3P_Primavera-atm_r1i1p1f1_gr_195211010000-195211301800.nc
pr_3hr_EC-Earth3P_Primavera-atm_r1i1p1f1_gr_195311010000-195311301800.nc
pr_3hr_EC-Earth3P_Primavera-atm_r1i1p1f1_gr_195411010000-195411301800.nc
pr_3hr_EC-Earth3P_Primavera-atm_r1i1p1f1_gr_195511010000-195511301800.nc
pr_3hr_EC-Earth3P_Primavera-atm_r1i1p1f1_gr_195611010000-195611301800.nc
pr_3hr_EC-Earth3P_Primavera-atm_r1i1p1f1_gr_195711010000-195711301800.nc
pr_3hr_EC-Earth3P_Primavera-atm_r1i1p1f1_gr_195811010000-195811301800.nc
pr_3hr_EC-Earth3P_Primavera-atm_r1i1p1f1_gr_195911010000-195911301800.nc
pr_3hr_EC-Earth3P_Primavera-atm_r1i1p1f1_gr_196011010000-196011301800.nc

````

ece2cmor3 does not print any error in the logfile (at least nothing that I can spot). The incomplete file is produced even if the most recent commit and even if I re-run the code several times. Data validation by Jon Seddon does not identify this missing record since there is no inconsistency in the time axis. However, after concatenation I found out using the validation scripts that ALL the 3hr fluxes are missing, which is a strange coincidence. 

The error is already there after the filtering, since file '143.128.1.3' does show only 239 records (i.e. the 21:00:00 of 30-nov-1950 is not there). Actually, plenty of files shows only 239 records. 

I am trying to double check the properties of the original file - my grib_ls is broke - which may have been compromised (even if it looks identical in size for November month and any other month).

More asap.
Cheers,
P

**Comment by oloapinivad** [comment]
Using the conda environment I was able to inspect the November ICMGG file.

````
(ece2cmor3) [pdavini0@r000u07l02 IFS]$  grib_ls -w,dataDate=19501130,paramId=143 -p dataDate,dataTime,paramId,levelType,level ICMGGdet4+195011
ICMGGdet4+195011
dataDate    dataTime    paramId     levelType   level       
19501130    0           143         sfc         0          
19501130    300         143         sfc         0          
19501130    600         143         sfc         0          
19501130    900         143         sfc         0          
19501130    1200        143         sfc         0          
19501130    1500        143         sfc         0          
19501130    1800        143         sfc         0          
19501130    2100        143         sfc         0          
8 of 25560 messages in ICMGGdet4+195011
`````
2100 is there. Which means at first sight that the original file is correct.

A further inspections shows that also the instantaneous field has something compromised, i.e. 2100 seems to be not there. 

Does anybody can see the same behavior in its data?
Could it be that some unlucky reasons the filtering is forgetting this file in November month only?

Cheers,
P

**Comment by goord** [comment]
Hi Paolo, this is probably a bug in the filtering. The filtering shifts fluxes by one time step and I believe I made a modulo error there. The last time step in December will probably be incorrect as well... I will fix it tomorrow morning. Thanks for the research work

**Comment by goord** [comment]
I had a look at the filtering code and indeed the problem was incorrect module arithmetic, causing only fluxes at the last timestep in november to be skipped. Can you please test with the fix in rev. 80232e67690aececd91ac6c507a02b54f31a8e06

**Comment by klauswyser** [comment]
Has this bug in the filter been there all the time? In particular has it been there when processing the PRIMAVERA results? If so it's very bad news for all daily averages of fluxes that involve solar radiation. Solar radiation has a strong diurnal cycle, and removing one of the points when computing the daily average has a large impact. This should be noted somewhere so users of the data are aware of the problem.

**Comment by oloapinivad** [comment]
Hi Gijs,

thanks a lot. The machine on which we are running is offline up to this evening. 
Not sure if this is related, but I noticed a strange behavior also in this file
```
ua4_Prim6hr_EC-Earth3P_Primavera-atm_r1i1p1f1_gr_195001010000-195001311200.nc

``` 
1800 is missing. Only January 1950 here. Also if I rerun the missing record is still here.

**Comment by goord** [comment]
Hi Klaus, the issue is in the automatic filtering, which to my knowledge has not been used for the stream 1 runs (because it wasn't developed yet). In any case, we should be aware that the version we are using now has many new features and issues like this might pop up, so don't throw away your raw model output just yet...

I will have to redo the fluxes for november for my stream 2 cmorization of course.

**Comment by goord** [comment]
Hi @oloapinivad the issue you mention there is due to pressure levels missing in the first year of the simulation. This is actually a very serious bug because it shifts all January pressure level output in the first year of the run. See issue #240, where I propose a poor man's fix by inserting missing values as the initial state. I am going to fix fix this tomorrow.

**Comment by goord** [comment]
Klaus reported this problem on the EC-Earth portal as well. For the stream1 cmorization I had to manually 'fix' the initial state file by interpolating from model levels to pressure levels, just to get a grib record for these variables.

**Comment by oloapinivad** [comment]
Hi @goord actually the fix works with both November files and with the weird January 1950 for ua4 (Primavera table). Great!

I will run further tests using the Jon Seddon validation, I will let you know in case of any issues.
