### ISSUE TITLE
wrong January record in 6hrPlevPt files

### ISSUE THREAD

**Issue by oloapinivad** [EC-Earth/ece2cmor3#246]
Hi,

 I am still getting incomplete files for January 1950 for table 6hrPlevPt for variable mrsos and hus.
First time step is missing.

`````
mrsos_6hrPlevPt_EC-Earth3P_Primavera-atm_r1i1p1f1_gr_195001010600-195001010000.nc
mrsos_6hrPlevPt_EC-Earth3P_Primavera-atm_r1i1p1f1_gr_195007010000-195007311800.nc
mrsos_6hrPlevPt_EC-Earth3P_Primavera-atm_r1i1p1f1_gr_195002010000-195002281800.nc  mrsos_6hrPlevPt_EC-Earth3P_Primavera-atm_r1i1p1f1_gr_195008010000-195008311800.nc
mrsos_6hrPlevPt_EC-Earth3P_Primavera-atm_r1i1p1f1_gr_195003010000-195003311800.nc  mrsos_6hrPlevPt_EC-Earth3P_Primavera-atm_r1i1p1f1_gr_195009010000-195009301800.nc
mrsos_6hrPlevPt_EC-Earth3P_Primavera-atm_r1i1p1f1_gr_195004010000-195004301800.nc  mrsos_6hrPlevPt_EC-Earth3P_Primavera-atm_r1i1p1f1_gr_195010010000-195010311800.nc
mrsos_6hrPlevPt_EC-Earth3P_Primavera-atm_r1i1p1f1_gr_195005010000-195005311800.nc  mrsos_6hrPlevPt_EC-Earth3P_Primavera-atm_r1i1p1f1_gr_195011010000-195011301800.nc
mrsos_6hrPlevPt_EC-Earth3P_Primavera-atm_r1i1p1f1_gr_195006010000-195006301800.nc  mrsos_6hrPlevPt_EC-Earth3P_Primavera-atm_r1i1p1f1_gr_195012010000-195012311800.nc
``````

I was able to spot it from operating concatenation

````
ncrcat: WARNING Intra-file non-monotonicity. Record coordinate "time" does not monotonically increase between 
(input file /marconi_scratch/userexternal/pdavini0/ece3/det4/cmorized/Year_1950/CMIP6/PRIMAVERA/EC-Earth-Consortium/EC-Earth3P/Primavera-atm/r1i1p1f1/6hrPlevPt/hus/gr/v20180918/hus_6hrPlevPt_EC-Earth3P_Primavera-atm_r1i1p1f1_gr_195001010600-195001010000.nc record indices: 122, 123) 
(output file /marconi_scratch/userexternal/pdavini0/ece3/det4/cmorized/Year_1950_NCO/hus_6hrPlevPt_EC-Earth3P_Primavera-atm_r1i1p1f1_gr_195001010600-195012311800.nc record indices 122, 123) record coordinate values 30.750000, 0.000000
`````

BTW, @klauswyser I am quite sure that the issues with time axis I was getting with ncrcat were related to this and to the November bug of #245 
More asap.

**Comment by goord** [comment]
Hi Arthur, it's no coincidence this occurs in the 6hrPlevPt table; its time axis was created using some variable on pressure levels which are missing in the initial state and therefore starts at 6 o'clock. I will fix this issue (#240) today. I do however not understand the second date in the file name: 1950-01-01 00:00.

BTW do you agree to insert missing values in the first time step for variables on pressure levels if they are not in the ICM*+000000 files?

**Comment by goord** [comment]
BTW I see you are using ncrcat now, does it preserve the metadata? I know we have seen some quite different outcomes of different cdo versions which is a bit awkward...

**Comment by oloapinivad** [comment]
Hi Gijs,

The reason of the wrong naming is connected to the fact that ece2cmor3 is putting the first time step **at the end of the file**. Look here:

[pdavini0@r000u06l01 v20180918]$ cdo sinfo hus_6hrPlevPt_EC-Earth3P_Primavera-atm_r1i1p1f1_gr_195001010600-195001010000.nc
   File format : NetCDF4 classic ZIP
    -1 : Institut Source   Steptype Levels Num    Points Num Dtype : Parameter ID
     1 : unknown  EC-Earth3P instant       7   1    131072   1  F32z : -1            
   Grid coordinates :
     1 : curvilinear              : points=131072 (512x256)
                        longitude : 0.3515625 to 359.6484 by 0.703125 degrees_east  circular
                         latitude : -89.46282 to 89.46282 by 0.7016692 degrees_east
                        available : cellbounds
                          mapping : undefined
                                i : 1 to 512 by 1 1
                                j : 1 to 256 by 1 1
   Vertical coordinates :
     1 : pressure                 : levels=7
                             plev : 92500 to 5000 Pa
   Time coordinate :  124 steps
     RefTime =  1950-01-01 00:00:00  Units = days  Calendar = proleptic_gregorian
  YYYY-MM-DD hh:mm:ss  YYYY-MM-DD hh:mm:ss  YYYY-MM-DD hh:mm:ss  YYYY-MM-DD hh:mm:ss
  1950-01-01 06:00:00  1950-01-01 12:00:00  1950-01-01 18:00:00  1950-01-02 00:00:00
  1950-01-02 06:00:00  1950-01-02 12:00:00  1950-01-02 18:00:00  1950-01-03 00:00:00
  1950-01-03 06:00:00  1950-01-03 12:00:00  1950-01-03 18:00:00  1950-01-04 00:00:00
  1950-01-04 06:00:00  1950-01-04 12:00:00  1950-01-04 18:00:00  1950-01-05 00:00:00
...
  1950-01-29 06:00:00  1950-01-29 12:00:00  1950-01-29 18:00:00  1950-01-30 00:00:00
  1950-01-30 06:00:00  1950-01-30 12:00:00  1950-01-30 18:00:00  1950-01-31 00:00:00
  1950-01-31 06:00:00  1950-01-31 12:00:00  1950-01-31 18:00:00  1950-01-01 00:00:00
cdo sinfo: Processed 1 variable over 124 timesteps ( 0.11s )
`````

Also, I have records for hus (code 133) in my initial files, BUT on **TWO** different vertical axis (frankly I don't know why, I will investigate, perhaps a mistake in the way it is code the ppt00000000). I guess that the 2 axis are putting in trouble the autofilter.

````
[pdavini0@r000u06l01 IFS]$ cdo sinfo -selcode,133 ICMGGdet4+194912 
cdo sinfo: Started child process "selcode,133 ICMGGdet4+194912 (pipe1.1)".
   File format : GRIB
    -1 : Institut Source   Steptype Levels Num    Points Num Dtype : Parameter ID
     1 : ECMWF    unknown  instant      44   1     88838   1  P16  : 133.128       
     2 : ECMWF    unknown  instant      91   2     88838   1  P16  : 133.128       
   Grid coordinates :
     1 : gaussian reduced         : points=88838  nlat=256  np=128
                              lat : 89.46282 to -89.46282 degrees_north
   Vertical coordinates :
     1 : pressure                 : levels=44
                             plev : 100000 to 40 Pa
     2 : hybrid                   : levels=91
                              lev : 1 to 91 by 1 level
                        available : vct
   Time coordinate :  1 step
     RefTime =  1950-01-01 00:00:00  Units = hours  Calendar = proleptic_gregorian
  YYYY-MM-DD hh:mm:ss  YYYY-MM-DD hh:mm:ss  YYYY-MM-DD hh:mm:ss  YYYY-MM-DD hh:mm:ss
  1950-01-01 00:00:00

````

However, for mrsos is more strange because everything seems fine.

````
[pdavini0@r000u06l01 IFS]$ cdo sinfo -selcode,39,40 ICMGGdet4+194912 
cdo sinfo: Started child process "selcode,39,40 ICMGGdet4+194912 (pipe1.1)".
   File format : GRIB
    -1 : Institut Source   Steptype Levels Num    Points Num Dtype : Parameter ID
     1 : ECMWF    unknown  instant       1   1     88838   1  P16  : 39.128        
     2 : ECMWF    unknown  instant       1   2     88838   1  P16  : 40.128        
   Grid coordinates :
     1 : gaussian reduced         : points=88838  nlat=256  np=128
                              lat : 89.46282 to -89.46282 degrees_north
   Vertical coordinates :
     1 : depth_below_land         : levels=1
                            depth : 3.5 cm
                           bounds : 0-7 cm
     2 : depth_below_land         : levels=1
                            depth : 17.5 cm
                           bounds : 7-28 cm
   Time coordinate :  1 step
     RefTime =  1950-01-01 00:00:00  Units = hours  Calendar = proleptic_gregorian
  YYYY-MM-DD hh:mm:ss  YYYY-MM-DD hh:mm:ss  YYYY-MM-DD hh:mm:ss  YYYY-MM-DD hh:mm:ss
  1950-01-01 00:00:00
cdo(2) selcode: Processed 177676 values from 91 variables over 1 timestep ( 0.06s )
cdo sinfo: Processed 2 variables over 1 timestep ( 0.06s )
````

I will have a loot at the metadata, perhaps opening a different issue

**Comment by goord** [comment]
Hi Paolo, you apparently do have pressure levels in your initial state file for hus?

mrsos depends only on surface fields so that is no problem, but the cmor time axis is created per table, and eec2cmor3 uses an arbitrary variable for this in that table, assuming all variables have the same time stamps. This goes wrong when pressure level fields are missing somewhere.

You may investigate the filtered output for the pressure level fields in the 6hrPlev table (ua, va, zg, hus); also ece2cmor3 will print somewhere
```
creating time axis using variable ...
```
which points to the post-processed nc file that is read to create the time stamps.

**Comment by oloapinivad** [comment]
Hi Gijs,

so I have ua7h used for this

````
INFO:ece2cmor3.ifs2cmor:Post-processed batch of 17 tasks.
INFO:ece2cmor3.ifs2cmor:Cmorizing 16 IFS tasks...
INFO:ece2cmor3.ifs2cmor:Cmorizing source variable 131 to target variable ua7h...
INFO:ece2cmor3.ifs2cmor:Loading CMOR table 6hrPlevPt...
INFO:ece2cmor3.ifs2cmor:Creating time axis using variable ua7h...
INFO:ece2cmor3.ifs2cmor:Cmorizing source variable 138 to target variable vortmean...
INFO:ece2cmor3.ifs2cmor:Loading CMOR table 6hrPlevPt...
````

But actually you are right, I am missing in my initial file all the pressure levels for ta, ua and va. Only hybrid levels, as mentioned in #240. 

Considering this, I agree that setting missing values is the only approach! The only strange part is that ta,va,ua are correctly set (i.e. starting from 0600, e.g. file is ua_6hrPlevPt_EC-Earth3P_Primavera-atm_r1i1p1f1_gr_195001010600-195001311800.nc) but this is not happening for the others (where the data are available).

**Comment by goord** [comment]
If ece2cmor3 uses an 'incomplete' variable to define the time axis, all incomplete variables which are processed using that axis will be fine, that is they will miss requested time stamps but that is it. Variables which are 'complete' however (e.g. you mrsol) will be (a) shifted backwards and (b) stream too much data to the cmor library at the end of the month.

Now instead of complaining about this, the cmor library decides to happily create a new time stamp; an incorrect one because it appears to be the beginning of the month. I can't tell you why that is, this is cmor internal behavior, but we can and should make sure we always check whether the time stamps that we read correspond to the ones in the time axis.

If we do that we may encounter that there are not enough time slices, in which case we should insert missing values, or there are too many, which case we should ignore (!) time slices. I propose to attempt to make sure the latter never happens by constructing the time axis from the fields we 'expect' to be complete (surface or model level fields).

But this is not so easy that I can do it in an hour or so, I expect it to be ready by tomorrow.

**Comment by oloapinivad** [comment]
I understand, thanks a lot for the explanation. Would it be possible to create time axis independently for every variable? This will be clearly slower but it will solve the problem. 
In the meantime I can try to re-run the first time step of the simulation using the correct ppt file...

**Comment by goord** [comment]
Unfortunately creating a time axis for every variable separately is not how cmor likes it: it expects a time axis per table.

**Comment by goord** [comment]
Hi Paolo, can you test your 1950-01 cmorization with the timeaxis branch and see whether it gives correct results? For my run it seems to insert extra slices when time stamps are missing in the original output.

**Comment by oloapinivad** [comment]
@goord unfortunately I re-run the first time step of my experiments in order to have the pressure levels available, so I cannot do the test right now. If you are not in hurry I can run a ad-hoc experiment and check it.

**Comment by goord** [comment]
Should be fixed at the cost of minor performance hit after rev. 5f4490ac441c49dd3cf4c0c342842791218d55c8

**Comment by goord** [comment]
No problem, I tested the fix on my own primavera output so it's fairly safe to assume it would work for you as well.
