### ISSUE TITLE
Determine whether the ping file xml "content" or the "expr" attribute should be used.

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#251]
The `create-basic-ec-earth-cmip6-nemo-namelist.py` script reads the xml "content" and the "expr" attribute. Sofar only the content is used and written to the xml "content" in the auto created file_def files. However, it seems, comparing the file_def files with the current default ones, that the expression in the "expr" attribute should be used. An examples is the `tob` variable where the "expr" attribute contains the XIOS average operator `@`. 

Note that the XIOS does not know (and allow) an "expr" attribute. We could give preference to the ping file "expr" attribute and print it in the file_def xml content in case the ping file "expr" attribute is not empty / None.

**Comment by treerink** [comment]
Summarize xios-xml rules after testing some inheritance properties which are not listed in the xios tutorial:

- The use of the "`this`"-keyword in the xml content expression is totally equivalent to the use of the variable itself in the expression instead of the "`this`"-keyword.
- No matter what is in the expression, the unit definition is copied via the field_ref. I.e. if an expression exists of a variable combination which has units different from the field_ref variable the unit should be explicitly defined in this field element definition.
- Using an expression without any field_ref resulted in a `checkEmpty` error: Data not initialized
- The order of xios-xml element definition does not matter. I.e. an field A can be defined below a certain field B definition while field A is used in the expression of the field B definition.
- The operation attribute value is inherited via the field_ref by the latest definition and if not defined between this goes up to the highest level of the field_definition (the default: operation="average" in our case).

Further I checked that fields which use the default: `operation`="average" without the `freq_op` attribute definition indeed have an `interval_operation` of 2700 s = 45 min which is the model time step.

**Comment by treerink** [comment]
In the ping files the `xml content` and the `expr` attribute values are checked for each field definition by our file_def creating subpackage: They are always identical except that in the `expr`-attribute the @-operator is added, with one exception: variable `no3` having `NO3_E3T/e3t*1e-3` versus `NO3_E3T/@e3t*1e-3`. Probably here the surprising thing is the @-operator in the `xml content`, a typo?

**Comment by klauswyser** [comment]
> NO3_E3T/@e3t*1e-3

appers like a type to me, it doesn't make sense to time average the depth of each layer of the T-grid. Unless the layer thickness is changing over time, but I don't think this is the case in NEMO.

**Comment by treerink** [comment]
@klauswyser I guess the layer thickness is changing over time, because it often occurs in the default file_def files and also in the expressions given in the ping file "expr"-attribute. But here it occurs in the ping file xml-content part, and that never happens further, so I guess this concerns a typo here.

**Comment by treerink** [comment]
I decided to use the ping file "expr"-attribute if it contains content instead of the ping file xml-content, after a comparison with the default file_def and field_def files. Using the ping file "expr"-attribute means that the time averaging @-operator is included in each expression on each field.

This is probably for all or nearly all of these variables correct, because the related assumption is that it concerns time average cases. However, if it appears for individual variable - table combinations that their CMIP6 data request description asks for instant, maximum or accumulated quantities, then this needs an adjustment, i.e.: the @-operator has to be removed in such expression and the operator attribute has to be set, eventually also the freq_op attribute has to be set.

**Comment by treerink** [comment]
In 7a4e59f a check is added whether variables which have a time average "@"-operator in their expression are time averaged variables, if this is not the case the expression is adjusted by removing the "@"-operator in this expression, which effectively corresponds with taking the ping file xml "content" instead of the "expr" attribute of the ping file.

In the current situation no check results in a adjustment.

So closing this issue.
