### ISSUE TITLE
cmor package not found

### ISSUE THREAD

**Issue by oloapinivad** [EC-Earth/ece2cmor3#256]
Hi guys,

I am porting ece2cmor3 to a new machine, and installing the environment now gets me an error stating that cmor package is not found

````
$ conda env create -f environment.yml  
Solving environment: failed

ResolvePackageNotFound: 
  - cmor==2018.08.16.master.npy1.14=py27h9ac9557_0
````

Commenting the mentioned package in the `environment.yml `file let me continue the installation. Anybody experienced this?
Cheers,
Paolo

**Comment by oloapinivad** [comment]
I have just find that the conda cmor package has changed. 
https://anaconda.org/PCMDI/cmor/files
It should read `cmor=2018.09.19.master.npy1.14=py27h9ac9557_0`
However, I am not enough sure this is fine for ece2cmor3. 
Cheers,
P

**Comment by treerink** [comment]
Hi @oloapinivad,

Yes it seems they rigorously cleaned up their 'nightly builts' including the one we used. You are correct the
`````
cmor=2018.09.19.master.npy1.14=py27h9ac9557_0
`````
is the correct one: it depends on libnetcdf >=4.6 and hdf5 >=1.10, python >=2.7,<2.8.

I will test recreating the environment and commit.

Actually we are still waiting for a 'main built' with these dependencies, they still don't provide. I guess they will release relatively soon from now a main cmor 3.4 built with these dependencies, as they are working on that already for a time.

**Comment by treerink** [comment]
Fixed and tested. So closing.

**Comment by oloapinivad** [comment]
Great thanks! 
Cheers,
P
