### ISSUE TITLE
building conda env fails

### ISSUE THREAD

**Issue by anthoni-p** [EC-Earth/ece2cmor3#268]
I get a package not found error, when trying to create the conda env:
```
conda env create -f env-osx-64.yml
Fetching package metadata ...............

ResolvePackageNotFound: 
  - cmor 3.3.3.2018.08.08.14.53.g4103823.npy1.14 py27hd5f3a30_0

```
Tried to replace it with the cmor name in the environment.yml, also didn't work.
Could be because I use miniconda3 on macOS, not sure.
But I also tried on our linux cluster and on my linux desktop and I get:
```
conda env create -f environment.yml
Using Anaconda API: https://api.anaconda.org
Fetching package metadata .............
Solving package specifications: 
NoPackagesFoundError: Dependency missing in current linux-64 channels: 
  - cmor 2018.09.19.master.npy1.14 py27h9ac9557_0 -> libgcc-ng >=7.3.0
```

**Comment by anthoni-p** [comment]
changed to cmor name to:
`- cmor=3.3.3=py27h18b3941_2   # from conda create -n cmor -c pcmdi/label/nightly -c conda-forge cmor and conda list --explicit
`
and it creates the ece2cmor3 env, but not sure if that is the correct cmor version

**Comment by treerink** [comment]
@anthoni-p I updated the cmor 3.3 dependency. This issue is related to #256, but now it concerns the Mac OS `env-osx-64.yml`. As I don't have a Mac to test it, could you please test and let me know? I think it is solved now. To test run in ece2cmor3 root tree (e.g. cmorize/ece2cmor3/):
`````
nosetests
`````
If it finishes without errors (probably two warnings) then it is ok.

**Comment by treerink** [comment]
By the way: The header of the `env-osx-64.yml` describes how to recreate your environment.

**Comment by treerink** [comment]
@anthoni-p can you try once more with latest commit?

**Comment by anthoni-p** [comment]
env create worked, nosetests finished with 2 unique Warnings
