### ISSUE TITLE
SImon files not passing PrePARE

### ISSUE THREAD

**Issue by oloapinivad** [EC-Earth/ece2cmor3#274]
Hi all,

I have just discovered the PrePARE tool, and I am checking the data I have produced (PRIMAVERA control-1950 stream2). 
Apparently there a few files that do not pass the validation, e.g.

```
siage_SImon 
sicompstren_SImon
siflswdtop_SImon
...
```

The metadata for variable is wrong in the sense that it reads:
```
"cell_measures":"area: areacello OR areacella"
```
while, as long as I understand looking to the other SImon files, it should be one of the two (i.e. mainly "areacello").  I could fix the metadata with NCO, but is it possible that they are not treated correctly by ece2cmor3?

Cheers,
Paolo

**Comment by oloapinivad** [comment]
The complete list of variables showing this issue is here below:
````
siage_SImon 
sicompstren_SImon 
siflswdtop_SImon 
sisali_SImon 
sispeed_SImon 
sitemptop_SImon 
sithick_SImon 
sithick_SIday
`````

I have also other 3 variables having issues connected to their name in the table which does not fit the output name, and they are: 

````
ta_Emon 
wap_6hrPlev 
zg_Emon
`````

I am using the last version of the Jon Seddon's PRIMAVERA tables but I quite sure this should be solid anyhow.

**Comment by goord** [comment]
Hi Paolo, I have the same issue, it's a problem with the tables we are using

**Comment by goord** [comment]
The "OR" is also in the current version of the tables, not sure what to do with it. I will contact the cmor people

**Comment by goord** [comment]
Asked info at https://github.com/PCMDI/cmor/issues/407

**Comment by oloapinivad** [comment]
Thanks @goord , I will open another issue for the other 3 vars.
Cheers,
P

**Comment by oloapinivad** [comment]
Hi @goord, I am not 100% sure I understood the reply. As long as I see, the new cmor tables will be corrected. However, what should we do with previously cmorized data? Should we fix manually with "areacello"?

**Comment by oloapinivad** [comment]
Actually, on the https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_SImon.json master branch of the CMIP6 table they have already "area: areacello" for all the variables discussed above. I guess that the solution will run on two streams:
1) wait for the release 1.00.28 
2) modify previously produced files

Do you agree?

**Comment by goord** [comment]
I think we should manually change it to areacello, if we want to be able to upload to the primavera DMT anytime soon. I will see if I can find Rein today to talk about the other metadata btw.

**Comment by goord** [comment]
I agree, this is one of those issues we encounter because we use beta-status data requests

**Comment by oloapinivad** [comment]
I can close this one, keeping in mind that the above-mentioned SImon and SIday PRIMAVERA files should be manually corrected with a command like this
`ncatted -a cell_measures,$var,m,c,"area: areacello" $file`

**Comment by oloapinivad** [comment]
Adding a note: if you will need to cmorize further data with the PRIMAVERA Jon Seddon's tables (e.g. PRIMAVERA WP5 in my case) it is better to manually correct the concerned variables directly in the SImon and SIday tables, setting "area: areacello". In this way everything goes smooth and you will not need to fix the metadata later.
