### ISSUE TITLE
Aerosol vs. atmos realms

### ISSUE THREAD

**Issue by tommibergman** [EC-Earth/ece2cmor3#282]
While doing the TM5 ece2cmor3 part I noticed that variable cdnc is in the realm aerosol, but it is only available from IFS. So it seems that we need to add also "aerosol" to realms of IFS, or how is it done with other models in similar circumstances?

**Comment by tommibergman** [comment]
It is one of the pextra variables, so I am not sure if they have fixed grib numbers yet?

**Comment by treerink** [comment]
Not yet, see issue 403 on the EC-Earth portal. I will make an proposal for grib codes of PEXTRA variables this week [here](https://docs.google.com/spreadsheets/d/17ipCYh48U0N0or8b0qG-_ALGmeD79wwK-s4W38r_YtM/edit#gid=1285118949) for the listed variables. They will be all on ec-earth grib table 126.

**Comment by tommibergman** [comment]
For some reason variable cdnc is at the moment in the _cmvmm_m=all-ece-mips-step-1+2-e=CMIP-t=1-p=1.available.txt_ marked as having source of tm5: tm5 variable name = cdnc which is incorrect. It should be one of the new grib numbers.

**Comment by treerink** [comment]
In the `grib_table_126` branch I think it will be correct ...

But wait cdnc is in the` tm5par.json` file, why?

**Comment by tommibergman** [comment]
Yes, that is the point for some reason we have identified as TM5 variable.

**Comment by tommibergman** [comment]
related to #385

**Comment by treerink** [comment]
Changes also merged in tm5 branch.
Closing.
