### ISSUE TITLE
Error after last commit

### ISSUE THREAD

**Issue by aearamos** [EC-Earth/ece2cmor3#284]
Hi, I'm getting an error after the last commit  "Fixed issue with zero nemo grid ids.".
When running cmorization I get an error with some 3D variables saying it should be 1D. Here's the error:

C Traceback:
! In function: cmor_variable
! 

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: You are defining variable 'thetaot' (table Emon)  with 1 dimensions, when it should have 3
!
!!!!!!!!!!!!!!!!!!!!!!!!!

The same goes for variables thetaot, thetaot2000, thetaot700, t20d.

**Comment by goord** [comment]
Reverted previous fix, will look for another way to cmorize msftyz correctly

**Comment by treerink** [comment]
Fixed as #287. Closing
