### ISSUE TITLE
   generate-ec-earth-namelsits.sh fails

### ISSUE THREAD

**Issue by tommibergman** [EC-Earth/ece2cmor3#286]
When doing ./generate-ec-earth-namelists.sh AerChemMIP   historical   1 1 the generation of namelists fails with following error:

>Traceback (most recent call last):
  File "./drq2ppt.py", line 174, in <module>
    main()
  File "./drq2ppt.py", line 167, in main
    write_ppt_files(ece2cmorlib.tasks)
  File "./drq2ppt.py", line 134, in write_ppt_files
    f90nml.write(nml, "pptdddddd%04d" % (100 * freq,))
  File "/Users/bergmant/conda/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/f90nml/__init__.py", line 89, in write
    nml_in.write(nml_path, force=force)
  File "/Users/bergmant/conda/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/f90nml/namelist.py", line 222, in write
    raise IOError('File {0} already exists.'.format(nml_path))

It seems it cannot overwrite a file.

**Comment by tommibergman** [comment]
Actually, it does not fail, it just doesn't produce all of the ppt files.

**Comment by treerink** [comment]
Only  AerChemMIP  hist-piNTCF should not produce the ppt files as reported on the EC-Earth portal issue 518-48. See also r6031, as the control output files for all other tier 1 experiments are added there in the cmip6-nemo-namelists branch.

**Comment by tommibergman** [comment]
I seems that with AerChemMIP it creates files pptdddddd0100 and pptdddddd-100, which are not moved to mip-folder. And the next time I run it, it cannot overwrite these files.

**Comment by treerink** [comment]
Yes saw something like that, will have a further look

**Comment by treerink** [comment]
See #293 for what goes wrong. As it is not an error in the` generate-ed-earth-namelsits.sh` script, I close this issue.
