### ISSUE TITLE
Creating 1hr time axis problem

### ISSUE THREAD

**Issue by tommibergman** [EC-Earth/ece2cmor3#288]
I have a problem with hourly output. CMOR gives following error:

 > Error: approximate time axis interval is defined as 86400.000000 seconds (1.000000 days), for value 8783 we got a difference of 3599.999999 seconds (0.041667 days), which is 95.833333 % , seems too big, check your values

I do not understand what is the problem. daily and monthly output work fine. The time interval for hourly output should be 3600 seconds, so why is it asking for daily interval?

Has anyone had the similar problems?

**Comment by goord** [comment]
Hi Tommy, nobody has yet tried the make hourly time interval axes; are you trying to process an existing variable or write new code?

**Comment by tommibergman** [comment]
I am writing new code for TM5. I'll leave it for now, for me it seems CMOR is not working right.

**Comment by tommibergman** [comment]
I asked about this at PCMDI/CMOR github. Their suggestion was that I am using wrong tables. And it seems that AERhr has interval of 1.0 days.

**Comment by tommibergman** [comment]
Just a note that tables from 1.00.28 do not resolve this problem. It has not been fixed yet. See discussion on https://github.com/PCMDI/cmip6-cmor-tables/issues/211 .

**Comment by mauzey1** [comment]
The approx_interval value for AERhr is now 0.041667 in the 01.00.29 version of the CMOR CMIP6 tables.

**Comment by tommibergman** [comment]
With data request 1.00.29 hourly output is working as expected.
