### ISSUE TITLE
CMOR variable names of lon & lat seems to be wrong

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#295]
It seems that the cmorised data contains the correct names `longitude` and `longitude` as long it concerns the coordinate names. But they are also outputted as field variables but then the CMOR name should be `lon` and `lat`. 

This was encountered when the ESMVal tool was used.

**Comment by goord** [comment]
This is not our choice, those variable names are generated by the cmor library, on the basis of the cmor tables. So either ecmvaltool has it wrong, or the cmor developers.

**Comment by zklaus** [comment]
[CMIP6_coordinate.json](https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_coordinate.json) specifies that `out_name` for `latitude` must be `lat` and similar for `lon`.

Do you agree that this is the name that should be used for the variable of the netcdf file?

**Comment by goord** [comment]
Hi @zklaus not sure if that is where our latitude/longitude variables come from, I think they originate from https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_grids.json because they are part of a 2d grid definition in CMOR. This is an interesting issue to address at the CMOR library development platform https://github.com/PCMDI/cmor

**Comment by zklaus** [comment]
Since this is an apparent inconsistency in the tables themselves, I opened an issue [there](https://github.com/PCMDI/cmip6-cmor-tables/issues/215).

However, I think ece2cmor is still responsible for the output, no matter what libraries it chooses to use, so I suggest to reopen this issue as well.

**Comment by goord** [comment]
Ok, I suggest we wait and see...

**Comment by taylor13** [comment]
See https://github.com/PCMDI/cmip6-cmor-tables/issues/215#issuecomment-433212192

**Comment by treerink** [comment]
So from the https://github.com/PCMDI/cmip6-cmor-tables/issues/215#issuecomment-433212192 comment the CMOR intention seems to be (in contrast to my first comment) to have: lon, lat as name for the longitude and latitude as long it concerns the coordinate names, but when they are also outputted as field variables then the CMOR name should be the full name longitude and latitude. In fact I agree with this naming, it is good to distinguish them and the naming like this is most intuitive I think. So lets check or bring everything in agreement with this.

**Comment by zklaus** [comment]
After the discussion in the mentioned cmip6-tables issue it seems cmip6 is even more liberal: If latitude and longitude are coordinate variables, ie. one dimensional in the direction of the axis of the field, they are mandated by `CMIP6_coordinates.json` which includes among other things that their `out_name` must be `lat` and `lon`, respectively. If they are auxiliary coordinates, eg. 2d fields as for native ocean grids, any `out_name` is permitted (cmor uses `latitude` and `longitude`, GFDL data on esgf uses `lat`/`lon`, IPSL data uses `nav_lat`/`nav_lon`), but in all cases, auxiliary or not, `standard_name` has to be `latitude`/`longitude` and this is the only reliable way to identify this information in cmip6 files.

Which in the end means that the original output I got was in fact ok and we have to fix ESMValTool instead.

This issue can be closed.

**Comment by goord** [comment]
ok, closing
