### ISSUE TITLE
Automatically set metadata for IFS and NEMO grid 

### ISSUE THREAD

**Issue by oloapinivad** [EC-Earth/ece2cmor3#297]
Hi all,

I was wondering if it could be possible to automatically set metadata information about grids (i.e `grid`, `grid_label` and `nominal_resolution`) from ece2cmor3. I know this can be done using a proper wrapper script, but it will simplify the metadata handling. 

This has been suggested here, and I agree that it may be a good idea. 
https://docs.google.com/document/d/16NTTxZM9l8B_tqLrG_zTJDGZYJr21dS7L3B-tGU2Wik

Thanks,
Paolo

**Comment by treerink** [comment]
I think this is covered already by https://github.com/EC-Earth/ece2cmor3/issues/214#issuecomment-416856045. If you agree you can you please close this one?

**Comment by oloapinivad** [comment]
Good to know, missed this one!
Thanks!
P
