### ISSUE TITLE
TM5 miss identification of variables

### ISSUE THREAD

**Issue by tommibergman** [EC-Earth/ece2cmor3#298]
I have made a wrong identification for some of the TM5 variables. Here is a list of variables not available from TM5:

nh50
od550csaer
h2o
co2
co2clim
co2mass
co2massclim
fco2antt
fco2fos
fco2nat

CO2 only transported in C-Cycle version, unclear if it is needed as output from TM5?
For h2o, TM5 cannot do all phases of water, should therefore come from IFS if anywhere.

Furthermore, I have not implemented any variables for 3hr output from TM5 since AerChemMIP does not request these. So output from TM5 in tables E3hr or CF3hr are not available.

**Comment by treerink** [comment]
I have taken off these variables from the` generate-tm5.json.sh` script and thus they are removed from the `resources/tm5par.json`. They have been added to the `resources/pre-list-of-ignored-cmpi6-requested-variables.xlsx` list but the ignored list itself has not been recompiled with this update yet.

**Comment by treerink** [comment]
Also remove the miss identified variables from the` pre-list-of-identified-missing-cmpi6-requested-variables.xlsx` file.

**Comment by treerink** [comment]
So closing.
