### ISSUE TITLE
A possibly erroneous second zdim is defined for msftyz

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#305]
When adding the NEMO Volume estimate I encountered the following:

For the **msftyz** cmor variable there seems to be two vertical dimensions. The first is the regular `olevel', the second is the `gridlatitude` which is possibly erroneously appearing here?

Overview:
`````
varname: msftyz   freq: mon   table: Omon    zdim: [u'olevel', u'gridlatitude'] 
`````

**Comment by goord** [comment]
Issue has been fixed in rev. 753f17bb3a558878d691181e531a00f6a3794561
