### ISSUE TITLE
Fix `hfbasin` cmorization

### ISSUE THREAD

**Issue by zklaus** [EC-Earth/ece2cmor3#306]
I tried cmorising one of the first runs with basin output turned on. Unfortunately, `ece2cmor` stopped at the hfbasin output with the `cmor` error message
```
! In function: cmor_variable
!

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: You defined variable 'hfbasin' (table Omon) with axis id 'gridlatitude' which is not part of this variable according to your table, it says: ( time basin latitude )
!
!!!!!!!!!!!!!!!!!!!!!!!!!
```
The full log is here: [ece2cmor3_hfbasin.log](https://github.com/EC-Earth/ece2cmor3/files/2561600/ece2cmor3_hfbasin.log).
The model output seems ok to me and doesn't mention `gridlatitude`.

How can I fix this?

**Comment by treerink** [comment]
Well this seems closely related to #305.

**Comment by zklaus** [comment]
Agreed, that seems related. One difference is that in `cmvme_CMIP_piControl_1_1.xlsx` for `hfbasin` the dimensions mention `latitude`, whereas for `msftyz` they have `gridlatitude`, which might be why cmor crashes with the former, but not with the latter.

**Comment by goord** [comment]
I tried to fix the inconsistency in the nemo-gridfixes branch, please can you test the entire ocean cmorization again?

**Comment by zklaus** [comment]
I just tried the nemo-gridfixes branch. Unfortunately, the error persists. Also maybe there is a misunderstanding: The solution is not to make ece2cmor accept `gridlatitude`. There should be no `gridlatitude`, also not for `msftyz` as far as I can tell, since that [is reserved for rotated grids](http://clipc-services.ceda.ac.uk/dreq/u/grid_latitude.html).

Rather what seems to be happening is that some integer identifier of an extra dimension (`basin`?) is misinterpreted as `gridlatitude`.

**Comment by goord** [comment]
Hi Klaus, sorry about that, can you try once more? If this doesn't work, it's best to send me the files containing hfbasin, msftyz and maybe a non-meridional variable.

I tried to make a solution that 'fits all', and continues working once they fix the msftyz dimensions.

**Comment by zklaus** [comment]
No worries. I had one problem where cmor complains about a parameter not being a `str`ing --- which is true since it comes in as a unicode object. I fixed this with the below patch; then everything seems to work.

```
diff --git a/ece2cmor3/nemo2cmor.py b/ece2cmor3/nemo2cmor.py
index 061f4fb..cbe51f4 100644
--- a/ece2cmor3/nemo2cmor.py
+++ b/ece2cmor3/nemo2cmor.py
@@ -419,7 +419,7 @@ def write_grid(grid, tasks):
                 task.set_failed()
                 continue
             latnames = {"latitude", "gridlatitude"}
-            latvars = list(set(dims).intersection(set(latnames)))
+            latvars = [lv.encode('ascii') for lv in set(dims).intersection(set(latnames))]
             if not any(latvars):
                 log.error("Variable %s in %s has no (grid-)latitude defined where its output grid %s does, dismissing "
                           "it" % (task.target.variable, task.target.table, grid.name))
```

**Comment by goord** [comment]
Ok, I implemented that bugfix on a slightly deeper level, I'm going to merge this branch into the main one and close the issue.
