### ISSUE TITLE
ngl package not found

### ISSUE THREAD

**Issue by jmcgove** [EC-Earth/ece2cmor3#308]
Hi, in conda virtual environment, the latest ece2cmor.py stops as ngl not found (for tm5, import ngl in tm52cmor.py). When I do conda install ngl, says the package is not in the current anaconda channels. Checked the anaconda channels listed (repos.anaconda...), no ngl.  
The ngl package is not found. I had similar issue with panda before, but panda package is in channel. Is there a channel with the ngl package? (I tried conda create, update, but no) Thanks J

**Comment by tommibergman** [comment]
pyngl is in conda-forge channel. I wonder why it is not found? Do others have this issue?

**Comment by goord** [comment]
I believe you need to type
```
conda install pyngl=1.5.0
```
within your virtual environment. Another (perhaps safer) way is to completely delete your environment (conda env remove -n ece2cmor3) and recreate it from the environment.yml file

**Comment by treerink** [comment]
I just recreated the environment on **linux** with the most update master branch
`````
 cd ${HOME}/cmorize/ece2cmor3/
 source deactivate ece2cmor3
 conda-env remove -y -n ece2cmor3
 conda env create -f environment.yml
 conda activate ece2cmor3
 nosetests 
`````
I did not encounter any problem? The nosetests gave no errors (there are always some warnings).

**Comment by goord** [comment]
Hi @jmcgove you did ```conda install ngl``` but you need to  ```conda install pyngl```

**Comment by jmcgove** [comment]
```
conda config --add channel conda-forge
conda install pyngl=1.5.0 
```
fixed that thanks.
