### ISSUE TITLE
ERROR:ece2cmor3.nemo2cmor:Dimension 3basin could not be found in file #415

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#311]
Trying to cmorise the test case in which all NEMO output is switched on, on the results of an EC-Earth run with the XIOS-2.5 & Shaconemo updates and where the additional Poleward heat and salt transport & Atlantic/Pacific/Indian basins computation are switched on, by using ece2cmor like this:

`````
ece2cmor /net/bhw463/nobackup/users/reerink/cmip6-ec-earth-output/t011/001 --exp t011 --oce --conf ece2cmor3/resources/metadata-templates/cmip6-CMIP-piControl-metadata-template.json --vars ece2cmor3/resources/test-data-request/varlist-nemo-all-without-problematic-ones.json
`````
I get the following error:
`````
ERROR:ece2cmor3.nemo2cmor:Dimension 3basin could not be found in file /net/bhw463/nobackup/users/reerink/cmip6-ec-earth-output/t011/001/t011_1m_19900101_19901231_opa_grid_ptr_T_2D.nc, inserting using length-one dimension instead

C Traceback:
! In function: cmor_treat_axis_values
! called from: cmor_axis
! 

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: requested value 0.000000 for axis basin (table: EmonZ) was not found
!
!!!!!!!!!!!!!!!!!!!!!!!!!


C Traceback:
! In function: cmor_treat_axis_values
! called from: cmor_axis
! 

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: requested value 0.000000 for axis basin (table: EmonZ) was not found
!
!!!!!!!!!!!!!!!!!!!!!!!!!


C Traceback:
! In function: cmor_treat_axis_values
! called from: cmor_axis
! 

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: requested value 0.000000 for axis basin (table: EmonZ) was not found
!
!!!!!!!!!!!!!!!!!!!!!!!!!

Traceback (most recent call last):
  File "/usr/people/reerink/anaconda2/envs/ece2cmor3/bin/ece2cmor", line 11, in <module>
    load_entry_point('ece2cmor3', 'console_scripts', 'ece2cmor')()
  File "/usr/people/reerink/cmorize/ece2cmor3/ece2cmor3/ece2cmor.py", line 129, in main
    ece2cmorlib.perform_nemo_tasks(args.datadir, args.exp, refdate)
  File "/usr/people/reerink/cmorize/ece2cmor3/ece2cmor3/ece2cmorlib.py", line 188, in perform_nemo_tasks
    nemo2cmor.execute(nemo_tasks)
  File "/usr/people/reerink/cmorize/ece2cmor3/ece2cmor3/nemo2cmor.py", line 105, in execute
    create_type_axes(dataset, task_list, table)
  File "/usr/people/reerink/cmorize/ece2cmor3/ece2cmor3/nemo2cmor.py", line 335, in create_type_axes
    axis_id = cmor.axis(table_entry=dim, coord_vals=axis_values, units=axis_unit)
  File "/usr/people/reerink/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/cmor/pywrapper.py", line 454, in axis
    type, cell_bounds, cbnds, interval)
_cmor.CMORError: Problem with 'cmor.axis'. Please check the logfile (if defined).
`````

**Comment by aearamos** [comment]
@treerink in xml files I have some of the variables with the grid definition grid_ref="grid_ptr_T_3basin_2D" or grid_ref="grid_ptr_T_3basin_3D", in which they take the 3 basin axis and the cmorization works. Could that be the case for you?

**Comment by treerink** [comment]
@aearamos do I understand correctly that you have a fix for "Dimension 3basin could not be found"? Could you explain us what you did. We didn't understand your comment.

**Comment by aearamos** [comment]
@treerink I'm not sure if it's a fix per se, but if I understood your issue correctly, cmorization couldn't find the 3basin axis in your nemo output, right? From what I know, if you want to have this axis in your nemo output, you have to ask for the right grid_ref in your xml file, such as in: 

 <file id="file4" name_suffix="_opa_grid_ptr_W_3basin_3D" output_freq="1mo">
        <field enabled="True" field_ref="zomsf_3bsn" grid_ref="grid_ptr_W_3basin_3D" id="id_1m_msftyz" name="msftyz" unit="kg s-1"> this * 1e6 * $rau0  </field>
    </file>

That way you can produce an output with the 3basin axis that can be read by cmorization. I know your file and variable are different, but hopefully this could help.

**Comment by treerink** [comment]
Yes it complains that this 3basin axis is missing, and this is indeed not in the netcdf. Ok thanks, we will have a look.

**Comment by treerink** [comment]
@aearamos I checked your code quote, but is identical to what I automatically generate with `genecec.`

@goord, what exactly do you mean?

The grid definition of  `grid_ptr_W_3basin_3D` in  `grids_def_nemo.xml` seems ok to me:
`````
       <grid id="grid_ptr_W_3basin_3D">
         <domain domain_ref="ptr" />
         <axis axis_ref="depthw" name="olevel"  />
         <axis axis_ref="3basin" />
       </grid>
`````
The 3basin axis is defined in the `axis_def_nemo.xml` file:
`````
      <axis id="3basin" axis_ref="basin" long_name="Sub-basin mask (1=Global 2=Atlantic 3=Indo-Pacific)" >
         <zoom_axis begin="0" n="3" />
      </axis>
`````

**Comment by treerink** [comment]
With the cmor table update to the data request version 01.00.28 the problematic variable `sltnortha` in this issue is removed. In fact it looks like that this is from the cmor table side the only real change. See:
[cmor table diff version 01.00.28 with 01.00.27](https://github.com/PCMDI/cmip6-cmor-tables/commit/e3173ef9d354981b43e3939224e2158eb2be96e8#diff-9a81eade72535a264baa6dde9cb549e9)

Therefore we close this issue, though for the current runned EC-Earth3 output this issue of course remains. But as soon all is based on the new data request it is solved because this variable won't appear anymore.
