### ISSUE TITLE
Add ece2cmor3 version to meta data of cmorized files

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#312]
Plan: ece2cmor3 itself (thus not from metadata file or so) will add this ece2cmor3 version to the meta data: the git revision (and release number). Later for an eventually ece2cmor3 pip version this needs some additional organisation.

**Comment by goord** [comment]
Fixed in rev. a5a88d55c75f1aca03acb291dc5beef22e6a1a7b
