### ISSUE TITLE
Is the available IFS variable mrros correctly treated by drq2ppt?

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#313]
Message from Fei Luo:

Dear Thomas,

I think I might have found a bug in ece2cmor3 tool. When I created my Jason list, I put mrros (surface runoff), but my it was not produced in my output files. So I checked the ppt file. This variable was not created when I converted Jason to ppt. Its ECMWF ID number is 8.

Fei

**Comment by goord** [comment]
If there are only 3-hourly variables, drq2ppt only creates a pptdddddd0300 file. I assumed EC-Earth will link this file to the 6-hourly postins as well, doesn't it?

**Comment by treerink** [comment]
Actually I realize that in the `r5717-cmip6-nemo-namelists` branch, we (Philippe and me) very recently built in this check: If the 3-hourly `ppt` exists and the 6-hourly `ppt` does not exist, then we link the 3-hourly `ppt` to all the  6-hourly `ppt` files in the `postins` directory.

However, I supposed that `ece2cmor` produced also a  6-hourly `ppt` when **only** 3-hourly variables are asked, so that is incorrect @goord?

But what happens then, if we have 3- and 6-hourly `ppt` files, with the 3-hourly variables at the 6-hourly intervals? I thought they were already also written to the 6-hourly `ppt` file, and therefore I thought that the 6-hourly `ppt` file is also automatically written as soon there are 3-hourly variables?

**Comment by goord** [comment]
If both 3- and 6-hourly files are there, the 3-hourly grib codes will be added to the 6-hourly namelist. But if it doesn't exist, it's not created either. I can change this if it causes confusion...

**Comment by treerink** [comment]
Ok, yes I think is good to change it if it is not much work (as I guess) because it is easier to understand. Otherwise, if it is a lot of work, it is in fact also solved already in the r5717-cmip6-nemo-namelists branch, as explained above.

Fei probably did not use this branch (or the update).

**Comment by goord** [comment]
Rev. 1931d21c744235bd052bd23fe5aa2592da51529d
