### ISSUE TITLE
Variable siconca (possible bug)

### ISSUE THREAD

**Issue by aearamos** [EC-Earth/ece2cmor3#315]
I believe there is a bug with variable siconca (Sea Ice Area Fraction (Atmospheric Grid)). The variable is in ifspar.json with code 31.128, which makes it possible to be output by ifs. However, the CMIP6_SImon.json shows the variable as:
"siconca": {
            "frequency": "mon", 
            "modeling_realm": "seaIce", 
            "standard_name": "sea_ice_area_fraction", 
            "units": "%", 
            "cell_methods": "area: time: mean", 
            "cell_measures": "area: areacella", 
            "long_name": "Sea Ice Area Fraction (Atmospheric Grid)", 
            "comment": "Area fraction of grid cell covered by sea ice", 
            "dimensions": "longitude latitude time typesi", 
            "out_name": "siconca", 
            "type": "real", 
            "positive": "", 
            "valid_min": "", 
            "valid_max": "", 
            "ok_min_mean_abs": "", 
            "ok_max_mean_abs": ""
        },

Shouldn't the modeling_realm be "atmo", since the variable is produced by IFS? That way the variable can be produced and cmorized. @treerink this is the variable I told you about during the Lisbon meeting.

**Comment by goord** [comment]
Hi Arthur this is again the issue with the variables being produced by multiple components. I added the seaIce to the ifs realms in the new branch ifs-realms for you to test. The thing is that if you now do a combined ocean-atmosphere cmorization job, ece2cmor3 might complain about multiple components producing siconca...

**Comment by treerink** [comment]
We could change it such that it is not allow to cmorize multiple components in one ece2cmor call? As we discussed several times that in a real cmorization case nobody will cmorize multiple components, it is maybe easier to make it impossible at all, for the reason of this kind of cases?

**Comment by goord** [comment]
That could be one of the elements of a solution. In general I don't like the thing we do with the realms now, it seems that the cmor-realms don't match our components so I would like to remove that logic entirely, and unambiguously specify which variable in which table will be produced by which component.

**Comment by goord** [comment]
Closed after merge of ifs-realms into master
