### ISSUE TITLE
ifs Cmorisation before 1900

### ISSUE THREAD

**Issue by aearamos** [EC-Earth/ece2cmor3#329]
Hi @goord and @treerink,

I'm not sure if this error persists, but today when running cmorisation in an experiment from 1850 (piControl), I got the following error: 

Traceback (most recent call last):
  File "./ece2cmor.py", line 153, in <module>
    main()
  File "./ece2cmor.py", line 136, in main
    cdothreads=args.ncdo)
  File "/gpfs/scratch/pr1eel00/pr1eel17/a1fu/auto-ecearth3/ece2cmor/ece2cmor3/ece2cmorlib.py", line 176, in perform_ifs_tasks
    outputfreq=ofreq, tempdir=tempdir, autofilter=auto_filter)):
  File "/gpfs/scratch/pr1eel00/pr1eel17/a1fu/auto-ecearth3/ece2cmor/ece2cmor3/ifs2cmor.py", line 92, in initialize
    dirname = exp_name_ + start_date_.strftime("-ifs-%Y")
ValueError: year=1850 is before 1900; the datetime strftime() methods require year >= 1900

I remember having this error before with an old version of ece2cmor and here at BSC we fixed it by not using strftime. I applied the same fix, which seems to work:

Instead of:
dirname = exp_name_ + start_date_.strftime("-ifs-%Y")
I added: 
dirname = exp_name_ + start_date_.isoformat().replace("-","")[:-2]

Now the cmorization works fine. I'm just not sure this fix is the best one, considering the problem is a Python problem, not a ece2cmor3 one. I found some other issues with people trying to use strftime before 1900 and they couldn't get around it. The thing is for for out version of Python strftime doesn't work.

**Comment by goord** [comment]
Hi @aearamos that workaround looks fine, I will implement it asap.

**Comment by goord** [comment]
Hi @aearamos committed a slightly modified version of your suggestin straight to the master, rev. aa4b95e6f4bad9f7a3afeed1a80547effe99acff

**Comment by aearamos** [comment]
Hi @goord,

Sorry for going back to this issue, but we recently updated ece2cmor to its last version and I got that same error. We were using the previous version of ece2cmor for the C4MIP runs and I noticed that the code still calls for  `strftime` in grib_filter.py, but for some reason, we never had a problem with that version. 

Now that we updated and I see a lot of changes, we started having this issue again:

```
File "/gpfs/scratch/bsc32/bsc32436/a3dk/auto-ecearth3/ece2cmor/ece2cmor3/grib_filter.py", line 357, in filter_fx_variables
    write_record(gribfile, key + (gridtype,), keys2files, shift=0, handles=handles, once=True, setdate=startdate)
  File "/gpfs/scratch/bsc32/bsc32436/a3dk/auto-ecearth3/ece2cmor/ece2cmor3/grib_filter.py", line 633, in write_record
    gribfile.set_field(grib_file.date_key, int(setdate.strftime("%Y%m%d")))
ValueError: year=1851 is before 1900; the datetime strftime() methods require year >= 1900
```

I think maybe it's accessing this part of the code whereas it wasn't before?

The code works for the first year and crashes for 1851 and on. 

Thanks!

**Comment by treerink** [comment]
@aearamos are you running the pure latest `ece2cmor3` master version? Or one with modifications on top of that?

**Comment by aearamos** [comment]
I think I am a couple of commits behind, but I updated two weeks ago I think. Should I call the most recent one?

**Comment by goord** [comment]
This is due to the ``fx`` variables we added, we didn't test those for runs starting before 1900 apparently.

**Comment by etiennesky** [comment]
Note that strftime is used in 4 places in the repository, it would be great to replace those with python function(s) which work before 1900. Thanks for your help!

**Comment by goord** [comment]
Hi I fixed the issue in the filter. I did not replace all occurences @etiennesky because some of them are just used in time stamps of the log files, which presumably won't have a date before 1900
