### ISSUE TITLE
Add the generation of LPJ-GUESS instruction (control output) files to genecec

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#330]
At this moment LPJ-GUESS has no control output files, however after a skype discussion with @nierad we decided it will be a good idea to add them. At the LPJ-GUESS side this needs the implementation of a standard `lpj-guess-instruction-file.ins` file, in ec-earth this file will be located in the  `runtime/classic/ctrl/` directory. This one will be the default, and effectively generate the same output as now by the hard coded approach.

In `genecec`, similar to what happens for IFS and NEMO, in each sub directory in the [`cmip-output-control-files`](https://dev.ec-earth.org/projects/ecearth3/repository/show/ecearth3/branches/development/2018/r5717-cmip6-nemo-namelists/runtime/classic/ctrl/cmip6-output-control-files) directory (see the [`r5717-cmip6-nemo-namelists`](https://dev.ec-earth.org/projects/ecearth3/repository/show/ecearth3/branches/development/2018/r5717-cmip6-nemo-namelists) branch) an `lpj-guess-instruction-file.ins` file will be added, which just configures the LPJ-GUESS output for each MIP experiment.

Setting in the [`config-run.xml`](https://dev.ec-earth.org/projects/ecearth3/repository/entry/ecearth3/branches/development/2018/r5717-cmip6-nemo-namelists/runtime/classic/config-run.xml) file the `OUTPUT_CONTROL_FILES_DIR` variable will then also be enough for LPJ-GUESS like for NEMO and IFS.

Note with this approach #326 will be solved: we can go back to the original approach in which we just provide a list of variables in `generate-lpjguess.json.sh` without table information which produces the `lpjguesspar.json` also without the table info.

**Comment by klauswyser** [comment]
How quickly can this be achieved? I still haven't give up hope that we can start the DECK simulations next week (we are already overdue by several month!). Can the addition of new output control files to LPJ-Guess really be done in a few days? If not, could we still start a historical run with the existing LPJG a.s.a.p., and the new output control files are then added later to the ESM version? If I understand correctly, the output will not change with the new output control files for LPJG, it only makes life easier for ece2cmor3.

**Comment by treerink** [comment]
I don't know whether next weak is very realistic...  Anyway we estimate it is one day work on the LPJ-GUESS side, but someone has  to do it, Lars will be asking David if he has time. From the ece2cmor3 side it is certainly the quest fix for #326, and there yes I expect changes. However, even doing nothing, will be correct for over 90% of the LPJ-GUESS variables is my wild guess.

**Comment by nierad** [comment]
Hi Klaus, 
well we could do it with the current setup. Worst case would be to rename a some files before cmorisation to fit the new names in ece2cmor3, but technically nothing would be lost, as we are writing out all the output anyways currently.
I'll let you know asap.

**Comment by treerink** [comment]
Yes, that's true. And see closing message  of #326. So we are fine for Core MIP, will take oof the 0.9 label.

However the proposed approach with the instruction file will be much saver for updates and might be nice to save output. So I leave the issue open, but with less priority.

**Comment by klauswyser** [comment]
Thanks @treerink  and @nierad  for your replies. I understand that we can start the first CMIP6 experiment but there may be later updates related to LPJG output control, and possibly some manual fixes needed on file/variable names in the first CMIP output. That's good news!

**Comment by treerink** [comment]
In 5de7e59 the new script `drq2ins.py` is added which generates the LPJ-GUESS instruction files and provides the LPJ-GUESS volume estimate.

**Comment by treerink** [comment]
All `lpjg_cmip6_output.ins` instruction files for all included MIPs can now be generated by `genecec`. 

So closing the issue, as the part from the `genecec`/`ece2cmor3` side seems to be ready.

**Comment by treerink** [comment]
As LPJ-GUESS is producing now the output along this control output file strategy, we need to change the `generate-lpjguess.json.sh` and the `lpjguesspar.json` accordingly.

**Comment by treerink** [comment]
@nierad can you test the cmorization of your new output with the master branch? I kind of expect some error with the table reading in the lpjgpar.json because this table info is now taken off, so can you post the message if there?

**Comment by goord** [comment]
Hi @nierad I just pushed a change to the master branch that I hope enables you to process the new frequency-specific lpjguess output files. Can you do a quick test with the latest rev.? If it fails, I suggest we find a way to transfer lpj output to my laptop so I can debug locally.

**Comment by treerink** [comment]
ece2cmor3 was broken today, until a quick BUG fix at the end of the afternoon. With adbf611 a proper  and better fix is provided. Tests for this issue should use this revision.

**Comment by treerink** [comment]
Again insert the update concerning the renamed variables et -> det and ec -> dec in the new `generate-lpjguess.json.sh` and `lpjgpar.json`.

**Comment by treerink** [comment]
By accident the commit 4777a16, now in the master branch, had been applied to the Ofx-support branch in commit  7dae7020a09bd6b4e52c562ad6b71e77f2b1eb7f.

**Comment by treerink** [comment]
@nierad can you test the cmorization of the LPJ-GUESS output once more (after all the confusing commits). We have to be sure there are no bugs in 4777a16 where we tried to fix `lpjg2cmor.py` for the new situation.

**Comment by nierad** [comment]
Hi all, 
will try to do tonight but I am really busy until tomorrow lunchtime. So, that's probably, when it will happen.

**Comment by treerink** [comment]
@nierad seeing your comments in #340, do I am correct that it means you are able to use the new setup? That means you run `ece2cmor3` with the master branch (with a version which is not older than 3 days)? If so, that means we can close this issue, because then you have successfully tested the new `lpjg2cmor.py` from  4777a16.

**Comment by nierad** [comment]
@treerink that is correct. It is running smoothly. We found a few bugs on hour side that we are fixing right now. The question on the issue with frequency "yrPt" remains though. 
Also, there are 15 output-files that have not been requested by any of the "*_TOTAL_* drqs. I will check against your control-output-files.

**Comment by treerink** [comment]
@nierad the "TOTAL" ones  you are referring to are probably based on the CMIP experiment suite and  do for instance not cover variables only asked by LS3MIP or only asked by LUMIP (if any).

However, closing this issue, because we are able now to produce the instruction files, and using them to run LPJ-GUESS leads to results we in principal can cmorize.
