### ISSUE TITLE
Does ece2cmor3 know where to find the right output directory?

### ISSUE THREAD

**Issue by nierad** [EC-Earth/ece2cmor3#332]
This just occurred to me. If this has been addressed previously, sorry for spamming!
Nevertheless:
I am not aware on how, if I was a total lay person, I would intuitively run ece2cmor, but I'd probably point it to an EC-Earth output dir like:
<run_dir>
and expect it to guess the subfolders
/output/lpjg/<leg_no>/
LPJG currently has subfolders inside the above for e.g. CMIP6 and CRESCENDO where the official output ends up in. 
Is there a rule on where to put them? Could we set an official PATH somewhere?  Should we rather move them to the top level-dir of the leg?

**Comment by goord** [comment]
Hi Lars, the directory you give to ece2cmor3 is the one where your output files are supposed to be in (not in a subfolder thereof). I haven't made this anymore sophisticated to allow different output directory structures like you are mentioning. Note that this means in practice you will always run ocean, atmosphere, land in separate jobs...

**Comment by goord** [comment]
I could create a separate 'wrapper' script that descends down into the EC-Earth output directory to find the correct leg and output though...

**Comment by nierad** [comment]
Thanks @goord! 
I think, that would be great. But also, how can we assure best, that a user has created all cmor-files from an experiment? Someone might just forget about one of the models.
Ok, we will move them to the top-level of the lpjg-output-dir.

**Comment by klauswyser** [comment]
@nierad: I am not sure if it is necessary to move the cmip6 output to the top level. The ece2cmor3 tools processes one year (or rather 1 leg) at a time and you have to specify the full path to the output directory, it's not enough to just tell $run_dir/output/$model  but you have to specify the leg explicietly when calling ece2cmor.py. You can then as well just say $run_dir/output/lpjg/$leg/cmip6_output when processing lpjg, taht's not much of a hassle.

**Comment by goord** [comment]
Perhaps a more convenient thing would be to have ece2cmor3 accept wildcards and linux glob expressions, so you could e.g. type
```
ece2cmor --exp exp1 --refd 1950-01-01 --lpj $SCRATCH/exp1/output/lpjguess/CMIP6/*
```
and let the tool run the found directories one after another?

**Comment by nierad** [comment]
That would be great! 
Else, I can imagine, regardless of how and where we bring it to the user's attention, someone would just set the path to 
<run_dir>/output/lpjg/<leg> 
as for every other model. But we will move it to the top level anyways for now. 
I am also concerned about people simply forgetting to cmorize one model. Actually, I would prefer to have to enter the path to <run_dir>/output and then have ece2cmor crawl the rest of the tree. You could still do anything at a time, the old way. But maybe that is a bit too much for now... ;)

**Comment by klauswyser** [comment]
Nothing against wildcards, but we need to tell ece2cmor3 how many years/legs/months to process in one go. As for now, we always process one year and get one output file per variable. If we add wildard and let ece2cmor process all the years found then we will get a problem when processing the 6-hourly variables of the 500-yr long piControl experiment.

@nierad: I don't think we specify <run_dir>/output/<model> but <run_dir>/output/<model>/<leg>. Whether or not we have to add yet another dir to this path doesn't really matter for me. And I don't really see how a user can forget to process the output from one model. Keep also in mind thatfor processing the output from a specific model itäs not enough to just change the directory to the data, you also have to tell ece2cmor.py which model you want to process (--oce, --land, etc) and even manually adjust the metadata file so it fits to the model that is processed (e.g. the nominal resolution). And not even speaking about the experiment and the MIP that needds to be specified. All this tells me that cmorising the output requires a lot of manual intervention anyway, so adding an extra subdir to the lpjg path isn't really introducing a lot of extra work.

**Comment by nierad** [comment]
Hi Klaus, I agree, it is indeed a lot of manual interaction required. Nevertheless, we removed the sub-dir. Just in case ;)

**Comment by treerink** [comment]
Close it. Reopen if necessary with a remaining question please.
