### ISSUE TITLE
1D coordinates for regular grids

### ISSUE THREAD

**Issue by zklaus** [EC-Earth/ece2cmor3#333]
For regular output from ifs, ece2cmor writes a full 2d grid. This seems unnecessary and a bit confusing, since this is usually taken to be a clue that the grid is irregular.

Can we change the output to normal 1d coordinate variables for the regular case?

**Comment by klauswyser** [comment]
When working with the cmorisation of SPECS the manual of CMOR3 clearly said that all non regular lonlat grids need to specify the latitude and longitues as 2-d fields and provide the vertices. This was a coupel of yeras ago, so the specs may have changed in the meantime. However, the CMIP6_grids.json file (1.00.27) still says:
````
        "latitude": {
            "dimensions": "longitude latitude",
            "valid_min": "-90.0",
            "long_name": "latitude",
            "standard_name": "latitude",
            "out_name": "latitude",
            "units": "degrees_north",
            "valid_max": "90.0"
        },
`````
which tells me that latitude still needs to be provided as a 2-d field, and similar for longitude. Or am I missing something here?

**Comment by zklaus** [comment]
I agree that non regular grids need to provide the information in a 2d field.
But here we are talking about regular grids, albeit non equidistant ones. Indeed, you will notice that we are talking about the *regular* gaussian grid.

As for the entry in `CMIP6_grids.json`, it is a bit strange for me, but there is also the entry in `CMIP6_coordinates.json` and furthermore the entry in `CMIP6_grids.json` seems not to be authoritative in the sense that any variable name is allowed and the `out_name` there is not required (see discussion [here](https://github.com/PCMDI/cmip6-cmor-tables/issues/215) and references therein).

**Comment by goord** [comment]
Hi @zklaus, let's ask this to the pcmdi people, we are relying on their library to create the grid axes. Perhaps there is a special way to create rectilinear grids with it. I will create an issue tomorrow.

**Comment by zklaus** [comment]
What I am about to write is not really a definitve answer. I am just trying to gather some sources since I am reading through the same material over and over again in an effor to piece together the somewhat scattered information.

With this caveat, I think the following supports my position.

On the [cmor website](https://cmor.llnl.gov/) I found the
>  [...]
> Define the axes (i.e., the coordinate values) associated with each of the dimensions of the data to be written and obtain “handles”, to be used in the next step, which uniquely identify the axes (`cmor_axis`).
> In the case of non-Cartesian longitude-latitude grids or for “station data”, define the grid and its mapping parameters (`cmor_grid` and `cmor_set_grid_mapping`)
> [...]

Then in the [cmor api documentation](https://cmor.llnl.gov/mydoc_cmor3_api/#cmor_grid)
> `cmor_grid()`
> [...]
> There is no need to call this function in the case of a Cartesian lat/lon grid. In this case, simply define the latitude and longitude axes and pass their id’s (“handles”) to cmor_variable.

I did, regrettably, not find an official definition of cartesian grid.

**Comment by goord** [comment]
Hi @zklaus I believe they are talking about rectilinear grids there which applies to our case. I will implement your suggestion and not use the cmor_grid() method in the IFS case but simply create lat/lon axes.

Note that the EC-Earth PRIMAVERA data has been cmorized with an older version so the HighresMIP submission has a 2D grid, @klauswyser do you think this is a problem?

**Comment by klauswyser** [comment]
No, I don't see any problem because the grid in the Primavera files is the same as in the coming CMIP6 files. I assume that the new CMIP6 will have 1-d lon/lat and bounds variables instead of 2-d as in the Primavera files, but there still will be a valid grid description in the new files that analysis tools such as ESMValTool can handle.

**Comment by zklaus** [comment]
In fact, certainly for ESMValTool the 1d case will be easier, but the 2d case should still be possible.

**Comment by goord** [comment]
Ok I will implement this.

**Comment by goord** [comment]
Hi Klaus and Klaus, I have enabled the regular lat/lon grid in ifs2cmor. You should be able to get 1D lat/lon arrays in the nc file by defining the environment variable
```
export ECE2CMOR3_IFS_GRID_2D=False
```
in your shell prior to the cmorization. Cab you perhaps do a small test, and if you reckon this is the preferred grid format, I will make this the default in ece2cmor?

**Comment by treerink** [comment]
What is the (testing) status here @zklaus  and @klauswyser?

**Comment by klauswyser** [comment]
I'd like to leave this question for @zklaus to answer, he wanted to have this in the ece2cmor3 tool. Unfortunately (for us) he has already left for vacation and won't be back before next year. I guess the tests have to wait.

**Comment by goord** [comment]
Made 1D grid representation the default in rev. 102380258fba71f1f66520f44f53b8b942ee8317
If you wish you can do further testing with esmvaltool. To keep the old-style 2D grid dimensioning, type ```
export ECE2CMOR3_IFS_GRID_2D=True
```
before calling ece2cmor.
