### ISSUE TITLE
temp and copy files

### ISSUE THREAD

**Issue by aearamos** [EC-Earth/ece2cmor3#334]
Hi @goord, 
When running cmorization I noticed that some years had a different size than others. Then, I noticed that a bunch of temp files were generated, together with .copy files of my netcdf.

Here are the files I have in my 6hPlevPt/va/gr/v20181129/ folder:
va_6hrPlevPt_EC-Earth3-LR_piControl_r1i1p1f1_grXpq0Or236485.nc
va_6hrPlevPt_EC-Earth3-LR_piControl_r1i1p1f1_gr_185001010000-185012311800.nc
va_6hrPlevPt_EC-Earth3-LR_piControl_r1i1p1f1_gr_185001010000-185012311800.nc.copy

Only one file is right and the other ones are just occupying space. Is there a reason for this temp and .copy files or is this maybe be a problem with my workflow (using Autosubmit here)?

Thanks!

**Comment by goord** [comment]
Hi Arthur, I think those files appear because the cmor library notices the target file already exists (we run in 'preserve' mode). Could it be you have va in the 6hrPlev table multiple times in your varlist? Perhaps on different pressure levels? We had this with the primavera cmorization, where e.g. ta27 and ta7h are both written to the same file ta_6hrPlev_....nc

**Comment by aearamos** [comment]
Hi Gijs, 
It can be. I noticed that this happened with some of the variables for the 6hrPlevPt table and also some variables in the day table. For some of these variables, I know I have them on daily and monthly frequencies, can that be a problem? I checked my xlsx table and I don't have the same variable multiple times in the same tab, only in different tabs (frequencies).

I'm running another year to see if I get a "clean" year.

**Comment by zklaus** [comment]
We observe the same problem. Indeed, `va` appears twice in the `6hrPlevPt` table, once from CMOR name `va` and once from CMOR name `va7h` and looking at the cmip6 tables, the two variables live on `plev3` and `plev7h` respectively. What's more is that both are actually requested by HighResMIP.

@goord: How did you solve this for PRIMAVERA?

**Comment by goord** [comment]
Hi @zklaus, only one of those is supposed to be produced (I believe this is mentioned in the variable comment?), so va with plev3 can be dismissed from the data request file if va7h is already in there. In primavera we manually removed those from the varlist json files.

**Comment by goord** [comment]
I could make a check in ece2cmor3 for identical output variable names, and throw an exception if they occur, forcing the user to fix his input data request. The other option, dismissing variables automatically, is not my preference. Note that if the user splits up his input variable list and runs the tool in multiple jobs, this check may still pass and lead to files being overwritten...

**Comment by zklaus** [comment]
I think an exception would be very good since really otherwise the output is invalid.

As for how to fix things, let's see what comes out of #253. If we end up creating json files instead of using directly the xlsx files from drq, that would be a good place to deal with these issues.

**Comment by goord** [comment]
rev. 4df29fb0bb94a7e1aca6f74f066cc8f49c3d6c7d
