### ISSUE TITLE
Enable the fx table for IFS

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#335]
If the "fx" table is enabled in `taskloader.py` by
`````
-        if sheetname.lower() in ["notes", "fx"]:
+        if sheetname.lower() in ["notes"]:
`````
we now get the following error with `drq2ppt.py:`
`````
INFO:ece2cmor3.taskloader:Created 130 ece2cmor tasks from input variable list.
Traceback (most recent call last):
  File "./drq2ppt.py", line 266, in <module>
    main()
  File "./drq2ppt.py", line 259, in main
    write_ppt_files(ece2cmorlib.tasks)
  File "./drq2ppt.py", line 69, in write_ppt_files
    if freq2 % freq1 == 0:
ZeroDivisionError: integer division or modulo by zero
`````

**Comment by goord** [comment]
So drq2ppt crashes on zero-frequency variables, which it should only adopt in the ppt00000000 file

**Comment by goord** [comment]
Hi @treerink can you test once more with the drq2ppt-fix branch?

**Comment by goord** [comment]
Fixed in rev. 560ef7190e5b8a8f68fa25287f353267a7175fdb

**Comment by treerink** [comment]
First we do once more the original test

**Comment by treerink** [comment]
It still needs the full test ...

**Comment by goord** [comment]
The fx variables in the experiment run at KNMI are being successfully processed, so I am closing this one.
