### ISSUE TITLE
IFS output for cmorisation

### ISSUE THREAD

**Issue by aearamos** [EC-Earth/ece2cmor3#341]
Hi @goord and @treerink 

I have a question regarding the structure of the ifs output after cmorisation. Here at BSC, with the previous versions of ece2cmor, we used to split the cmorisation into 12 different jobs, one for each month. The reason was because cmor would read each month separately and produce one output for each month, such as in:  
clt_Amon_EC-Earth3-LR_piControl_r1i1p1f1_gr_199001-199001.nc
clt_Amon_EC-Earth3-LR_piControl_r1i1p1f1_gr_199002-199002.nc
clt_Amon_EC-Earth3-LR_piControl_r1i1p1f1_gr_199003-199003.nc
and so on...

But now, when I run cmorisation with the last version, I noticed that ece2cmor computes every month at the same time and generates one single file, such as in

 clt_Amon_EC-Earth3-LR_dcppA-hindcast_r1i1p1f1_gr_185001-185012.nc

Does that behavior should be expected or is it because of the way we run here at BSC? The twelve months file seems correct, with all the dates and data. 

I'm thinking this can be related to the other issue I opened about the .copy and temp files I had before. 

Thanks for your help.

**Comment by goord** [comment]
Hi Arthur, yes since I merged the ifsyearly branch, ece2cmor processes the entire year, so no need for twelve jobs.

**Comment by goord** [comment]
You can speed up your job by (i) increase the number of subprocesses per node (option --npp) or (ii) split the data request (in a smart way...) and apply ece2cmor3 on the partial variable lists on separate nodes.

**Comment by aearamos** [comment]
Hi Gijs, the cmorisation is working fine. Thanks!
