### ISSUE TITLE
ece2cmor3 doesn't work anymore

### ISSUE THREAD

**Issue by nierad** [EC-Earth/ece2cmor3#345]
Hi all, 

probably an error I made but I can't quite solve it. Maybe you have come across it before. This is the error:
(ece2cmor3) [x_larni@aurora-rviz01 ece2cmor3]$ ece2cmor /lunarc/nobackup/users/x_larni/RUNDIR/ece2cmor_test_output --lpj --vars ece2cmor3/scripts/cmip6-data-request/cmip6-data-request-m\=CMIP-e\=CMIP-t\=1-p\=3/cmvmm_CMIP_TOTAL_1_3.xlsx --lpjgpar.json ece2cmor3/scripts/lpjguesspar.json --odir CMOR
Traceback (most recent call last):
  File "/home/x_larni/.conda/envs/ece2cmor3/bin/ece2cmor", line 11, in <module>
    load_entry_point('ece2cmor3==0.8.0', 'console_scripts', 'ece2cmor')()
  File "/home/x_larni/.conda/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-0.8.0-py2.7.egg/ece2cmor3/ece2cmor.py", line 97, in main
    if not os.path.isfile(args.conf):
  File "/home/x_larni/.conda/envs/ece2cmor3/lib/python2.7/genericpath.py", line 37, in isfile
    st = os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found

Any idea? 
I'll be off for two hours now. 

Thanks, Lars

**Comment by treerink** [comment]
Hi, so you tried:
`````
ece2cmor /lunarc/nobackup/users/x_larni/RUNDIR/ece2cmor_test_output --lpj --vars ece2cmor3/scripts/cmip6-data-request/cmip6-data-request-m=CMIP-e=CMIP-t=1-p=3/cmvmm_CMIP_TOTAL_1_3.xlsx --lpjgpar.json ece2cmor3/scripts/lpjguesspar.json --odir CMOR
`````
With the latest revision you have explicitly to add the metadata file (since yesterday):
`````
--conf ece2cmor3/resources/metadata-templates/cmip6-CMIP-piControl-metadata-template.json
`````
And this:
`````
--lpjgpar.json ece2cmor3/scripts/lpjguesspar.json
`````
Why do you use something else than the default? For the default (ece2cmor3/resources/lpjgpar.json) you can leave it out at all. Maybe the error concerns a syntax error in your local lpjguesspar.json?

A working NEMO example of mine:
`````
ece2cmor cmip6-ec-earth-output/t214/001/ --exp t214 --oce --conf ece2cmor3/resources/metadata-templates/cmip6-CMIP-piControl-metadata-template.json --vars ece2cmor3/resources/test-data-request/varlist-nemo-all.json --odir cmor-test-all-214
`````

**Comment by treerink** [comment]
So try for instance (only substitute your run label in the ????):
`````
ece2cmor /lunarc/nobackup/users/x_larni/RUNDIR/ece2cmor_test_output --exp ???? --lpj --conf ece2cmor3/resources/metadata-templates/cmip6-CMIP-piControl-metadata-template.json --vars ece2cmor3/scripts/cmip6-data-request/cmip6-data-request-m=CMIP-e=CMIP-t=1-p=3/cmvmm_CMIP_TOTAL_1_3.xlsx --odir CMOR
`````

**Comment by nierad** [comment]
I

**Comment by nierad** [comment]
@goord : Sorry, I don't understand your message.
