### ISSUE TITLE
Update for the new CMIP6 data request version 01.00.29

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#346]
The CMIP6 data request version 01.00.29 has just been released. Because `drq` in 01.00.28 appeared to be broken for CMIP experiments (see #331), we have to update to CMIP6 data request version 01.00.29.

**Comment by treerink** [comment]
The nested cmor tables are now in e7dfc71 based on data request version 01.00.29,

**Comment by goord** [comment]
Some tests are failing though... we need to update the cmor library too I guess

**Comment by treerink** [comment]
Will try that today

**Comment by treerink** [comment]
The failed tests are solved by solving #363.

**Comment by treerink** [comment]
All steps are now based on thel CMIP6 data request version 01.00.29. The identification part has been here repeated relying on all aspects on CMIP6 data request version 01.00.29.

Therfore closing this issue.
