### ISSUE TITLE
Switch off IFS model levels by default, but print grib codes

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#350]
Changing the 'magic' number from -99 (include all model levels) to  'magic' number -1 (excluding all model levels).

The grib codes are still printed for `MFP3DFS`. Does it also concern others?

What about the IFS volume estimate: check whether model level variables now still contribute (did they before?)?

**Comment by treerink** [comment]
https://dev.ec-earth.org/issues/568

**Comment by goord** [comment]
This is not the way to do it imo, as it will lead to many errors during cmorization: if the data request contains variables on model levels which are not in the provided model output, many errors will appear and I cannot guarantee that the whole process isn't going to fail.

**Comment by treerink** [comment]
Ok that doesn't sound good, so that means we have to do it differently.  I thought we discussed this extensively ... Anyway, in which direction are you thinking? For instance if we can distinguish at the level of the data request or just after reading the data request at the moment of creating the tasks that might be fine. For instance if there are model levels requested, we create in addition alternative ppt files which include them while the default ones do not include model levels?

**Comment by goord** [comment]
I can make a filter on IFS model levels in the taskloader, which then has to be enabled during the drq2ppt and cmorization, but I am hesitant to switch it on by default. There are others that are going to use this software which aren't part of CMIP6...

So how about we choose an environment variable, e.g. IFS_DISMISS_MODEL_LEVELS which automatically ignores the IFS model level tasks at loading. For CMIP6, we then agree to set this flag on during drq2ppt and cmorization of the output.

**Comment by treerink** [comment]
Maybe better to make this `dismiss_model_levels` an argument of both `drq2ppt` and `ece2cmor`, that keeps the documentation (help) more clear I would say?

**Comment by treerink** [comment]
Just to be sure we are on the same page:  we decided in the CMIP6 WG that the model levels won't be cmorized in any case, also if we do produce them for CORDEX.

**Comment by goord** [comment]
That's also an option.

Although note that I already have introduced 'custom options' to ece2cmor as environment variables to keep the main script simple but allow some flexibility:

- ECE2CMOR3_IFS_POSTPROC: set to 'false' to skip IFS post-processing (useful for debugging the cmorization step in ifs2cmor)
- ECE2CMOR3_IFS_CLEANUP: set to 'false' to skip cleaning up all temporary files
- ECE2CMOR3_IFS_NFRPOS: post-processing frequency used by ece2cmor3 whenever the auto-filtering is set false.
- ECE2CMOR3_IFS_GRID_2D: flag for representing the regular grid of atmosphere data as 2D array or not

**Comment by goord** [comment]
Hi Thomas I was not referring to CORDEX, but rather primavera, crescendo, etc. and some project of Frank Selten where he wants to use ece2cmor3.

**Comment by goord** [comment]
As discussed at knmi, I will add an option to the ece2cmor script to skip model level variables.

**Comment by goord** [comment]
The option has been added in merge caf9aa709feb96b0659e336ed725fd425ba36eae
