### ISSUE TITLE
NEMO crashes looking for 'time_centered' in a _1y_ file.

### ISSUE THREAD

**Issue by aearamos** [EC-Earth/ece2cmor3#351]
I'm not sure if this problem is way too specific, but today I had a problem with NEMO when running my fourth month (and fourth chunk) of a simulation because NEMO chose the file "a1mz_1y_19820201_19820228_opa_grid_T_2D" to exctract variable time_centered in nemo2cmor.py, line 151. For some reason, this file doesn't have the time_centered variable, as you can see here:

dimensions:
	axis_nbounds = 2 ;
	x = 362 ;
	y = 292 ;
	nvertex = 4 ;
	time_counter = UNLIMITED ; // (0 currently)
variables:
	float nav_lat(y, x) ;
		nav_lat:standard_name = "latitude" ;
		nav_lat:long_name = "Latitude" ;
		nav_lat:units = "degrees_north" ;
		nav_lat:bounds = "bounds_nav_lat" ;
	float nav_lon(y, x) ;
		nav_lon:standard_name = "longitude" ;
		nav_lon:long_name = "Longitude" ;
		nav_lon:units = "degrees_east" ;
		nav_lon:bounds = "bounds_nav_lon" ;
	float bounds_nav_lon(y, x, nvertex) ;
	float bounds_nav_lat(y, x, nvertex) ;
	float area(y, x) ;
		area:standard_name = "cell_area" ;
		area:units = "m2" ;
	float areacello(y, x) ;
		areacello:standard_name = "cell_area" ;
		areacello:long_name = "Horizontal area of ocean grid cells" ;
		areacello:units = "m2" ;
		areacello:online_operation = "once" ;
		areacello:cell_measures = "area: area" ;
		areacello:_FillValue = 1.e+20f ;
		areacello:missing_value = 1.e+20f ;
		areacello:coordinates = "nav_lat nav_lon" ;
	float sftof(y, x) ;
		sftof:standard_name = "sea_ice_area_fraction_in_percent" ;
		sftof:long_name = "Sea-ice area fraction in percent" ;
		sftof:units = "%" ;
		sftof:online_operation = "once" ;
		sftof:cell_measures = "area: area" ;
		sftof:_FillValue = 1.e+20f ;
		sftof:missing_value = 1.e+20f ;
		sftof:coordinates = "nav_lat nav_lon" ;
	float basin(y, x) ;
		basin:standard_name = "ocean_tracer_region_masks" ;
		basin:long_name = "ocean tracer region masks" ;
		basin:units = "1.0" ;
		basin:online_operation = "once" ;
		basin:cell_measures = "area: area" ;
		basin:_FillValue = 1.e+20f ;
		basin:missing_value = 1.e+20f ;
		basin:coordinates = "nav_lat nav_lon" ;
	float hfgeou(y, x) ;
		hfgeou:standard_name = "upward_geothermal_heat_flux_at_sea_floor" ;
		hfgeou:long_name = "Upward geothermal heat flux at sea floor" ;
		hfgeou:units = "W m-2" ;
		hfgeou:online_operation = "once" ;
		hfgeou:cell_measures = "area: area" ;
		hfgeou:_FillValue = 1.e+20f ;
		hfgeou:missing_value = 1.e+20f ;
		hfgeou:coordinates = "nav_lat nav_lon" ;

// global attributes:
		:name = "a1mz_1y_19820201_19820228_opa_grid_T_2D" ;
		:description = "Created by xios" ;
		:title = "Created by xios" ;
		:Conventions = "CF-1.6" ;
		:timeStamp = "2018-Dec-18 14:08:25 GMT" ;
		:uuid = "9fb0ec51-ec86-4e23-9258-6b56064552f4" ;
}

Is there a way to tell nemo2cmor to always choose another file, instead of this yearly file, that may have time_centered? What's the cleanest solution here?
Also, how can I make sure this file has this variable?

Edit 1: I realized this file doesn't have time_centered because it's not requested by the variables, but how can I make sure cmor looks for a file that has the variable? 

Thanks

**Comment by goord** [comment]
Hi Arthur, can you post the log output before the crash appears? Does ece2cmor report for which table it is trying to create a time axis?

**Comment by aearamos** [comment]
Hi Gijs, here is the log. It makes sense to me not to have the time_centered variable, since I'm not using this in any of the variables in the file. It doesn't tell me which table since it's right at the beginning of cmorisation.

a1mz_1y_19820201_19820228_opa_grid_T_2D
Traceback (most recent call last):
  File "./ece2cmor.py", line 151, in <module>
    main()
  File "./ece2cmor.py", line 136, in main
    ece2cmorlib.perform_nemo_tasks(args.datadir, args.exp, refdate)
  File "/gpfs/scratch/pr1eel00/pr1eel17/a1mz/auto-ecearth3/ece2cmor/ece2cmor3/ece2cmorlib.py", line 188, in perform_nemo_tasks
    if not nemo2cmor.initialize(datadir, expname, tableroot, refdate):
  File "/gpfs/scratch/pr1eel00/pr1eel17/a1mz/auto-ecearth3/ece2cmor/ece2cmor3/nemo2cmor.py", line 59, in initialize
    cal = read_calendar(f)
  File "/gpfs/scratch/pr1eel00/pr1eel17/a1mz/auto-ecearth3/ece2cmor/ece2cmor3/nemo2cmor.py", line 372, in read_calendar
    timvar = ds.variables["time_centered"]
KeyError: 'time_centered'

**Comment by aearamos** [comment]
The problem was fixed with the last push.
