### ISSUE TITLE
setup.py InvalidGitRepositoryError

### ISSUE THREAD

**Issue by jmcgove** [EC-Earth/ece2cmor3#353]
In the latest ece2cmor trunk, activating ece2cmor environment ok.  
`python setup.py install` gives
```
File "/perm/ms/ie/dujm/miniconda2/envs/ece2cmor3/lib/python2.7/
site-packages/git/repo/base.py", line 168, in __init__
    raise InvalidGitRepositoryError(epath)
git.exc.InvalidGitRepositoryError: /perm/ms/ie/dujm/p-process/ece2cmor3/trunk
```
@treerink you got this before? As if invalid git repository? svn info gives
`Repository Root: https://github.com/EC-Earth/ece2cmor3.git/trunk.` Looks like temp connection issue, though got this few days ago too (that part was fine before).

`./ece2mor.py `gives `ImportError: No module named ece2cmor3` For this I updated the ece2cmor environment - do other modules need to be loaded (this could just be because of setup.py)

**Comment by goord** [comment]
Hi Jonathan, will fix this problem asap

**Comment by jmcgove** [comment]
Hi Gijs, updated the latest changes, setup.py works now, thanks. Yes i use subversion svn up.
