### ISSUE TITLE
3- and 6-hourly averages in ifs2cmor time bounds

### ISSUE THREAD

**Issue by goord** [EC-Earth/ece2cmor3#354]
ifs2cmor3 creates symmetric time bounds around the ifs variables, but this is incorrect for 3- and 6-hourly averaged fields (e.g. fluxes), which have been accumulated before the time point, so which have their time coordinate at the end of the averaging interval.

**Comment by goord** [comment]
Hi Klaus I have been thinking about this as well, the times we report are shifted to get the correct daily averages. It is not incorrect, the time bounds are what really matters for averages imo, but it would be more transparent to shift them back before calling the cmor library

**Comment by klauswyser** [comment]
This is certainly possible, but is it good? One issue with that solution already mentioned above is that if users take all 3-hourly fluxes from a given day and compare it to the daily average for the same day they will find a mismatch. Another issue is that we then will not have any data for 00Z of the last day and instead a last timestep at 00Z of the first day after the end of the simulation. I personally think that it therefore would be better to leave the times as they are and just fix the time_bnds, but that's my opinion and others may think differently. Shall we bring this question forward to the CMIP6 WG of the EC-Earth consortium?

**Comment by goord** [comment]
Hi Klaus, that's fine, we can discuss next CMIP6 WG telco, in any case I can start fixing the time bounds issue, no ambiguity there.

**Comment by klauswyser** [comment]
Sure, go ahead. I still would like to bring the question forward to the CMIP6 WG sooner than the next telco (next week? I haven't heard anything yet about the date) to make people aware of the problem so we really can take a descision at the telco.

**Comment by jhardenberg** [comment]
This should not be a matter of discussion, but a CMIP specification. Comparison with CMIP5 shows that then for example for the 3h files we recorded fractional hours (1:30, 4:30 etc). The variable had the attribute "pr:cell_methods = "time:mean (interval: 3 hours)"  so it seems logical that the timestamp lies at the center. time_bnds would then be [0:00,3:00],[3:00,6:00]" etc...

**Comment by noije** [comment]
I don't see why this wouldn't be the same for sub-daily fields as for daily, monthly or yearly accumulated fields or averages?

**Comment by jhardenberg** [comment]
In any case it works out. If you do the mean of 8 daily fluxes at [1:30, 4:30 ... 22:30] you get a daily mean center date of exactly 12:00 ....

**Comment by klauswyser** [comment]
Thanks for the interesting discussion! I think we all agree that ``time_bnds`` should be [0 3],[3 6],[6 12],... for the 3-hourly accumulated fields. And I didn't know that you can save your data with timesteps other than 00, 03, 06, ..., that's good news. So it would be possible to set
````
time = [ 1.5, 4.5, 7,5...
````
for 3-hourly fluxes which would be fine. Only we (and other users) have to be aware that if we do so then the time axis in say the 3-hourly temperature field differs from the time axis in the 3-hourly precipitation or radiation fields. Is that acceptable?

**Comment by goord** [comment]
Fixed in pull request #386
