### ISSUE TITLE
Spotted trouble with grib code 138 at SMHI

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#357]
At SMHI they struggle currently with grib code 138, leading to segmentation faults. I did not encounter the problem so far at the HPC of KNMI.

@goord quick checking with you, any idea if something changed at our side with respect to 138?

https://dev.ec-earth.org/issues/403#note-123

Uwes comment:
It's variable no. 138 in FP3DFP. If I take it off the list, everything works fine. If I include it, the model crashes. This is in the 3d pressure level output on grid points, if I'm not mistaken.

Klaus commented:
Variable 138 is relative vorticity.

**Comment by ufladrich** [comment]
Another piece of information around this: I made a test (following one of Klaus' suggestions) to see if the segfault is influenced by the setting of `NRFP3S`. Both `NRFP3S=-1` (no levels written) and `NRFP3S=-99` (all levels written) will crash, as soon as 138 is in `MFP3DFP`.

**Comment by treerink** [comment]
Close this here, seems to be not at the ece2cmor3 side.
