### ISSUE TITLE
Fraction vs percent in LPJG output

### ISSUE THREAD

**Issue by klauswyser** [EC-Earth/ece2cmor3#359]
I just tested cmorising the  LPJG output, there are still a few missing variables but I think this is already taken care of. But what seems to be a problem are the units in the output, for many fields the units are set as % despite teh variable being saved as fraction. I guess the units should be fraction (or 1?) because the name of the variables are e.g. baresoilFrac, cropFrac, etc

**Comment by etiennesky** [comment]
Hi @klauswyser in CMIP6 most fractions are expressed in %, and the variable names were not changed. This is the case for sea-ice concentration which is now in %.  Maybe this is the same for the  land variables as well?

This seems to be the case for bareSoilFrac (see http://clipc-services.ceda.ac.uk/dreq/u/9cdb8d54d49e98acadd87e2a1139225e.html) 

```
1.2 MIP Variable: [baresoilFrac] Bare Soil Percentage Area Coverage
Comment on this page:Reload annotations

Home → 1.2 MIP Variable section index
procnote[i]: ('',)
description[i]: Percentage of entire grid cell that is covered by bare soil.
title[i]: Bare Soil Percentage Area Coverage
prov[i]: CMIP5_Lmon,PMIP3_Lclim,PMIP3_Lmon,SPECS_Lmon
unid[i]: [units] percentage [fd6ee984-3468-11e6-ba71-5404a60d96b5]
label[i]: baresoilFrac
provmip[i]: [mip] CMIP5 [CMIP5]
1.8 CF Standard Names [sn[i]]: AreaFraction
units[i]: %

```

**Comment by etiennesky** [comment]
therefore fractions have to be multiplied by 100 and stored as %

**Comment by nierad** [comment]
Hi, @klauswyser @etiennesky thanks for letting us know, we'll take care of it!

**Comment by nierad** [comment]
Thomas @treerink, can't we simply use the "convert":"frac2percent" functionality as is implemented in ifspar.json?  

The below snippet of code in the generate-lpjguess.json.sh would do:

`
function add_item {
 echo '    {'                     >> ${output_file}
 echo '        "source": "'$1'",' >> ${output_file}
 case $1 in
     *Frac*); echo '        "convert": "frac2percent",' >> ${output_file}
	 ;;
 esac
 echo '        "target": "'$1'"'  >> ${output_file}
 echo '    },'                    >> ${output_file}
}

function add_last_item {
 echo '    {'                     >> ${output_file}
 echo '        "source": "'$1'",' >> ${output_file}
 case $1 in
     *Frac*); echo '        "convert": "frac2percent",' >> ${output_file}
	 ;;
 esac
 echo '        "target": "'$1'"'  >> ${output_file}
 echo '    }'                     >> ${output_file}
}` 
What do you think?

**Comment by treerink** [comment]
Idea is good I think: easy to maintain. I had to correct a  bash syntax with case-case in `generate-lpjguess.json.sh` and cleaned the code.

**Comment by treerink** [comment]
Solved in 8bba20a

Removed the lpjg branch, please do not use this one anymore please.

**Comment by nierad** [comment]
Thanks Thomas. That's great. Will you also use the updated lpjg2cmor.py from the lpjg-branch?

**Comment by nierad** [comment]
Ok, I will not!

**Comment by treerink** [comment]
The `lpjg2cmor.py` is updated in 8bba20a see:
https://github.com/EC-Earth/ece2cmor3/commit/8bba20ad4b14033f8eba29edef8aec3eec25a62a
