### ISSUE TITLE
Check IFS volume estimates

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#367]
The current piControl run shows that the IFS output is 84 GB per year, this seems far less than the volume estimates give.

**Comment by tommibergman** [comment]
Without CMORisation? If so, maybe part of the difference comes from spectral and reduced grid?

**Comment by goord** [comment]
That we have taken into account. We just need to count grib messages, in both GG and SH files and compare against our estimates.

**Comment by treerink** [comment]
The IFS volume estimates in the volum-estimate* files in the control output files are not correct, we did not found time to address this so far. The best way to estimate your Volume, simply is: run EC-Earth for 2 years, and cmorise the second leg, take that estimate and multiply it by the number of years you will run your experiment.

**Comment by treerink** [comment]
The IFS estimate does not linearly extent in the vertical. Best estimate method: run & cmorise 1 year.

This issue is closed after it has been added to the [Cold case issues](https://github.com/EC-Earth/ece2cmor3/wiki/Cold-case-issues).
