### ISSUE TITLE
Change for the cmor-3.4.0 library from the PCMDI to conda-forge 

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#370]
Finally a main built has released for the cmor-3.4.0 library, and it contains a version with the correct hdf5 1.10 and libnetcdf =4.6 dependencies we need. So we can change now from:
https://anaconda.org/PCMDI/cmor/files
to
https://anaconda.org/conda-forge/cmor/files

A nice thing is that the linux and mac cmor libraries in this conda-forge have the same names, so as a consequence it will be possible to use one `environment.yml` from now on, which simplifies the installation guide lines.

**Comment by tommibergman** [comment]
With Mac the nosetests are all okay for the current master.

**Comment by treerink** [comment]
The cmor-3.4.0 library is used now, and the linux and mac os install procedure have become identical.

Closing.
