### ISSUE TITLE
cmor . load_table error

### ISSUE THREAD

**Issue by aearamos** [EC-Earth/ece2cmor3#373]
Hi @goord,

I'm running CMOR 3.3, table version 1.00.28 and got some errors I didn't have before:
!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: Reading table grids: axis name: 'time2' for variable: 'eta2' is not defined in table. Table defines dimensions: 'longitude latitude time2' for this variable
!
!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: Reading table grids: axis name: 'time1' for variable: 'ps1' is not defined in table. Table defines dimensions: 'longitude latitude time1' for this variable
!
!!!!!!!!!!!!!!!!!!!!!!!!!

they all come with warnings such as in:
!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Warning: attribute for unknown section: time3,{ "standard_name": "time", "units": "days since ?", "axis": "T", "long_name": "time", "climatology": "yes", "formula": "", "must_have_bounds": "yes", "out_name": "time", "positive": "", "requested": "", "requested_bounds": "", "stored_direction": "increasing", "tolerance": "", "type": "double", "valid_max": "", "valid_min": "", "value": "", "z_bounds_factors": "", "z_factors": "", "bounds_values": "", "generic_level_name": "" } (table: )
!
!!!!!!!!!!!!!!!!!!!!!!!!!

I asked my sys admin to update the version of CMOr to CMOR 3.4, but I'm not sure that's the reason why it's not working. This error is new for me and I never had it before. 

I believe these "eta", "ps" and "time2" variables are related to the CMIP6_formula_terms.json table, right? 

Thank you for your help.

**Comment by treerink** [comment]
Note drq is broken for the CMIP experiments in data request version 01.00.28.

Don't you install ece2cmor3 under anaconda, so you have all the permissions yourself?

**Comment by aearamos** [comment]
But drq is not being used in that case, is it? I mean, not directly. 
I'm not using anaconda, only our own environment. I'm waiting for CMOR 3.4 to be installed so I can try again.

**Comment by treerink** [comment]
The cmorization does not use `drq` itself. However it is important that you use the cmor-3.4.0 library, the latest cmor tables (based on data request version 01.00.29) and dreq(drq) version 01.00.29, so it is matching all together. As long you use the just updated `environment.yml` file to install without changes, you are fine.

**Comment by aearamos** [comment]
Hi @treerink thanks for the info! I actually found the error. There was an extra line when I was trying to add another plev to CMIP6_coordinates.json (to use in one of our internal experiments) and the file couldn't be read thoroughly.

Now it works! I'll update to the last version of CMOR and dreqPy anyway.
