### ISSUE TITLE
Variables in subhr table should be ignored?

### ISSUE THREAD

**Issue by tommibergman** [EC-Earth/ece2cmor3#374]
I get error with two variables that are in CFsubhr table. I think these should be  in the ignored list, since we are not providing any subhr variables.

[u'phalf', 'CFsubhr'], [u'ps', 'CFsubhr']

**Comment by treerink** [comment]
related to #342

**Comment by treerink** [comment]
I expect to be able to fixthis one today or tomorrow ...

**Comment by treerink** [comment]
Should be fixed.

Closing.
