### ISSUE TITLE
computing monthly hurs from 6hr hurs, but not saving 6hr and daily hurs

### ISSUE THREAD

**Issue by etiennesky** [EC-Earth/ece2cmor3#375]
Hi, I would like to know  how hurs is somputed for the monthly tables, is it first computed using 6hr tas and tdps, and then daily/monthlyt means are computed?

Or is it the other way around, that monthly hurs is computed from monthly tas and tdps?

If the second is used, then this can be a problem since it will be wrongly computed.

And the follow up question is would it be possible to compute hurs (and hursmin) from the 6hr data, but without saving 6hr data in the end. 

Thanks!  @aearamos

**Comment by goord** [comment]
Hi Etienne, it is your first guess. From my output:
```
INFO:ece2cmor3.postproc:Post-processing target hurs in table Amon from file /lustre3/projects/PRIMAVERA/oord/primavera/s2hh/tmp/s2hh-ifs-199201/168.128.105_167.128.105.3 with cdo command -monmean -expr,'var80=100.*exp(17.62*((var168-273.15)/(var168-30.03)-(var167-273.15)/(var167-30.03)))' -setgridtype,regular -selcode,168,167
```
The time aggregation occurs after the expression evaluation. Here the mapping to the regular grid occurs before the nonlinear expression, I have already changed this for a better accuracy.

**Comment by goord** [comment]
Regarding your follow up question: yes, it is possible to compute hurs/hursmin/hursmax without cmorizing tas and tdps, as long as grib codes 167 and 168 are in your output with reasonable frequency (3 or 6 hours).

**Comment by etiennesky** [comment]
ok thanks for such a quick reply. what if you have hurs for both daily and monthly, the computation is done twice?

**Comment by etiennesky** [comment]
thanks a lot!

**Comment by goord** [comment]
The filtering is done once, but the postprocessing twice

**Comment by etiennesky** [comment]
Hi @goord re-opening this issue because I am trying to find the origin of the formulas used to compute hurs (defined in ifspar.json).

```
"expr": "100.*exp(17.62*((var168-273.15)/(var168-30.03)-(var167-273.15)/(var167-30.03)))"
```

This differs slightly from the ECMWF recommendation given here https://confluence.ecmwf.int/display/CKB/ERA-Interim+documentation

```
Relative humidity should be calculated: RH = 100 * es(Td)/es(T)
The relative humidity can be calculated with respect to saturation over water, ice or mixed phase by defining es(T) with respect to saturation over water, ice or mixed phase (water and ice). The usual practice is to define near-surface relative humidity with respect to saturation over water.
```
If you dig into the IFS documentation the formula is a bit different - see p. 155 of https://www.ecmwf.int/sites/default/files/elibrary/2016/17117-part-iv-physical-processes.pdf#subsection.7.4.2

**Comment by goord** [comment]
Hi Etienne, I have rewritten the numerator and denominator (saturation over water at dewpoint and 2m temperature as a single exponent:
```
RH=100*exp{a3*((Td - T0)/(Td - a4) - (Ts - T0)/(Ts - a4))}
```
Where ``a3=17.62`` and ``a4=30.03``, these parameters were copied from the old version of ece2cmor in EC-Earth. I see that ``a4`` differs slightly from the ECMWF recommendation, which in its turn differs from e.g. [this version of Teeten's formula](http://glossary.ametsoc.org/wiki/Tetens%27s_formula)

**Comment by etiennesky** [comment]
Thanks @goord I see that the previous version of ece2cmor3 was maintained by @klauswyser with prior work from @pabretonniere and others - maybe he remembers where those parameters come from?

https://dev.ec-earth.org/projects/ecearth3/repository/revisions/4062/entry/ecearth3/tags/3.2.2/sources/util/ece2cmor/run_ece2cmor.sh
```
           cdo -s setcode,101 -expr,"e_t=611.*exp(17.62*(var167-273.15)/(var167-30.03))" ${file}_167.128.grb e_t.grb
           cdo -s setcode,102 -expr,"e_t=611.*exp(17.62*(var168-273.15)/(var168-30.03))" ${file}_168.128.grb e_td.grb
           # rel humidity
           cdo -s setparam,80.128 -mulc,100 -div e_td.grb e_t.grb ${file}_80.128.grb
```

**Comment by treerink** [comment]
Closing. Please reopen if still relevant. But we have lived already so long with the situation as it is, so we decided to leave it like this.
