### ISSUE TITLE
Add timestamps to logging

### ISSUE THREAD

**Issue by ufladrich** [EC-Earth/ece2cmor3#378]
It would be helpful if the log output lines where preceded by timestamps. This would help for manual inspection, but even more when using log file analysis tools (I'm using [lnav](http://lnav.org), for example).
This could be easily achieved by adding a `format` argument to the `logging.basicConfig() `calls in `ece2cmor.py`, such as in
```
diff --git a/ece2cmor3/ece2cmor.py b/ece2cmor3/ece2cmor.py
index 0bd5d46..71159fd 100755
--- a/ece2cmor3/ece2cmor.py
+++ b/ece2cmor3/ece2cmor.py
@@ -85,9 +85,9 @@ def main(args=None):
         dirs = os.path.abspath(args.datadir).split(os.sep)
         fname = '-'.join([args.exp] + dirs[-2:] + [time.strftime("%Y%m%d%H%M%S", time.gmtime())])
         logfile = '.'.join([fname, "log"])
-        logging.basicConfig(filename=logfile, level=logging.DEBUG)
+        logging.basicConfig(filename=logfile, level=logging.DEBUG, format='%(asctime)s %(levelname)s:%(name)s: %(message)s', datefmt='%Y-%m-%d %H:%M:%S')
     else:
-        logging.basicConfig(level=logging.DEBUG)
+        logging.basicConfig(level=logging.DEBUG, format='%(asctime)s %(levelname)s:%(name)s: %(message)s', datefmt='%Y-%m-%d %H:%M:%S')
 
     if not os.path.isdir(args.datadir):
         log.fatal("Your data directory argument %s cannot be found." % args.datadir)
```
(realising that you may have opinions about _how_ the arguments where added; it's just an example)

**Comment by goord** [comment]
Hi Uwe I just invited you to the EC-Earth github organization, can you make a pull request with this modification?

**Comment by ufladrich** [comment]
Does this mean I should have write access to the repository (apparently I haven't) to make a branch. Or do you want me to make a pull request from a clone?

**Comment by goord** [comment]
Ok sorry Uwe, you should now be able to create a branch locally with your changes, push it to the github repo and send a pull request. Then either me or @treerink should merge the pull request. I changed some permissions so I hope it behaves as expected...

**Comment by ufladrich** [comment]
Hm, still get
```
> git push origin log-add-timestamp
Username for 'https://github.com': ufladrich
Password for 'https://ufladrich@github.com': 
remote: Permission to EC-Earth/ece2cmor3.git denied to ufladrich.
fatal: unable to access 'https://github.com/EC-Earth/ece2cmor3.git/': The requested URL returned error: 403
```

**Comment by goord** [comment]
You need to accept the invitation to join the EC-Earth organization on github

**Comment by ufladrich** [comment]
Maybe a naive question, but: Where/how do I accept the invitation?

**Comment by goord** [comment]
You haven't received an email?

**Comment by ufladrich** [comment]
As suspected: a naive question. Yes, I did receive an email, but I overlooked it. Now I'm in the club and I was able to push my branch. Thanks for pointing me to the right track!

**Comment by treerink** [comment]
We should add the time stamps to the other scripts too perhaps...

**Comment by goord** [comment]
Done, so closing....
