### ISSUE TITLE
Global and Climatological CH4, O3

### ISSUE THREAD

**Issue by tommibergman** [EC-Earth/ece2cmor3#382]
It seems that if there is actual field of ch4 or O3 available, the global and climatological fields should be omitted. So for AerChem version we should only produce ch4 and o3 and leave out ch4Clim, ch4global, ch4globalClim, and o3Clim.  So the latter ones can be moved to ignored list.

For the other versions at the moment ch4 or o3 is not produced at all. They are basically the boundary conditions, and in any case there you should produce one of the climatological values since it is prescribed.

**Comment by zklaus** [comment]
This links with #334 which also deals with variables that appear more than once in the same table.
On the chemical side of things one might add co2, co2mass, n2o, n2oglobal, and o3.

**Comment by tommibergman** [comment]
co2 and co2mass are to my understanding not available in IFS or TM5. For IFS my understanding is that only the mean concentrations are used? 

Only in C-Cycle version actual field of CO2 is transported in TM5, but I was told that for this there is no need for output from TM5. Has this changed?

N2o is not available in either IFS or TM5.

**Comment by treerink** [comment]
`co2Clim` & `co2massClim` are added to the ignored list because `co2` is not available in either IFS or TM5, see also #320.

**Comment by treerink** [comment]
This issue is taken over by #441 and by a post in #440 for o3 to ignore the Clim variant.

So closing this one.
