### ISSUE TITLE
phalf on Amon table should be ignored

### ISSUE THREAD

**Issue by tommibergman** [EC-Earth/ece2cmor3#385]
phalf, so the pressure at half levels (interface between two levels), is now coming only from TM5. The variables in Amon table are generally from IFS and TM5 is not available in most of the MIPs. Also in Amon pfull is produced by IFS, so there would be a resolution miss-match between the two.

So if this variable is not available from IFS we should ignore the combination phalf-Amon. 

In AerChemMIP phalf will still be provided for the table AERmon when requested.

**Comment by tommibergman** [comment]
related to #282

**Comment by treerink** [comment]
`phalf` is not in the `ifspar.json`. And in can't find [here](https://confluence.ecmwf.int//display/OIFS/How+to+control+OpenIFS+output#HowtocontrolOpenIFSoutput-Pressureleveloutput) any description on pressure on vertical staggered levels, @goord agree?

So I propose to ignore: `Amon` `phalf`

**Comment by treerink** [comment]
Done, so closing.
