### ISSUE TITLE
What to do with 3hr tos for AMIP

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#389]
The `3hr` `tos` for an AMIP run needs to be taken from NEMO. The confusing thing here is that the request asks for `tos` from the ocean grid cell. What do we do? Ignore that latest fact, and just provide it from IFS (the forced and interpolated field). Or do we ignore this variable for this table for AMIP?

**Comment by treerink** [comment]
I am voting for ignoring, other opinions?

**Comment by goord** [comment]
Why did you move the Amon tos to the ignored file? This is an important variable for amip experiments...

**Comment by treerink** [comment]
Ok this ignoring of `3hr` `tos` (if) should of course only happen for the AMIP experiment when NEMO is not available, so it needs to be handled in the (to be created) perference file. Therefore correcting the current changes which cause the ignoring of `3hr` `tos` in all cases #393.

**Comment by treerink** [comment]
We will ignore the `tos` `3hr` combination for AMIP. The preference file will take care of this.

**Comment by goord** [comment]
We have removed tos from the IFS parameter file altogether as there doesn't seem to be a request for it on the atmospheric grid.
