### ISSUE TITLE
Surface pressure variable ps

### ISSUE THREAD

**Issue by tommibergman** [EC-Earth/ece2cmor3#390]
I noticed that variable for surface pressure _ps_ is in many different tables. However, it is marked to be from TM5, which is only available for AerChemMIP. Is there a reason not to produce this from IFS, or is it just a mistake. I think surface pressure is always present in the IFS output anyway.

**Comment by tommibergman** [comment]
related to #224

**Comment by aearamos** [comment]
Hi @tommibergman, @goord, and @treerink I too recently noted the problem with ps. So, before issue #224 is closed it won't be possible to output cmorised ps from IFS? Is that correct? 

I've tried different ways and just now decided to have a look in the issues. 

At first, I thought it was a problem with land/sea mask, so I added 172 to my pptd files, and now I can see the "Post-processing with cdo command" part in my log file. I can also find ps_Amon.nc in my tmp_folder, but it doesn't cmorize all the way to the end. Is there a fix for that or do we wait for the other issue to be implemented?

Thanks.

**Comment by treerink** [comment]
@aearamos indeed is `ps` part of the newly setup `preferences file` (see 3ae9a712f0e06dfb52d051abc400a64a49d1d712). So indeed when #224 and #253 are solved then this issue should be solved as well. Because then if will take the `ps` from IFS in case TM5 is not active in your model configuration.

**Comment by goord** [comment]
As discussed, ps in the AER(mon/6hr) tables is produced by tm5 cmorization, in the other tables by ifs. So closing.
