### ISSUE TITLE
negative values for rsus and rsuscs

### ISSUE THREAD

**Issue by aearamos** [EC-Earth/ece2cmor3#400]
Hi, @treerink and @klauswyser ,
I'm not sure this is the right place to report it, but there's no "IFS CMIP6 data quality control"  issue in the EC-Earth portal, so I decided to put it here. here at BSC we found that variables rsus and rsuscs, produced by ece2cmor, following the ifspar.json file, have some negative values close to Antarctica, which we think should not be the case. Maybe it's a problem with the inteporlation, maybe it's related to IFS, but we can't figure out the problem. 

Did anybody else see this problem? 

Here are some plots showing the wrong negative values (the figures are upside down):

![rsus_anom_feb](https://user-images.githubusercontent.com/4387474/53248277-a6630b00-36b5-11e9-8925-74a4590ecec8.png)
![rsuscs_anom_feb](https://user-images.githubusercontent.com/4387474/53248280-a7943800-36b5-11e9-9e29-12d5987ad08a.png)
![rsuscs_feb](https://user-images.githubusercontent.com/4387474/53248281-a7943800-36b5-11e9-856a-eab4343dcdf2.png)
![rsus_feb](https://user-images.githubusercontent.com/4387474/53248282-a7943800-36b5-11e9-8439-22e558d0c515.png)

**Comment by goord** [comment]
Hi Arthur, this does look like an interpolation issue at the gradient along the coast of Antarctica...

you can use cdo to mimic the steps of ece2cmor3 to produce these upwelling fluxes from the raw ifs output yourself and see whether cdo's interpolation to a regular grid causes this, or the evaluation of the expression itself...

**Comment by goord** [comment]
BTW Klaus the formulas for rsus and rsuscs are the same, not sure what else we're supposed to give there:
```
rsus(cs) = SSR - SSRD
```
The downwelling clear-sky radiation is SSRC (the net surface clear-sky solar radiation) minus the expression above. Does this choice of splitting up SSRC into up- and downwelling components make sense?

**Comment by goord** [comment]
I guess the double radiation call should provide us with the actual rsuscs...

**Comment by klauswyser** [comment]
I know that we save SSRC in IFS, but how about SSRCD? Where does the downwelling clear-sky radiation come from that you need to compute the upwelling flux?

**Comment by goord** [comment]
Hi Klaus, SSRCD is not available in IFS, it is computed by us under the assumption that the upwelling component rsuscs is equal to rsus.

I doubt whether these two fluxes are correct... unless they are used in combination as a net flux.

**Comment by goord** [comment]
So I was wondering whether the double radiation call could give us a **real** downwelling clear sky solar flux...

**Comment by klauswyser** [comment]
Now I understand your assumption, but I am afraid to say that it's wrong. The correct way would be to compute the SFC albedo from SSR and SSRD and then apply it on SSRC to get SSRCD and SSRCU.
````
ALB = 1 - SSR/SSRD
SSRCD = SSRC/(1-ALB)
SSRCU = SSRCD * ALB = SSRC * ALB/(1-ALB)
````
This of course only works where SSRD>0.

**Comment by goord** [comment]
Aha that's the trick! But I guess the albedo is the instantaneous field, so instead of calculating it, would grib code 174 do the job as well?

Btw do you have a clue what's going on above with the negative rsus?

**Comment by klauswyser** [comment]
I am not 100% sure about ALBF (=parameter 174) for 2 reasons:
1. What exactly is 174, is it really the broadband albedo or just from one band?
2. Radiation are an accumulated value, but 174 is instantaneous. It could happen that a cloud is there just at 00Z, but all 3 hours before have been cloud free, so your ALBF value is definitely different from the one derived from the averaged radiation over the last 3 hours,

I tend to agree with you that the negative values are rounding errors. Alternatively it could be a problem with the midnight sun at high latitudes, but not sure.

**Comment by goord** [comment]
Hi Klaus, it turns out albf is the background albedo, I think the forecast albedo fal (code 243) is what we can use:

Albedo as used by the IFS, consisting of a background albedo, modified over the ocean dependent on solar elevation and modified over land areas with snow.

This is again an instantaneous field, but isn't that more accurate than derived mean albedo's from the cloudy-sky fluxes? Given the net clear-sky flux, wouldn't IFS distribute the reflected and absorbed fluxes using this instantaneous parameter?

**Comment by goord** [comment]
Below I post monthly means of the shortwave surface fluxes. The clear-sky fluxes were calculated with ece2cmor3 using the forecast albedo 143 and the net clear-sky flux. Again we see outliers (which I color-scaled away) around the antarctic ice sheet, where both the albedo and the net clear-sky flux are high  
![rsds_Amon](https://user-images.githubusercontent.com/5041758/54818966-d09aef00-4c9a-11e9-8087-353acc28f534.png)
![rsdscs_Amon](https://user-images.githubusercontent.com/5041758/54818975-d42e7600-4c9a-11e9-89fb-ea1002445dc2.png)
![rsus_Amon](https://user-images.githubusercontent.com/5041758/54818979-d690d000-4c9a-11e9-8151-b5039ee93ac9.png)
![rsuscs_Amon](https://user-images.githubusercontent.com/5041758/54818982-d98bc080-4c9a-11e9-8cdc-1d6a74f89c1f.png)

**Comment by klauswyser** [comment]
> it turns out albf is the background albedo, I think the forecast albedo fal (code 243) is what we can use:
> [...}
> This is again an instantaneous field, but isn't that more accurate than derived mean albedo's from the cloudy-sky fluxes? Given the net clear-sky flux, wouldn't IFS distribute the reflected and absorbed fluxes using this instantaneous parameter?

Yes, you should indeed use ALBF (parameter 243) _if_ you want use the albedo for computing the upwelling fluxes. But then again, I am still not convinced that combining instantaneous albedo with time averaged fluxes is working flawlessly. Have you tried it the other way round: computing the albedo from SSR and SSRD and then apply this to the clear-sky fluxes?

What puzzles me is the upward radiation (full sky) that gets negative around Antarctica. This is nothing to do with which albedo you take, it simply is the difference between net and downwelling flux, both directly saved by IFS. A negative upwelling flux implies that the net radiation is larger than the downwelling flux which is physically impossible. Why do we get these values? Are they already in the IFS output (on the reduced Gauss grid), or do they appear when making the interpolation to the full Gauss grid?

**Comment by goord** [comment]
Hi Klaus I believe this is not an interpolation issue: the global minimum SSR is always 1.0800e-11, whereas the SSRD can become zero.

Perhaps this due to round-off errors in the radiation scheme?

**Comment by goord** [comment]
So when I use 10e-6 as a threshold on SSR (below we assume rsdscs=SSRC and rsdsus=0), I get similar results to the above (not identical). I will commit this in the rscs-correction branch.

**Comment by goord** [comment]
Clear-sky fluxes using calculated albedo:
![rsdscs_Amon](https://user-images.githubusercontent.com/5041758/54839939-2a67dd00-4ccc-11e9-97a3-b3f0fac77247.png)
![rsuscs_Amon2](https://user-images.githubusercontent.com/5041758/54839945-2dfb6400-4ccc-11e9-8fe7-45b5a0554892.png)

**Comment by klauswyser** [comment]
I can confirm that this is not an interpolation issue, I get SSR>SSRD also on the reduced Gauss grid:
````
cdo info: Started child process "expr,SSRU=(SSRD-SSR)/21600 ttl3+206001 (pipe1.1)".
    -1 :       Date     Time   Level Gridsize    Miss :     Minimum        Mean     Maximum : Parameter ID
     1 : 2060-01-01 06:00:00       0    88838       0 :     -53.997      27.152      688.31 : -1            
     2 : 2060-01-01 12:00:00       0    88838       0 :     -47.550      34.998      725.59 : -1            
     3 : 2060-01-01 18:00:00       0    88838       0 :     -56.581      27.594      663.61 : -1            
     4 : 2060-01-02 00:00:00       0    88838       0 :     -44.207      22.163      599.32 : -1            
 ```` 
Note that the computation of SSRU is done on the reduced Gauss grid, and we get still substantial SSRU<0 which is unphysical.

One may argue that this happens randomly in a few gridpoints and these negative values will vanish when taking time averages, but unfortunately this is not true. Here is a timeseries of 6-hourly SSRU values from a point just outside Antarctica:

![ttl3_ssru_1pt](https://user-images.githubusercontent.com/26412703/54841302-5042b100-4ccf-11e9-8d21-dd6c3144f6d5.PNG)

The albedo (FAL) at the same point is 0.05 (=ocean) for the entire month. Except for a few points in time SSR is always larger than SSRD, why do we get this unphysical behaviour? We can ask the question at the dev portal, maybe some of the IFS cracks has a good answer.

What can we do for ece2cmor? Not much I guess, except maybe limit SSR so it never gets larger than SSRD. But is that a good solution, or is it better to leave the values as we get them from the model and leave it to users to make corrections where necessary?

**Comment by klauswyser** [comment]
One may be tempted to blame the problem on the coupling between ocean and atmosphere, that something in the remapping of sea ice goes wrong. However, this likely isn't the case, here is an example from an AMIP run:

![b602_ssru_1pt](https://user-images.githubusercontent.com/26412703/54846044-41fa9200-4cdb-11e9-8b26-4fc57cddc267.PNG)

The selected point is also outside of Antarctica and has SSR>SSRD for most of the time.

**Comment by goord** [comment]
The issue SSR>SSRD has been addressed at the EC-Earth portal. Implemented the clear-sky fluxes using the calculated mean albedo as was suggested by @klauswyser, see pull request #420

**Comment by klauswyser** [comment]
Opened [issue 634](https://dev.ec-earth.org/issues/634) on the EC-Earth dev portal.
