### ISSUE TITLE
Python 3 version

### ISSUE THREAD

**Issue by goord** [EC-Earth/ece2cmor3#403]

**Comment by treerink** [comment]
This migration to [python 3](https://confluence.ecmwf.int/display/UDOC/Migration+to+Python+3) page from ECMWF might be helpful.

**Comment by tommibergman** [comment]
Just to make a note here about CMOR plans, there is a discussion going about ending support for python 2.7 at CMOR repo: https://github.com/PCMDI/cmor/issues/563

**Comment by goord** [comment]
Hi Tommi thanks for the notification, we will have to migrate at some point... I will hopefully have time next year to do it (the CMOR people will have a python-2.7 compatible release in 2020)

**Comment by tommibergman** [comment]
I think we need to do some planning on moving to python 3:

> conda-forge will no longer support Python 2.7: https://github.com/conda-forge/cfep/blob/master/cfep-15.md


CMOR is making a some kind of exception for it based on the discussion in https://github.com/PCMDI/cmor/issues/563

**Comment by goord** [comment]
Yes we should start testing and fixing broken stuff. I'm afraid in particular about integer divisions...

**Comment by treerink** [comment]
From e626d3e onwards, running `genecec` with  python3 inside the miniconda2 environment  is possible (in the master branch) by using your system python3 after:
 ``` 
 sudo apt install -y python3-pip
 pip3 install dreqPy==01.0.33
```
Note the` drq2*` and `checkvars` scripts are still run with python2 (but based on python3 compatible code).

**Comment by treerink** [comment]
With #754 being closed the `Ofx` `basin`  issue is resolved at the `ece2cmor3` side. With that the transition from `python` `2.7.15` to `python` `3.11.0` has been finalized. The last wrap-up stuff will be taken by #748.
