### ISSUE TITLE
Problem with some dates in the ocean output

### ISSUE THREAD

**Issue by aearamos** [EC-Earth/ece2cmor3#404]
Hi @goord , 
I was just checking some of the cmorised output from our historical simulations and it seems to me that some files have the wrong name and wrong time variable.

e.g. file thetao_Omon_EC-Earth3_historical_r10i1p1f1_gn_185201-185212.nc has the right name and dates, but here is the "time" variable for file thetao_Omon_EC-Earth3_historical_r10i1p1f1_gn_185302-185401.nc:

In [4]: ds.time                                                                                                     
Out[4]: 
<xarray.DataArray 'time' (time: 12)>
array(['1853-02-01T00:00:00.000000000', '1853-03-01T00:00:00.000000000',
       '1853-04-01T00:00:00.000000000', '1853-05-01T00:00:00.000000000',
       '1853-06-01T00:00:00.000000000', '1853-07-01T00:00:00.000000000',
       '1853-08-01T00:00:00.000000000', '1853-09-01T00:00:00.000000000',
       '1853-10-01T00:00:00.000000000', '1853-11-01T00:00:00.000000000',
       '1853-12-01T00:00:00.000000000', '1854-01-01T00:00:00.000000000'],
      dtype='datetime64[ns]')
Coordinates:
  * time     (time) datetime64[ns] 1853-02-01 1853-03-01 ... 1854-01-01
Attributes:
    bounds:         time_bnds
    axis:           T
    long_name:      time
    standard_name:  time

As you can see, that year started in February and ended in December. Is there a reason for the dates to be shifted? I just wanna make sure it's not our workflow, since it appears to be kind of random.

Here is cdo showdate for the right files (cmorised and raw output):

cdo showdate thetao_Omon_EC-Earth3_historical_r10i1p1f1_gn_185201-185212.nc
 
1852-01-16  1852-02-15  1852-03-16  1852-04-16  1852-05-16  1852-06-16  1852-07-16  1852-08-16  1852-09-16  1852-10-16  1852-11-16  1852-12-16

And for the wrong file:

cdo showdate thetao_Omon_EC-Earth3_historical_r10i1p1f1_gn_185302-185401.nc

1853-02-01  1853-03-01  1853-04-01  1853-05-01  1853-06-01  1853-07-01  1853-08-01  1853-09-01  1853-10-01  1853-11-01  1853-12-01  1854-01-01

The raw output seems to be right. 

Thanks.

**Comment by goord** [comment]
Hi Arthur, this is an issue with the CMOR-library, that component decides on the file name. Perhaps it gets confused (as am I) because the first time step is actually the second of January, 0h. This is quite strange no, I would expect it to be at 1853-01-01T00:00.

Is this also the case in the original NEMO output?

**Comment by aearamos** [comment]
Hi Gijs,
Thanks for answering. 
This is what I have for the original file:

cdo showdate a1sx_1m_18530101_18531231_opa_grid_T_3D.nc

1853-01-16  1853-02-15  1853-03-16  1853-04-16  1853-05-16  1853-06-16  1853-07-16  1853-08-16  1853-09-16  1853-10-16  1853-11-16  1853-12-16

I have the same configuration for different years. Do you have an output where you can see if it also starts on the 16/01 instead of 01/01? 

Thanks

**Comment by goord** [comment]
Hi Arthur could you also post the time bounds from the Nemo output and the cmorized file?

**Comment by aearamos** [comment]
time_bnds for the wrong file thetao_Omon_EC-Earth3_historical_r10i1p1f1_gn_185302-185401.nc :
data:
 time_bnds =
  31, 31,
  59, 59,
  90, 90,
  120, 120,
  151, 151,
  181, 181,
  212, 212,
  243, 243,
  273, 273,
  304, 304,
  334, 334,
  365, 365 ;
}

For the right file thetao_Omon_EC-Earth3_historical_r10i1p1f1_gn_185201-185212.nc: 
data:
 time_bnds =
  0, 31,
  31, 60,
  60, 91,
  91, 121,
  121, 152,
  152, 182,
  182, 213,
  213, 244,
  244, 274,
  274, 305,
  305, 335,
  335, 366 ;
}

So, there is a difference between the two files in time_bnds.

**Comment by goord** [comment]
Hi @aearamos I guess those time bounds are in seconds since 1800-1-1T00:00:00. Could you send me the file a1sx_1m_18530101_18531231_opa_grid_T_3D.nc via wetransfer? And could you also send me the log output?

**Comment by aearamos** [comment]
I just sent the link to your email.

**Comment by aearamos** [comment]
Hi Gijs,
I'm not sure this is relevant, but I had a simulation that I was able to run 250 years and the files seemed right. In this simulation, the xml files had much fewer variables and I was using it as a spinup run. After a while I changed the run to use the actual historical run and picontrol files (with more variables for opa and lim), then I started having this problem in some random years. If you want I can send you the files as well.

**Comment by aearamos** [comment]
Hi @goord,
I did a little digging myself and found one warning in one of my log files that I didn't notice before:

2019-03-13 01:41:53 INFO:ece2cmor3.nemo2cmor: Creating time axis for table Omon using file /gpfs/scratch/pr1egi00/pr1egi15/a1sx/18500101/fc0/runtime/output/nemo/055/a1sx_1m_19040101_19041231_opa_grid_U_2D.nc...

^[[2;34;47mC Traceback:
In function: cmor_check_monotonic
! called from: cmor_treat_axis_values
! called from: cmor_axis
! ^[[0m

^[[1;34;47m!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Warning: axis time (table: Omon) has bounds values that leave gaps
! (index 0): 31.000000, 31.000000, 60.000000
!
!!!!!!!!!!!!!!!!!!!!!!!!!^[[0m

This warning goes for all the indexes from time_bnds.

Also, the cdo showtime for the cmor output in the wrong files gives me:

cdo showtime thetao_Omon_EC-Earth3_historical_r10i1p1f1_gn_185302-185401.nc
 00:00:00 00:00:00 00:00:00 00:00:00 00:00:00 00:00:00 00:00:00 00:00:00 00:00:00 00:00:00 00:00:00 00:00:00

And for one of the files in the raw output:
cdo showtime a1sx_1m_18530101_18531231_opa_grid_W_3D.nc 
 12:00:00 00:00:00 12:00:00 00:00:00 12:00:00 00:00:00 12:00:00 12:00:00 00:00:00 12:00:00 00:00:00 12:00:00

Whereas, for the right files, the output is the same for the cmor and raw output:
 12:00:00 00:00:00 12:00:00 00:00:00 12:00:00 00:00:00 12:00:00 12:00:00 00:00:00 12:00:00 00:00:00 12:00:00

In leap years the second term is 12:00:00

I hoe this helps.

**Comment by goord** [comment]
Ah ok can you send me this grid_U file Arthur?

**Comment by aearamos** [comment]
I just uploaded the files to that ftp link I sent you before. There is also a new log file with more information and warnings.

**Comment by goord** [comment]
Hi @aearamos I have pushed a fix to the nemo-time-axes branch. I tested locally with your data and it seems to work, but on the other hand the issue seemed to occur only occasionally. Could you test a few years and check whether you come across the problem once more? Thanks.

**Comment by aearamos** [comment]
Hi @goord 
Thanks for the fix, I'll test it right now. 
Just one thing, I tried running, and got the error with using the xlsx file instead of a varlist:

2019-03-20 21:59:39 CRITICAL:__main__: Your variable list json file /gpfs/scratch/pr1egi00/pr1egi17/a1rh/auto-ecearth3/ece2cmor/outclass/piControl/cmvmm_*.xlsx cannot be found.
 Exiting ece2cmor.

Does it mean that using the xlsx file is no longer supported or is it a bug? I'll test now with a varlist file to make sure the fix works. 

Thanks!

**Comment by aearamos** [comment]
Thanks, Gijs! 
I will test the fix right now. I noticed that it's very random indeed. I'll let you know if it works.

**Comment by goord** [comment]
So @aearamos note that we have changed the script options: if you want to use the excel files you need to use the --drq option

**Comment by aearamos** [comment]
Hi Gijs, 
So, now I'm getting some errors when reading the SImon and SIday variables, specially siu and siv.
Here's one:

ERROR:ece2cmor3.nemo2cmor:Failed to read time axis information from file /gpfs/scratch/pr1egi00/pr1egi17/a1rh/18500101/fc0/runtime/output/nemo/072/a1rh_1d_19210101_19211231_lim_grid_V_2D.nc, skipping variable siv in table SIday

Which gives me:
^[[2;31;47mC Traceback:
! In function: cmor_variable
! ^[[0m

^[[1;31;47m!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: You are defining variable 'siv' (table SIday)  with 1 dimensions, when it should have 3
!
!!!!!!!!!!!!!!!!!!!!!!!!!^[[0m

and finally a "_cmor.CMORError: Problem with 'cmor.variable'. Please check the logfile (if defined)."

Again, oddly enough, it happens to random years. I managed to run some years with the Omon table fixed, but some failed when reached SImon and SIday.

**Comment by goord** [comment]
Ok, I committed a fix for that one in the same branch Arthur, you can pull and test once more.

**Comment by aearamos** [comment]
I applied the fix and will let you know by the end of the day if it works, but apparently, it did. 

It's just that I'm not at the office today.

Thanks!

**Comment by aearamos** [comment]
Hi  Gijs, your fixes to the time axis seem to be working. I think you can now merge them to trunk.

**Comment by goord** [comment]
Fixed in pull request #414
