### ISSUE TITLE
Inconsistent vertical levels in cmorised NEMO output

### ISSUE THREAD

**Issue by ufladrich** [EC-Earth/ece2cmor3#412]
We have stumbled over an inconsistency that appears in cmorised files, where vertical levels for ocean variables are inconsistent with the original output from NEMO. We have seen this for the `thetao` variable for some (non-contiguous) years of a longer experiment.

This is what the vertical levels in the raw NEMO output file looks like:
```
 olevel = 0.50576, 1.555855, 2.667682, 3.85628, 5.140361, 6.543034, 8.092519, 
    9.82275, 11.77368, 13.99104, 16.52532, 19.4298, 22.75762, 26.5583,    [...]

 olevel_bounds =
  0, 1.023907,
  1.023907, 2.10319,
  2.10319, 3.251309,
  3.251309, 4.485053,
  [...]
```
And this is how the cmorised file for the `thetao` variable looks like _when everything is fine_:
```
 lev = 0.505760014057159, 1.55585527420044, 2.66768169403076, 
    3.8562798500061, 5.14036130905151, 6.54303359985352, 8.09251880645752, 
    9.82275009155273, 11.7736797332764, 13.9910383224487, 16.5253219604492, 
    19.429801940918, 22.7576160430908, 26.5583000183105, [...]

 lev_bnds =
  0, 1.02390658855438,
  1.02390658855438, 2.10318994522095,
  2.10318994522095, 3.25130915641785,
  3.25130915641785, 4.48505258560181,
  [...]
```
However, for some of the years, the cmorised output file contains this:
```
lev = 0, 1.02390658855438, 2.10318994522095, 3.25130915641785, 
    4.48505258560181, 5.82523775100708, 7.29744291305542, 8.93268585205078, 
    10.767897605896, 12.8459920883179, 15.2152690887451, 17.9279232025146, 
    21.0375709533691, 24.5959873199463, 28.6496505737305, [...]

 lev_bnds =
  0, 0.505760014057159,
  0.505760014057159, 1.55585527420044,
  1.55585527420044, 2.66768169403076,
  2.66768169403076, 3.8562798500061,
  3.8562798500061, 5.14036130905151,
  5.14036130905151, 6.54303359985352,
  [...]
```
It looks like the level bounds of the original file where taken for levels in the cmorised output and vice versa.

We have no clue so far why and exactly when this is happening, or which variables are affected (other than `thetao`).

Besides being incorrect, this issue creates problems in later usage of the cmorised files, such as with ESMValTool, since files for different years come on different vertical coordinates.

**Comment by ufladrich** [comment]
Here are the years that had consistent vertical levels in our cmorising job:
```
[1850, 1851, 1852, 1854, 1855, 1856, 1857, 1858, 1859, 1860, 1862,
      1863, 1864, 1865, 1867, 1868, 1870, 1871, 1872, 1873, 1876, 1877,
      1878, 1879, 1880, 1882, 1883, 1885, 1887, 1889, 1891, 1893, 1894,
      1896, 1898, 1899, 1901, 1905, 1908, 1909, 1910, 1911, 1912, 1914,
      1917, 1918, 1921, 1922, 1923, 1924, 1925, 1927, 1932, 1933, 1936,
      1939, 1940, 1942, 1943, 1945, 1946, 1947, 1949]
```
and here the ones with inconsistent levels:
```
[1853, 1861, 1866, 1869, 1874, 1875, 1881, 1884, 1886, 1888, 1890,
      1892, 1895, 1900, 1904, 1906, 1907, 1913, 1915, 1916, 1919, 1920,
      1926, 1928, 1929, 1930, 1931, 1934, 1935, 1937, 1938, 1941, 1944,
      1948]
```

**Comment by goord** [comment]
Hi Uwe, which revision did you use to produce this? Because it seems a lot like issue #401 which we recently resolved. In that issue we observed a mixup between the vertical axes, where T-grid variables were assigned half-levels in random cases.

**Comment by ufladrich** [comment]
Hi Gijs, thanks for pointing out #401, I hadn't made the connection. Yes, it seems that we were hit by the same issue while using an somewhat older version of ece2cmor for that particular cmorisation job.

**Comment by goord** [comment]
Hi Uwe, sorry for that, I hope you haven't invested too many core hours in this cmorization. I hope to have all these nemo-related issues (the new output format affected ece2cmor3 more than I anticipated) resolved by tomorrow and have a release by Monday (which is a week later than planned).
