### ISSUE TITLE
Bool not iterable in `inspect_day` of `grib_filter.py`

### ISSUE THREAD

**Issue by ufladrich** [EC-Earth/ece2cmor3#413]
I am getting `TypeError: 'bool' object is not iterable` when cmorising some IFS output. See full stack trace below.

While there may be particular circumstances triggering the error [*], I do think that the problem is general. Here is the code throwing the exception, from `inspect_day` in `grib_filter.py`:
```python
frqs = [24] if len(hrs) == 1 else numpy.mod(hrs[1:] - hrs[:-1], numpy.repeat(24, len(hrs) - 1))
frq = frqs[0]
if any(frqs != frq):
    log.error("Variable %d.%d on level %d or type %s is not output on regular "
              "intervals in first day in file %s" % (key[0], key[1], key[3], key[2], gribfile))
```
Even though `frqs` is a list, the result of `frqs != frq` will be a scalar and can't be iterated by `any`. So it seems to me that the error is inevitable.

*) I am cmorising the first leg of a scenario experiment, which means that the "previous" grib files are not initial conditions, i.e. IFS didn't do a cold start.

Full stack trace:
```
+ ece2cmor --ifs --conf ../cmorise.metadata.ifs.json --vars ../cmvme_ae.c4.cd.cf.cm.co.da.dc.dy.fa.ge.gm.hi.is.ls.lu.om.pa.pm.rf.sc.si.vi.vo_piControl_1_1.xlsx --exp t621 --npp 32 --tmpdir [...]/ece2cmor-job-2222264-166 --log --odir [...]/t621 --skip_alevel_vars [...]/t621/output/ifs/166
Traceback (most recent call last):
  File "[...]/bin/ece2cmor", line 11, in <module>
    load_entry_point('ece2cmor3==0.9.0', 'console_scripts', 'ece2cmor')()
  File [...]/lib/python2.7/site-packages/ece2cmor3-0.9.0-py2.7.egg/ece2cmor3/ece2cmor.py", line 150, in main
    cdothreads=args.ncdo)
  File "[...]/lib/python2.7/site-packages/ece2cmor3-0.9.0-py2.7.egg/ece2cmor3/ece2cmorlib.py", line 176, in perform_ifs_tasks
    tempdir=tempdir, autofilter=auto_filter)):
  File "[...]/lib/python2.7/site-packages/ece2cmor3-0.9.0-py2.7.egg/ece2cmor3/ifs2cmor.py", line 130, in initialize
    grib_filter.initialize(ifs_gridpoint_files_, ifs_spectral_files_, temp_dir_)
  File "[...]/lib/python2.7/site-packages/ece2cmor3-0.9.0-py2.7.egg/ece2cmor3/grib_filter.py", line 49, in initialize
    varsfreq.update(inspect_day(grib_file.create_grib_file(gpf), grid=cmor_source.ifs_grid.point))
  File "[...]/lib/python2.7/site-packages/ece2cmor3-0.9.0-py2.7.egg/ece2cmor3/grib_filter.py", line 103, in inspect_day
    if any(frqs != frq):
TypeError: 'bool' object is not iterable
```

**Comment by ufladrich** [comment]
Just as a suggestion: It could be
```python
if any(f != frq for f in frqs):
```

**Comment by goord** [comment]
Hi @ufladrich I can (and will) fix the issue by replacing ``[24]`` on line 101 by ``numpy.array([24])``, because equality between an numpy array and a scalar is an array of booleans on which ``any`` works correctly.

You noticed this because you are the first where the code enters the branch ``len(hrs)==1`` on line 101, which means you somehow have a 'single` field in the output. I suspect this is one of the fields in the 'spinup` data at 0-hours that has disappeared from the scenarioMIP output, could that be?

**Comment by goord** [comment]
Uwe, I pushed a fix with an extra warning to the master branch. The warning appears if a record is only detected once. Note that in the newest version you should use the ``--drq`` option for excel file data requests, or convert your data request to a component-wise json file with drq2varlist

**Comment by klauswyser** [comment]
> I suspect this is one of the fields in the 'spinup' data at 0-hours that has disappeared from the scenarioMIP output, could that be?

Indeed we were testing a new case: the start of a scenario experiment. A historical experiment ends in 2014 and is followed by several scenarios starting in 2015. The scenario experiments will receive new experiment names yet they don't make a cold start but use the last set of restart files from the historical run. This implies that the ICM*+201412 that are saved at teh beginning of the scenario experiment are incomplete in the sense that they only contain 1 timestep, and I think this is where the logic breaks down. It's good if this can be solved.

**Comment by ufladrich** [comment]
@klauswyser, thanks for the clarification! And I have learned that numpy arrays behave differently :-)

@goord, yes I'm aware that my scripts calling ece2cmor have to be adapted.

**Comment by goord** [comment]
Would it be an option to create symlinks to the december files in 2014 with the new experiment name? At least we don't have to equip ece2cmor3 to handle multiple experiment names.

The ppt files and data request both changed in the scenario runs w.r.t. the historical right?

**Comment by ufladrich** [comment]
Closing the issue since `numpy.array([24])` is a fix. We'll have to open a new one with the first-leg-of-scenario problem.
