### ISSUE TITLE
AttributeError: 'no attribute 'ScriptUtils'

### ISSUE THREAD

**Issue by jmcgove** [EC-Earth/ece2cmor3#415]
Hi, I updated latest ece2cmor (r3561), and `ece2cmor.py` gives
```
File "./ece2cmor.py", line 39, in main
cmor_utils.ScriptUtils.add_model_exclusive_options(parser, "ece2cmor")
AttributeError: 'module' object has no attribute 'ScriptUtils'
```
Anyone seen this? Thought it was an environment issue, though I updated ece2cmor3 conda environment ok. Doesn't look like a proxy, connection error either. Thanks.

**Comment by treerink** [comment]
I will have a look, probably due to some change of me yesterday.

**Comment by goord** [comment]
Hi @jmcgove did you do
```
conda activate ece2cmor3
python setup.py install
```
in your repo clone?

**Comment by jmcgove** [comment]
Hi @goord (@treerink), sorry, `python setup.py install ` did it. Didn't do so in a while (forgot that step). ok now.
