### ISSUE TITLE
No JSON object could be decoded

### ISSUE THREAD

**Issue by jmcgove** [EC-Earth/ece2cmor3#416]
Hi @treerink , running the latest ece2cmor.py, as before, I get now
```
File "/perm/ms/ie/dujm/miniconda2/envs/ece2cmor3/lib/python2.7/
json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```
Here I have set, as before, template.json and varlist .xlxs file directories
`CONFIGFILE=$SRCDIR/resources/metadata-templates/cmip6-CMIP-piControl-metadata-template.json`
and
`VARLIST=$DRF/cmip6-data-request-m=CMIP-e=$EXPdr-t=1-p=1/cmvme_CMIP_${EXPdr}_1_1.xlsx`
These paths are correct and are those used before (ece2cmor.py ran through with these). Could be something else, just checking - these are still correct with the latest version, right? Thanks

**Comment by goord** [comment]
Hi Jonathan, you have to either (i) change the invocation of ece2cmor in your script so that it uses ```--drq $VARLIST``` instead of --vars, or (ii) convert all those data request excel files to json files using the script ```drq2varlist```, which is now installed in your conda environment.

**Comment by jmcgove** [comment]
Hi Gijs, `--drq` instead of `--vars` did it, thanks.
