### ISSUE TITLE
Duplicate requested variables were found, dismissing all cmorization tasks

### ISSUE THREAD

**Issue by tommibergman** [EC-Earth/ece2cmor3#417]
I got an error with duplicate variables, which leads to total tasks being 0. 

What to do next? So should I just add the variables in prefs.py?

**Comment by tommibergman** [comment]
Could we add a check for IFS part for number of tasks is zero to stop there. At the moment it continues to post processing anyway?

**Comment by goord** [comment]
No you should remove 'em from your data request/varlist!

**Comment by tommibergman** [comment]
I was using --drq, where I just took the data request as it is. So I guess this means that it is always preferable to use the json-files instead.

**Comment by goord** [comment]
Yes it is recommended to first run drq2varlist and review the result. In this case the duplicates are a signal that the preferences are not complete, so we should make them 'all-exclusive'.

For all configurations and data request, we want the varlist.json to contain no duplicates whatsoever.

**Comment by goord** [comment]
@treerink you may want to regenerate all those data request json files, since they contain duplicate variables which causes ece2cmor3 to stop the entire process.

**Comment by goord** [comment]
Tommi can we proceed this in #224 which I reopened?
