### ISSUE TITLE
runs rthough output not produced

### ISSUE THREAD

**Issue by jmcgove** [EC-Earth/ece2cmor3#418]
Hi Gijs @goord, sorry again. When I run the same script again I ran ok before (with the --vars changed to --drq), it runs through ok, finishes with 

```
2019-03-22 13:56:31 INFO:ece2cmor3.nemo2cmor: Looking up variables in files...
2019-03-22 13:56:31 INFO:ece2cmor3.nemo2cmor: Creating NEMO grids in CMOR...
2019-03-22 13:56:31 INFO:ece2cmor3.nemo2cmor: Executing 0 NEMO tasks...
2019-03-22 13:56:31 INFO:ece2cmor3.nemo2cmor: Cmorizing NEMO tasks...
! ------
! All files were closed successfully. 
! ------
! 
```
all good, except cmor output file isn't produced, unlike before.
When I ran the same script before (with --vars instead of --drq) cmorised output files were produced ok. Not this time though. The directory output folder is seen while the run is taking place but disapears at the end with no output. I will check this again next week. In case you might know? --vars is not needed, right? Have a nice weekend.

**Comment by goord** [comment]
Hi Jonathan, perhaps you are suffering from #253 (see at the end)?

**Comment by jmcgove** [comment]
#253 sounds familiar, yep. will follow tanks
