### ISSUE TITLE
problems with lambda550nm 

### ISSUE THREAD

**Issue by tommibergman** [EC-Earth/ece2cmor3#421]
Now that ps1 and zfactor is solved, I ended up with another problem with singular dimension with 3d spatial dimensions. This problem is already being solved in https://github.com/PCMDI/cmor/issues/430 .

**Comment by treerink** [comment]
This issue appears when cmorising  `6hrLev ec550aer`.

**Comment by tommibergman** [comment]
This issue depends on CMOR 3.5.0 to be finalised.

**Comment by tommibergman** [comment]
Current nightly build of CMOR library works now  with fifth dimension, in our case the lambda550nm. I an implementing this in branch `fix-ec550aer`

**Comment by treerink** [comment]
With the merge of #525 this issue has been solved now in the master as well. Note you need to rebuilt your ece2cmor environment, follow the instructions in the header of https://github.com/EC-Earth/ece2cmor3/blob/master/environment.yml. Also the cmor tables and the data request version are updated, see #524.

I am closing this issue, when necessary please open again.
