### ISSUE TITLE
Level preferences

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#422]
For instance [this post](https://github.com/EC-Earth/ece2cmor3/issues/253#issuecomment-475683857) shows the risk that variables will be overwritten.
`````
ERROR:ece2cmor3.taskloader: Found duplicate output name for targets ua, ua7h in table 6hrPlevPt for model ifs
ERROR:ece2cmor3.taskloader: Found duplicate output name for targets va, va7h in table 6hrPlevPt for model ifs
ERROR:ece2cmor3.taskloader: Found duplicate output name for targets ta, ta7h in table 6hrPlevPt for model ifs
ERROR:ece2cmor3.taskloader: Found duplicate output name for targets zg7h, zg27 in table 6hrPlevPt for model ifs
`````
Therefore the idea is to always take the largest number of levels, and to organize this from `drq2varlist.py,` by adding another preference routine in the `prefs.py.`

**Comment by goord** [comment]
Fixed in #426
