### ISSUE TITLE
odir, vars - query

### ISSUE THREAD

**Issue by jmcgove** [EC-Earth/ece2cmor3#425]
Hi Gijs @goord, I no longer get the error with json (#253), though the run finishes with 
```! ------
! All files were closed successfully. 
! ------
! 
```
and no cmor output directory/files created. I adjusted the call to ece2cmor.py according to changes that have taken place (eg. --atm to --ifs,` --ececonf EC-EARTH-AOGCM`). I have `--drq $VARLIST` , with $VARLIST the location of the xlsx file. `./ece2cmor.py help` gives

```
required arguments:
  --vars FILE                 File (json) containing cmor variables grouped
                              per table, grouped per EC-Earth component
                              (default: None)
  --drq FILE                  File (json|f90 namelist|xlsx) containing cmor
                              variables, grouped per table (default: None)
  --conf FILE.json            Input metadata file (default: None)

```
Still confused  - is --vars needed? If so what file is this exactly? (The metadata json file - as it is I have `--conf CONFIGFILE=$SRCDIR/resources/metadata-templates/cmip6-CMIP-piControl-metadata-template.json`.)
Also  `--odir` output metadata file - the input metadata file is conf, --odir is a new folder with the  the output metadata?
Thanks

**Comment by goord** [comment]
Hi Jonathan, regarding the requested variables for your cmorization job you either have to

(i) Prepare a 'varlist' json file which goes 3 levels down: model-comomponent : tables : variables. Thomas is preparing these from the MIP data request excel files and will check them into the EC-Earth repo. You can also produce such a file yourself by running 'drq2varlist' on a data request excel file, but you have to provide a --ececonf value in that case.

OR

(ii) Use the --drq option with a good old data request file (either excel or 2-level json table - variables). In that case you should provide the --ececonf value too, otherwise all 'duplicate' variables shared by multiple components stay in, causing the program to quit without processing data.

The --odir option is there to determine where the cmorized output will go. You may recall you previously had to specify this in your metedata json file (the --conf option), but now we overwrite that path whenever you specify it in the script.

**Comment by treerink** [comment]
See at the ec-earth portal [issue 635 ](https://dev.ec-earth.org/issues/633) and the [r6705-control-output-files](https://dev.ec-earth.org/projects/ecearth3/repository/revisions/6720/show/ecearth3/branches/development/2019/r6705-control-output-files) branch, for instance have a look at this [data-request-varlist.json](https://dev.ec-earth.org/projects/ecearth3/repository/revisions/6720/entry/ecearth3/branches/development/2019/r6705-control-output-files/runtime/classic/ctrl/cmip6-output-control-files/CMIP/EC-EARTH-AOGCM/cmip6-experiment-CMIP-piControl/cmip6-data-request-varlist-CMIP-piControl-EC-EARTH-AOGCM.json) file.

**Comment by jmcgove** [comment]
Thanks. I uploaded the new .json file from the repo   -
cmip6-data-request-varlist-CMIP-piControl-EC-EARTH-AOGCM with three levels
down, eg.  ifs / 3hr / ps
I set --vars to the path of this .json file, and tried with this (2nd call
in wiki),

ece2cmor.py $LEGDIR --exp $EXP --ifs --nemo --conf $CONFIGFILE --vars
$VARLIST_ECEARTHAOGCM --ececonf EC-EARTH-AOGCM --odir $OUTMETADIR --npp
$THREADS --tmpdir $WORKDIR --tabledir $TABLEDIR
LEGDIR=/path/to/raw/data
CONFIGFILE=/path/to/cmip6-CMIP-piControl-metadata-template.json
VARLIST_ECEARTHAOGCM=/path/to/cmip6-data-request-varlist-CMIP-piControl-EC-EARTH-AOGCM.json
TABLEDIR=/path/to/Tables/

I still get no directory created. The run finishes as before with
! ------
! All files were closed successfully.
! ------
!
I get no errors, though a series of metadata comments as before eg.
2019-03-27 15:42:52 INFO:ece2cmor3.ece2cmorlib: Metadata attribute
sub_experiment: none
I noticed one of these is
2019-03-27 15:42:52 INFO:ece2cmor3.ece2cmorlib: Metadata attribute
#variant_info: uncomment and describe briefly what makes your ripf
identifier unique (only needed if i/=1, p/=1 or f/=1)
Should I change this part of the metadata file here.

**Comment by treerink** [comment]
Let's see if we can get something running first. So first just choose between ifs and nemo, so let's try first only` --nemo` (thus remove `--ifs`).

For LEGDIR  I would expect something like `LEGDIR`=/path/to/raw/data/`output/nemo/001`

I don't think you need to specify `TABLEDIR` in your case, leave it away.

**Comment by treerink** [comment]
Just an NEMO cmorisation example (though on a NEMO-all test case) which successfully ended (I had to remove zhalfo from the json data request file, waiting on PCDMI to fix an issue (see #388). 

`````
       ece2cmor ~/mount-point-lustre-3/ec-earth-3.3.0/branch-r6705-control-output-files/t009/output/nemo/001/ --exp t009 --nemo --conf ece2cmor3/resources/metadata-templates/cmip6-CMIP-piControl-metadata-template.json --vars ece2cmor3/resources/test-data-request/cmip6-data-request-varlist-CMIP-piControl-EC-EARTH-AOGCM-without-zhalfo.json --ececonf EC-EARTH-AOGCM --odir cmor-test-all-nemo-mip-variables-without-zhalfo >& log-cmip6-cmorizing-test-all-nemo-mip-variables-without-zhalfo.txt &
`````

**Comment by jmcgove** [comment]
Thanks. Trying a run with just `--nemo`, and without tabledir, I get
 ```raise Exception("Cmorization table directory does not exist")
Exception: Cmorization table directory does not exist
```
It seems tabledir is looked for. Leaving tabledir in,
` ece2cmor.py $LEGDIR --exp $EXP --nemo --conf $CONFIGFILE --vars $VARLIST_ECEARTHAOGCM --ececonf EC-EARTH-AOGCM --odir $OUTMETADIR --npp $THREADS --tmpdir $WORKDIR --tabledir $TABLEDIR
`
I get as before (output attached). An error I get is to do with the ifs variables. 
`ERROR:ece2cmor3.taskloader: Found duplicate output name for targets ua, ua7h in table 6hrPlevPt for model ifs
`
I checked paths, there are no errors to do with path, these are right. Might this be why it doesnt follow through?

Ok for zhalfo and .json file, will see after

**Comment by treerink** [comment]
Concerning the tables you did:
git submodule update --init --recursive
Concerning the error:
git pull
python setup.py install

**Comment by jmcgove** [comment]
Runs now thanks. I did a one year test. Output cmorised files are produced
ok. There are still, as before, files of type      8.128.1.3,
31.128.1.3       Might just be a platform issue, and ok. As if like not all
cmor files are produced. That's ok?

Also, not sure this is right: when I run multiple years in a loop, 1850-55
say,  (do LEG=001:005 ece2cmor.py... end do)  I get output cmor folders of
type    r6i1-ifs-1850,  r6i1-ifs-1851, 52... .  In the folders of latter
years (52,53...) fewer files are produced. This is ok?

**Comment by treerink** [comment]
1. Did you set a `--tmpdir` ? Because it sounds like the temporary files, which usually end up in the tempdir, so those doesn't matter.

2. You have to post which files. It might depend on the `--overwritemode` flag setting?

**Comment by jmcgove** [comment]
1.   Ah yes, I set  --tmpdir, prob just temporary files. That's ok, though
just noticed (but maybe it is ok?):   as is, my call has
--tmpdir=$SCRATCH/tmp/cmor      and
--odir=$SCRATCH/tmp/cmor/cmor-all-nemo-mip-variables
      Running it I get .nc files produced in $SCRATCH/tmp/cmor
(--tmpdir)     and  a  $SCRATCH/tmp/cmor/cmor-all-nemo-mip-variable folder
produced but nothing produced in it  (--odir). This seems right?

**Comment by treerink** [comment]
@jmcgove I think it is good to remove all these directories before you run once more your cmorisation try again. This saves you from left overs of previous attempts. Just set something like:
`````
--tmpdir=$SCRATCH/tmp/cmor-temp --odir=$SCRATCH/tmp/cmor-all-nemo
`````
The results, after the cmorisation has finished, should be available in the (deep) sub directories of `$SCRATCH/tmp/cmor-all-nemo/CMIP6/*`

**Comment by jmcgove** [comment]
I got it now with the latest version, thanks. I say so, this looks right?
The 1 year test (1850) now produces .nc files in cmor-all-nemo in
subdirectories as displayed in metadata file
(CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/piControl/r1i1p1f1  and the
frequency (3hr, Amon..) and then clt/gr/v20190404/)
I will next try several years.

**Comment by treerink** [comment]
Issue itself seems solved, so closing it.
