### ISSUE TITLE
Missing newline characters at the end of varlist.json files

### ISSUE THREAD

**Issue by ufladrich** [EC-Earth/ece2cmor3#429]
The `cmip6-data-request-varlist-*.json` files that are present in the EC-Earth repository under `runtime/classic/ctrl/cmip6-output-control-files/[...]` do not have newline characters at the end of the files. I guess that's an [genece](../blob/master/ece2cmor3/scripts/genecec.py) issue and suggest to add the newline for [POSIX compliance](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206) and, for example, less noise in svn diffs.

**Comment by treerink** [comment]
Yes agree, had it on the list already. Will have a look. It is a propperty of the python json writer we use. Anoying, for instance after opening and closing such a file with an editor the return is added giving svn changes.

**Comment by treerink** [comment]
The lacking newline at the end of a json file is a known issue/property with `python json dump`, so  just add it in 62cfb59.

Done. Closing.
