### ISSUE TITLE
Unsupported combination of frequency monC

### ISSUE THREAD

**Issue by oloapinivad** [EC-Earth/ece2cmor3#431]
I found this while cmorizing CMIP6 historical AOGCM data, but I am not quite sure if it is relevant or not. It occurs at the beginning of the cmorization, right after the land-sea mask selection.

```
ERROR:ece2cmor3.postproc: Unsupported combination of frequency monC with time operators [u'mean within years', u'mean over years'] encountered
```

should I worry about it?

**Comment by goord** [comment]
Hi Paolo, you should remove them from your input variable list, we will support them at some point, but not yet. See issue #262

**Comment by oloapinivad** [comment]
Thanks, roger, closing this.
