### ISSUE TITLE
drq2ppt surface fields with singular height axis

### ISSUE THREAD

**Issue by goord** [EC-Earth/ece2cmor3#434]
To determine whether an averaged field should get 3- or 6-hourly output frequency, drq2ppt looks for a vertical axis. This is error prone because some surface fields have 'singular' vertical axis and get classified as 3D-fields (e.g. 2-metre temperature has a vertical axis "height2m"). Possible solutions would be:

- Check whether the vertical axis has multiple or single coordinate values, in the former case we consider it to be a true '3d' fields. This means that requested fields on single pressure levels (e.g. ta850 in Eday) will also be classified as 2D and become part of the 3-hourly ppt files.

- Check whether the grib code is in the set of IFS surface fields. In this case, requested 3D fields on a single level will still be classified as 3D, and get a 6-hour output frequency.

**Comment by klauswyser** [comment]
I would prefer a solution that decides on the output frequenmcy based on a comparison of the GRIB code against the set of IFS 2-D fields. Note that not all 2-D fields are SFC fields, there are also TOA fields (e.g. radiation) and even vertical integrals (e.g. precipitable water).

**Comment by goord** [comment]
Ok I changed this directly in the master branch, following the preference of Klaus above. @treerink you may want to run the namelist generator again for all mips...

**Comment by treerink** [comment]
@goord a lot of differences in the ppt files, probably as expected. Can you shorty check the diff file:
[differences-due-to-issue-434.txt](https://github.com/EC-Earth/ece2cmor3/files/3073639/differences-due-to-issue-434.txt) to check if the differences look fine?

**Comment by treerink** [comment]
This one should be solved with c4511b1680a41306cafe39e3e1001824a5cbb340, and will be the basis of  upcoming `pre-release 0.9.9`. If anything wrong or not optimal please reopen. The changes in the control files will be uploaded at the ec-earth portal.

Closing.
