### ISSUE TITLE
Request for cdo 1.9.6

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#436]
@nierad asked whether a `cdo` update to version 1.9.6 is possible.

The upgrade has no conflict in rebuilding the `ece2cmor3` environment, the `nosetest` went fine as well. 

Before upgrading, a more extensive ifs cmorisation test will be done, as that part is heavily `cdo` dependent.

**Comment by treerink** [comment]
One ifs leg for a CMIP piControl run has been successfully cmorised, so cdo 1.9.6 seems to work alright.

Closing.

**Comment by nierad** [comment]
Great, thank you. I am currently fiddling around with the new remapping.

I’ll let you know, when it works.

Cheers, Lars

—

Lars Peter Nieradzik
Institute for Physical Geography and Ecosystem Science
Lund University
Sölvegatan 12
223 62 Lund, Sweden

Phone: +46 (0)46 222 3977

On 4 Apr 2019, at 16:45, Thomas Reerink <notifications@github.com<mailto:notifications@github.com>> wrote:


One ifs leg for a CMIP piControl run has been successfully cmorised, so cdo 1.9.6 seems to work alright.

Closing.
