### ISSUE TITLE
Amon o3 of IFS is missing

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#440]
Because `o3` has been identified within TM5, `o3` was not any longer a "missing" variable. Therefore we missed it, and did not identify it for IFS. However `Amon o3` can be provided by IFS with grib code `128.203`. Currently we therefore miss `o3` when TM5 is not included.

We want to give IFS preference for `Amon o3`, while we want to give TM5 preference for  `AER* o3`, so this has to be organised in the `prefs.py.` Note further that we want to move the ` E3hrPt o3` combinion to the ignored list.

Note, however, that the o3 field values of IFS might be prescribed, we are not sure yet?

**Comment by treerink** [comment]
Further `Amon o3Clim` will be ignored because, likewise in #441, the data request mentioned that  `Amon o3Clim` can be omitted if  `Amon o3` is produced.

**Comment by goord** [comment]
Hi @treerink I have made the proposed changes and committed them in the 'ozone' branch. Note that this again may change the drq2ppt results. Moving E3hrPt o3 to the ignored list has still to be done though

**Comment by treerink** [comment]
Ah ok I was about doing this as well, ok I will do the rest.

**Comment by treerink** [comment]
I tested `genecec` in the ozone branch, the differences look good. So I will merge the ozone branch into the master.

**Comment by treerink** [comment]
All done, closing.
