### ISSUE TITLE
E3hr prrc: Precip. flux from convection liquid

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#444]
Do we want to make this one available?:
`````
E3hr     prrc         Availlable in IFS: Precip. flux from convection liquid grib 128.107, this is a 3D field so the surface field has to be extracted from this. So only level 91 needs to be outputted.
`````
I suggest to ignore it, no one has made any effort for a long time on this. If I am right,  we need to ask IFS a 3D 3hr field while only using one layer of it. Is it worth the costs?

**Comment by goord** [comment]
Hi Thomas I completely agree, there is already convective liquid+ice at 3 hours btw

**Comment by treerink** [comment]
Moved `prrc` from identified missing to ignored list.

Done, closing.
