### ISSUE TITLE
"4D" SImon/icemod variables  

### ISSUE THREAD

**Issue by pabretonniere** [EC-Earth/ece2cmor3#46]
Hi,

Did anyone try to CMORize the variables siitdconc (sea_ice_area_fraction_over_categories) and siitdsnthick (snow_thickness_over_categories) from the SImon CMIP6 table (1m_*_icemod* nemo file)?
They are priority 3 variables but we tried to produce them anyway and as they have the dimensions time,iceband,latitude,longitude (iceband being the category, called ncatice in nemo) and no bounds associated nor a name starting with "depth", cmor fails.
I can work something out but I just wonder if someone already faced a similar issue before starting rewriting all the "depth management".
Thank you,

**Comment by goord** [comment]
I believe this is working now, at least on my laptop
