### ISSUE TITLE
Wrong time unit in cmorised NEMO/LIM files

### ISSUE THREAD

**Issue by ufladrich** [EC-Earth/ece2cmor3#466]
We have encountered an issue with cmorised NEMO/LIM files, where the time unit is
```
time:units = "days since 1800-01-01 00:00:00"
```
despite the fact that ece2cmor was run with `--refd 1850-01-01`. 

NEMO/LIM output comes with the following time definitions:
```
	double time_centered(time_counter) ;
		time_centered:standard_name = "time" ;
		time_centered:long_name = "Time axis" ;
		time_centered:calendar = "gregorian" ;
		time_centered:units = "seconds since 1800-01-01 00:00:00" ;
		time_centered:time_origin = "1800-01-01 00:00:00" ;
		time_centered:bounds = "time_centered_bounds" ;
	double time_centered_bounds(time_counter, axis_nbounds) ;
	double time_counter(time_counter) ;
		time_counter:axis = "T" ;
		time_counter:standard_name = "time" ;
		time_counter:long_name = "Time axis" ;
		time_counter:calendar = "gregorian" ;
		time_counter:units = "seconds since 1800-01-01 00:00:00" ;
		time_counter:time_origin = "1800-01-01 00:00:00" ;
		time_counter:bounds = "time_counter_bounds" ;
```
and it seems that ece2cmor is keeping this information instead of overwriting with the setting from `--refd`.
The problem is that cmorised files for the same experiment will have different time units. We checked with [nctime](http://prodiguer.github.io/nctime), which is recommended [here](https://pcmdi.llnl.gov/CMIP6/Guide/dataManagers.html), and it complains.
As a side note, IFS and LPJG data from the same experiment and cmorised with the same ece2cmor call, will have the correct time unit (`days since 1850-01-01 00:00:00`).

Adding further to problems with time units is the fact that some files have `days since 1850-01-01 00:00:00` while others have `days since 1850-01-01`, i.e. without attached time. This causes errors for nctime as well, but it might be another issue.

**Comment by treerink** [comment]
Hmm that's strange, because the default is 1850 (doesn't need evermore `--refd 1850-01-01`, because it is the default). This is also shown by a [1850 search](https://github.com/EC-Earth/ece2cmor3/search?q=1850&unscoped_q=1850) while a search on 1800 doesn't give a hit.

**Comment by ufladrich** [comment]
Maybe 1800 isn't explicitly set by ece2cmor, it's just taking the attribute values from the NEMO output files?

**Comment by oloapinivad** [comment]
I can confirm the issue with data cmorized with version 1.0.0
BTW, those files pass PrePARE check

```
$ncdump -h siconc_SImon_EC-Earth3_historical_r4i1p1f1_gn_185001-185012.nc 
netcdf siconc_SImon_EC-Earth3_historical_r4i1p1f1_gn_185001-185012 {
dimensions:
	time = UNLIMITED ; // (12 currently)
	j = 292 ;
	i = 362 ;
	bnds = 2 ;
	vertices = 4 ;
	strlen = 7 ;
variables:
	double time(time) ;
		time:bounds = "time_bnds" ;
		time:units = "days since 1800-01-01 00:00:00" ;
		time:calendar = "gregorian" ;
		time:axis = "T" ;
		time:long_name = "time" ;
		time:standard_name = "time" ;
...
```

**Comment by ufladrich** [comment]
> BTW, those files pass PrePARE check

Yes, the whole QA-DKRZ, which runs PrePARE as one of the checks, seems okay with it.

**Comment by treerink** [comment]
See also [248](https://github.com/EC-Earth/ece2cmor3/issues/248#issuecomment-423562614)

**Comment by pabretonniere** [comment]
I confirm we had the same issue with @aearamos in the BSC files. It seems that the time origin is set from the one from the original nemo files.

We fixed this afterwards with a small python script.





```
#!/usr/bin/env python
"""Module to change time units into netCDF files.
# Example: new_units = "days since 1950-01-01"
"""
import netCDF4 as nc4
import sys


def change_units(fname, new_units, time_var='time'):
    """ Method that requires a full path filename and a string with new time
    units"""
    with nc4.Dataset(fname, 'r+') as nc:
        time = nc.variables[time_var]
        time_array = nc4.num2date(time[:], time.units, time.calendar)
        time[:] = nc4.date2num(time_array[:], new_units, time.calendar)
        time.units = new_units


if __name__ == "__main__":
    import sys
    if len(sys.argv) not in (3,4):
        print("Error. Usage: {} <FILENAME> <NEW_UNITS> [TIME_VAR]".format(sys.argv[0]))
        sys.exit(1)
    if len(sys.argv) == 4:
        time_var = sys.argv[3]
    else:
        time_var = 'time'
    fname = sys.argv[1]
    new_units = sys.argv[2]

    change_units(fname, new_units, time_var)

```

**Comment by goord** [comment]
I thought I added this feature a few months ago, I will have look at it today

**Comment by goord** [comment]
Hi @ufladrich apparently I never built support for this in nemo2cmor... It must have slipped my mind.

**Comment by zklaus** [comment]
@pabretonniere, interesting! Note that according to [the output metadata requirements, p.7, note 14](https://goo.gl/neswPr)

> a. The same 'base time' should apply to all time samples in a single simulation (i.e., when creating a series of files containing model output for a single run, don't change the units or ‘base time’ from one file to the next; in the above example 1800-1-1 is the 'base time').

and

> b. For simulations meant to represent a particular historical period, set the ‘base time’ to the time at the beginning of the simulation.  A historical run initialized with forcing for year 1850 would, for example, have units of “days since 1850-1-1”.

and

> c. For the future scenario runs, retain the same ‘base time’ as used in the historical run from which it was initiated.

Looking at some BSC data on ESGF the basetime seems to be "moving" from one file to the next.

**Comment by treerink** [comment]
Twan saw that as well with the BSC data on ESGF, thereafter run it myself and checked, but we did not have that shift of 13 months (if I remeber the 13 correctly).

**Comment by ufladrich** [comment]
@goord Never mind! Could you make an educated guess how difficult it is to add?

**Comment by goord** [comment]
I just made a branch for this that can be tested (I am currently not easily capable of testing myself)

**Comment by ufladrich** [comment]
@goord Great! I'll give it a try!

**Comment by zklaus** [comment]
@treerink , @pabretonniere here is what I mean:

File|time:units
----|----
`sltovovrt_Omon_EC-Earth3_historical_r2i1p1f1_gn_185701-185712.nc` | `days since 1857-01-01 00:00:00`
`sltovovrt_Omon_EC-Earth3_historical_r2i1p1f1_gn_185801-185812.nc` | `days since 1858-01-01 00:00:00`

where both should have
```
time:units = "days since 1850-01-01 00:00:00"
```
ie the beginning of the historical run.

**Comment by ufladrich** [comment]
Made a first test with 3b0c4e3, cmorising NEMO files of 10 years historical. Looks good, the files have the correct `time:units` now.
@goord Thumbs up for instant response!

**Comment by ufladrich** [comment]
@goord Before we let you off the hook: The time unit for IFS+NEMO/LIM comes including the time, i.e.
```time:units = "days since 1850-01-01 00:00:00"```
while for LPJG it's just the date
```time:units = "days since 1850-01-01"```
While one can discuss what's correct/required (@zklaus has the references), it should be consistent. Is that equally easy to fix (e.g. by adding the time to LPJG variables)?

**Comment by zklaus** [comment]
I agree with @ufladrich that consistency would be nice and which version to choose is probably less critical. Having said that, in [the output metadata requirements, p.7, note 14](https://goo.gl/neswPr) it is said that

> basetime must be specified by the user, typically in the form year-month-day (e.g., "days since 1800-1-1").

so if it's all the same to you, that is what I would be going with (understanding that from [the CF conventions](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#time-coordinate) we know that this implies the very same time).

**Comment by treerink** [comment]
Actually `ece2cmor3` does write "`hours since`"  but cmor changes this to "`days since`" and with that cmor takes the control of the formatting, thus unfortunately this last point is not easy to change.

Anyway after the merge, now the ref date should be correctly for NEMO as well.

**Comment by zklaus** [comment]
Well, we can live with that, but we should really write `days since` in ece2cmor3 since (quoting the same document as above) [the output metadata requirements, p.7, note 14](https://goo.gl/neswPr) states

> 14. For all time coordinates the units must be "days since <basetime>",[...]

so that really is the one thing that is clear and unambiguous about the time coordinate.
