### ISSUE TITLE
Inconsistent `time:calendar` attributes in cmorised output

### ISSUE THREAD

**Issue by ufladrich** [EC-Earth/ece2cmor3#467]
Cmorising EC-Earth output with ece2cmor results in set of files that have different `time:calendar` attributes set: NEMO/LIM files have
```time:calendar = "gregorian"```
while IFS/LPJG files have
```time:calendar = "proleptic_gregorian"```
This may in some way be natural, since NEMO does use the Gregorian calendar in it's raw output files. However, I wonder if it doesn't make sense to use the Proleptic Gregorian calendar for all output? It's not so much a problem for current experiments, for which both calendars are compatible. But is it a problem for paleo-runs, where the Gregorian calendar may not be valid?

Furthermore, it could be an QA issue, with at least the nctime package complaining when sets of files with different calendars are tested. But this could be seen as a false positive outcome.
@zklaus , I'm sure you can provide the correct references to the data request documents concerned with calendar usage? ;-)

**Comment by treerink** [comment]
@goord will try to make the NEMO/LIM time calendar "proleptic_gregorian" as well, which should be better for PMIP experiments (though it should be checked that NEMO itself handles that case correctly as well). Anyway at the ece2cmor3 side this can be fixed already now.

**Comment by zklaus** [comment]
Good point, @treerink. The whole issue really is important when the run contains dates before 1582 since in that case the dates from the components with different calendars would not line up.
That probably is relevant for PMIP runs, but depending on the setup it might also be relevant for "artificial" runs like piControl, or 4xCO2 and 1pctCO2 that don't correspond directly to historical dates and hence are sometimes started from something like year 0.

**Comment by treerink** [comment]
It seems that XIOS in fact uses  the `proleptic_gregorian calendar` according to [XIOS issue 133](http://forge.ipsl.jussieu.fr/ioserver/ticket/133), but that this is incorrectly called the `gregorian calendar` in the XIOS meta data, see `ncdump -h` output:

```
		time_centered:calendar = "gregorian" ;
		time_counter:calendar = "gregorian" ;
```
See also the linked references in this XIOS issue: https://github.com/PCMDI/cmor/issues/325 and [Taylor PCMDI docu](https://goo.gl/neswPr).

Trying to modify XIOS is maybe not the way to go here, as time units are rather essential and an eventual error would have large consequences. So, if I am correct, we could just read the NEMO time values and keep them unchanged, but then for NEMO during the cmorisation replace "gregorian" by "proleptic_gregorian" in the meta data, so it becomes:
```
		time_centered:calendar = "proleptic_gregorian" ;
		time_counter:calendar = "proleptic_gregorian" ;
```

**Comment by goord** [comment]
Ok, I will do this today

**Comment by goord** [comment]
In the single-calendar branch, I have unified the setting of the cmor calendar for all components. So a full test (including lpj2cmor) is actually preferred.

**Comment by treerink** [comment]
I will test ifs & nemo.

Can someone test with LPJG output? I can't, and from today's mail correspondence with Lars I know he hasn't time to do it this week.

**Comment by treerink** [comment]
For two NEMO variables the branch seems to work, will do a full test now.

**Comment by treerink** [comment]
For NEMO and IFS this branch seems alright for all produced variables in my test. Also I checked for one NEMO and  one IFS variable that the time values remained the same.

**Comment by treerink** [comment]
The single-calendar branch merged in the master.

Hope someone is testing for LPJG en TM5 as well.

**Comment by tommibergman** [comment]
TM5 cmorized output is proleptic_gregorian. TM5 raw output data calendar is Gregorian, but as I understand, TM5 is not used in paleo simulations. So that should not pose any problems.

**Comment by oloapinivad** [comment]
I tested it the AOGCM configuration using the `nctime` tool and it does not report any error now!

**Comment by treerink** [comment]
Great, so closing this one.

Though any reporting about LPJG component would be still nice.
