### ISSUE TITLE
IFS 10 meter wind speed

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#468]
@goord I see in the ifspar.josn that the following one is defined: 214.128 for 10 meter wind speed, shouldn't it be defined as `214.129`? It confuses now with table 128.

By the way `207.128` is IFS 10 meter wind speed according to the [IFS grib docu](https://apps.ecmwf.int/codes/grib/param-db), this one is not used because it does not work with IFS, right?

**Comment by goord** [comment]
You are right, the 10 meter wind speed is a ece2cmor3 derived variable and should be in table 129. I'm not sure whether 207 works in EC-Earth, you would have to test that.

**Comment by treerink** [comment]
fixed, closing
