### ISSUE TITLE
[QA-DKRZ] Error: Variable <*> empty data body.

### ISSUE THREAD

**Issue by oloapinivad** [EC-Earth/ece2cmor3#471]
Together with @uwefladrich we started using QA-DKRZ to investigate the cmorized data: this is a powerful that performs plenty of checks on the data quality.  There are many "warnings" and a few "errors" so we will report them separately. My tests are run on the EC-Earth AOGCM historical configuration. 

Some of the variables present in the varlist are empty, meaning that we are potentially uploading empty variables on the ESGF
```
{
            "DRS_6": [ "Omon" ],
            "DRS_7": [ "rlntds", "hfibthermds", "hflso", "friver", "agessc", "ficeberg", "hfsso" ],
            "DRS_8": [ "gn" ],
            "annotation": "Variable <*> empty data body.",
            "example": "Variable <rlntds> empty data body.",
            "tag": "6_15",
            "severity": "Error"
        },
```
 
As long as I am aware, @uwefladrich found also  `fgsf6`, `cfc11`, `fgcfc12` which come from nemo-Omon in ssp126

As seen from https://dev.ec-earth.org/issues/609 these have been already identified as empty but they are still on the varlist.json: I think that the confusion comes from the fact that they should probably be in the CC DECK runs but not in the AOGCM and in the Veg (at least for some of them, as `fgsf6`, `cfc11`, `fgcfc12` ). However, it is a bit unclear to me why runoff as `friver` is still empty: perhaps is this related to the last version of control files (I am running with r6827? 
Could somebody confirm this?

**Comment by oloapinivad** [comment]
Similarly, I think we should be aware that we need to remove from the varlist `hfcorr` and `wfcorr`: this are fluxes correctors and I guess that they should be present only for DCPP experiments. 

`````
        {
            "DRS_6": [ "Omon" ],
            "DRS_7": [ "hfcorr", "wfcorr" ],
            "DRS_8": [ "gn" ],
            "annotation": "Variable <*>: Entire file of const value=0.",
            "example": "Variable <hfcorr>: Entire file of const value=0.",
            "tag": "6_1",
            "severity": "Warning"
        }

**Comment by uwefladrich** [comment]
Concerning `friver`: We had already found out why this variable is zero in our runs, see [issue 609, note 10ff](https://dev.ec-earth.org/issues/609#note-10) on the EC-Earth Portal. However, the fix never made it's way into the output control files. It is an easy fix that changes the definition of `friver` in `file_def_nemo-opa.xml`.

**Comment by oloapinivad** [comment]
I can confirm that with the correction in the ctrl files mentioned by @uwefladrich it is possible to correctly produce and cmorize friver

**Comment by treerink** [comment]
The fix for `friver` has been applied in the ping file in the latest control-output-files branch of ec-earth3 and in the cotrol output files. And at the `genecec` side by 032f628 and 47afdb7.

**Comment by oloapinivad** [comment]
I run the QA-DKRZ on a single year as a first order test on EC-Earth3-Veg historical. All these variables are set to zero:

````
      {
            "DRS_6": [ "Emon", "Eyr", "Lmon", "Omon" ],
            "DRS_7": [ "fProductDecomp", "fDeforestToProduct", "nProduct", "fLulccProductLut", "fLuc", "fNProduct", "fProductDecompLut", "shrubFrac", "fracInLut", "cProduct", "fracOutLut", "residualFrac", "hfcorr", "wfcorr" ],
            "DRS_8": [ "gr", "gn" ],
            "DRS_9": [ "v20190613" ],
            "annotation": "Variable <*>: Entire file of const value=0.",
            "example": "Variable <fProductDecomp>: Entire file of const value=0.",
            "tag": "6_1",
            "severity": "Warning"
        },

`````

I cannot tell a lot about many of them, but for example after a chat with a colleague of mine with a bit of experience with LPJG I can say that `shrubFrac` is not computed by LPJG itself (unless something changed very recently). @uwefladrich, did you have time to run QA-DKRZ on LPJG output for the full simulation?

**Comment by uwefladrich** [comment]
I did run qa-dkrz over our AMIP and historical experiments, both with `EC-Earth3-Veg`. For AMIP, I have
```
        {
            "DRS_6": [ "Emon", "Lmon" ],
            "DRS_7": [ "treeFracNdlDcd", "fLuc", "fGrazing", "fFire" ],
            "annotation": "Warning: Data record totally with constant value  <0>.",
            "tag": "R200",
            "severity": "Warning"
        },
        {
            "DRS_6": [ "Eyr", "Lmon" ],
            "DRS_7": [ "shrubFrac", "residualFrac" ],
            "annotation": "Variable <*>: Entire file of const value=0.",
            "example": "Variable <shrubFrac>: Entire file of const value=0.",
            "tag": "6_1",
            "severity": "Warning"
        }
```

For the historical experiment, I have unfortunately problems with `qa-dkrz`. It crashes (_IndexError: list assignment index out of range_) in `qa_summary.py`. I tried to hack a fix, but it only moves the same error to another location in the code. This means that I only get a log file, but no annotations. Nevertheless, I get about the same empty LPJG files.

Overall, we are having less LPJG variables than you mention, but I guess your runs were done with a later version of EC-Earth and have more LPJG output.

Side question: @oloapinivad, have you seen similar qa-dkrz crashes?

**Comment by zklaus** [comment]
@oloapinivad could you please go through this issue, move the still relevant stuff to #504 and close this one then?

Sorry

**Comment by oloapinivad** [comment]
I am updating the Veg annotations and I will move everything to #504.
