### ISSUE TITLE
[QA-DKRZ] Warning: Missing time bounds

### ISSUE THREAD

**Issue by oloapinivad** [EC-Earth/ece2cmor3#472]
Together with @uwefladrich we started using QA-DKRZ to investigate the cmorized data: this is a powerful that performs plenty of checks on the data quality. There are many "warnings" and a few "errors" so we will report them separately. My tests are run on the EC-Earth AOGCM historical configuration.

Variable `tslsi` at 3hr seems to do not have correctly set time bounds. 

```
 {
            "DRS_6": [ "3hr" ],
            "DRS_7": [ "tslsi" ],
            "DRS_8": [ "gr" ],
            "annotation": "Missing time bounds.",
            "tag": "T_9",
            "severity": "Warning"
        },

````

**Comment by oloapinivad** [comment]
Following the recent update, also `siddivel` now is cmorized but shows the same error as `tslsi`

```
  {
            "DRS_6": [ "SImon", "3hr" ],
            "DRS_7": [ "sidivvel", "tslsi" ],
            "DRS_8": [ "gn", "gr" ],
            "annotation": "Missing time bounds.",
            "tag": "T_9",
            "severity": "Warning"
        },
```

**Comment by zklaus** [comment]
It is correct that these variables don't have time bounds; the QA warning is wrong.

Well, it's a warning, so.. but the point is that these variables *in these tables* are instantaneous and don't require time bounds. Instantaneousness can be seen by:

- `cell_method` containing `time: point`
- Frequencies ending in `...Pt`
- Associated dimension `time1` (cf [CMIP6_coordindates.json](https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_coordinate.json), ll 2374, particularly l 2381

```
            "must_have_bounds": "no",
```

**Comment by oloapinivad** [comment]
Thanks @zklaus, good news! I think we can close this!

**Comment by treerink** [comment]
Ok thanks for looking into this!

Then we close the issue :)

**Comment by zklaus** [comment]
Cheers.

Of course, the question somehow becomes why it is only complaining about two variables and no other instantaneous ones?

**Comment by goord** [comment]
Are we absolutely sure the tool uses the same data request version?

**Comment by zklaus** [comment]
Good question! However, these two variables have been in this state for 2 years, so I think it unlikely that they are affected by differing versions.

**Comment by oloapinivad** [comment]
This is what I get from QA-DKRZ

```
qa-dkrz --version -P CMIP6

qa-dkrz-0.6.7-59,master-5fdfa30|
CF_STD_NAME_VERSION:std-name=v66,15May.2019,region=v4,18Dec.2018,area=v9,07Aug.2018|
CMIP6_CVs:master-7f7e6ee|
CMIP6_MIP_tables.xlsx:2019-05-20|
CMOR:cmor-3.4.0-py27h17cb6a4_2|
cmip6-cmor-tables:master-b0b0263
```

Even if I am a bit lost, it seems that its updated to the most recent versions
