### ISSUE TITLE
Wind at 100m ua100m va100m

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#476]
As reported in #435 (see also [here):](https://github.com/EC-Earth/ece2cmor3/issues/435#issuecomment-484057109) 

````
2019-04-16 06:54:36 ERROR:ece2cmor3.grib_filter: Field missing in the first day of file: code 131.128, level type 105, level 100. Dismissing task ua100m in table 6hrPlev
2019-04-16 06:54:36 ERROR:ece2cmor3.grib_filter: Field missing in the first day of file: code 132.128, level type 105, level 100. Dismissing task va100m in table 6hrPlev
````

**Comment by oloapinivad** [comment]
Just found this here: `https://confluence.ecmwf.int/display/OIFS/How+to+control+OpenIFS+output`

> _The height level output is not encoded correctly to GRIB and may appear as model 'hybrid' levels._

That's why ece2cmor misses it.

**Comment by goord** [comment]
Hi Paolo can you confirm with grib_ls on your spectral output that this is the case? Do you see the 100m level listed as hybrid model levels?

**Comment by oloapinivad** [comment]
Yes, here an example:
```
grib_ls -w,dataDate=18500102,levelType=ml -p dataDate,dataTime,paramId,levelType,level ICMGGchst+185001 

ICMGGchst+185001
dataDate    dataTime    paramId     levelType   level       
18500102    0           131         ml          100        
18500102    0           132         ml          100        
18500102    600         131         ml          100        
18500102    600         132         ml          100        
18500102    1200        131         ml          100        
18500102    1200        132         ml          100        
18500102    1800        131         ml          100        
18500102    1800        132         ml          100        
```

**Comment by goord** [comment]
So the question now is, how can I distinguish these from 'correct' model level fields. In this case I see 100 > 91 so I know it must be 100m wind, but I don't really like such a solution. Is there something in those records that we can recognize...

**Comment by oloapinivad** [comment]
I have a very similar problem in for the `save_ic` flag (see here https://dev.ec-earth.org/issues/664) and I came across to a similar `grib_filter` option. 

However, one thing that could help us that it just pops up in my mind: these are winds, and they are in the gaussian file. Usually winds are in the spectral file (pressure and I think model levels too). This could allow us to separate the two... it should works for all the 3D spectral diagnostics (I think humidity only is in gaussian one). Could it work?

**Comment by goord** [comment]
O I didn't notice they were in the GG file... That is a distinguishing feature, although it's also a complicating one!

**Comment by goord** [comment]
Hi @oloapinivad I tried to fix the problem in the new branch uv100mfix

**Comment by oloapinivad** [comment]
Unfortunately due to the issue discussed in https://dev.ec-earth.org/issues/664 (U100 and V100 are missing as a consequence of saving initial conditions during the run) I don't have any complete year to test the new leg.

**Comment by oloapinivad** [comment]
FYI, I also discovered that U100/V100 could be saved using 228.246 and 228.247. In such case they would be at the surface, perhaps it is easier to handle.

**Comment by oloapinivad** [comment]
So I have now a complete leg where I can test the branch.
Visual inspection of the files seems they are ok, as well as values and metadata.
I think we can merge and close this.

**Comment by treerink** [comment]
Ok has been merged, thanks for testing @oloapinivad
