### ISSUE TITLE
Cmorising non-CMIP6 variables

### ISSUE THREAD

**Issue by klauswyser** [EC-Earth/ece2cmor3#478]
I have been asked to save the daily maximum zos in our experiments. This is not a CMIP6 variable, yet I managed to modify the file-def.xml file and save zosmax in the daily 2-D NEMO output. But when it comes to cmorising this variable I am stuck. I have added a "zosmax" entry in the CMIP6_Oday file, and a "zosmax" entry in  my own nemopar.json file. When then running ece2cmor (with --nemopar.json nemopar.json) I get:

````
Traceback (most recent call last):
  File "/home/sm_wyser/.conda/envs/ece2cmor3-test/bin/ece2cmor", line 11, in <module>
    load_entry_point('ece2cmor3==1.1.0', 'console_scripts', 'ece2cmor')()
  File "/home/sm_wyser/.conda/envs/ece2cmor3-test/lib/python2.7/site-packages/ece2cmor3-1.1.0-py2.7.egg/ece2cmor3/ece2cmor.py", line 118, in main
    check_duplicates=True)
  File "/home/sm_wyser/.conda/envs/ece2cmor3-test/lib/python2.7/site-packages/ece2cmor3-1.1.0-py2.7.egg/ece2cmor3/taskloader.py", line 74, in load_tasks
    return create_tasks(filtered_matches, get_models(active_components))
  File "/home/sm_wyser/.conda/envs/ece2cmor3-test/lib/python2.7/site-packages/ece2cmor3-1.1.0-py2.7.egg/ece2cmor3/taskloader.py", line 533, in create_tasks
    parmatch = [b for b in parblocks if matchvarpar(target, b)][0]
IndexError: list index out of range
````

However, if I make a similar change not in my own nemopar.json but in the nemopar.json that has been installed in the conda env, then everything works fine.

Could it be that the option ``--nemopar.json ...`` is never used? I tested by adding a syntax error in my own nemopar.json file and it didn't trigger any error.

If you'd like to test my example I have put my varlist.json, CMIP6_Oday.json, nemopar.json and an example netCDF file on our [Exporter](http://exporter.nsc.liu.se/b1ae3cf45abf45d78239905b03ed4172)

I don't know whether or not the *par.json work for other components but it would be nice to have this functionality.

**Comment by treerink** [comment]
I tried your case of  introducing an error in the `ece2cmor3/resources/nemopar.json`, but in my case it does lead to an error. So I cannot confirm your case.

Could it be you made your modifications but forgot to run in your ece2cmor3 root directory:
`````
python setup.py install
`````
because in that case many changes are ignored (you need to do this after each change). If you get annoyed of running this one after each single modification you can also use
`````
python setup.py develop
`````
so your changes immediately affect your test.

**Comment by klauswyser** [comment]
Well, I though that setting ``--nemopar.json ...`` would overwrite the default nemopar.json file that has been installed with ```python setup.py install``. If one always needs to run setup to update the default nemopar.json file then there is no point in having a ``--nemopar.json`` option in ``ece2cmor``, or am I missing something?

**Comment by treerink** [comment]
My test and reply before only covers your last remark. So it is still possible that somehow when you explicitly specify the `--nemopar.json option` it doesn't take that one. Need to test that first.

**Comment by goord** [comment]
Hi Klaus, that is correct, the --nemopar and --tabdir options (should) override the installed files so no need to reinstall the package. I will add extra logging to see what's going on.

**Comment by klauswyser** [comment]
@goord: just to let you know that ``--tabdir`` works fine, I am using it to make ece2cmor use my modifed tables. I am only having problems with the ``--nemopar.json`` option.

**Comment by goord** [comment]
Hmm it looks like the 'custom' model table file feature has been lost during the restructuring of the task loading...

**Comment by treerink** [comment]
Indeed I can also confirm that currently with the option `--nemopar.json modified-nemopar.json` instead of the `modified-nemopar.json` still the default `nemopar.json` is taken.

**Comment by goord** [comment]
Hi @klauswyser and @treerink I attempted to fix your problem in the parfile-fix branch

**Comment by treerink** [comment]
Tested, works fine, I will merge it into the master now.

**Comment by treerink** [comment]
Tested after merge in master, works fine, so closing issue.
