### ISSUE TITLE
pip installable distribution

### ISSUE THREAD

**Issue by jmrgonza** [EC-Earth/ece2cmor3#48]
I forked into [this project](https://github.com/jmrgonza/ece2cmor3) to create a distribution of ece2cmor3 that could be installed through pip. It is available for testing.
To create a source distribution:
`python setup.py sdist`
To install the resulting file:
`pip install dist/ece2cmor3-1.0.0.tar.gz`

**Comment by goord** [comment]
Since there exists no CMOR3 pip package, I propose to drop this request and focus on the release of a conda package.

**Comment by jmrgonza** [comment]
Actually, you can use the pip package in the conda release. That was also my goal in the forked project.

**Comment by goord** [comment]
Ok, let's have a look at that then. I like pip slightly more than conda.

**Comment by zklaus** [comment]
What happened to this? In the current version it seems
```
python setup.py sdist
```
works.
@jmrgonza: Can this issue be closed? If not, could you check what needs to be done and prepare a pull request?

**Comment by jmrgonza** [comment]
The development in my fork was merged long ago, but with the aim to create a conda package for the distribution of ece2cmor3. The pip package was an intermediate step for that. I have not tested it recently, but I am almost sure that the requirements for the conda package are outdated. They are listed in the meta.yaml file, and control the installation of required conda packages. At the moment that I opened the issue, all the dependencies were required to be conda packages, which I think it is not the case now.
From the logs, I see that the setup.py file has been mantained, which means that you can probable use it to do a pip based installation.
As far as I know, the conda package was never built, probably because a conda repository was needed for a proper distribution of the package.
There is no problem from my side to close the issue. If we want a conda package in the future I offer to collaborate in building it.

**Comment by treerink** [comment]
Ok let's close this then for now. If in the end we want someting like this, we just open a new issue. As long we don't are at a 1.0 or higher version, we are not investing the time yet.
