### ISSUE TITLE
UserWarning: Error: your data shape ((256, 512, 1, 1460)) does not match the expected variable shape ([256, 512, 91, 0])

### ISSUE THREAD

**Issue by pnolan22** [EC-Earth/ece2cmor3#480]
I am experiencing the following errors/warnings with ece2cmor3:

**/ichec/work/ichec002/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/cmor/pywrapper.py:764: UserWarning: Error: your data shape ((256, 512, 1, 1460)) does not match the expected variable shape ([256, 512, 91, 0])
Check your variable dimensions before caling cmor_write
warnings.warn(msg)**

ece2cmor3 completes for nemo and produces over ~60GB of IFS data but then hangs until job time exceeds. I get the same problem on both cca and the ICHEC machine.

Has anyone else experienced such problems?

I used EC-Earth 3.3.1 (and the control output files of this version) and the master version of ece2cmor3 as of 05/06/2019 (commit a99fc7f46e7d81510fed1be9be0c28056752d2d1).

**Comment by goord** [comment]
Hi @pnolan22 this looks like a mode-level variable you're trying to process, which is not there in your output. You can skip these with the ```--skip_alevel_vars``` option. If you do want to have those, you probably will need to rerun the model with 3D model level variables enabled....

**Comment by pnolan22** [comment]
Thank you @goord for your helpful & prompt response. Using "--skip_alevel_vars" solved the problem.
