### ISSUE TITLE
tos 3hr time window

### ISSUE THREAD

**Issue by oloapinivad** [EC-Earth/ece2cmor3#487]
Hi all,

there is something which puzzles me regarding 3hr `tos` (see #477)
This is an instantaneous field - not a flux - which should be exactly as `tas`, since physically should be the same. Both in the table reads `frequency": "3hrPt"`

So why the files have different time window? tos ends up at the midnight (as a cumulated flux) while tas ends at the 2100 of the 31/12. You can spot this from the file names:

`tos_3hr_EC-Earth3_historical_r4i1p1f1_gn_185001010300-185101010000.nc`
`tas_3hr_EC-Earth3_historical_r4i1p1f1_gr_185001010000-185012312100.nc`

Is this expected?

**Comment by goord** [comment]
Well they come from different models, and I know for instance that XIOS does not produce initial state variables, but always at the end of the time step, just like the flux variables in IFS

**Comment by oloapinivad** [comment]
I see as long as it is instantaneous in XIOS too should be fine. Closing this.
