### ISSUE TITLE
fixmonths/filter6h works only if previous month is given

### ISSUE THREAD

**Issue by pabretonniere** [EC-Earth/ece2cmor3#49]
Hi,

After discussion with @goord, we wanted to make a point about the use of the filter6h in the primavera branch. For the 1st month of the leg/chunk, the "previous file" must be prescribed (filter6h.py -p ICMGG$expid+000000 ICMGG$expid+195001) else the CMORization works but doesn't produce the good timestamp (half a time step forward shift). This must be taken into account when cmorizing the files.

Thanks.

**Comment by goord** [comment]
Closed issue, the fixmonths script is deprecated and one should use the autofilter option or use their own script to filter raw model output.
