### ISSUE TITLE
Frequent failure of cmorisation of ua100m & va100m

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#496]
During the cmorisation of the `scenario ssp5 8.5` results I see the following:

About half of the times `ua100m_6hrPlev` & `va100m_6hrPlev` are cmorised, that means for IFS I have 146 or 144 cmorised variables for `scenario ssp5 8.5`. It seems random for me which leg has it, and which one doesn't have it.

The related error in the ece2cmor3 log:
```
ERROR:ece2cmor3.cdoapi: (returncode:1) cdo(2) selcode: Process started
ERROR:ece2cmor3.postproc: Could not retrieve height levels for ua100m with axes []
ERROR:ece2cmor3.cdoapi: (returncode:1) cdo(2) selcode: Process started
ERROR:ece2cmor3.postproc: Could not retrieve height levels for va100m with axes []
```

The slurm log reports something like:
```
Error in calling operator showltype with:
>>> cdo -O showltype -selcode,131 /lustre3/projects/CMIP6/reerink/temp-cmor-dir/s585/ifs/211/s585-ifs-2060/131.128.109.6<<<
STDOUT:

STDERR:cdo(2) selcode: Process started
Warning (cgribexScanTimestep2): Record  3 (id=131.128 lev1=1 lev2=0) timestep 2: Parameter not defined at timestep 1!
cdo(2) selcode: Open failed on >/lustre3/projects/CMIP6/reerink/temp-cmor-dir/s585/ifs/211/s585-ifs-2060/131.128.109.6<
Unsupported file structure

Error in calling operator showltype with:
>>> cdo -O showltype -selcode,132 /lustre3/projects/CMIP6/reerink/temp-cmor-dir/s585/ifs/211/s585-ifs-2060/132.128.109.6<<<
STDOUT:

STDERR:cdo(2) selcode: Process started
Warning (cgribexScanTimestep2): Record  3 (id=132.128 lev1=1 lev2=0) timestep 2: Parameter not defined at timestep 1!
cdo(2) selcode: Open failed on >/lustre3/projects/CMIP6/reerink/temp-cmor-dir/s585/ifs/211/s585-ifs-2060/132.128.109.6<
Unsupported file structure

('caught signal', <cdo.Cdo object at 0x7f80adc79350>, 15, <frame object at 0x7f80adbf2790>)
```

**Comment by oloapinivad** [comment]
As discussed with @goord the main issue of these two variables is that they are stored on hybrid levels even if they are on height levels, and this is quite a big problem since it creates confusion to the grib filtering. For instance, if you save initial conditions during your leg you will lose these variables (see https://dev.ec-earth.org/issues/665 and https://dev.ec-earth.org/issues/664: a solution is provided there). 

Do you save initial conditions in your run? Can you run a grib_ls and see if the variables are there for the whole leg? 

An alternative would be to use 228.246 and 228.247 as mentioned in #476

**Comment by treerink** [comment]
Added a branch `ua-va-100m,` in which I will try to make use of grib codes `228.246` and `228.247` as you suggested.

**Comment by oloapinivad** [comment]
If you decide to go for this way please only try to keep a backward compatibility with the formulation on hybrid levels: many of us already run - me included ;-) - the model with the previous ppt files so that we need to be able to cmorise `u100m` and `v100m` from `131` and `132`.

**Comment by treerink** [comment]
Okay, that's not really workable: a backward compatible option in ece2cmor3 is already not so nice but possible. But with the control files you need then a total separate archiving. (I just run genecec with the branch, that seems to work fine so far).  I think it is not worth these two variables. I propose to skip them at all then?

**Comment by oloapinivad** [comment]
Well, with the current configuration I am able to cmorise them from the hybrid levels. See the figure here for `u100m`: <img width="1034" alt="Schermata 2019-06-18 alle 14 16 57" src="https://user-images.githubusercontent.com/28352235/59681251-c1610a00-91d3-11e9-9ea9-d0ba1c512813.png">
The file passes the PrePARE checks and on the 5 years I am testing I always got it right. Could it be that there is something in your configuration/output?

**Comment by treerink** [comment]
I have also many legs with this correct output as you show, but also many ones without as said above. See the list below, when in the 2nd column I have 144 then I miss ua100m & va100m, when I have 146 these are included and fine.

Well maybe it is only something on our KNMI HPC?

First column is leg nr of scenario run. Second column is number of successfully cmorised variables:
```
166: 108  This probably due to the restart of historical run, stuff is missing

167: 146
168: 146
169: 146
170: 146
171: 144
172: 146
173: 144
174: 146
175: 146
176: 146
177: 146
178: 146
179: 144
180: 144
181: 146
182: 144
183: 144
184: 146
185: 144
186: 144
187: 146
188: 146
189: 144
190: 146
191: 144
192: 146
193: 146
194: 144
195: 146
196: 144
197: 146
198: 146
199: 144
200: 146
201: 144
202: 146
203: 146
204: 144
205: 144
206: 146
207: 146
208: 144
209: 146
210: 146
211: 144
212: 144
213: 144
214: 146
215: 144
216: 146
217: 144
218: 146
219: 144
220: 144
221: 146
222: 146
223: 146
224: 144
225: 144
226: 146
227: 144
228: 146
229: 146
230: 146
231: 144
232: 146
233: 144
234: 144
235: 144
236: 146
237: 146
238: 144
239: 144
240: 144
241: 146
242: 146
243: 144
244: 146
```

**Comment by goord** [comment]
Hi @treerink although it would be better to use the dedicated surface variables in IFS for these 100m winds (not sure how good the interpolation in the boundary layer by fullpos is), it can become a pain to keep things backward compatible. I don't know why your cmorization of ua100 and va100 fails half of the time, but on Thursday I could have a look at the temporary files created within one of those failed legs (the log doesn't provide any usable information)

**Comment by plesager** [comment]
I have a similar issue on the KNMI HPC with the `ece3-postproc/hiresclim2` package. It crashed for 2 years out of 65, where @grib_filter@ produces grib files with "missing GRIB end section". Quite puzzled by that...

**Comment by goord** [comment]
@treerink can you post the log file of one of the incomplete legs?

BTW I can implement a solution where the 'old' output is still accepted, but the dedicated surface fields have preference for the 100m winds.

**Comment by treerink** [comment]
@goord  I think it is all in the [first post here](https://github.com/EC-Earth/ece2cmor3/issues/496#issue-456836914). At this moment I don't have them anymore, as I am preparing for shipping the disks one by to Sweden now, I just omitted `ua100m` & `va100m` from the cmorisation.

**Comment by treerink** [comment]
For our CMIP historical run I get the same behavior after the restart in 1949: `ua100m` & `va100m` are in about 30% of the cases missing. Before the restart they are always there. We restarted our run in 1949 because we include from there on the CORDEX model level output. So clearly switching on model level output causes this problem, which is indeed the case for our scenario runs as well.

**Comment by goord** [comment]
Hmm seems some misidentification in the grib filtering...

**Comment by treerink** [comment]
Hi Gijs,

The relevant path at the bull for the data:
```
/lustre3/projects/CMIP6/reerink/ec-earth-3/branch-r6485-historical-setup/h002/output/ifs
```
For the cmorised result:
```
/lustre3/projects/CMIP6/reerink/cmorised-results/cmor-cmip-historical/h002/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/part-1/6hrPlev
```
For instance the cmorised data of year 1951 (leg 102) includes the ua100m & va100m, while for year1952 (leg 103) those two fields fail.

**Comment by treerink** [comment]
Going to merge the `ua-va-100m` branch into the master. This means `genecec` needs to be rerun and the control-output files need an update, which will be made available in the `r7144-control-output-files` branch in the ec-earth repository.

**Comment by treerink** [comment]
The changes are uploaded in the ec-earth repository in  r7309 in the `r7144-control-output-files` branch.

Closing.
