### ISSUE TITLE
Unused dimension bnds

### ISSUE THREAD

**Issue by zklaus** [EC-Earth/ece2cmor3#506]
ece2cmor produces a dimension `bnds` in every netcdf file.
This is used for all bounded 1d coordinates, which might be `lat`, `lon`, or `time`.
However, in (very) few cases there are no bounded 1d coordinates in the file and the still existing `bnds` dimension goes unused. This is namely the case for ocean variables (lat, lon are 2d) that are instantaneous (time is unbounded).

It would be cleanest to not produce this dimension in this case, but if this is very difficult, I would consider it a low priority item.

Let us just document here the decision so that we can take it into account for the QA.

**Comment by goord** [comment]
Hi @zklaus I didn't check this myself but I would expect no time bounds at all for instantaneous variables:
on line 297 of nemo2cmor 
```python
if time_bounds is None:
    tid = cmor.axis(table_entry=str(time_dim), units=tunits, coord_vals=tstamps)
```
The variable ```time_bounds``` is read from the XIOS output, so apparently XIOS produces bounds for instantaneous variables. Can you confirm that?
A possible fix in that case would be to dismiss the time bounds if the CMOR variable is instantaneous. However, that opens up a possible loophole for averaged variables to be treated as instantaneous fields...

**Comment by oloapinivad** [comment]
ncdump output from 3hr opa file, which includes which is one of the variables in the QA-DKRZ list

```
netcdf chis_3h_18590101_18591231_opa_grid_T_2D {
dimensions:
	axis_nbounds = 2 ;
	x = 362 ;
	y = 292 ;
	nvertex = 4 ;
	time_counter = UNLIMITED ; // (2920 currently)
variables:
	float nav_lat(y, x) ;
		nav_lat:standard_name = "latitude" ;
		nav_lat:long_name = "Latitude" ;
		nav_lat:units = "degrees_north" ;
		nav_lat:bounds = "bounds_nav_lat" ;
	float nav_lon(y, x) ;
		nav_lon:standard_name = "longitude" ;
		nav_lon:long_name = "Longitude" ;
		nav_lon:units = "degrees_east" ;
		nav_lon:bounds = "bounds_nav_lon" ;
	float bounds_nav_lon(y, x, nvertex) ;
	float bounds_nav_lat(y, x, nvertex) ;
	float area(y, x) ;
		area:standard_name = "cell_area" ;
		area:units = "m2" ;
	double time_instant(time_counter) ;
		time_instant:standard_name = "time" ;
		time_instant:long_name = "Time axis" ;
		time_instant:calendar = "gregorian" ;
		time_instant:units = "seconds since 1800-01-01 00:00:00" ;
		time_instant:time_origin = "1800-01-01 00:00:00" ;
		time_instant:bounds = "time_instant_bounds" ;
	double time_instant_bounds(time_counter, axis_nbounds) ;
	double time_counter(time_counter) ;
		time_counter:axis = "T" ;
		time_counter:standard_name = "time" ;
		time_counter:long_name = "Time axis" ;
		time_counter:calendar = "gregorian" ;
		time_counter:units = "seconds since 1800-01-01 00:00:00" ;
		time_counter:time_origin = "1800-01-01 00:00:00" ;
		time_counter:bounds = "time_counter_bounds" ;
	double time_counter_bounds(time_counter, axis_nbounds) ;
	float tos(time_counter, y, x) ;
		tos:standard_name = "sea_surface_temperature" ;
		tos:long_name = "potential sea surface temperature" ;
		tos:units = "degC" ;
		tos:online_operation = "instant" ;
		tos:interval_operation = "3 h" ;
		tos:interval_write = "3 h" ;
		tos:cell_methods = "time: point" ;
		tos:cell_measures = "area: area" ;
		tos:_FillValue = 1.e+20f ;
		tos:missing_value = 1.e+20f ;
		tos:coordinates = "time_instant nav_lat nav_lon" ;

// global attributes:
		:name = "chis_3h_18590101_18591231_opa_grid_T_2D" ;
		:description = "Created by xios" ;
		:title = "Created by xios" ;
		:Conventions = "CF-1.6" ;
		:timeStamp = "2019-Jun-13 03:49:27 GMT" ;
		:uuid = "302be0bf-7cf9-4f7a-8aea-81f59fe6a6a6" ;
}
````

**Comment by zklaus** [comment]
What @oloapinivad posted is the raw model output. I am talking about the ece2cmor output. @goord is right that there are no time bounds, and that is correct.

What I was talking about is the *dimension*. Here an excerpt from the ncdump for `(Ofx, areacello)` (I leave out only the global attributes).
```
netcdf areacello_Ofx_EC-Earth3-Veg_historical_r1i1p1f1_gn {
dimensions:
        j = 292 ;
        i = 362 ;
        bnds = 2 ;
        vertices = 4 ;
variables:
        int j(j) ;
                j:units = "1" ;
                j:long_name = "cell index along second dimension" ;
        int i(i) ;
                i:units = "1" ;
                i:long_name = "cell index along first dimension" ;
        double latitude(j, i) ;
                latitude:standard_name = "latitude" ;
                latitude:long_name = "latitude" ;
                latitude:units = "degrees_north" ;
                latitude:missing_value = 1.e+20 ;
                latitude:_FillValue = 1.e+20 ;
                latitude:bounds = "vertices_latitude" ;
        double longitude(j, i) ;
                longitude:standard_name = "longitude" ;
                longitude:long_name = "longitude" ;
                longitude:units = "degrees_east" ;
                longitude:missing_value = 1.e+20 ;
                longitude:_FillValue = 1.e+20 ;
                longitude:bounds = "vertices_longitude" ;
        double vertices_latitude(j, i, vertices) ;
                vertices_latitude:units = "degrees_north" ;
                vertices_latitude:missing_value = 1.e+20 ;
                vertices_latitude:_FillValue = 1.e+20 ;
        double vertices_longitude(j, i, vertices) ;
                vertices_longitude:units = "degrees_east" ;
                vertices_longitude:missing_value = 1.e+20 ;
                vertices_longitude:_FillValue = 1.e+20 ;
        float areacello(j, i) ;
                areacello:standard_name = "cell_area" ;
                areacello:long_name = "Grid-Cell Area for Ocean Variables" ;
                areacello:comment = "Horizontal area of ocean grid cells" ;
                areacello:units = "m2" ;
                areacello:original_name = "areacello" ;
                areacello:cell_methods = "area: sum" ;
                areacello:missing_value = 1.e+20f ;
                areacello:_FillValue = 1.e+20f ;
                areacello:coordinates = "latitude longitude" ;
}
```

As you can see in the `dimensions` section there is an entry for `bnds`, which is not used at all in the rest of the file.

This affects ocean variables that don't have time bounds, essentially those from `Ofx` and any instantaneous ones from any table.

**Comment by oloapinivad** [comment]
> The variable time_bounds is read from the XIOS output, so apparently XIOS produces bounds for instantaneous variables. Can you confirm that?

I posted the raw model output replying to this specific question of @goord.

**Comment by zklaus** [comment]
Yes, sorry @oloapinivad, didn't mean to be rude. Please accept my apologies.

I was only hiding your post because actually the ece2cmor output is more correct than @goord thought: The fields are actually correctly output without time bounds. It is only the dimension that is superfluous.

**Comment by goord** [comment]
Hi @zklaus this I think is an issue in the underlying CMOR library, I think it is always creating this dimension even when no variables with time bounds are included... This is not so easy to fix, we should address it perhaps with the PCMDI people.

**Comment by zklaus** [comment]
Right. I commented on an already existing issue on the topic there (PCMDI/cmor#482) and suggest we ignore this here pending resolution of that issue.
