### ISSUE TITLE
Missing 1 or 2 variables in 2015 cmorised scenario output

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#509]
For scenario s585 all seems fine. But for the other scenarios I am just missing 1 or 2 variables in the 2015 cmorised output which is the first leg of the scenario experiments after they have been restarted from the historical run.

With
```
find CMIP6/ -name '*_2015*.nc' |sort -u > find-all-2015-variables.txt; find CMIP6/ -name '*_2016*.nc' |sort -u > find-all-2016-variables.txt
meld find-all-2015-variables.txt find-all-2016-variables.txt &
```

I detect that `Oday` `tos` is missing from my 2015 scenario s370 cmorised output:
```
CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp370/r1i1p1f1/Oday/tos/gn/v20190702/tos_Oday_EC-Earth3_ssp370_r1i1p1f1_gn_20160101-20161231.nc
```

I detect that `SImon` `sidivvel` s missing from my 2015 scenario s245 cmorised output:
```
CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp245/r1i1p1f1/SImon/sidivvel/gn/v20190701/sidivvel_SImon_EC-Earth3_ssp245_r1i1p1f1_gn_201602-201701.nc
```

I detect that `Oday` `tos` & `SIday `siconc` are missing from my 2015 scenario s370 cmorised output:
```
CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp126/r1i1p1f1/3hr/tos/gn/v20190701/tos_3hr_EC-Earth3_ssp126_r1i1p1f1_gn_201601010300-201701010000.nc
CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp126/r1i1p1f1/SIday/siconc/gn/v20190701/siconc_SIday_EC-Earth3_ssp126_r1i1p1f1_gn_20160101-20161231.nc
```

**Comment by jmrgonza** [comment]
Hi Thomas,
comparing the control files, I have found that the ppt0000000000 and pptdddddd0600 files are different in ssp126 and ssp585 from the ones in ssp245 and ssp370.
In ssp126 and ssp585 there is an additional entry in MFP3DFS (code 133), whereas in ssp245 and ssp370 it is not included. Could this be the cause of the cmorization problems?

**Comment by treerink** [comment]
Hi @jmrgonza  yes I have seen this as well, it is a different issue though. I was planning to mention this at the wiki (to come). I myself did add `hus` `133` in the ppt 's for `ssp245` & `ssp370,` but I didn't add it to the json data request file, because I don't know what will happen with the ESGF checks. Actually I guess it is a data request error, I can't think of a reason to omit this important variable in twoof the four scenario experiments, seems also not consistent.

**Comment by oloapinivad** [comment]
@treerink should we report this to who produce the data request (I guess it is PCMDI but I am not sure on which portal I should address it...)

**Comment by treerink** [comment]
Please for the hus problem continue here: In scenario s245 & s370 hus (grib 133) is missing #517

**Comment by treerink** [comment]
I opened this issue originally in order to share this kind of experience.  The cmorisation of this particularly dataset has been repeated later. From general experience it looks like this situation is typically encountered in the case of a simple glitch. So just repeat and it will be solved.

Closing the issue, as it got outdated further.
