### ISSUE TITLE
Apply a time shift

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#513]
It would be easy to have a kind of simple option / hack to apply a time shift. For instance our piControl starts at 2260, but it would be nicer to have it start at 1850, though it not really matters of course.

**Comment by treerink** [comment]
A little hack is added and can be activated by uncommenting in `nemo2cmor.py` & `fs2cmor.py` the stating lines:
```python
timeshift = datetime(2260,1,1) - datetime(1850,1,1)   # Apply timeshift for instance in case you want manually to add a shift for the piControl
```
In case you want to shift the starting time from 2260 to 1850, the rest of the times use the same shift.

Default the shift is zero of course.

Done, closing.

**Comment by goord** [comment]
Hi Thomas, you accidentily checked in the uncommented code (see failing tests), I will comment this out...
