### ISSUE TITLE
msftyz not working for HR grid

### ISSUE THREAD

**Issue by aearamos** [EC-Earth/ece2cmor3#518]
Hi,

Here at BSC we tried to cmorise msftyz with a high resolution grid (ORCA025L75) and I got an error in gridlatitude:

2019-07-16 04:18:21 INFO:ece2cmor3.nemo2cmor: Creating NEMO grids in CMOR...

^[[2;31;47mC Traceback:
! In function: cmor_check_monotonic
! called from: cmor_treat_axis_values
! called from: cmor_axis
! ^[[0m

^[[1;31;47m!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: axis gridlatitude (table: Omon) has non monotonic values:
! 89.707733, 89.725159 and  89.707733
!
!!!!!!!!!!!!!!!!!!!!!!!!!^[[0m

And I also got this similar error:

^[[1;31;47m!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: axis gridlatitude (table: Omon) has non monotonic
! bounds values : 89.684120, 89.716446, 89.699020
!
!!!!!!!!!!!!!!!!!!!!!!!!!^[[0m

The number of points in my grid is x = 1442 and y = 1050.

Is it a release issue or maybe it's because of the resolution?

Thanks

**Comment by goord** [comment]
Hi Arthur, is this issue still a problem? If so, can you send me the NEMO output file containing msftyz?

**Comment by aearamos** [comment]
I believe we just removed this variable from the varlist.json and continued the run. 
I just added this variable to our HR run and will send you the file ASAP.

**Comment by treerink** [comment]
@aearamos what is the status here?

**Comment by aearamos** [comment]
Hi @treerink we should close the issue for now. We're not using this variable and I didn't have a chance to reproduce it.
