### ISSUE TITLE
Cmorisation of TM5 netcdf output

### ISSUE THREAD

**Issue by aearamos** [EC-Earth/ece2cmor3#522]
Hi,

This isn't much of a bug, but more a request for some help and/or clarification. I'm trying to cmorise the TM5 output that comes in netcdf format, but right after ece2cmor finds all the variables from the varlist, I get the following error:

2019-07-25 17:18:04 INFO:ece2cmor3.ece2cmorlib: Selected 109 TM5 tasks from 109 input tasks
Traceback (most recent call last):
  File "./ece2cmor.py", line 158, in <module>
    main()
  File "./ece2cmor.py", line 149, in main
    ece2cmorlib.perform_tm5_tasks(args.datadir, args.tmpdir, args.exp, refdate)
  File "/gpfs/scratch/bsc32/bsc32436/a217/auto-ecearth3/ece2cmor/ece2cmor3/ece2cmorlib.py", line 221, in perform_tm5_tasks
    if (not tm52cmor.initialize(datadir, expname, table_dir, prefix, refdate)):
  File "/gpfs/scratch/bsc32/bsc32436/a217/auto-ecearth3/ece2cmor/ece2cmor3/tm52cmor.py", line 74, in initialize
    print netCDF4.Dataset(areacella_file[0])
IndexError: list index out of range

Apparently, it can't read or find the areacella file. I have one areacella netcdf file in my tm5 output directory:

areacella_AERfx_EC-Earth3-AerChem_a1ud_r1i1p1f1_gn.nc

Since I have no experience whatsoever with TM5 output, I'm not sure this is the right file, format or location. Any thoughts here?

Thank you

**Comment by tommibergman** [comment]
It falls on me. It is weird, it seems that the master (you are using master, right?) has some left over debugging stuff. I'll have to fix it. I am sorry, I was not aware that someone is already using TM5 cmorization, since it is all AerChemMIP output, and AerChem version is not tuned yet.

**Comment by aearamos** [comment]
Hi Tommi,

Thank you for replying. 

I'm using master, yes. Here at BSC, we're starting to try to cmorise the output to get it to work before the main runs. I don't know much about the AerChem runs or even about TM5, so I just tried running ece2cmor using the output I was provided. I tried debugging but I don't know much about the output structure. 

I believe the netcdf files come pre-cmorised, right? So all we have to do is fix the metadata, just like the NEMO cmorisation.

I can test some fixes you suggest.

**Comment by tommibergman** [comment]
I is really weird, if you have the areacella file in the same directory as the rest of output, it works for me.  It should work if path and expname are correct. 

What you can do easily is to comment the two lines getting the areacella to see if it works otherwise. Areacella is only needed for zonal means, so most data should finish even without. Of course when it gets to zonal means it will crash again.

**Comment by tommibergman** [comment]
Just to comment on the error, the code returns a list based on expname, path, 'fx' and 'areacella'. Normally this is length 1, but for you it is an empty list.

**Comment by tommibergman** [comment]
Actually I should make an error handler there.

**Comment by treerink** [comment]
@tommibergman What is the status of this? Can this issue be closed?

**Comment by tommibergman** [comment]
It is not done yet. I have an error handler locally, but I wanted to make another branch after fix-ec505aer for creation of a pull request.

**Comment by aearamos** [comment]
Hi,

So, most of my variables are working now. It was a problem with the names of my files and the regex. My issue now is with the "ps" variable, table Amon. 

When I use the varlist from CMIP/EC-EARTH-AerChem/cmip6-experiment-CMIP-1pctCO2, I have the following tm5 varlist:

```
 "tm5": {
        "Amon": [
            "ch4",
            "ch4global"
        ]
    }
```
And when I run cmorisation for tm5, I get the following error: 

Traceback (most recent call last):
  File "./ece2cmor.py", line 157, in <module>
    main()
  File "./ece2cmor.py", line 148, in main
    ece2cmorlib.perform_tm5_tasks(args.datadir, args.tmpdir, args.exp, refdate)
  File "/gpfs/scratch/bsc32/bsc32436/a2bb/auto-ecearth3/ece2cmor/ece2cmor3/ece2cmorlib.py", line 223, in perform_tm5_tasks
    tm52cmor.execute(tm5_tasks)
  File "/gpfs/scratch/bsc32/bsc32436/a2bb/auto-ecearth3/ece2cmor/ece2cmor3/tm52cmor.py", line 195, in execute
    ps_tasks=get_ps_tasks(tasks)
  File "/gpfs/scratch/bsc32/bsc32436/a2bb/auto-ecearth3/ece2cmor/ece2cmor3/tm52cmor.py", line 861, in get_ps_tasks
    setattr(ps_task, cmor_task.output_path_key, filepath[0])
IndexError: list index out of range

So I had to remove the "ps" variable from ifs and add it to tm5 in the varlist, since I can't have the same variable in both models. This way cmorisation works fine. 

Is this an issue with cmorisation of tm5 or the data request?

Thanks!

**Comment by etiennesky** [comment]
I would check with existing or new ece2cmor3 issue. 

Ps is computed by ifs and sent to tm5 which is lower res so we want to report ps from ifs not tm5.

On October 25, 2019 3:28:02 PM GMT+02:00, Arthur Ramos <notifications@github.com> wrote:
>Hi,
>
>So, most of my variables are working now. It was a problem with the
>names of my files and the regex. My issue now is with the "ps"
>variable, table Amon. 
>
>When I use the varlist from
>CMIP/EC-EARTH-AerChem/cmip6-experiment-CMIP-1pctCO2, I have the
>following tm5 varlist:
>
>```
> "tm5": {
>        "Amon": [
>            "ch4",
>            "ch4global"
>        ]
>    }
>```
>And when I run cmorisation for tm5, I get the following error: 
>
>Traceback (most recent call last):
>  File "./ece2cmor.py", line 157, in <module>
>    main()
>  File "./ece2cmor.py", line 148, in main
>ece2cmorlib.perform_tm5_tasks(args.datadir, args.tmpdir, args.exp,
>refdate)
>File
>"/gpfs/scratch/bsc32/bsc32436/a2bb/auto-ecearth3/ece2cmor/ece2cmor3/ece2cmorlib.py",
>line 223, in perform_tm5_tasks
>    tm52cmor.execute(tm5_tasks)
>File
>"/gpfs/scratch/bsc32/bsc32436/a2bb/auto-ecearth3/ece2cmor/ece2cmor3/tm52cmor.py",
>line 195, in execute
>    ps_tasks=get_ps_tasks(tasks)
>File
>"/gpfs/scratch/bsc32/bsc32436/a2bb/auto-ecearth3/ece2cmor/ece2cmor3/tm52cmor.py",
>line 861, in get_ps_tasks
>    setattr(ps_task, cmor_task.output_path_key, filepath[0])
>IndexError: list index out of range
>
>So I had to remove the "ps" variable from ifs and add it to tm5 in the
>varlist, since I can't have the same variable in both models. This way
>cmorisation works fine. 
>
>Is this an issue with cmorisation of tm5 or the data request?
>
>Thanks!
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/EC-Earth/ece2cmor3/issues/522#issuecomment-546353722

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

http://bsc.es/disclaimer

**Comment by tommibergman** [comment]
> Hi,
> 
> So, most of my variables are working now. It was a problem with the names of my files and the regex. My issue now is with the "ps" variable, table Amon.

Can you tell what was the problem with the regex, I could make it more elaborate to catch files correctly, it that is needed.

**Comment by tommibergman** [comment]
About the ps, it is a bit of a tricky variable. We need that for 3D variables also in TM5, because it has to be either saved in all the model level variables or used for interpolation of the pressure level variables. I think I already have implemented some exceptions for it on time resolutions where it is not normally included in the data request, so that could be extended.

**Comment by aearamos** [comment]
Hi, Tomi.

So my tm5 output files were pre-cmorised (AERCOM output) and the names are, for example:

areacella_AERfx_EC-Earth3-AerChem_a2ax_r1i1p1f1_gn.nc
ch4_AERmon_EC-Earth3-AerChem_a2ax_r1i1p1f1_gn_199001-199012.nc
bldep_AERmon_EC-Earth3-AerChem_a2ax_r1i1p1f1_gn_199001-199012.nc

I tried running the cmorisation and it couldn't find any of my files, causing the search for the areacella file in cmor_utils.py to fail, as well for all the other files. 

I fixed just by looking for every .nc file, but it's not ideal I think. 
Here's my generic fix:

> def find_tm5_output(path, expname=None, varname=None, freq=None):
>     subexpr = ".*"
>     if expname:
>         subexpr = expname
>     if varname == None:
>         expr = re.compile(".*.nc$")
>     elif varname != None and freq == 'fx':
>         expr = re.compile( "areacella_.*.nc$")
>

**Comment by tommibergman** [comment]
That is really weird, since for me the code finds e.g. 
 areacella_AERfx_EC-Earth3-AerChem_aspi_r1i1p1f1_gn.nc without problems.

**Comment by aearamos** [comment]
It is weird. 
And now I think if I use this generic way to find every netcdf file, then I won't be able to cmorise variables that have the same name but are from different subexp, such as emilnox_AERmon_EC-Earth3-AerChem_a2ax_r1i1p1f1_gn_199001-199012.nc and emilnox_crescendo_AERmon_EC-Earth3-AerChem_a2ax_r1i1p1f1_gn_199001-199012.nc. 

I'll keep digging to see if I can make it work.

**Comment by tommibergman** [comment]
Actually, for the CMIP6 experiments the crescendo output can be switched off. It used only in CRESCENDO project. I will email Philippe to set it off by default.

**Comment by aearamos** [comment]
Thanks! That would help cmorising the two variables that have crescendo tag.

**Comment by etiennesky** [comment]
> Actually, for the CMIP6 experiments the crescendo output can be switched off. It used only in CRESCENDO project. I will email Philippe to set it off by default.

Hi @tommibergman how can we switch it off? Is it in the namelists or tm5 code? If the former, we could do it in our bugfix branch.

**Comment by etiennesky** [comment]
> About the ps, it is a bit of a tricky variable. We need that for 3D variables also in TM5, because it has to be either saved in all the model level variables or used for interpolation of the pressure level variables. I think I already have implemented some exceptions for it on time resolutions where it is not normally included in the data request, so that could be extended.

Any specifics or news on this? It is especially relevant for the tm5:co2 config, since we only get one variable from tm5 (co2), it would be better to get ps cmorized from ifs output if possible.

**Comment by plesager** [comment]
> > Actually, for the CMIP6 experiments the crescendo output can be switched off. It used only in CRESCENDO project. I will email Philippe to set it off by default.
> 
> Hi @tommibergman how can we switch it off? Is it in the namelists or tm5 code? If the former, we could do it in our bugfix branch.

This is done in the trunk of EC-Earth repo now (it is just a rc key in TM5 rc file).

**Comment by tommibergman** [comment]
> > About the ps, it is a bit of a tricky variable. We need that for 3D variables also in TM5, because it has to be either saved in all the model level variables or used for interpolation of the pressure level variables. I think I already have implemented some exceptions for it on time resolutions where it is not normally included in the data request, so that could be extended.
> 
> Any specifics or news on this? It is especially relevant for the tm5:co2 config, since we only get one variable from tm5 (co2), it would be better to get ps cmorized from ifs output if possible.

The new C4MIP output in TM5 will output `ps` regardless of the settings. So it will need a exception for the IFS output control files. I believe @treerink is working on this?

**Comment by etiennesky** [comment]
Would it be possible to have ps from TM5 in the Aermon table, and ps from ifs in the Amon table? This is requested for the aerchemip runs, but not the c4mip ones, so this might have to be added for the c4mip ones.

**Comment by tommibergman** [comment]
First, I do not see why not. Depends on the automatic generation of ppt-files, so maybe @treerink has an idea? Where it needs to be added for c4mip?

**Comment by treerink** [comment]
In general, if a variable is requested that is available in two of our model components (for instance `ps` in IFS & and in TM5), then `genecec` will take care that both model components will output this variable. When cmorising this variable we have to choose, we can only publish the variable once, so therefore the `prefs.py` sets the preference from which components the variable is taken. If for instance `ps` is taken from IFS instead of TM5, then the task to cmorise TM5 is removed. If the task is absent, then probably it won't be possible to use this variable for the cmorisation of other variables, and I understood from Philippe that this applies for 3D variables in TM5 which need `ps.` So if this is indeed the problem then this needs to be fixed somehow.

Anyway this issue appears very chaotic to me. I have not been working on this. Philippe informed me yesterday a bit about some ps discussion of some telcon. I would suggest to close this issue, and to start new specific issues with a clear problem description and clear questions and when possible addressing the person you think is in charge. The best is to have short lasting issues addressing one problem at the time. So please go ahead.
