### ISSUE TITLE
Problems with nemo variables not passing PrePARE after upgrade to cmor 3.5

### ISSUE THREAD

**Issue by jmrgonza** [EC-Earth/ece2cmor3#523]
Hi,
I have updated my cmor tables to the latest version and also the cmor library to the 3.5 version, and it seems that the issues with ifs variables reported in #462 are solved, but there are some problems with nemo variables instead:
```
=====================================================================================
Your file contains "standard_name":"surface_downward_x_stress" and
CMIP6 tables requires "standard_name":"downward_x_stress_at_sea_water_surface".
=====================================================================================

âââ> :: CV FAIL    :: /scratch/ms/es/sp0/cmor/SSP2/nemo/168/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp245/r3i1p1f1/Omon/tauuo/gn/v20190725/tauuo_Omon_EC-Earth3_ssp245_r3i1p1f1_gn_201701-201712.nc

=====================================================================================
Your file contains "cell_methods":"area: mean where sea time: mean" and
CMIP6 tables requires "cell_methods":"area: sum where sea time: mean".
=====================================================================================

âââ> :: CV FAIL    :: /scratch/ms/es/sp0/cmor/SSP2/nemo/168/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp245/r3i1p1f1/Omon/masscello/gn/v20190725/masscello_Omon_EC-Earth3_ssp245_r3i1p1f1_gn_201701-201712.nc

=====================================================================================
Your file contains "standard_name":"surface_downward_y_stress" and
CMIP6 tables requires "standard_name":"downward_y_stress_at_sea_water_surface".
=====================================================================================

âââ> :: CV FAIL    :: /scratch/ms/es/sp0/cmor/SSP2/nemo/168/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp245/r3i1p1f1/Omon/tauvo/gn/v20190725/tauvo_Omon_EC-Earth3_ssp245_r3i1p1f1_gn_201701-201712.nc

=====================================================================================
Your file contains "cell_methods":"area: mean where sea time: mean" and
CMIP6 tables requires "cell_methods":"area: sum where sea time: mean".
=====================================================================================

âââ> :: CV FAIL    :: /scratch/ms/es/sp0/cmor/SSP2/nemo/168/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp245/r3i1p1f1/Omon/wmo/gn/v20190725/wmo_Omon_EC-Earth3_ssp245_r3i1p1f1_gn_201701-201712.nc

Number of files scanned: 89
Number of file with error(s): 4
```

**Comment by oloapinivad** [comment]
Uhm looking at the history in their github they have changed once again the definition of some variables, which may explain the PrePARe failure. Did you cmorized with 3.5 or with 3.4? 

https://github.com/PCMDI/cmip6-cmor-tables/commit/02c87565bcac3c3fc916cd1e0f5242a68b588158

**Comment by jmrgonza** [comment]
I cmorized with 3.4, using the tables from the ece2cmor3 submodule, which means that tables were not at the latest version either.

**Comment by oloapinivad** [comment]
So I guess that the PrePARE issue comes from this... your data is cmorized with 3.4 but PrePARE expects tables compatible with 3.5...

**Comment by jmrgonza** [comment]
So you think that updating the cmor version and the tables in my ece2cmor3 conda environment would solve the issue? That would "only" require to cmorize the nemo data again.

**Comment by oloapinivad** [comment]
It depends on which constraints you have on the version of PrePARE (i.e. are you doing the check on your own or are you depending on the version of an ESGF node?) 

I am using a github version of the cmor environment which had fixed the #462 and it is based on 3.4. So that all the variables are passing the PrePARE checks. 

In other words, I would not to re-cmorize the ocean just to address a bug in PrePARE, but rather pick the version of PrePARE that fits your data. Of course these are my 2 cents, others may have different views...

**Comment by jmrgonza** [comment]
I tried using cmor 3.5 but not updating the tables (i.e. using the version specified in the submodule of ece2cmor3/1.2.0). With that settings I can also validate all the variables (ifs and nemo) with PrePARE. That means that the nemo validation problems come from the updated tables, while the new cmor release solved the zg and wap issues. My problem is that I am not in control of the cmor installation in the ESGF node. In any case, I would suggest considering to update the cmor dependency to 3.5 version in the environment.yaml file, to get rid of the zg and wap problems with PrePARE, but I haven't tried to cmorize with that setup.

**Comment by goord** [comment]
Hi @jmrgonza , updating the cmor library is usually not such a big deal, apart from the dependency issues in the environment that may arise, I can have look at it this week.

**Comment by treerink** [comment]
@jmrgonza As the master is updated to cmor 3.5.0 maybe it is worth another try?

**Comment by jmrgonza** [comment]
Hi @treerink, it took me some time to test the new version, due to some quota issues, but I was finally able to run the cmorization of a 1 year leg (both ifs and nemo) of one of my scenario runs, and all the variables passed the PrePARE tests.
