### ISSUE TITLE
Incorrect cmorisation of Ofx basins 

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#529]
The quality control of `Ofx basins` shows that its cmorisation is incorrect. Instead of reopen #365, I open a new issue.

So what is the matter with  `Ofx basins`?

It seems really completely wrong, at least in the latest cmorizations:
This is an `int` field that follows the Flags part of [CF](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#flags) and as such has the following attributes (excerpt):

```
basin:flag_values = 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ;
basin:flag_meanings = "global_land southern_ocean atlantic_ocean
pacific_ocean arctic_ocean indian_ocean mediterranean_sea black_sea
hudson_bay baltic_sea red_sea" ;
basin:missing_value = -999 ;
```
ie land points should here have a value of 0, southern ocean points of 1, the atlantic should be marked by 2 etc.

Instead, all the land points have a value of -2147483648 (which isn't even the fill value), a few ocean points along the border of the domain have zero (ie land), and the vast majority of ocean points have 1, ie southern ocean.

**Comment by treerink** [comment]
From [here](http://clipc-services.ceda.ac.uk/dreq/u/baa3f718-e5dd-11e5-8482-ac72891c3257.html): 

Report on the same grid as the temperature field. flag_values=0,1,2,3,4,5,6,7,8,9,10 corresponding to flag_meanings=global_land, southern_ocean, atlantic_ocean, pacific_ocean, arctic_ocean, indian_ocean, mediterranean_sea, black_sea, hudson_bay, baltic_sea, red_sea.

**Comment by treerink** [comment]
Currently the produced Ofx basin is taken from `h003_1y_*_opa_grid_T_2D.nc` and not from `ofx-data/subbasins.nc`.

**Comment by goord** [comment]
/home/gvdoord/Data/EC-Earth/issue530/cmor/basins.svg

**Comment by goord** [comment]
basins are working in the nemo-basins branch, but notice the missing values...

**Comment by treerink** [comment]
Thanks, I can reproduce this, indeed including the missing values (also at the domain border of the domains which is not so visible in the screenshot above). 

How do these missing values (-999) enter the `basin` field? I assume the composed `basin` field is based on the fields in the `ofx-data/subbains.nc` file, where for instance in the indian-pacific ocean mask `indpacmsk` the 3-gridpoint wide invalid band downwards of Australia  is visible though as zero values. But in none of those fields invalid values are visible at the domain boundaries?

**Comment by treerink** [comment]
The `nemo-basins` branch has been merged in the master. The `basin` field should be better now, though it contains various areas and domain boundaries with invalid values which are in fact already present in the `subbasins.nc` data.

Further ESMval checking is recommended as well that someone judges whether the invalid value areas are an issue.

**Comment by treerink** [comment]
Closing this issue as it seems ok from the ece2cmor3 perspective. Anyway, please reopen if necessary.
