### ISSUE TITLE
issue with non-integer land sea mask for tos Amon gr?

### ISSUE THREAD

**Issue by pabretonniere** [EC-Earth/ece2cmor3#531]
Hi,

When looking at a tos_Amon_gr file, we noticed that there seem to be some discontinuities in the values along the coast, as shown in the screenshot below.

After investigation, it seems to be coming from the land_sea_mask of the IFS initial conditions that have some non integer values along the coast (as it might be expected) but that lead to this strange behaviour. Maybe an option would be to use a threshold of 0.9 (>0.9 =1 , <0,9 = 0) before applying the mask to avoid this issue.

Has anybody else already noticed this issue?

Thanks.

![imagen](https://user-images.githubusercontent.com/4979994/66057134-7a0b4900-e538-11e9-8b65-f32b29a6c998.png)

@aearamos

**Comment by etiennesky** [comment]
Another problem is that along the coastline there is an interpolation form SST values (from 20 to 30 say) to the value over land (0), which leads to these strange values. maybe the land-sea mask should bet set to nodata before interpolation (based on the threshold suggested by @pabretonniere ).

**Comment by goord** [comment]
Hi, is there an atmosphere tos in the Amon table? Because I thought for CMIP6 all tos variables were moved to the NEMO-part of the drq. 

I think that you're right @etiennesky this is probably a regridding issue: the mask should be set before interpolation.

**Comment by pabretonniere** [comment]
Hi,

You're right, tos is not in the official Amon table, it just comes from an internal test. We will apply some masks locally.
Closing the issue.
