### ISSUE TITLE
add possibility to "cmorize" LPJG variables not in the data request

### ISSUE THREAD

**Issue by etiennesky** [EC-Earth/ece2cmor3#532]
Hi @goord @treerink @nierad I would like to be able to cmorize (in reality, at least produce a valid netcdf file) any lpjg variable not in the data requests, stored  in the standard LPJG .out format .

How might I be able to do that with the ece2cmor3 package?

Thanks!

**Comment by treerink** [comment]
In that case you need to define them in the cmor tables (do they belong to a certain existing table and are they defined against existing dimension definitions?). And you need to create your own `varlist-lpjg-external.json` for instance here:
```
ece2cmor3/ece2cmor3/resources/test-data-request
```

**Comment by etiennesky** [comment]
Hi, thanks for the info.

I would like to be able to create a netcdf on the fly, without having to define the variable in any table. 

I guess everything has to conform to the cmor table paradigm for now.  It would be great to have this flexibility some time in the future. 

Maybe I can adapt the lpjg2cmor.py code for my use case.

**Comment by nierad** [comment]
Hi Etienne,


if you only want to have a netCDF-file use the lpjg2cmor part where an intermediate, remapped nc-file is written (about line 211 "ncfile = create_lpjg_netcdf..."). If you want that just comment out line 268 (os.remove(ncfile) and rename it someway.


Cheers, Lars

________________________________

**Comment by nierad** [comment]
Sorry, you will have to fake the dimensions somehow, too.


Lars

________________________________

**Comment by treerink** [comment]
No open question seems to be left here, so closing.
