### ISSUE TITLE
Frequency of operation for some 3d fields

### ISSUE THREAD

**Issue by aearamos** [EC-Earth/ece2cmor3#534]
Hi,
 
Here at BSC we were trying to run two identical experiments, and we noticed differences in some fields, such as thetao 3D. Then, we found that we were using two different versions of the data request and the cmip6 ctrl output files. 

In the latest version, some fields in file_def_nemo-*.xml have their frequency operation set to 1 month (freq_op=1mo). e.g.
`<field enabled="True" field_ref="toce_pot" freq_op="1mo" grid_ref="grid_T_3D" id="id_1m_thetao" name="thetao" operation="average" unit="degC">    @toce_pot_e3t / @e3t                                                </field>`

As per CMIP6 protocol (at least for ocean fields) there is no sub-sampling in time for averaging.

We believe all averages should be carried out using every time step (freq_op=1ts), like it was before.

See Appendix A1 in Griffies et al. 2016 (doi:10.5194/gmd-9-3231-2016)

Can anyone check why was it changed to 1mo?

**Comment by treerink** [comment]
I find for instance an example of what you bring up in the following file:
```
control-output-files/cmip6-output-control-files/CMIP/EC-EARTH-AOGCM/cmip6-experiment-CMIP-historical/file_def_nemo-opa.xml
```

To find the responsible block of code, search in `scripts/create-basic-ec-earth-cmip6-nemo-namelist.py` on:
```
# The previous incorrect method
```
currently on line 660. You find the previous way in a `if False:` and below in the `else` what happens now: If a variable has an time averaging @-operator in its non-empty expression then the `freq_op` is set equal to  `output_freq`.

This has been changed after contacting Yann Meurdesoif (from XIOS) by a telcon, see https://github.com/EC-Earth/ece2cmor3/issues/299#issuecomment-457644692. So does this match your findings @aearamos that this changed somewhere shortly after 25 of January 2019?

See also #251, #327, but #299 is most relevant here.
