### ISSUE TITLE
Corrupt fx orog field

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#541]
While testing the "test all ifs"  case, it appears that the `fx orog` gives a corrupt field. Looks like wrong dimension matching.

**Comment by goord** [comment]
Fixed in rev. 8113a695b7fb81fbd0ac44bacbaec46cd80375e6

**Comment by treerink** [comment]
Debug prints introduced in 3d75c413f8f3c761543aaefbbe45916ee74bb660 are removed #541.
