### ISSUE TITLE
Can't output "ps" variable for table Amon

### ISSUE THREAD

**Issue by aearamos** [EC-Earth/ece2cmor3#549]
Hi,

I'm having some confusion when trying to cmorise variable "ps". I ran one month using the ppt/xml/varlist.json from `/sources/runtime/classic/ctrl/cmip6-output-control-files/CMIP/EC-EARTH-AOGCM/cmip6-experiment-CMIP-piControl`. 

In my output I have code 134.128, the code for "ps", and in my `cmip6-data-request-varlist-CMIP-piControl-EC-EARTH-AOGCM.json` I have "ps" for tables Emon, CFday, Amon, 6hrLev, and 3hr, all for IFS. 

I now checked my cmorised files and I have "ps" for tables 3hr, Emon, CFday, but not for Amon (we're not using model level, so no "ps" for 6hrLev).

Is there a reason why "ps" appears in table Emon and not Amon in my output? According to the tables they are the same variable, but is there a preference for the same variable within differente tables?  Or is it because of the position in the varlist.json file?

I had problems before where ece2cmor would find and compute "ps" for Amon but wouldn't output it, e.g.:

`2019-11-19 22:21:44 INFO:ece2cmor3.postproc: Post-processing target ps in table Amon from file /gpfs/scratch/bsc32/bsc32436/a2bb/19900101/fc00/runtime/tmp/cmor/tmp-atm-fc00-199001/a2bb-ifs-1990/134.128.1.3 with cdo command -setgridtype,regular -monmean -selcode,134`

Thanks

**Comment by goord** [comment]
Hi Arthur, the variable should be produced for both tables if it is listed in your varlist.json under both Amon and Emon, I will run a small test to check this.

**Comment by treerink** [comment]
Hi Arthur,

I just tested the latest `test-all` test: And I get `Amon ps` and `Emon ps` both in the same cmorisation job.

I run EC-Earth3 with the latest `r7144-control-output-files` branch with `ctrl/cmip6-output-control-files/test-all-ece-mip-variables/` and  cmorised those results with the latest ece2cmor3 master.

**Comment by aearamos** [comment]
Ok, Thomas.

I'll test it from here and will post the results ASAP. 

Thanks

**Comment by aearamos** [comment]
Hi, I still can't output from table Amon. 

I'm using the control and jason files from  `sources/runtime/classic/ctrl/cmip6-output-control-files/CMIP/EC-EARTH-AOGCM/cmip6-experiment-CMIP-piControl/`. I have ps in 4 tables, 3hr, CFday, Emon, and Amon, but after I run the cmorisation I only have it in 3 tables:

./3hr/ps/gr/v20191025/ps_3hr_EC-Earth3_piControl_r1i1p1f1_gr_199001010000-199001312100.nc
./CFday/ps/gr/v20191025/ps_CFday_EC-Earth3_piControl_r1i1p1f1_gr_19900101-19900131.nc
./Emon/ps/gr/v20191025/ps_Emon_EC-Earth3_piControl_r1i1p1f1_gr_199001-199001.nc

I'm attaching my log file here.

[output_cmoratm_piControl.txt](https://github.com/EC-Earth/ece2cmor3/files/3887086/output_cmoratm_piControl.txt)

**Comment by goord** [comment]
Hi Arthur, can you confirm that the file ps_Amon.nc appears in you temp directory? You can skip the temp dir cleanup by defining the environment variable
```
ECE2CMOR3_IFS_CLEANUP = FALSE
```
in the same shell as where you run ece2cmor.

**Comment by aearamos** [comment]
Hi @goord 

As a matter of fact, I do. I have ps for Amon, Emon, CFday, nad 6hrLev in my tmp folder. Is there some sort of priority in the .json file that could cause that? How can I post process this temp ps_Amon.nc file by hand? 

Thanks!

**Comment by aearamos** [comment]
So, I have an update on this issue.

By using the control and jason files from` sources/runtime/classic/ctrl/cmip6-output-control-files/CMIP/EC-EARTH-AOGCM/cmip6-experiment-CMIP-piControl/` I tried adding/removing  different variables from the varlist to see if they somehow influenced ps_Amon. 

After running cmorisation many times, I noticed that the guilty ones are the variables with "alevel", such as `cl`, `clw`, and `cli`. I believe these variables use ps somehow to be calculated, but since I'm not outputing "alevel" there must be a conflict between the variables not being computed and ps not being postprocessed. 

Does that make sense at all? 

Thanks!

**Comment by goord** [comment]
Hi @aearamos this actually does make sense... ece2cmor3 uses the ps in Amon to parametrize the hybrid levels of the model level fields in Amon. What may be going on here is that the 3D tasks are failing and because of that, ece2cmor3 is (wrongfully) canceling the ps task as well...

Can you run the same job with the --skip-alevel-vars flag that we added to the script?

**Comment by aearamos** [comment]
Hi @goord,
By using the --skip_alevel_vars I can output ps for Amon. I wouldn't call this is a bug, it's just that we're not using alevel data. 

Closing the issue.

**Comment by treerink** [comment]
Indeed I did my test with `--skip_alevel_vars`. This is much faster as well. I turned it on in the example submit scripts, see `ece2cmor3/ece2cmor3/scripts/submit-script-examples`.

**Comment by aearamos** [comment]
Hi @treerink 
I was just wondering, are the "alevel" variables working? Because In your tests, ps for Amon is working, but you're not using the --skip_alevel_vars flag, right? So are you outputing alevel variables or are you usgin the flag too? 

Thanks!

**Comment by treerink** [comment]
Hi @aearamos, no I did use the `--skip_alevel_vars` flag, so it is matching with your findings (and thus not solving your problem in case you do not use this flag).

**Comment by aearamos** [comment]
All right then, I'll use this flag now. We can try to solve this in another issue I guess. 

Closing again
