### ISSUE TITLE
Atmospheric grid longitude does not start at 0

### ISSUE THREAD

**Issue by goord** [EC-Earth/ece2cmor3#553]
Since revision d709240349e5e565d8052934e9c1ec57a90251d1, it seems that the longitude of the atmospheric grid has been shifted by half a grid cell size in the eastward direction. This is not in correspondence with the grid in the grib files.

This seems like a bug that affects all ece2cmor3 atmosphere output, including primavera, and uploaded and published data on the ESGF nodes.

**Comment by goord** [comment]
We can create a python script that fixes the atmospheric grid, to be run on the ESGF nodes.

**Comment by goord** [comment]
Fix is in the ifs-grid-lons branch

**Comment by jonseddon** [comment]
For all of the data that's already been published it may be useful to add an entry to the CMIP6 errata system at https://errata.es-doc.org/ to make users aware of the problem.

**Comment by treerink** [comment]
I tested the `ifs-grid-lons` branch, and the fix causes changes as expected for the values of `lon` and `lon_bnds`.

Before the the fix we had:
```
 lon = 0.3515625, 1.0546875, 1.7578125, 2.4609375, 3.1640625, 3.8671875, 
    4.5703125, 5.2734375, 5.9765625, 6.6796875, 7.3828125, 8.0859375, 
    ...
    354.7265625, 355.4296875, 356.1328125, 356.8359375, 357.5390625, 
    358.2421875, 358.9453125, 359.6484375 ;
```
and
```
 lon_bnds =
  0, 0.703125,
  0.703125, 1.40625,
  ...
  358.59375, 359.296875,
  359.296875, 360 ;
```
Now, after the fix we have:
```
 lon = 0, 0.703125, 1.40625, 2.109375, 2.8125, 3.515625, 4.21875, 4.921875, 
    5.625, 6.328125, 7.03125, 7.734375, 8.4375, 9.140625, 9.84375, 10.546875, 
    ...
    352.265625, 352.96875, 353.671875, 354.375, 355.078125, 355.78125, 
    356.484375, 357.1875, 357.890625, 358.59375, 359.296875 ;
```
and
```
 lon_bnds =
  -0.3515625, 0.3515625,
  0.3515625, 1.0546875,
  ...
  358.2421875, 358.9453125,
  358.9453125, 359.6484375 ;
```
which looks fine and in agreement with the `grib_dump` of the IFS grib file. Note that the lon itself is expected to coincide with grid cell center. So in the previous erroneous case everything was shifted half a grid cell  `0.3515625` degrees eastward.

**Comment by treerink** [comment]
The fix for the longitude easward shift BUG is fixed in the master now

**Comment by treerink** [comment]
I am leaving this issue open until we have a script which can modify the wrong data. The idea is that the cmorised data will be fixed by using some `cdo` or `nco` commands which will replace the `lon` and `lon_bnds` values.

**Comment by goord** [comment]
Thomas should we in the meantime add an erratum on esdoc?

**Comment by treerink** [comment]
@goord are you applying the BUG fix to the PRIMAVERA branches?

**Comment by goord** [comment]
Well... they are no longer supposed to be used anyway, so I would say no

**Comment by treerink** [comment]
I think we wait with the erratum until we had the CMIP6 WG meeting? As it concerns simulations by many institutes I think it is good to be sure everybody is informed before?

**Comment by treerink** [comment]
> Well... they are no longer supposed to be used anyway, so I would say no

Okay. So we only have to make sure the fix script applies as well to PRIMAVERA data.

**Comment by goord** [comment]
Yes the correction script should also work for 2D longitude variables, and it should have minimal dependencies so it works on any esgf nodes. I'm still in doubt whether to use nco, or cdo, or write a simple python script that only has a netCDF4 dependency

**Comment by klauswyser** [comment]
A script that changes variables ``lon`` and ``lon_bnds`` on the ESGF nodes (if possible) is one thing to do, but unfortunately the consequences of the bug are a little bit larger. SInce it's a serious bug we have to unpublish the data from the ESGF and re-publish, but that means the version has to change as well. So it's not just changing the variables in all the files, but also the name of the version (directory vYYYYMMDD) has to be updated. I don't know if it's a good idea to do everything - changing variables and directory name - in one and the same script, or if it's better to do that in two steps.

**Comment by goord** [comment]
@klauswyser you're right, plus the tracking_id and creation date in the files have to be updated too. But I would guess the ESGF system has some infrastructure in place to unpublish/republish (automatically generating a new version number and tracking_id)?

**Comment by klauswyser** [comment]
> But I would guess the ESGF system has some infrastructure in place to unpublish/republish (automatically generating a new version number and tracking_id)?

I doubt this is the case, the version and tracking_id are set when the file is generated with help of the CMOR library. The publishing process doesn't change any of these metadata, only reads them.

**Comment by oloapinivad** [comment]
Klaus is right. I am start wondering if the safest approach would be a
brand new cmorization. We could fix also other minor metadata issues that
are emerging.



Il giorno ven 29 nov 2019 alle ore 10:34 klauswyser <
notifications@github.com> ha scritto:

**Comment by goord** [comment]
It is my understanding that not everybody has kept the raw model output. Moreover the cost of transferring the data to the ESGF node can be very high no?

**Comment by etiennesky** [comment]
re-cmorizing is not an option for a few groups (BSC for sure, and Jenny told us that as well). Both options should be possible - if someone chooses to re-cmorize that is fine, but we should be able to correct the files on-site if possible.

**Comment by treerink** [comment]
I think it can be all in one script, the `lon` & `lon_bnds` fix, the new version, the new `track_id` and the general looping over all the data. An script option for PRIMAVERA.

I want to make use of one of Uwe scripts for the `track_id`

**Comment by goord** [comment]
Uwe has a script to generate a valid ```tracking_id```?

**Comment by treerink** [comment]
See the line:
```
ds.tracking_id = 'hdl:21.14100/' + str(uuid.uuid4())
```
in `ece2cmor3/ece2cmor3/scripts/data-qa/recipes/sftlf.py`

**Comment by treerink** [comment]
I think the script should also be robust against files produced after the BUG fix, i.e. it won't apply a shift when the lons are correct.

**Comment by goord** [comment]
@oloapinivad you mentioned other minor metadata issues, can you elaborate?

**Comment by oloapinivad** [comment]
@goord this is not something related to ece2cmor3 directly, but more in general to mistakes that have been done during the set up of the metadata by the different groups. Wrong branch/parent times, wrong parent variant labels, etc. There are a few examples that are now reported on the dev portal.

**Comment by treerink** [comment]
Yes good point to discuss this at the coming CMIP6 WG as well. And maybe good to make a table with the correct branch times on the portal: what it should be?

**Comment by oloapinivad** [comment]
There is a brief paragraph we prepared with @klauswyser and Uwe which discusses the branch times. You can find it at the end of [this document ](https://docs.google.com/document/d/16NTTxZM9l8B_tqLrG_zTJDGZYJr21dS7L3B-tGU2Wik/edit). 

Unfortunately it didn't prevent me to make some mistakes, so it may be a good idea to expand it ;-)

**Comment by jonseddon** [comment]
Unfortunately, I already have some experience with fixing errors in published data (for MPI rather than EC-Earth). You should first flag the affected data in the errata system (https://errata.es-doc.org/), then you can ask the ESGF node administrator to withdraw the data. You then need to fix the data and update the version sting in the directory path and update the tracking id in each file. You can then republish. At CEDA's ESGF node, withdrawing the data deletes the local copy of the data. You should check with your node administrator how their withdrawal process works. 

I generate a new tracking id with the Python code `new_value = f'hdl:21.14100/{uuid.uuid4()}'` and then used ncatted to write the new value into the file.

I had to write a script to fix the latitude bounds in the MPI data. I created a netCDF file with the corrected founds and then added them to the data file with `ncks -A -v lat_bnds {corrected_bnds_file} {original_nc}`. Does EC-Earth use Arakawa grids and so do you need to consider that u and v components are on different grids to other variables?

I'd be really grateful if the script that you develop to fix the data has an option to just fix the longitude and not to update the version or tracking id. The PRIMAVERA publication system can already do this and it also updates the metadata in the DMT so that we can keep track of each file. As the PRIMAVERA data's not been published yet then we may not need to update these anyway.

**Comment by treerink** [comment]
Ok an option to disable a new version number and track_id makes sense.

Yes I was also thinking of just making a netcdf file with the correct lon and lon_bnds and just replacing them with nco. We need than different files for PRIMAVERA data, but this method is robust when the script is applied on a mix of pre & post BUG fix generated data.

**Comment by slothm** [comment]
When do you think this will be fixed in ece2cmor3? At DMI, we would like to do re-cmorization for some of the experiments, which have other issues as well.

**Comment by treerink** [comment]
@slothm for new cmorisation exercises ithas already been fixed yesterday in the master branch, see #555. So you can go ahead.

**Comment by treerink** [comment]
@slothm Note that we are working hard to release ece2cmor3 v1.3 within a few days from now #550.

**Comment by goord** [comment]
Script ready for testing,

https://github.com/EC-Earth/cmor-fixer

This uses a pip requirements file, no need for anaconda, it will be easier to deploy on an esgf node if we keep it simple

**Comment by treerink** [comment]
Testing the script on my laptop (ubuntu) goes fine. When applying the script on a file which has the correct `lon`, `lon_bnds` values, no shift is applied, which is convenient and save. In this latter case the `tracking_id` is changed, which I think not a big issue or actually a choice, though we could choose not to modify the `tracking_id` in that case.

I diffed the ncdump results, which show the differences after the fix. I also diffed the ncdump results after the fix with one produced with the latest fixed master branch: The track_id attribute is at different position (at the end), but this seems unimportant to me.

However on the HPC, I get netcdf - hdf5 errors. Also when using the minconda environment and installing with pip:
```
pip install netCDF4==1.5.3
pip install numpy
```

Maybe we need to create an environment within miniconda?

**Comment by treerink** [comment]
The cmor-fixer has been updated with an miniconda3 (python3 based) environment. This enables to install the cmor-fixer by installing miniconda3 and creating the cmorfixer conda environment, see [EC-Earth/cmor-fixer](https://github.com/EC-Earth/cmor-fixer/blob/master/README.md). 

The full install summary reads as:
```
 mkdir -p Downloads; cd Downloads/
 wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
 bash Miniconda3-latest-Linux-x86_64.sh -b -u -p /$HOME/miniconda3
 minconda3path=${HOME}/miniconda3/
 alias activateminiconda3='source ${minconda3path}/etc/profile.d/conda.sh; export PATH="${minconda3path}/bin:$PATH"'
 activateminiconda3
 conda update -y -n base -c defaults conda
 
 cd ${HOME}/cmorize
 git clone https://github.com/EC-Earth/cmor-fixer.git
 cd ${HOME}/cmorize/cmor-fixer
 conda env create -f environment.yml

 conda activate cmorfixer
 ./fix_lons.py -h
 ./fix_lons.py --verbose CMIP6/ --dry    # A dry-run showing what will hapen without applying
 ./fix_lons.py --verbose CMIP6/          # Applying the script on the data
 conda deactivate
```

**Comment by treerink** [comment]
For the cmor-fixer grid I think one issue is to be discussed [Apply or not apply a new track_id when lon data are correct?](https://github.com/EC-Earth/cmor-fixer/issues/2). The discussion can be continued overthere.

I close this issue, as the fix script is tested and working, and ece2cmor3 itself is fixed for this bug.
