### ISSUE TITLE
Crash of ece2cmor3 due to try of deleting a temporary file that has been deleted already

### ISSUE THREAD

**Issue by krumit** [EC-Earth/ece2cmor3#562]
I am redoing the CMORisation of our DCPP-runs (data not published on ESGF yet) here at SMHI to get rid of the longitude-bug that has been discovered recently.
Therefore I checked out the most recent ece2cmor3-version from master:
commit 5bfcda805d7ab2f17d52d1e935699708482e8470
Author: treerink
Date:   Tue Dec 3 21:27:28 2019 +0100

However, ece2cmor3 crashes at some point because it tries to delete a temporary file that has been deleted a few seconds before already. The detailed error message is:

```
Traceback` (most recent call last):

  File "/home/sm_timkr/miniconda2/envs/ece2cmor3/bin/ece2cmor", line 11, in <module>
    load_entry_point('ece2cmor3==1.2.1', 'console_scripts', 'ece2cmor')()

  File "/home/sm_timkr/miniconda2/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-1.2.1-py2.7.egg/ece2cmor3/ece2cmor.py", line 141, in main
    cdothreads=args.ncdo)

  File "/home/sm_timkr/miniconda2/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-1.2.1-py2.7.egg/ece2cmor3/ece2cmorlib.py", line 186, in perform_ifs_tasks
    ifs2cmor.execute(ifs_tasks, nthreads=taskthreads)

  File "/home/sm_timkr/miniconda2/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-1.2.1-py2.7.egg/ece2cmor3/ifs2cmor.py", line 213, in execute
    clean_tmp_data(tasks_todo)

  File "/home/sm_timkr/miniconda2/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-1.2.1-py2.7.egg/ece2cmor3/ifs2cmor.py", line 316, in clean_tmp_data
    os.remove(dp)

OSError: [Errno 2] No such file or directory: '/scratch/local/cm-18-6/001/d180-ifs-2018/202.128.105.3'
```

My ece2cmor-experience is still limited, so I am not sure whether this is a general bug or if something about my specific ece2cmor-configuration is wrong. However, it worked exactly the way it is now configured before I checked out the new version yesterday. I am using a customized `varlist` to include some extra variables but I get the very same error when making use of the standard `varlist` for EC-Earth and DCPP that is `output-control-files/DCPP/cmip6-experiment-DCPP-dcppA-hindcast/cmip6-data-request-varlist-DCPP-dcppA-hindcast-EC-EARTH-AOGCM.json`

Any help is appreciated, best,

Tim

**Comment by treerink** [comment]
Hi Tim,

You specify with --tmpdir a temporal directory. What if you move this one, and create again an empty new one? Can you try whether you can go ahead with this?

Regards Thomas

**Comment by krumit** [comment]
Hej Thomas!
Thank you for your quick response.
I have to admit that I am not entirely sure that I understand where/when you want me to move and recreate the tmpdir.
However, I have an update including a shortterm workaround working for me:
As written above, this error is triggered by ece2cmor3 trying to delete a temporary file which has been deleted already. This seems to be **related to variables that are processed via more than one CMOR table** (e.g. for `Amon` but also for `day`). I could run a successful CMORisation once I removed all "repetitions" of the same variable.
Of course this is not a proper solution because some data requests contain requirements for one variable via different CMOR-tables. Even more so that it is not only about variables that are identical in the sense of their CF-conform definition but also about derivatives. Two examples for the latter are that ece2cmor also crashed as long as I tried to produce `sfcWind` and `sfcWindmax` or `zg` and `zg500`.
So this issue seems quite serious to me.

However, there is a simple short-term solution working for me now, which is to disable the cleaning of temporary IFS-files by setting the environment variable
`ECE2CMOR3_IFS_CLEANUP = FALSE`
I can live with this solution for now as the tmpdir will be deleted anyway on our HPC as soon as the respective job is finished.

Interestingly the whole issue did not apply to my case for a repetition of a NEMO-variable (`siconc` was cmorized successfully in my case both for `SImon` and `SIday` without any workarounds necessary.

I leave the issue open for now, as it still seems to me that this is a more general bug that should affect others, too, and hence should be eliminated.

Best, Tim

**Comment by goord** [comment]
Hi Tim,
Thanks for reporting this issue, this is a definite bug in the cleanup of temp. files used by multiple cmor-variables. For NEMO, all variables (even ``siconc`` on daily and monthly frequency) are in separate files in the model output, so there we do not suffer from this. I will fix the issue today, in the meantime you can continue working by skipping the automatic cleanup.

**Comment by goord** [comment]
This should be fixes from rev. c7651e3048494d4992d3d525a9b95c23691c868e

**Comment by krumit** [comment]
Great thank you!
I will check this out on Monday and close the issue if successful.
Best,
Tim

**Comment by krumit** [comment]
Works as it should. Thank you very much. I am closing this issue.
