### ISSUE TITLE
Masking cdnc

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#563]
From Declan's note in the [ec-earth portal issue 736-2](https://dev.ec-earth.org/issues/736#note-2) we learn that an additional masking is needed for `cdnc`:
```
cdnc=126.101/126.105 where 126.105 /= 0 else CDNC=0
```
We propose to use the following expression for that in the `ifspar.json` file:
```
"expr": " (var126022 != 0) * var126020 / var126022"
```
This works under the assumption that cdo evaluates 0 * NaN as 0, the latter needs to be tested (we are not entirely sure about this).

**Comment by goord** [comment]
![cdnc](https://user-images.githubusercontent.com/5041758/70618788-fba3e500-1c13-11ea-8658-0d1558eb6dd8.png)

Cmorization of cndc is working after prepending the ec-earth grib table path

**Comment by treerink** [comment]
Great :)

**Comment by plesager** [comment]
Thanks. But shouldn't the units (in the figure) say cm3 instead of m3? @noije

**Comment by noije** [comment]
Yes, I was thinking exactly the same. The unit in IFS is cm-3 (times seconds which is later divided away), which should be converted to m-3 in the CMORized file. The other thing I'd like to check is if the division is done before or after temporal (in this case monthly) accumulation/averaging. CDNC values of 1000 cm-3 seem too high. @plesager
