### ISSUE TITLE
Longitude shift correction needed in TM5 cmorisation component.

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#565]
Also, like for IFS and LPJ-GUESS, the TM5 cmorisation component seems to be corrected for a shift in `lon` & `lon_bnds.` 

As TM5 data have not been cmorised and published yet, this needs not to be part of the [cmor-fixer](https://github.com/EC-Earth/cmor-fixer).

**Comment by treerink** [comment]
Of course it has to be made sure that the gird of TM5 has the same convention as IFS: grid center of first point coincides with lon = 0.

**Comment by goord** [comment]
Also the lat and lon variables are still 2D arrays in TM5, where they should preferably by 1D arrays for rectilinear grids, so this can be fixed in the same effort

**Comment by tommibergman** [comment]
Actually by default TM5 part uses 1D arrays. I just left the 2D solution there as well because I implemented that first. I can of course remove it if it is just adding confusion.

**Comment by tommibergman** [comment]
My understanding is that the longitude (and latitude) is the middle of the grid cell. And this is how I have implemented the output routines in TM5. But @plesager could confirm that the coordinates indeed represent the center of the cell. The bounds are calculated only in ece2cmor3 based on the Lon(lat) values.

**Comment by treerink** [comment]
TM5 is fine I suppose. It is what the tm5 component of `ece2cmor3` does. And there it seems the IFS related #553 BUG is copied to the TM5 component of `ece2cmor3` in [tm52cmor.py](https://github.com/EC-Earth/ece2cmor3/blob/master/ece2cmor3/tm52cmor.py). 

I assume the same fix as 2365359bb4495a9c8c9c5dcf8715a285e3adb35e is needed.

**Comment by tommibergman** [comment]
I don't understand, could you state the line where it is copied?

**Comment by treerink** [comment]
I mean the `tm52cmor.py` file at the start has probably been a copy of the `ifs2cmor.py` file.

**Comment by tommibergman** [comment]
Yes, that maybe. In the beginning I was looking at nemo and ifs codes. However, I can just remove all mentions of create_lonlat_grid, because currently the code does not use create_lonlat_grid by default. I think that's the way to go.

**Comment by tommibergman** [comment]
So there is a boolean variable using_grid, which is set in the beginning as false. This controls if we are using LonLat grid or Lon and Lat arrays. I left it just in case it is needed, but I think it will not be needed for anything, so we can just remove it. Seems to just cause confusion.

**Comment by treerink** [comment]
Ok you clean it? It is better that this BUG code disappears everywhere. Anyway, in the current state the `lon` and `lon_bnds` should be correct as well if I understand you correctly, so let's check that with Phillipes output.

**Comment by tommibergman** [comment]
Yes, I can do that.

**Comment by plesager** [comment]
I confirm that the current lon/lat values are correct. No need for a correction.

**Comment by etiennesky** [comment]
Hi all, just so I understand correctly, is this fix absolutely needed for correct cmorization of TM5 output produced by the EC-Earth-3.3.2 code? Or is it to make the code clean & avoid bugs if the wrong setting is used (using_grid_=True)?

**Comment by treerink** [comment]
It appeared to be not a BUG in practice, because the BUG code was not really used in practice and it has therefore been cleaned by Tommi now.
