### ISSUE TITLE
Unit & average procedure check for cdnc

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#570]
With solving #563 the cmorisation of `cdnc,` a pextra variable, became possible. 

However, the question is whether the units should be cm3 instead of m3 (or whether we are a factor 10^6 off)?

The other thing to be checked is if the division is done before or after temporal (in this case monthly) accumulation/averaging. CDNC values of 1000 cm-3 seem too high.

See also figure in https://github.com/EC-Earth/ece2cmor3/issues/563#issuecomment-564504619.

**Comment by noije** [comment]
No, this is not the question. The unit should be m-3 but a factor 10^6 is missing.

My question indeed is if the calculation of the monthly variable is done correctly.

**Comment by goord** [comment]
@noije Expressions in ece2cmor3 are evaluated at the highest time resolution, before time averaging. I would like to copy the cdo command here but I can't remotely access the bull anymore to fetch it from the log...

**Comment by treerink** [comment]
There you go:
```
INFO:ece2cmor3.postproc: Post-processing target sp in table AERmon from file /lustre2/projects/model_testing/reerink/temp-cmor-dir/acdb/ifs/001/acdb-ifs-1990/134.128.1.3 with cdo command -setgridtype,regular -monmean -selcode,134
INFO:ece2cmor3.ifs2cmor: Post-processing variable 23 for target variable cdnc...
INFO:ece2cmor3.postproc: Post-processing target cdnc in table AERmon from file /lustre2/projects/model_testing/reerink/temp-cmor-dir/acdb/ifs/001/acdb-ifs-1990/20.126.109_22.126.109.6 with cdo command -setgridtype,regular -monmean -expr,'var23=(var22!=0)*var20/var22' -selzaxis,hybrid -selcode,22,20
```

**Comment by goord** [comment]
By the way I think the easiest way to get the units right is by adopting the factor 1e-6 in the expression in ifspar.json

**Comment by noije** [comment]
Can't you just replace the order? i.e. replace var20 and var22 in this expression by their monthly sums (or means), and remove the -monmean operation.

Here is what the CNDC fields should look like (with additional averaging in the vertical):
https://www.atmos-chem-phys.net/19/6821/2019/#&gid=1&pid=1

**Comment by plesager** [comment]
> There you go:
> 
> ```
> INFO:ece2cmor3.postproc: Post-processing target sp in table AERmon from file /lustre2/projects/model_testing/reerink/temp-cmor-dir/acdb/ifs/001/acdb-ifs-1990/134.128.1.3 with cdo command -setgridtype,regular -monmean -selcode,134
> INFO:ece2cmor3.ifs2cmor: Post-processing variable 23 for target variable cdnc...
> INFO:ece2cmor3.postproc: Post-processing target cdnc in table AERmon from file /lustre2/projects/model_testing/reerink/temp-cmor-dir/acdb/ifs/001/acdb-ifs-1990/20.126.109_22.126.109.6 with cdo command -setgridtype,regular -monmean -expr,'var23=(var22!=0)*var20/var22' -selzaxis,hybrid -selcode,22,20
> ```

Perfect, the order of things goes from right to left, so the division is done before the time averaging, as we want.

**Comment by goord** [comment]
Well, I understand from @noije that we are supposed to calculate the fraction of monthly means... This is not supported yet by ece2cmor3 but I can add this feature without problems...

**Comment by noije** [comment]
@goord that's correct.

**Comment by treerink** [comment]
In 0eb6b3e6ff1221c1da18347a44b8ac16bbf12ea1 the conversion factor from cm-3 to m-3 is added for `cdnc`.

**Comment by treerink** [comment]
Noting that:
```
Grib code 126020 = cdnc * time_clouds_exits
Grib code 126022 =  time_clouds_exits
```
We want a weighted average, so we should first add all 6-hourly cdnc * time_clouds_exits values within a month, and divide that number by the sum of the 6-hourly time_clouds_exits values within that month.

If I understand correctly the cdo log should then read as:
```
 -setgridtype,regular -expr,'var23=(var22!=0)*var20/var22'  -monmean -selzaxis,hybrid -selcode,22,20
```
However this functionality of an interchange can not be specified yet in the ifspar.json, so @goord will create something for that in one or the other way.

**Comment by goord** [comment]
This can now be tested in the expr_post branch I created

**Comment by treerink** [comment]
Ok testing it

**Comment by treerink** [comment]
There seems to be something not correct yet:

In the log I still have exactly the same cdo message. But also when I try in the `ifspar.json`:
```
"expr_order": "0"
```
instead of
```
"expr_order": "1"
```
The field values of `cdnc` are identical. So it looks like option 1 is not really active yet?

**Comment by goord** [comment]
Should be working now in the branch, strangely enough I can't test the entire task creation method because it is still part of the identified_missing list (there is now also a pextra version of this...I'm lost in the complexity there)

**Comment by treerink** [comment]
You need to run in the `scripts` directory:
```
./switch-on-off-pextra-mode.sh activate-pextra-mode
```

**Comment by plesager** [comment]
Here is a screenshot of CDNC at model level 82 computed in two different ways. The first one follows Declan method (provided by email):

    cdo setmisstoc,0 -div -timsum var20.gb \
       -setctomiss,0 -setmissval,-9e33 -timsum var22.grb \
        output_file

where `var20.gb` and `var22.gb` are separate files with the corresponding variable. The second one is what @noije was asking and @goord made possible, i.e.: 

     -expr,'var23=(var22!=0)*var20/var22'  -monmean

The title says 1.3.1 because this did not make it into release 1.3.0. (The 'good data' refers to a clean up of the corrupted IFS test data.) The two plots are very similar. Differences between the two calculations are found where the averaged cloud time is 0. Declan sets CDNC to 0 there, while `ece2cmor3` leaves it at NaN (-9e+33). Do we have a preference here?

![cdnc-averaging](https://user-images.githubusercontent.com/11032052/70909824-93d40c80-200e-11ea-884a-8a9e874f0377.png)

**Comment by noije** [comment]
Can you add the colour bar?

**Comment by plesager** [comment]
![cdnc-averaging-2](https://user-images.githubusercontent.com/11032052/70911739-cbdd4e80-2012-11ea-8707-56f8e53b466e.png)

**Comment by noije** [comment]
Thanks, CDNC values are very high in polluted regions, but this seems consistent with the (column averaged) data I provided for the study mentioned above (https://www.atmos-chem-phys.net/19/6821/2019/#&gid=1&pid=1). 

I am not sure whether we should put NaN or zero when the monthly liquid cloud time is zero. In the monthly fields provided for that study, there are NaNs in this case but, as there haven't been any liquid clouds, the monthly CDNC might as well be set to zero at those points. The thing is that the annual mean cannot be calculated properly as long if we don't keep the monthly liquid cloud time together with the monthly CDNC.

**Comment by goord** [comment]
This puzzles me Philippe, because I would expect the the expression ```var23=(var22!=0)*var20/var22``` evaluates to zero if the monthly mean liquid cloud time is zero...

**Comment by plesager** [comment]
Looks like NaN pop up where I have 0/0, both variables with a monthly average of 0. Using @cdo 1.8.1@.

**Comment by plesager** [comment]
When both are zero,
`(var22!=0)*var20/var22`
becomes
`0*0/0`
Have you try the conditional `?`? Something like:
`var22 ? var20/var22 : 0.`

**Comment by plesager** [comment]
The ternary conditional (top) works better:
![ternary](https://user-images.githubusercontent.com/11032052/70928922-436ea600-2032-11ea-93c6-c6ec16b9bbbe.png)

**Comment by goord** [comment]
Implemented @plesager 's fix and merged branch into master

**Comment by plesager** [comment]
Could you add this small improvement to your commit c6a9614? It makes the code more robust by ignoring the small negative values in var126022. Ideally that should be fixed in IFS itself, but that will not happen soon and it is a good think to not compare floats with 0 anyway.
Replace (l. 474 of `ece2cmor3/resources/ifspar.json`):

      "expr": " var126022 ? var126020/var126022 : 0",

with

      "expr": " (var126022 > 1e-6)? var126020/var126022 : 0",

**Comment by goord** [comment]
Done in rev. cd24014cbba5d8c3bd213bb508124040ad543f52
