### ISSUE TITLE
Adding a maintainable method to add non-cmor variables for own use

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#575]
Of course now and then there is the need to handle variables which are totally absent in the CMIP6 data request. The question is whether it is possible to cmorise these. This is not possible because the variable needs to be part of the data request. However, with a lockal hack in your cmor tables you can mimic its cmorisation by producing some nice 'cmorised' variable with a self picked fake-cmor name.

Important is that when doing this we have a maintainable solution, so when the cmor tables from the nested repository are updated, it is easy to keep update.

Therefore a script will be added which adds such non-cmor variables  at the end of the concerned cmor table files.

**Comment by etiennesky** [comment]
I fully support this idea. Could we have a user-defined "table" which is independent from the data request?

**Comment by goord** [comment]
Hi Etienne, a table has usually a single frequency so if we want custom daily and monthly variables for instance, a single table file won't do the job

**Comment by etiennesky** [comment]
I see - I mis-read the issue. I thought it was about adding official variables 

@treerink wouldn't it be easier to use HEREDOC syntax instead of many echo statements, or better yet write .json files directly which are appended by the script? This would be much simpler, the script would be shorter and more flexible. Just some thoughts!

**Comment by goord** [comment]
We could even make a 'vendor fork' of the cmip6 cmor tables and add our variables in separate commits...

**Comment by treerink** [comment]
Please wait a bit with this, I am first testing the setup with Philippe. The important restriction for me is that the method is cmor table update proof while using the cmor table definitions to the largest extent.

When the first tryout works, I am happy to improve with your suggestions :)

**Comment by treerink** [comment]
Running `./add-non-cmor-variables.sh` will now allow cmorisation of these four non-cmor variables: `rsscsaf,` `rssaf,` `rlscsaf` & `rlsaf`.

We decided to add them permanently in the `ifspar.json` as it does not harm much and makes the administration complete: it prevents non allowed duplicate variable names and duplicate grib codes.

Only default, when the `add-non-cmor-variables.sh` modifications are absent, the script `check-for-obsolete-cmor-variables-in-json-file.py` will report those non-cmor variables (we might want to add an additional message about this in that script).

The `add-non-cmor-variables.sh` script will be further cleaned.

**Comment by treerink** [comment]
Done, closing.
