### ISSUE TITLE
Problem with time axis for AERmon [XY-A]

### ISSUE THREAD

**Issue by plesager** [EC-Earth/ece2cmor3#583]
I came across something similar to #288, but for different data set. First thing to notice is that this is coming from a production run, i.e. I've cmorized years of data from the same experiment without any problem. But for two years (4 and 11) out of 66, the code get stuck (I must kill it or let it reach walltime). I've resubmitted the job few times to no avail. The error messages are all of the type: 

    Traceback:
    ! In function: cmor_check_interval
    ! called from: cmor_axis
    ! 
    
    !!!!!!!!!!!!!!!!!!!!!!!!!
    !
    ! Error: approximate time axis interval is defined as 2592000.000000 seconds (30.000000 days), for value 1 we got a difference of 48686400.000000 seconds (563.500000 days), which is 1778.333333 % , seems too big, check your values
    !
    !!!!!!!!!!!!!!!!!!!!!!!!!

The parallelization hides things a bit, because I have several messages like this in the same log with 2 or 3 different sets of number. 

The second log gives more information. In both years, I got:

    2020-01-29 18:55:37 INFO:ece2cmor3.ifs2cmor: Loading CMOR table AERmon...
    2020-01-29 18:55:37 INFO:ece2cmor3.ifs2cmor: Creating time axis using variable wa...

`wa` on AERmon is monthly average on model levels. 

Another clue: from another experiment on another machine, I had two problematic years (19 and 43). One also choked on `wa AERmon`, but the other on `ta AERmonZ` which is on pressure levels. But the first time I run them it did not happen (I rerun because of an error message in the submit script log - inconsequential apparently).

**Comment by tommibergman** [comment]
Could it be somehow mixing up the files where it gets the time data? This error is basically caused by having a month which is too long.

**Comment by goord** [comment]
Hi Philippe, do you have the intermediate netcdf file produced by cdo? It's called wa_AERmon.nc in the temp directory

**Comment by klauswyser** [comment]
How do the origiinal GRIB files look like? One timestep too much can end in the last file of the last year after a crash, and I think I have seen this error message in that context.

Alternatively, does it happen at the first year of a scenario?

**Comment by plesager** [comment]
Just killed another stuck job. This time it was stuck on `hur` from CFmon. @goord 
you can find the temp file on cca@ECMWF in (the newest file):

    /scratch/ms/nl/nm6/temp-cmor-dir/onep/ifs/043/onep-ifs-1892

**Comment by plesager** [comment]
Aha, 13 of the monthly files have 13 timesteps, the other ones have 12 steps:

    [5111] >>> for f in *mon.nc; do echo -n $f: ; ncdump -h $f | grep "time = UNLIMITED"; done
    cdnc_AERmon.nc:	time = UNLIMITED ; // (13 currently)
    cli_Amon.nc:	time = UNLIMITED ; // (13 currently) 
    hfss_Amon.nc:	time = UNLIMITED ; // (12 currently)
    hur_CFmon.nc:	time = UNLIMITED ; // (13 currently)
    hus_Amon.nc:	time = UNLIMITED ; // (13 currently)
    huss_Amon.nc:	time = UNLIMITED ; // (13 currently)
    lwp_AERmon.nc:	time = UNLIMITED ; // (13 currently)
    mrro_Lmon.nc:	time = UNLIMITED ; // (12 currently)
    ps_Amon.nc:	time = UNLIMITED ; // (13 currently)
    rsscsaf_AERmon.nc:	time = UNLIMITED ; // (13 currently)
    snc_LImon.nc:	time = UNLIMITED ; // (13 currently)
    ta_CFmon.nc:	time = UNLIMITED ; // (13 currently)
    tas_Amon.nc:	time = UNLIMITED ; // (13 currently)
    tasmin_Amon.nc:	time = UNLIMITED ; // (12 currently)
    va_AERmon.nc:	time = UNLIMITED ; // (13 currently)
    zg_AERmon.nc:	time = UNLIMITED ; // (13 currently)

and I have 13 times the error message:

    ! Error: approximate time axis 

Those with a 13th step have an additional 0 step at the beginning.

**Comment by goord** [comment]
hmm the first time stamp is 1850-1-1 00:00:00 in all of those files, this comes from the filtered grib files

**Comment by goord** [comment]
Do you have a log file where it says it can't find the previous leg?

**Comment by plesager** [comment]
I see. I have:

    2020-01-30 13:58:00 INFO:ece2cmor3.grib_filter: Assumed previous month file for /scratch/ms/nl/nm6/ECEARTH-RUNS/onep/output/ifs/043/ICMGGonep+189201: /scratch/ms/nl/nm6/ECEARTH-RUNS/onep/output/ifs/001/ICMGGonep+000000

I thought I needed to keep leg 001 but obviously I also need leg-1. I've been to hungry in backing up data! Seems obvious now... Shouldn't that INFO be flagged as a WARNING or an ERROR btw, since ece2cmor get stuck? 
So @tommibergman was right. I will retrieve data and try again. Thanks all for the prompt replies.

**Comment by goord** [comment]
You're right it should be an error unless you're processing the very first leg so...myeah

**Comment by plesager** [comment]
Reinstalling previous leg data did fix my problem.

**Comment by goord** [comment]
P.S. Better error messages implemented in rev. a5a9ef7720f0519f03e2e5f359b0ab3757a4cf94
