### ISSUE TITLE
'caught signal' reported by cdo python binding

### ISSUE THREAD

**Issue by plesager** [EC-Earth/ece2cmor3#584]
On only one of the two platforms I used, namely BULL at KNMI, I randomly got this message in the submit script output:

     ('caught signal', <cdo.Cdo object at 0x7ff9a96cf190>, 15, <frame object at 0x7ff9a9604638>)

The cmor logs do not report any error or warning that is not here when I do not get this 'caught signal`, suggesting that everything is fine.

It happens irregularly: 13 times out of 488 IFS cmorizations. Not that many but that's enough to worry. So I rerun one of these legs and the message disappeared. I compared the two resulting cmorizations and checked that all the data are identical and, while I'm at it, that they do not contains any NaN. Conclusion: nothing to worry.

**Comment by plesager** [comment]
Closing the issue, since we can ignore that message.

**Comment by goord** [comment]
Apparently cdo sometimes exists with status code 15, not sure what it means...
