### ISSUE TITLE
Negative O3 values in the zonal mean

### ISSUE THREAD

**Issue by plesager** [EC-Earth/ece2cmor3#590]
We found negative values in the **monthly zonal mean of O3 on pressure levels** in our AerChem cmorized data:

![zonal-mean-O3](https://user-images.githubusercontent.com/11032052/74927288-9a4c7f00-53d7-11ea-8e8d-754e949fc219.png)

Vertical axis is pressure and is upside down. Clearly at the surface, near the poles, something goes wrong. I guess that the high pressure is not always or never reached there and the interpolated value is incorrect. The calculation is done in `tm52cmor.py`, where the interpolation to pressure levels is done first https://github.com/EC-Earth/ece2cmor3/blob/54e36a782c6d9471d39a80677234b0113155fbf9/ece2cmor3/tm52cmor.py#L432
and then a simple `numpy,mean` is applied https://github.com/EC-Earth/ece2cmor3/blob/54e36a782c6d9471d39a80677234b0113155fbf9/ece2cmor3/tm52cmor.py#L443

I think that the pressure interpolation is not working as expected. Shouldn't we set to NaN, if the pressure target is out of the range of the pressure input? @tommibergman @noije

**Comment by noije** [comment]
Yes, when calculating the zonal mean at a certain pressure level, mixing ratios should be set to zero at elevated locations where the surface pressure is lower than that pressure.

**Comment by tommibergman** [comment]
I agree, it is not correct. Unfortunately, I cannot fix this now. Just happens that we found this bug at a very unfortunate time.

**Comment by plesager** [comment]
This can always be recreated from the 3D model level cmorized output. If I have time, I will write a recipe to replace the data in place. That's the easiest solution, or we just do not provide this zonal mean.

**Comment by plesager** [comment]
Looking at the code, I wonder is a quick fix is possible. The interpolation is now done like this:

https://github.com/EC-Earth/ece2cmor3/blob/54e36a782c6d9471d39a80677234b0113155fbf9/ece2cmor3/tm52cmor.py#L559

but the documentation for the last flag says:

> If False, then no extrapolation is done when the pressure level is outside of the range of psfc (psdata in our call). 

To test.

**Comment by plesager** [comment]
I did a quick test setting the last argument to `False` in the  call to `Ngl.vinth2p`. This seems to be a step in the right direction, although the NaN are not correctly hanlded (I use the same color scale as the in the first plot above):
![o3z-interpol-false](https://user-images.githubusercontent.com/11032052/76204346-863ab700-61f8-11ea-9639-c49b4e17a830.png)

The top area in purple has the 1e+30 value everywhere.

**Comment by plesager** [comment]
Further tests with the corrected SP in EC-Earth output. Here is a reference. This a zonal slice (not mean) of O3 on model levels from the AERmon table. Y-axis goes from 0 (bottom) to 1 (top):
![Screenshot from 2020-03-20 10-17-58](https://user-images.githubusercontent.com/11032052/77150621-92decb00-6a94-11ea-8ecc-7ddeb5b12a1d.png)

There is no spatial average, only a monthly mean. Data range in the entire atmosphere is [8e-9, 9.7e-6]

**Comment by plesager** [comment]
Now the zonal mean on 39 pressure levels. This involves vertical interpolation, followed by the zonal mean. I am using the correct surface pressure in the vertical interpolation (as fixed in #603). The result is still wrong. The range of data is now [1.6e-8, 1.8e-4] with the largest values at the surface (top plot), but the top of the atmosphere is ok (bottom plot where I use the same color scale as the reference plot above):

![zonal-mean-two-ranges-noNaN-wEXTRA](https://user-images.githubusercontent.com/11032052/77152391-2ebe0600-6a98-11ea-9e61-81a5205e39fd.png)

**Comment by plesager** [comment]
So the only improvement so far is that the negative values disappeared.

**Comment by plesager** [comment]
For the record, I tried to remove the extrapolation out of the original range during the vertical interpolation (setting the last argument to `False` in the  call to `Ngl.vinth2p`), and accounting for NaN (white area):

![zonal-mean-w-noEXTRA-NaN](https://user-images.githubusercontent.com/11032052/77154398-e7397900-6a9b-11ea-9ac9-59996e9a5a9e.png)

It is not clear to me what `False` in the  call to `Ngl.vinth2p` exactly does, but this seems too aggressive.

**Comment by plesager** [comment]
I think there is still something wrong with the vertical interpolation on plevel. Needs to be fixed or clarified before we can address the zonal mean.

**Comment by noije** [comment]
> Further tests with the corrected SP in EC-Earth output. Here is a reference. This a zonal slice (not mean) of O3 on model levels from the AERmon table. Y-axis goes from 0 (bottom) to 1 (top):
> 
> There is no spatial average, only a monthly mean. Data range in the entire atmosphere is [8e-9, 9.7e-6]

The range is ok, but I wonder about the vertical axis. Is the surface (y=0) really at the bottom of the graph? Does the vertical distribution agree with that shown in https://dev.ec-earth.org/issues/752#note-41?

**Comment by noije** [comment]
So, in the plot the y-axis goes from 0 at the bottom (=TOA) to 1 at the top (=surface), and the problem appears only near the surface/in the lower troposphere? Is that correct. I have the feeling this is indeed related to the treatment of the points with high surface elevation, where the surface pressure is lower than the required pressure level. These should be set to NaN in the vertical interpolation, and should be excluded when calculating zonal means at those pressure levels. @plesager I understand you already tried that, right?

**Comment by plesager** [comment]
Re: vertical axis. That's correct.
Re: setting NaN. I tried something different, namely avoiding extrapolation out of the range of data of input data. I will try your proposition.

**Comment by plesager** [comment]
I rerun everything. Things are looking better. Model levels on the left, zonal mean on 39 pressure levels on the right:

![O3 from 2020-03-24 master](https://user-images.githubusercontent.com/11032052/77428183-04da4b80-6dd8-11ea-89a9-0180210c5e88.png)
 
Note that there is still some small negative in the interpolated data, as indicated by the data range. They are found near the surface above the Antartic. But this is a lot better than the first plot.

**Comment by noije** [comment]
I suspect the small negatives appear where all points at that latitude have surface pressure lower than the pressure level of interest. If that is indeed the case, the zonal mean is undefined and these values should in fact be set to NaN.

**Comment by plesager** [comment]
I think it work the other way around: if the _target_ pressure is smaller than what's available in the column, then you have to extrapolate. And we are in the opposite case. Or do I miss something?

**Comment by noije** [comment]
Yes, but extrapolation can produce negatives in case of strong vertical gradients. Just assuming the mixing ratios in the lowest model level are valid throughout the whole cell, i.e. down to the surface, and assuming NaN at higher pressures, is the safest thing to do.

**Comment by tommibergman** [comment]
I think this also resolved by PR #618

**Comment by treerink** [comment]
Solved by merging #618.
