### ISSUE TITLE
incorrect AERmon aerosol-free fluxes

### ISSUE THREAD

**Issue by plesager** [EC-Earth/ece2cmor3#592]
This is a follow up on one particular problem that was found in [issue 752](https://dev.ec-earth.org/issues/752#note-30) on the EC-Earth portal. It looks like ece2cmor doe not account for the accumulated nature of the 8 aerosol-free fluxes.

**Comment by treerink** [comment]
Ok as we just discussed, probably we have to add some of them in the `"ACCUMFLD"` part of 
`ece2cmor3/resources/grib_codes.json`

**Comment by goord** [comment]
@plesager what are the grib codes of those fluxes? As mentioned by @treerink they have to be part of the ACCUMFLD list to be automatically de-accumulated. You can do it of course by hand by dividing by the time step, but you should take into account that the interval 21h -0h of december 31st is participating in the january monthly mean...

**Comment by plesager** [comment]
In the post [issue 752-37](https://dev.ec-earth.org/issues/752#note-37) on the EC-Earth portal, I reported a couple of problems. The four variables that need to be added to ACCUMFLD are:
70.126, 71.126, 74.126 and 75.126.  Basically the all series 68-75 of table 126 consists of accumulated fields.

The other problem is about `74.129 = var128212-var126069`. Both 212.128 and 69.126 are flagged as accumulated, but not 74.129, which does not seem to inherit the accumulated flag of its components.

**Comment by goord** [comment]
Hi Philippe, for this you will need the extra field
```
"convert": "cum2inst"
```
in the definition of the derived variable in ifspar.json. It is a bit complicated, but with reason: the ACCUMFLD grib codes are there for the filtering to pick out the right time interval (skip midnight point of previous year, include midnight point of next year) from the grib files. the convert attribute in the ifspar.json is there to have ece2cmor3 divide the value by the NFRPOS time so we obtain a mean flux over the postprocessing time step.

**Comment by plesager** [comment]
Aha, interesting. So what's needed:

- add 70.126, 71.126, 74.126 and 75.126 to ACCUMFLD in grib_codes.json
- add "convert": "cum2inst" to targets: *af  in ifspar.json

**Comment by treerink** [comment]
Ok I was about to push my changes to the master, but with pulling I see @goord added a branch. Changes are not identical. Will have a look.

**Comment by plesager** [comment]
I did a test earlier today - it had the same problem as the master at the the time (#598). Probably safe to merge into master though.

**Comment by plesager** [comment]
The scaling is correct now. Today's tests (with a merge of master and deaccum-126):
![all-v1](https://user-images.githubusercontent.com/11032052/76411184-8f12c080-6391-11ea-81bb-a8586d99d9fa.png)

There are still some sign issues, but this is addressed in another thread. So the issue at hand is solved, and the the branch can be merged in master.

**Comment by treerink** [comment]
Merged in #600.

Closing.
