### ISSUE TITLE
Cmor-fixing the fx sftlf basic file and easen its procedure

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#593]
As mention at [this wiki](https://github.com/EC-Earth/ece2cmor3/wiki/Recommended-strategies) `fx` `sftlf` can be created from the `sftlf_fx_EC-Earth3-Veg_TEMPLATE_r1i1p1f1_gr.nc` file. The latter file needs the `lon` fix with cmor-fixer.

Secondly, a more convenient script to modify the metadata based on an arbitrary file from your considered experiment, is desired.

**Comment by uwefladrich** [comment]
> [...] Secondly, a more convenient script to modify the metadata based on an arbitrary file from your considered experiment, is desired.

I've made a first attempt to come up with such a script. It takes a yaml file and a number of netcdf files (or directories) as argument and sets the netcdf global attributes accordingly.

See [here](https://git.smhi.se/ec-earth/data-qa/blob/master/scripts/fixattr.py).

**Comment by treerink** [comment]
Upcoming change in producing ` fx sftlf` will make this issue obsolete. With help of  ` fx sftlf` data to be available on b2share for each resolution the cmorisation of  ` fx sftlf` will no longer need additional effort of the user (see #676).
