### ISSUE TITLE
problem with cmorizing product of variables

### ISSUE THREAD

**Issue by xlevine** [EC-Earth/ece2cmor3#596]
Hello @pabretonniere ,

I have an issue with cmorizing the covariance moisture flux (the product of meridional/zonal wind with specific humidity). I have defined this variable in ifspar.json (search for vqrea in /gpfs/scratch/bsc32/bsc32647/a20e/autoecearth3/ece2cmor/ece2cmor3/resources/ifspar.json). This variable fails to cmorize properly, even though all other covariance fluxes (vT, vu, etc) are produced successfully.

The source of the problem can be traced to velocities (ua, va) and specific humidity (hus) being outputted on different grids; to be clear, velocities are stored in ICMSHa20e files, while specific humidity is stored in ICMGGa20e files. 

Is there a way to produce covariance of variables that are stored on different grids? 

Thank you for your help. Any help would be very appreciated!

**Comment by goord** [comment]
Hi @xlevine it is currently not supported in ece2cmor3 to combine spectral and gridpoint variables in a derived variable formula. This would need us to create more temporary files for the interpolated fields onto the regular grid before applying the cdo formula.

Does this feature have a high priority?

For 6-hourly fields on pressure levels the product of hus and u/v can be computed from the cmorized variables btw.

**Comment by etiennesky** [comment]
I also think this is a post-cmorizing issue since they are on different grids and can be done pretty easily after regridding both variables to a common resolution.

BTW are there CMOR variables for these covariance fluxes?

**Comment by xlevine** [comment]
Hi Gisj and Etienne,

Thank you for your prompt replies! 

@goord : No, this feature is not urgent. It just would be nice to be able to output directly monthly mean (Amon) specific humidity fluxes without having to stored the 6 hourly wind fields and specific humidity; it's already possible with other 3D variables (ua, va, wap, zg, ta), so outputting specific humidity on the same grid would seem logical.

@etiennesky : I have added manually covariance fluxes for temperature and geopotential height in the CMIP6_Amon.json (vtrea, vzrea, etc.); as far as I know those covariance fluxes are not produced by any of the default outclasses (dcpp, reduced, cmip6). 

Thanks for looking into it!
Xavier.

**Comment by treerink** [comment]
I consider this discussion as closed.
