### ISSUE TITLE
Variable "areacella" not available in IFS cmorized data?

### ISSUE THREAD

**Issue by nierad** [EC-Earth/ece2cmor3#597]
Hi all, 
I got an Email simply stating the following: 

"The variable areacella is missing from ESGF for all EC-Earth_consortium models." 

I quickly checked the files I have and ifs2cmor.py and tm52cmor.py. 
There is no dataset "areacella" in the cmorized IFS files as it is in TM5, but in its descriptions for the main variables (e.g. tas...) _cell_measure_ is defined as:
`cell_measures = "area: areacella"`
with areacella being defined as an external variable in the global attributes  
`external_variable = "areacella"`.
There seems to be no reference to an external file. Should it maybe be:
`external_variable = "areacella: <file-name>`
or something like that?

I asked for more info on how the writer encountered the problem but he hasn't responded yet. Most likely because he is from North America.

I guess, you Guys have a quick answer to this. 

Thanks, Lars

**Comment by treerink** [comment]
Hi Lars, 

See: https://dev.ec-earth.org/issues/748#note-3

**Comment by zklaus** [comment]
That comment tells us how to create this manually. But surely ece2cmor should do it automatically?

**Comment by nierad** [comment]
Hi Thomas and Klaus, 

>  But surely ece2cmor should do it automatically?

I think so too. Especially, when tools like nco automatically  generate totals...

**Comment by klauswyser** [comment]
Not sure about "automatically", fx files only need to be created once for each experiment and member while ece2cmor3 loops over years. There are other examples of fx files for the ocean that are not created automatically for the time being. All this could be solved of course, but is it worth the effort?

**Comment by nierad** [comment]
With "automatically" I understood "provide the information". To me it looks like there is incomplete information in the attributes. 
However, the variable description for _areacella_ reads:
` description[i]: For atmospheres with more than 1 mesh (e.g., staggered grids), report areas that apply to surface vertical fluxes of energy.`
So I think there is no need to "fix" this.

**Comment by treerink** [comment]
Note that `areacella` is not in the request,  surprisingly enough as it is quite an import one. So it needs manual addition anyway. 

Note also that `areacella` is used for something different than a cmor name of a variable, c.f.:
```
cell_measures = "area: areacella"
```

**Comment by zklaus** [comment]
What do you mean by "it is not in the request"? You can certainly find it [here](http://clipc-services.ceda.ac.uk/dreq/u/baa83a12-e5dd-11e5-8482-ac72891c3257.html).

**Comment by treerink** [comment]
yes, see once more https://dev.ec-earth.org/issues/748#note-3

**Comment by goord** [comment]
I will have a look at it today or tomorrow. So... what about the ocean grid cell areas? Do we provide them?

**Comment by treerink** [comment]
`areacello` is in 'our' requests. Though areacella is in principle defined in the CMIP6 data request it is simply never asked in any of 'our' requests (which looks like a cavity in the requests).

**Comment by treerink** [comment]
We will permanently add `fx` `areacella` for the `ifs` case. That means although it is never asked in any of our EC-Earth cases by the CMIP6 data request (I think an omission), it will be added always.

**Comment by treerink** [comment]
@goord I checked that `3hr` `tas` (grib code 167) is asked in any of the EC-Earth experiments (it is always available in `pptdddddd0300` & `pptdddddd0600`. So that one can be used with `cdo gridarea`.

I checked the control-output files with:
```
for i in $(find . -name pptdddddd0600); do echo $i; done|wc
for i in $(find . -name pptdddddd0300); do more $i|grep 167; done|wc
for i in $(find . -name pptdddddd0600); do more $i|grep 167; done|wc
```

**Comment by goord** [comment]
Fix has been committed in branch areacella. Nevertheless it may be worth considering a --nofx option to dismiss static fields (otherwise they get overwritten each time)

**Comment by treerink** [comment]
Ok that latter point is made separately in #608.

**Comment by treerink** [comment]
Done. Closing.
