### ISSUE TITLE
Wong unit conversion for Radiation fluxes due to recent commit

### ISSUE THREAD

**Issue by plesager** [EC-Earth/ece2cmor3#598]
Here is `rsds` cmorised with the master branch at HEAD (f5aa06e, Feb 21) on the right and at b4ebba9 (Jan 17) on the left, which I have been using to cmorize all my data up to now. 

![conversion-bug](https://user-images.githubusercontent.com/11032052/76300597-42f64c00-62bd-11ea-9304-a388fb774d29.png)

Everything else is the same. The problem seems to be a scale factor at conversion. I suspect it affects all experiment (`rsds` is not specific to AerChemMIP exps) and maybe other variables (definitively other radiative fluxes I checked).

**Comment by klauswyser** [comment]
The division of the accumulated value by 10800 (= 3 hours) seems to have been forgotten in the right plot.

**Comment by goord** [comment]
The bug is in line 428 of cmor_utils.py, where the 'and' should be an 'or'. I will fix it right away on the master branch so you can test it Philippe.

**Comment by goord** [comment]
btw the bug you discovered was introduced 28 days ago in 5a0919c2dd7158fa24371d68c4d71ff8fb8a2c0c

**Comment by plesager** [comment]
Tested, it works. Thanks for the quick fix.
