### ISSUE TITLE
Incorrect sign in aerosol-free fluxes, as well as rsut(cs)?

### ISSUE THREAD

**Issue by plesager** [EC-Earth/ece2cmor3#599]
These sign conventions are driving me crazy, but let me try to get the story straight. For the aerosol-free fluxes, `ece2cmor3` assumes positive-up fluxes at the top, and positive-down at the surface, but we provide them with the same (positive down) sign.

After closer inspection of the IFS and CMIP6 json files, I think all the TOA aerosol-free fluxes must be inverted to be positive up, and for the particular case of @rsutaf@ its expression should be @var128212+var126069@ (down-net) instead of the @var128212-var126069@ currently used. But I begin to doubt. Because that would also imply that @rsut@ and @rsutcs@, which are also defined as positive upward, are not computed correctly. Their expression is @var178-var212@ and @var208-var212@, respectively. I think they should be @var212-var178@ and @var212-var208@, i.e. "down - net", according to [the documentation](https://www.ecmwf.int/sites/default/files/elibrary/2015/18490-radiation-quantities-ecmwf-model-and-mars.pdf). However this has already been investigated in #92, and the opposite conclusion was reached. Am I missing something?

**Comment by goord** [comment]
Hi Philippe, if I recall correctly, we define all fluxes positively downward, and the cmor library inverts them automatically if the variable is requested positively upward.

To check, all fluxes we produce should be positive numbers, this is how the CMOR tables have defined them.

**Comment by plesager** [comment]
> Hi Philippe, if I recall correctly, we define all fluxes positively downward, and the cmor library inverts them automatically if the variable is requested positively upward.

Alright, that's the step I was missing. Makes sense now. `rsut` and `rsutcs` are correct. I need to double check `rsutaf`.

**Comment by goord** [comment]
I know it's tricky, I figured this out after the primavera release of ece2cmor3 so I will admit there are some upwelling fluxes in the early primavera data (I believe the amip runs we did) that are actually negative. Obviously any user will immediately notice this and figure out we made an orientation error, but we should actually make an erratum for this...

**Comment by plesager** [comment]
Ok good to know.

Further investigation. I want to replace:
`    {
        "source": "68.126",
        "target": "rsutcsaf"
        "convert": "cum2inst",
    },
`
with
`    {
        "source": "??.TAB",
        "target": "rsutcsaf"
        "convert": "cum2inst",
        "expr": "var126068-var128212"
    },
`

How do I do that? It looks like you are using table 129, which is full of empty slots. Can I just pick any slot not used in the `ifspar.json`?

**Comment by goord** [comment]
Yes, you can pick any unused grib code.

**Comment by plesager** [comment]
Got a fix for the two variables left (`rsutcsaf` and `rsutaf`):

![correct-rsutaf](https://user-images.githubusercontent.com/11032052/76427564-c5116e00-63ac-11ea-869e-53be3d928637.png)

This is just few lines in `ifspar.json`. Pull request coming.
