### ISSUE TITLE
Travis tests broken

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#607]
Since the 2c4179cc12b247b00cc8734df757232ab07afc74 merge, and probably since 181e63ed54789e9ccd5a06226dcdd086d20074b4 the Travis tests are broken.

**Comment by treerink** [comment]
Which therefore also affects the branches

**Comment by goord** [comment]
I don't understand, clean environment gives no errors whatsoever on my system...

**Comment by treerink** [comment]
On the bull I got:
```
................................
======================================================================
FAIL: test_date2num_types (cmor_utils_tests.utils_tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nfs/home/users/reerink/cmorize/ece2cmor3/test/cmor_utils_tests.py", line 151, in test_date2num_types
    ok_(isinstance(dates[0], datetime.datetime))
AssertionError: None

----------------------------------------------------------------------
Ran 104 tests in 411.756s

FAILED (failures=1)
```

**Comment by goord** [comment]
Hey that's the same error on the travis test env

For some reason, the cftime-1.1.1 package is being downloaded, has nothing to do with my merge, just some dependency changed...

**Comment by goord** [comment]
@treerink can you edit the file cmor_utils_test.py:

insert "print dates[0]" after line 150

after that, replace line 150 with

```
dates = netCDF4.num2date(nums, units, calender, only_use_cftime_datetimes=False)
```

**Comment by treerink** [comment]
I can only find a `cmor_utils.py` file and no `cmor_utils_test.py`. Which is the same on my ubuntu laptop where I don't have the error.

**Comment by goord** [comment]
Sorry I meant ```cmor_utils_tests.py```. In the ```test``` directory.

**Comment by treerink** [comment]
With that I get on the bull:
```
................................
======================================================================
FAIL: test_date2num_types (cmor_utils_tests.utils_tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nfs/home/users/reerink/cmorize/ece2cmor3/test/cmor_utils_tests.py", line 152, in test_date2num_types
    ok_(isinstance(dates[0], datetime.datetime))
AssertionError: None
-------------------- >> begin captured stdout << ---------------------
1849-12-15 12:30:30

--------------------- >> end captured stdout << ----------------------

----------------------------------------------------------------------
Ran 104 tests in 334.935s

FAILED (failures=1)
```

**Comment by goord** [comment]
The issue originates from a new release of the cftime package that is part of netCDF4. From their release notes:

2/12/2020: version 1.1.0 released. cftime.datetime instances are returned by default from num2date (instead of returning python datetime instances where possible (issue #136)). num2pydate convenience function added (always returns python datetime instances, issue #134). Fix for fraction seconds in reference date string (issue #140). Added daysinmonth attribute (issue #137).

This is potentially harmful to nemo2cmor, further investic=gation needed

**Comment by goord** [comment]
Fixed in rev. 57eb90806cd7cf33fd8e4609e52a975828550a20
