### ISSUE TITLE
Procedure to update the CMIP6 cmor tables

### ISSUE THREAD

**Issue by plesager** [EC-Earth/ece2cmor3#611]
I have the non-cmor variables for AerChemMIP added, as explained [here](https://dev.ec-earth.org/issues/736#note-11). Now I cannot update the cmip6 cmor tables:

![cmip6-tables-issue](https://user-images.githubusercontent.com/11032052/77420719-d6a23f00-6dca-11ea-93c1-e2b10c66b32f.png)

Can I just ignore it? What would be the safe procedure to update it? Revert to vanilla ece2cmor3, update the tables, and then reapply the `./add-non-cmor-variables.sh`?

**Comment by treerink** [comment]
No.

As stated in the README, you have to do:
```
git submodule update --init --recursive
```

**Comment by treerink** [comment]
It is independent of your other stuff. Of course after that you have to do again in your `ece2cmor3` root directory:
```
python setup.py develop;
```

**Comment by plesager** [comment]
> ```
> git submodule update --init --recursive
> ```

I got that, but it is aborting. See bottom of the picture in OP.

**Comment by treerink** [comment]
Ah sorry didn't see the picture. Yes ok indeed you first need to do:
```
cd ece2cmor3/resources/cmip6-cmor-tables
git checkout Tables/CMIP6_AERmon.json
```
And then (as you know):
```
cd -
git submodule update --init --recursive
cd ece2cmor3/scripts/
./add-non-cmor-variables.sh
cd -
python setup.py develop;
```

**Comment by plesager** [comment]
Ok thanks, that works.
