### ISSUE TITLE
interpolation of TM5 output to the IFS gaussian grid?

### ISSUE THREAD

**Issue by etiennesky** [EC-Earth/ece2cmor3#614]
For the EC-Earth-CC runs it would be great to be able to report the co2 and co2mass variables in the IFS reduced gaussian grid, after doing the vertical interpolation which is now mostly working.

Is this possible?

**Comment by goord** [comment]
Hi etienne, do you want to output these variables on the reduced grid? Because we interpolate IFS variables on regular grid right?

**Comment by etiennesky** [comment]
Hi @goord the idea would be to have it on the same grid as all other ifs cmorized variables, so the regular gaussian grid.

**Comment by goord** [comment]
Yes that is possible, if tm5cmor has somewhere the grid description of IFS available a simple cdo command before sending the data to cmor would do the job I guess. @tommibergman, could tm52cmor derive the IFS resolution from its own data or do we need to hardcode it somehow?

BTW this is not a very simple task, it requires a new grid to be declared in tm52cmor and passed to the cmor library and so on

**Comment by etiennesky** [comment]
Hi @goord couldn't it get the grid using create_grid_from_file(filepath) which is currently defined in ifs2cmor.py ?  Of course it would need one GG file available.

**Comment by etiennesky** [comment]
I would say this is not so important, #613 is more pressing
