### ISSUE TITLE
gzip-compress LPJG test data

### ISSUE THREAD

**Issue by etiennesky** [EC-Earth/ece2cmor3#615]
Since ece2cmor3 supports reading compressed LPJG output files (*.out.gz) this would allow to save considerable space taken by some test files stored in LFS.

For example. the file test/test_data/lpjg/tsl_daily.out currently occupies 521MB, compressing it would reduce it to 72MB.

**Comment by nierad** [comment]
Hi @etiennesky,
I think you meant IFS instead of LPJG in the issue-description.

**Comment by etiennesky** [comment]
no, I precisely meant LPJG output which can compress quite nicely with gzip and cal also be cmorized when compressed.  IFS output is already compressed by grib.

**Comment by nierad** [comment]
Ah, OK, sorry. I think I missed the whole purpose...

**Comment by etiennesky** [comment]
this is mostly to save space in the LFS files, which take up more space than necessary at this point. We are setting up a copy of ece2cmor3 on our internal gitlab server and would like to save some space.
