### ISSUE TITLE
Empty slice in mean of TM5 data

### ISSUE THREAD

**Issue by plesager** [EC-Earth/ece2cmor3#622]
Trying the last release candidate, and I got this warning:

`.../ece2cmor3/ece2cmor3/tm52cmor.py:452: RuntimeWarning: Mean of empty slice
  vals=numpy.nanmean(vals,axis=-1)
`

**Comment by tommibergman** [comment]
I was meaning to put an issue on this, but forgot. But I think it is working as it should, NumPy just likes to warn that all values in this slice are nan. So this is basically the Antarctica where all the points in the lowest pressure level is nan. I was not sure if I want make these warnings go away. I think there should be a way to ignore them.

**Comment by plesager** [comment]
Actually there are ways to get around the warnings. I do not like to ignore them because we could miss a bug. But the non-accepted answer from [this SE thread](https://stackoverflow.com/questions/29688168/mean-nanmean-and-warning-mean-of-empty-slice) would be fine. Something like:
`np.NaN if np.all(a!=a) else np.nanmean(a)`

**Comment by plesager** [comment]
Well, not as straightforward with the axis... I found another way:

```
In [16]: a                                                      
Out[16]: 
array([[nan, nan],
       [nan,  3.]])

In [17]: np.nanmean(a,axis=-1)                                                 
/usr/local/bin/ipython:1: RuntimeWarning: Mean of empty slice
  #!/usr/bin/python3
Out[17]: array([nan,  3.])

In [18]: with warnings.catch_warnings(): 
    ...:     warnings.filterwarnings('ignore', '.*Mean of empty slice.*',) 
    ...:     b = np.nanmean(a,axis=-1) 
    ...:    

In [19]: b                                         
Out[19]: array([nan,  3.])

In [20]: np.nanmean(a,axis=-1)        
/usr/local/bin/ipython:1: RuntimeWarning: Mean of empty slice
  #!/usr/bin/python3
Out[20]: array([nan,  3.])
```
The `with warnings.catch_warnings():` is just to apply the filter warning only inside the block. I guess it could something more simple?

**Comment by tommibergman** [comment]
That is what I got from google as well. Maybe, that is the way to go. Just ignore that warning for this nanmean?

**Comment by etiennesky** [comment]
> Trying the last release candidate, and I got this warning:

Hi @plesager where do we get information on the release candidate? Or is that unofficial?

**Comment by treerink** [comment]
@etiennesky : the latest master

**Comment by plesager** [comment]
Releases are managed (by @treerink  and @goord)  with a dedicated issue. For the next one, this is #605. Milestones could have been used I guess, but that's fine.

**Comment by plesager** [comment]
>  Maybe, that is the way to go. Just ignore that warning for this nanmean?

Yes, that what we should do. Not us ignoring, but make the code ignore it.

**Comment by plesager** [comment]
I'll test and push it.

**Comment by plesager** [comment]
I did a quick visual check of all AERmonZ data. Everything is fine. You can release 1.4 after #623 MR.

**Comment by treerink** [comment]
Merge #623 completed.
