### ISSUE TITLE
Inconsistent units/values in sea ice fraction (atmosphere grid)

### ISSUE THREAD

**Issue by plesager** [EC-Earth/ece2cmor3#627]
As reported [this issue](https://dev.ec-earth.org/issues/816). I see the problem in both SIday/siconca and SImon/siconca, but not on the ocean grid (SIday/siconc and SImon/siconc).

**Comment by treerink** [comment]
The data request says for both [siconca](http://clipc-services.ceda.ac.uk/dreq/u/5914ab90-9e49-11e5-803c-0d0b866b59f3.html) & [siconc](http://clipc-services.ceda.ac.uk/dreq/u/150ada98-357c-11e7-8257-5404a60d96b5.html) that the unit should be %. For `siconc` everything seems fine. For `siconca` (also in the latest tested revision) the factor 100 is missing. It means that `ece2cmor3` needs a fix for `siconca:` an additional converting factor of 100 should be added and the reported unit should stay %.

**Comment by treerink** [comment]
In 61166e1 the conversion factor from fraction to percentage for `siconca` is added.

**Comment by goord** [comment]
Should this fix also be added to cmor-fixer?

**Comment by plesager** [comment]
I'd say yes, although in my case (not yet published data) it is trivial to fix it with an ad-hoc script.

**Comment by treerink** [comment]
The `fix-siconca` branch includes this siconca fix. See [here](https://github.com/EC-Earth/cmor-fixer/issues/28).

**Comment by treerink** [comment]
The `fix-siconca` branch has been merged in the master of the `cmor-fixer` `v2.2` and will be part of the next  `cmor-fixer` release.
