### ISSUE TITLE
Possible bug on genecec.py

### ISSUE THREAD

**Issue by aearamos** [EC-Earth/ece2cmor3#628]
Hi @treerink 

I ran `genecec.py`and noticed that some of xml, ppt and json files were missing, especially under `/ece2cmor3/ece2cmor3/scripts/cmip6-output-control-files/CMIP/EC-EARTH-CC`. 

I looked into the drq commands and noticed that the reason for the missing files is because one of the mips being used was not on the list of possible MIPs:

> NOT FOUND: CDRMIP:  SUGGESTIONS: CMIP [ 0.8]; DAMIP,RFMIP [ 0.7]; CMIP [ 0.7]; DAMIP,RFMIP [ 0.7]
> ----------------------------------------
> Traceback (most recent call last):
>   File "/shared/earth/software/dreqPy/1.0.27-foss-2015a-Python-2.7.9/bin/drq", line 11, in <module>
>     load_entry_point('dreqPy==1.0.27', 'console_scripts', 'drq')()
>   File "/shared/earth/software/dreqPy/1.0.27-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/dreqPy-1.0.27-py2.7.egg/dreqPy/dreqCmdl.py", line 53, in main_entry
>     x.run()
>   File "/shared/earth/software/dreqPy/1.0.27-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/dreqPy-1.0.27-py2.7.egg/dreqPy/scope.py", line 1864, in run
>     assert ok,'Available MIPs: %s' % str(self.sc.mips)
> AssertionError: Available MIPs: ['CMIP', 'AerChemMIP', 'C4MIP', 'CFMIP', 'DAMIP', 'DCPP', 'FAFMIP', 'GeoMIP', 'GMMIP', 'HighResMIP', 'ISMIP6', 'LS3MIP', 'LUMIP', 'OMIP', 'PAMIP', 'PMIP', 'RFMIP', 'ScenarioMIP', 'VolMIP', 'CORDEX', 'DynVar', 'SIMIP', 'VIACSAB']

After I removed CDRMIP, the files were generated just fine.

**Comment by treerink** [comment]
The BUG is not encountered when using the most update dependencies. So I close this issue.
