### ISSUE TITLE
T159 is not yet an option in ece2cmor3

### ISSUE THREAD

**Issue by nierad** [EC-Earth/ece2cmor3#630]
As discovered in issue #830 on the ec-earth dev-portal, the T255 grid is hard-coded in lpjg2cmor.py. I will generate a T159 griddesc-file for the regridding.

**Comment by nierad** [comment]
@treerink @goord @uwefladrich:
Hmmm, I thought I solved it but now `cdo invertlat` doesn't seem to work on the T159-files. 
I have looked at the meta-data in the two files but can't really get my head around it. 

I have uploaded two files to: 
http://stormbringer.nateko.lu.se/public/lars/issue630/
When using ncview or panoply the T159 data is upside-down. T255 is normal. Both created with the same code. Any idea?

**Comment by klauswyser** [comment]
I recently had problems with "cdo invertlat" in a different context. It turned out that invertlat only works when the grid of the inputdata is a regular lonlat grid, for any other grid the command is just ignored without any message. I never had this problem before, so maybe invertlat has been changed recently in cdo.

**Comment by nierad** [comment]
Thanks Klaus! How inconvenient:) 
It works with T255 though...

**Comment by nierad** [comment]
Another update: 
I uploaded the current lpjg2cmor.py to 
http://stormbringer.nateko.lu.se/public/lars/issue630/
This now flips T159 but doesn't flip T255. This is odd. I am afraid I am right for the wrong reasons, i.e. somewhere there might still be something w.r.t. grid-specifications that I haven't taken care of. Will deal with it later today. If anyone of you feels challenged to have a look, it would be highly appreciated;)

**Comment by nierad** [comment]
Hi  @treerink and @goord!
Would you have a look at the  py-file uploaded in https://github.com/EC-Earth/ece2cmor3/issues/630#issuecomment-639405829, please? Especially at the create_grids function (ll 610)?
Thanks a lot, Lars

**Comment by nierad** [comment]
@treerink: 
Thanks for the discussion! Could have taken forever to find the problem alone. 
I have uploaded all files to 
http://stormbringer.nateko.lu.se/public/lars/issue630/
Including the script to generate the grid-description for cdo and the new ingrid_"grid"_unstructured.txt files. 
The updated lpjg2cmor.py doesn't need any flipping any longer.  The cmorized T255-files are identical to the last digit. 
Thanks for support!

**Comment by treerink** [comment]
Hi Lars,

Could you test the LPJG cmorisation with the current state of the `add-T159-grid-for-lpjg` branch, you can check out this branch by:
```
git pull
git checkout add-T159-grid-for-lpjg
python setup.py install                         # from your ece2cor3 root directory
```

Note with your first test don not run the added `create_cdo_ingrid_for_lpjgout.py` script because this will change the `lon-lat-lpjg-auxiliary-T255-grid.nc` file.

I did not update the `ingrid_T255_unstructured.txt` file because this might cause backward compatibility problems. So the status is that the current `ingrid_T255_unstructured.txt` is still the old one and thus compatible with previous LPJG cmorisation, but that we can not exactly reproduce that one. Just running the `create_cdo_ingrid_for_lpjgout.py` script gives a new `ingrid_T255_unstructured.txt` which is probably good/better and nearly the same and it generates the now added new `ingrid_T159_unstructured.txt`.

Another thing is that I had to keep python2 for `create_cdo_ingrid_for_lpjgout.py` to obtain identical results with your ingrid files. However I think it is good that we test the python3 varaints, because if they are correct as well then we better immediately switch to those, certainly for T159.

**Comment by treerink** [comment]
Oh and please review [here](https://github.com/EC-Earth/ece2cmor3/compare/master...add-T159-grid-for-lpjg?expand=1) the changes in `lpjg2cmor.py` (scrol down a bit and just have a look).

**Comment by nierad** [comment]
Hi Thomas,

I get this exception:

cdo.CDOException: (returncode:1) cdo(2) setgrid: Process started
cdo(2) setgrid (Abort): Open failed on /home/x_larni/miniconda2/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-1.4.0-py2.7.egg/ece2cmor3/resources/lpjg-grid-content/ingrid_T159_unstructured.txt!



the folder

(ece2cmor3) [x_larni@tetralith1 l611]$ ll /home/x_larni/miniconda2/envs/ece2cmor3//lib/python2.7/site-packages/ece2cmor3-1.4.0-py2.7.egg/ece2cmor3/resources/
total 16263
drwxrwsr-x 5 x_larni s-cmip-lu     4096 Jun 11 14:47 .
drwxrwsr-x 4 x_larni s-cmip-lu     4096 Jun 11 14:47 ..
-rw-rw-r-- 1 x_larni s-cmip-lu        0 Jun 11 14:47 __init__.py
-rw-rw-r-- 1 x_larni s-cmip-lu      237 Jun 11 14:47 __init__.pyc
-rw-rw-r-- 1 x_larni s-cmip-lu     3543 Jun 11 14:47 grib_codes.json
-rw-rw-r-- 1 x_larni s-cmip-lu    18236 Jun 11 14:47 ifspar.json
-rw-rw-r-- 1 x_larni s-cmip-lu  4655575 Jun 11 14:47 ingrid_T159_unstructured.txt
-rw-rw-r-- 1 x_larni s-cmip-lu 10369178 Jun 11 14:47 ingrid_T255_unstructured.txt
-rw-rw-r-- 1 x_larni s-cmip-lu    10482 Jun 11 14:47 list-of-identified-missing-cmpi6-requested-variables-enable-pextra.xlsx
-rw-rw-r-- 1 x_larni s-cmip-lu    14348 Jun 11 14:47 list-of-identified-missing-cmpi6-requested-variables.xlsx
-rw-rw-r-- 1 x_larni s-cmip-lu    78737 Jun 11 14:47 list-of-ignored-cmpi6-requested-variables.xlsx
drwxrwsr-x 2 x_larni s-cmip-lu     4096 Jun 11 14:47 lists-of-omitted-variables
-rw-rw-r-- 1 x_larni s-cmip-lu    11335 Jun 11 14:47 lpjgpar.json
drwxrwsr-x 2 x_larni s-cmip-lu     4096 Jun 11 14:47 metadata-templates
-rw-rw-r-- 1 x_larni s-cmip-lu    20912 Jun 11 14:47 nemopar.json
-rw-rw-r-- 1 x_larni s-cmip-lu      945 Jun 11 14:47 permanent-tasks.json
-rw-rw-r-- 1 x_larni s-cmip-lu    10119 Jun 11 14:47 pre-list-of-identified-missing-cmpi6-requested-variables.xlsx
-rw-rw-r-- 1 x_larni s-cmip-lu    30905 Jun 11 14:47 pre-list-of-ignored-cmpi6-requested-variables.xlsx
-rw-rw-r-- 1 x_larni s-cmip-lu     4215 Jun 11 14:47 prefs.py
-rw-rw-r-- 1 x_larni s-cmip-lu     4428 Jun 11 14:47 prefs.pyc
drwxrwsr-x 2 x_larni s-cmip-lu     4096 Jun 11 14:47 tables
-rw-rw-r-- 1 x_larni s-cmip-lu     7643 Jun 11 14:47 tm5par.json



so it seems the Path to the ingrid files is not correct.


I'll check the code too, now!


Cheers, LArs

________________________________

**Comment by nierad** [comment]
Hi again,


the changes in the code are correct, except:

- that the git pull didn't give me the sub-folders for resources/lpjg-grid-content/

- lines 601,2 / 614,5 in old/new code are not changes I made... at least I don't remember.;)


Cheers, Lars



________________________________

**Comment by treerink** [comment]
Hmm, as you can see here the files are checked-in in the branch: https://github.com/EC-Earth/ece2cmor3/tree/add-T159-grid-for-lpjg/ece2cmor3/resources/lpjg-grid-content
So it is a new subdir `lpjg-grid-content/` with files, no further subfolders therein.

**Comment by nierad** [comment]
Hi Thomas,


yes I have seem that but my ece2cmor want to find it in:

/home/x_larni/miniconda2/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-1.4.0-py2.7.egg/ece2cmor3/resources/lpjg-grid-content/


Did I fuck up the reinstall ??

________________________________

**Comment by treerink** [comment]
Hi Lars,

Ok these were exactly th lines why I asked you to review:
```diff
     # create the cell bounds since they are required: we have a 512x256 grid with longitude from 0 to 360 and
     # latitude from -90 to 90, i.e. resolution ~0.7 longitude values start from 0 so the cell lower bounds are the
     # same as lons (have to be: cmor requires monotonically increasing values so 359.X to 0.X is not allowed)
-    lon_half_dists = np.insert(0.5 * (lons[1:] - lons[:-1]), 0, [0.5 * (lons[1] - lons[0])])
-    lon_bnd = np.stack((lons[:] - lon_half_dists, lons[:] + lon_half_dists), axis=-1)
+    lon_bnd_upper = np.append(lons[1:], 360.0)
+    lon_bnd = np.stack((lons, lon_bnd_upper), axis=-1)
```
They changes came in with the file you uploaded, see [here](http://stormbringer.nateko.lu.se/public/lars/issue630/lpjg2cmor.py).

**Comment by nierad** [comment]
Ah, that means my code wasn't up to date?

I don't know when I last did an update , though. I think these changes were made to the master to fix the half-degree shift, thus the old ones (the upper two lines) should remain.

Can you look into the change-log of this file and see, when it came in? There shouldn't be many changes recently.

I am sorry but I am still only half-way familiar with this code.


Cheers, Lars

________________________________

**Comment by treerink** [comment]
Yes that's it, see [here](https://github.com/EC-Earth/ece2cmor3/commit/3b9e49e7d5cc06420427f7e53150ae77436f5bfc). Ok I will fix it.

**Comment by nierad** [comment]
Great!


Thank you Thomas!


Cheers, Lars

________________________________

**Comment by treerink** [comment]
Hi Lars,

Ok done in 4d1f478.

Once more: review [here](https://github.com/EC-Earth/ece2cmor3/compare/add-T159-grid-for-lpjg?expand=1) the changes in `lpjg2cmor.py` (scrol down a bit and just have a look).

And can you test the actual lpjg cmorisation with this branch?

**Comment by nierad** [comment]
Ok, this looks good!


I will test it on the standard data!


Cheers, Lars

________________________________

**Comment by nierad** [comment]
Hi,

I cloned the full repository again, cmorized both grids and everything is fine for the master (almost identical output).

But it won't work for version 1.2 that I still use for T255 because some of our runs were done with ECE 3.3.1.1.


But I don't know if there are older LR runs that require T159...

Cheers, Lars

________________________________

**Comment by nierad** [comment]
Hi @treerink,

Shall we than close #830 and tell @uwefladrich that he can re-cmorize the T159 runs with the new master? 
@uwefladrich: Which version of ECE have the runs been performed with?

**Comment by treerink** [comment]
No, we are not there yet. We have to set the exact ingrid versions for both grids.

Lars I mail you a telco invitation.

**Comment by treerink** [comment]
The issue is solved. 

However, finalizing the subject, needs also the closure of #633. When #633 is closed als the [EC-Earth portal issue 830](https://dev.ec-earth.org/issues/830) can be closed.

**Comment by uwefladrich** [comment]
> [...] @uwefladrich: Which version of ECE have the runs been performed with?

@klauswyser did the runs and our overview document says the version is r7273, which would be between 3.3.1.1 and 3.3.2. It's after the lowres branch `2019/r6458-lowres_for_cmip6` was merged.
