### ISSUE TITLE
Tier 2 and 3 experiments for AerChemMIP

### ISSUE THREAD

**Issue by Declan-FMI** [EC-Earth/ece2cmor3#631]
Hi,
Hereby I request production of control output files for the following AerChemMIP experiments, to be run as a special project at ECMWF:
hist-piAer
histSST-piAer
ssp370SST-lowAer
~~ssp370-lowBC~~  ssp370SST-lowBC
piClim-aer
piClim-BC
piClim-2xdust
piClim-2xss
Thanks,
Declan

**Comment by treerink** [comment]
Hi Declan,

I will have a look for this, but I am currently also halfway a data request and table update, so I have a look if I can finish that first, then you will have the most update version.

Also KNMI needs:
hist-piAer

So there are more parties looking for this.

Would be medio next week fine?

**Comment by plesager** [comment]
I believe Declan meant `ssp370SST-lowBC` and not `ssp370-lowBC`.

**Comment by Declan-FMI** [comment]
Thanks, Philippe, that is correct. 
hist-piAer I need as soon as you can, next week is good, but please, please not later. The rest I can happily wait for.

**Comment by plesager** [comment]
KNMI would like to account for these three AerChemMIP experiments:

- ssp370-lowNTCFCH4

- ssp370SST-lowNTCFCH4

- ssp370pdSST

The first two are tier 3, the last one is tier 2.

**Comment by treerink** [comment]
In the mip-experiment-list.txt I indeed have all the experiments you are asking:

| line |    MIP     |  experiment          |  tier  | experiment description|
|   -- | ---------- | -------------------- | ------ | ------------- |
|    2 | AerChemMIP | hist-piAer           | tier-2 | historical forcing, but with pre-industrial aerosol emissions                          |
|    7 | AerChemMIP | histSST-piAer        | tier-2 | historical SSTs and historical forcing, but with pre-industrial aerosol emissions      |
|   13 | AerChemMIP | piClim-2xdust        | tier-2 | pre-industrial climatological SSTs and forcing, but with doubled emissions of dust     |
|   16 | AerChemMIP | piClim-2xss          | tier-2 | pre-industrial climatological SSTs and forcing, but with doubled emissions of sea salt |
|   18 | AerChemMIP | piClim-BC            | tier-2 | pre-industrial climatological SSTs and forcing, but with 2014 black carbon emissions   |
|   30 | AerChemMIP | ssp370-lowNTCFCH4    | tier-3 | SSP3-7.0, with low NTCF emissions and methane concentrations                           |
|   31 | AerChemMIP | ssp370pdSST          | tier-2 | SSP3-7.0, with SSTs prescribed as present day                                          |
|   33 | AerChemMIP | ssp370SST-lowAer     | tier-2 | SSP3-7.0, prescribed SSTs, with low aerosol emissions                                  |
|   34 | AerChemMIP | ssp370SST-lowBC      | tier-2 | SSP3-7.0, prescribed SSTs, with low black carbon emissions                             |
|   37 | AerChemMIP | ssp370SST-lowNTCFCH4 | tier-3 | SSP3-7.0, prescribed SSTs, with low NTCF emissions and methane concentrations          |
|  275 | RFMIP      | piClim-aer           | tier-1 | effective radiative forcing by present-day aerosols                                    |

The `piClim-aer` is RFMIP, this is correct that you want that one Declan?

**Comment by Declan-FMI** [comment]
Apparently piClim-aer is common to RFMIP and AerChemMIP, according to [https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_experiment_id.html](url). But I do not know why that is, since I do not find any reference to this CMIP6 label in the RFMIP paper [https://www.geosci-model-dev.net/9/3447/2016](url) (although the similar label piClim-aerO3 does occur), whereas in the aerChem paper it's clear enough, see Table 6 therein [https://www.geosci-model-dev.net/10/585/2017](url). As my understanding goes, this is (or at least should be) an AerChemMIP experiment.

**Comment by plesager** [comment]
`piClim-aer` is tier 1 in RFMIP and tier 2 for AerChemMIP, and has the two activity ids on the CMIP CVs.  As tier 1, it is indeed already available in our RFMIP control output.

**Comment by treerink** [comment]
It appeared (indeed) that two experiments of the list above are already available in the current `cmip6-output-control-files/` directories. The two available experiments are:
```
cmip6-output-control-files/AerChemMIP/cmip6-experiment-AerChemMIP-piClim-2xdust/
cmip6-output-control-files/RFMIP/cmip6-experiment-RFMIP-piClim-aer/
```
The other nine will be added in `genecec.`

**Comment by treerink** [comment]
Issue solved at the `genecec` side. The control output files for these tier2 &3 experiments have been successfully added in the `cmip6-output-control-files/`. A new version, including these will be uploaded in a branch in th ec-earth repository.

**Comment by treerink** [comment]
As reported in [ec-earth portal issue 844-4](https://dev.ec-earth.org/issues/844#note-4) the AerChemMIP tier2 &3 experiments have been uploaded now in the ec-earth repository in the `r7850-control-output-files` branch (see the [overview).](https://svn.ec-earth.org/ecearth3/branches/development/2020/r7850-control-output-files/runtime/classic/ctrl/cmip6-output-control-files/AerChemMIP/)
