### ISSUE TITLE
Change sign evspsbl

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#632]
Issue #57 has been reporting this before.

The cmor-fixer will be able to handle this for already cmorised data.

The point with changing this in `ece2cmor3` itself is that if this will be implemented in `ece2cmor3` itself, by for instance adding a convert rule, that this will be a problem as soon the CMOR table will complement their:
```
"positive": ""
```
with value "up" instead of leaving it empty like now. Because `ece2cmor3` applies a `flip_sign` in that case.
```
        flip_sign = (getattr(task.target, "positive", None) == "up")
```
Moreover `evspsbl` has already a convert in the `ifspar.json`:
```
"convert": "vol2flux"
```
so a variant including the factor -1 needs to be added. (Don't think it is easy to specify two convert rules for one variable in the `ifspar.json`?).

**Comment by treerink** [comment]
Actually in this case the handiest approach would be to add some changes on top of the nested CMOR table files. Usually this is absolutely a no-go route, but in this case it would be anticipating on a correction in the tables. The change would be for the `evspsbl` variable:
```
"positive": "up"
```
See also [ec-earth portal issue 768-18](https://dev.ec-earth.org/issues/768#note-18) because this will apply as well to:
```
evspsbl
evspsblpot
evspsblsoi
evspsblveg
```
in the files:
```
CMIP6_Amon.json
CMIP6_CF3hr.json
CMIP6_CFsubhr.json  # Not relevant for us
CMIP6_Eday.json
CMIP6_Emon.json
CMIP6_Lmon.json
```
Anyway I have to figure out whether this is a maintainable solution.

**Comment by treerink** [comment]
Checked the latest CMOR tables: the `"positive": ""` is still empty.

**Comment by klauswyser** [comment]
That's no surprise and probably will not change in the future. The description of evspsbl clearly says ``...flux of water into the atmosphere...`` which - at least for me - makes it intuitively clear that the flux is from the ground to the atmosphere which means positive upward.

**Comment by treerink** [comment]
If we make an issue...

**Comment by goord** [comment]
Hi Thomas the easiest fix is to add expressions for these variables, flipping the sign during post-processing.

**Comment by treerink** [comment]
Hi Gijs, I understand, but then, if later on the tables are adjusted and the "up" is added then the sign will flip again unintended because of `flip_sign`. An escape could be to add a check for these variables, and sent a ERROR message when we detect for these variables that they obtained `"positive": "up"` (due to a table update), such that we will be quickly informed.

**Comment by goord** [comment]
Aha ok, then there is a better solution: we add a minus sign in the expression, and then we change the code on line 517 of ifs2cmor.py:
```python
var_id = cmor.variable(table_entry=str(task.target.variable), units=str(unit), axis_ids=axes, positive="down")
```
to 
```python
var_id = cmor.variable(table_entry=str(task.target.variable), units=str(unit), axis_ids=axes, positive="up" if task.target.variable.startswith("evspsbl") else "down")
```
This code basically says: all our fluxes are oriented downward except the evapotranspiration, and the cmor library will automatically correctly flip the sign if the variable gets an orientation in the table

**Comment by goord** [comment]
If we add a new 'convert' option, say ```vol2fluxup``` and absorb the minus sign there, the above may be written less hacky as follows:
```python
var_id = cmor.variable(table_entry=str(task.target.variable), 
                                    units=str(unit), 
                                    axis_ids=axes, 
                                    positive="up" if getattr(task, cmor_task.conversion_key, None) == "vol2fluxup" else "down")
```

**Comment by treerink** [comment]
Following @goord's suggestion a fix for this is committed in the `fix-sign-evspsbl` branch. 

Note that the sign flip will be applied as well to the variable [sblIs](http://clipc-services.ceda.ac.uk/dreq/u/53825806-bf01-11e6-a554-ac72891c3257.html), which I think is correct and happens at the same place in the `ifspar.json` because both `sblIs` & `evspsbl` are in the same block.

With further inspection the variables:
```
evspsblpot
evspsblsoi
evspsblveg
```
are not part of the `ifspar.json` they are only present in the lpjgpar.json (and I assume that the sign of these variables is correct in the LPJ-GUESS output).

The `fix-sign-evspsbl` branch will be tested now.

**Comment by treerink** [comment]
The `fix-sign-evspsbl` branch has been merged after a successful test.
