### ISSUE TITLE
Decide about final lpjg ingrid version

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#633]
In addition to #630 a last thing has to be decided:

Preferably I would like to use python3 for the `create_cdo_ingrid_for_lpjgout.py` script. This in order to prevent changes in a later stage. For some reason the produced ingrid files are not identical with python3 compared to the current results with python2. It looks like they differ in precision, but due to the format of the file it was not so easy fully check this. In any case, also if it only concerns precision, it has to become clear that the changes are ok.

**Comment by etiennesky** [comment]
forcing python3 has many implications, although I understand this has only to be done once in a while?

**Comment by treerink** [comment]
> forcing python3 has many implications, although I understand this has only to be done once in a while?

This concerns only this short `create_cdo_ingrid_for_lpjgout.py` script for now (not `ece2cmo3` itself).

**Comment by etiennesky** [comment]
then I would advocate that you should limit it to python3 only to make sure results are always the same - plus we should migrate to python3 sometime

**Comment by treerink** [comment]
> then I would advocate that you should limit it to python3 only to make sure results are always the same

Sure, that's the plan, but we have to make sure the results with python3 are correct. Scheduled for tomorrow.

**Comment by treerink** [comment]
Hi Lars,

I added a branch with the updated ingrid files, so you can check them and the cmorisation with them without having to install any python3 netcdf stuff. The new files have been produced by using python3 from a miniconda3 environment.

Just enter your latest updated ece2cmor3 master environment and do:
```
git pull
git checkout lpjg-ingrid-python3-version
```
and inspect the ingrid files, cmorise and inspect those results. I expect only precision differences. 

Note: you don't need to run `create_cdo_ingrid_for_lpjgout.py`.

**Comment by treerink** [comment]
The new ingrid_T* files have been tested and merged in the master. They are now based on running the `create_cdo_ingrid_for_lpjgout.py` script with python3 from a miniconda3 environment. Cmorised lpjg results only differ on their last digit.

Closing this issue.
