### ISSUE TITLE
something wrong in modify-metadata-template.sh

### ISSUE THREAD

**Issue by jenzh** [EC-Earth/ece2cmor3#642]
Hi,
I have updated the new version, but I noticed that T159L91 for LPJG column in modify-metadata-template.sh script on line 72.

**Comment by treerink** [comment]
It should be T159L62 ?

**Comment by treerink** [comment]
Ok yes I see, it is 'as atmos.' and because the 'atmos' resolution has been just adjusted, I should have adjusted this as well. Thanks for spotting this!

**Comment by treerink** [comment]
related to #641

**Comment by treerink** [comment]
Done. The updates metadata template files will be part of an updated version of the control output files in the ec-earth repository in the `r7877-control-output-files` branch.
