### ISSUE TITLE
How to handle cmorization of ECE3-Veg v3.3.1.1 output?

### ISSUE THREAD

**Issue by nierad** [EC-Earth/ece2cmor3#654]
Hi all, 

technically, everything is ready to go w.r.t. the upload to ESGF of the global-deforestation run data. But there remains a question:

I used ece2cmor3 v1.2 to cmorize this run because of the non-downward-incompatibility issue in v1.3 item 9 (https://github.com/EC-Earth/ece2cmor3/tree/v1.3.0; ua100, va100, #496). 
But, of course, there have been other fixes in later versions, that aren't taken care of. 
My question is: 
Re-cmorize with the latest version and add an erratum for the ?a100 or use current cmorized data and add notifications about issues that came up in succeeding versions? 
This data has already been used in publications, so major changes would probably not be so great...

**Comment by treerink** [comment]
Hi Lars,

Would it be an idea to keep the `?a100` files from your `ece2cmor3` `v1.2` cmorisation and to redo the rest of the cmorisation with `v1.5` (taking out `?a100` from your json data request file)? And then to move the `?a100` `v1.2` in between the other `v1.5` variables?

**Comment by nierad** [comment]
Thanks, Thomas. 
I just actually checked the data-request and it turns out, ua100 and va100 aren't even requested for these experiments... 
I feel a bit silly now, but at that time, when reading the old emails, it looked like you'd go with 1.2 for ECE < 3.3.2 and v1.3 else. 
So, sorry for the hassle! I'll redo it with the latest (v1.5).
