### ISSUE TITLE
Amon surface pressure is not processed in AerChemMIP experiments

### ISSUE THREAD

**Issue by plesager** [EC-Earth/ece2cmor3#655]
Amon/ps on IFS grid has been missing in all my 15 AerChemMIP experiments, despite being requested. For most of these experiments, I am able to compute the monthly ps from either daily or 3hr output where I found the surface pressure. But in 3 experiments (piClim) without daily or sub-daily output, I need a new strategy. I will try and add CFday/ps to the data request as a quick fix.

Despite these workarounds, something is not working as expected. I first thought the problem was with the priority wrongly given to TM5 when AERmon/ps is also requested. But removing the latter from the data request, Amon/ps is still missing. 
I am using the PEXTRA control output directories, not sure if that makes a difference though.

**Comment by plesager** [comment]
@tommibergman @Declan-FMI @noije
To summarize: `IFS/Amon/ps` is missing, and keeping or removing `TM5/AERmon/ps` does not fix it.

**Comment by treerink** [comment]
I confirm for a one-case check that indeed `ps` is asked in the basic data request. I checked this one:
```
cmip6-data-request/cmip6-data-request-m=AerChemMIP.CMIP.RFMIP-e=historical-t=1-p=1/cmvme_ae.cm.rf_historical_1_1.xlsx
```

**Comment by goord** [comment]
Philippe does ifs2cmor say something in the log file about ps in Amon?

**Comment by plesager** [comment]
Got that from the log:
```
    107:2020-09-14 03:43:39 INFO:ece2cmor3.postproc: Post-processing target ps in table Amon from file /lustre3/projects/CMIP6/sager/temp-cmor-dir/pic1/ifs/007/pic1-ifs-1856/134.128.1.3 with cdo command -setgridtype,regular -monmean -selcode,134
```
Nothing else, besides the usual:
```
    106:2020-09-14 03:43:39 ERROR:ece2cmor3.postproc: Unsupported combination of frequency monC with time operators ['mean within years', 'mean over years'] encountered for variable sp in table Amon
```

**Comment by plesager** [comment]
Just came across this. Cannot tell if this is the same issue. With a simple (only IFS variables) data request like this:
```
{
    "ifs": {
        "6hrLev": [
            "ta",
            "ua",
            "va",
            "hus",
            "ps"
        ]
    },
    "lpjg": {},
    "nemo": {},
    "tm5": {}
}
```
`ps` is also missing. I only get:
```
cca-login4 /scratch/ms/nl/nm6/cmorised-results/.../r1i1p1f1/6hrLev 
[6717] >>> tree
 .
 |-|hus
 |-|--|gr
 |-|--|--|v20200911
 |-|ta
 |-|--|gr
 |-|--|--|v20200911
 |-|ua
 |-|--|gr
 |-|--|--|v20200911
 |-|va
 |-|--|gr
 |-|--|--|v20200911

cca-login4 /scratch/ms/
```

**Comment by goord** [comment]
It probably has to do with the fact that the 3D variables need surface pressure as well for cmorization to define the hybrid model levels. This interferes somewhere with the Amon ps task, I will have a look at it tomorrow.

**Comment by plesager** [comment]
Indeed SP is in these datasets as an additional variable, but no on its own. Which gives me another workaround to get Amon/ps.

**Comment by treerink** [comment]
@plesager can you check whether with the latest master version `ps` is now added as independent cmorised output as well in your AerChemMIP case? For the cordex model-level output this is the case now. If all is fine now, you can close this issue.

**Comment by plesager** [comment]
I checked that this is working as expected with the `pextra/CMIP/AerChemMIP/amip`.
