### ISSUE TITLE
"ScenarioMIP" will be replaced with value "ScenarioMIP AerChemMIP"

### ISSUE THREAD

**Issue by pnolan22** [EC-Earth/ece2cmor3#656]
Hi. 

I receive the below warning when cmorising EC-EARTH-Veg ssp370 data. Other SSPs don't give this warning.

Does this warning look normal? Any feedback would be appreciated.

Thanks.

^[[2;34;47mC Traceback:
In function: _CV_checkExperiment
! called from: cmor_setGblAttr
! called from: cmor_write
! ^[[0m

^[[1;34;47m!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Warning: Your input attribute "activity_id" with value
! "ScenarioMIP" will be replaced with value "ScenarioMIP AerChemMIP"
! as defined for experiment_id "ssp370".
!
!  See Control Vocabulary JSON file.(/ichec/work/ichec002/2020_Anaconda/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-1.5.0-py2.7.egg/ece2cmor3/resources/tables/CMIP6_CV.j\
son)
!
!
!!!!!!!!!!!!!!!!!!!!!!!!!^[[0m

! ------
! CMOR is now closed.
! ------
! During execution we encountered:
!   1 Warning(s)
!   0 Error(s)
! ------
! Please review them.
! ------
!

**Comment by klauswyser** [comment]
That's allright, it's not a bug but a feature! SSP3-7.0 is used not only in ScenarioMIP but also in AerChemMIP, therefore both activities are set in the activity_id.

**Comment by pnolan22** [comment]
Thank you Klaus!
