### ISSUE TITLE
Error in CMIP6 data request for RFMIP-rad-irf?

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#661]
No `ppt` files are found in the `cmip6-output-control-files/RFMIP/cmip6-experiment-RFMIP-rad-irf/` directory. This is due to the CMIP6 data request of RFMIP-rad-irf (I checked the xlsx file) which is empty (only four fx variables), and which is reflected in the json data requests being totally empty.
```
cmip6-output-control-files/RFMIP/cmip6-experiment-RFMIP-rad-irf/cmip6-data-request-varlist-RFMIP-rad-irf-EC-EARTH-A*
```

When `genecec` tries to run:
```
./drq2ppt.py --drq cmip6-data-request/cmip6-data-request-m=OMIP-e=omip1-t=1-p=1/cmvme_OMIP_omip1_1_1.xlsx
```
with an empty `ifs` list,  it crashes. Also no variable in the file_def file is set to `true`, because also the nemo list is empty.

When looking into the RFMIP-CMIP joined data request file (the xlsx):
```
cmip6-data-request-m=RFMIP-e=rad-irf-t=1-p=1/cmvme_cm.rf_rad-irf_1_1.xlsx
```
then this one is not empty.

So it seems to go wrong with the data request with:
```
drq -m RFMIP -e rad-irf -t 1 -p 1 --xls --xlsDir cmip6-data-request-m=RFMIP-e=rad-irf-t=1-p=1
```
So it seems there is an error in the CMIP6 data request for RFMIP-rad-irf?

The error part is:
```
Running drq2ppt.py with:
 ./drq2ppt.py --drq cmip6-data-request/cmip6-data-request-m=RFMIP-e=rad-irf-t=1-p=1/cmvme_RFMIP_rad-irf_1_1.xlsx

Traceback (most recent call last):
  File "./drq2ppt.py", line 327, in <module>
    main()
  File "./drq2ppt.py", line 320, in main
    write_ppt_files(ece2cmorlib.tasks)
  File "./drq2ppt.py", line 113, in write_ppt_files
    min_freq = max(freqgroups.keys())
ValueError: max() arg is an empty sequence
mv: cannot stat 'ppt0000000000': No such file or directory
mv: cannot stat 'pptdddddd*': No such file or directory
```

**Comment by noije** [comment]
All I know is that the "rad-irf" label is associated with the RFMIP-IRF part of RFMIP, which the EC-Earth consortium isn't contributing to.

**Comment by treerink** [comment]
Like in #660 also skipping the call to `drq2ppt` for this `rad-irf`experiment and giving a message.

Done
