### ISSUE TITLE
Extra variables in AerChemMIP output

### ISSUE THREAD

**Issue by plesager** [EC-Earth/ece2cmor3#665]
Variables other than the one the file is named after (and not known by CDNOT as to be ignored) are present in the AerChemMIP output. The extraneous variables are: `ap`, `ap_bnds`, `ps`, and `wavelength`. Below is a table (non exhaustive!) summarizing affected output. Note that `gn` are produced by TM5, and `gr` are produced by IFS. The `wavelength` is simply a TM5 by-product and should be removed since it is redundant. The other three go together and define the pressure levels, and they are added by:
- either TM5 or ece2cmor3 in the TM5 output,
- ece2cmor3 in the IFS output.

There is definitively an issue with the handling of `ps` in ece2cmor3 with the AerChem configuration (see also #655). 

```
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                        ps  ap  ap_bnds  wavelength 
────────────────────────────────────────────────────
 AERmon/airmass/gn      x   x   x                   
 AERmon/c2h6/gn         x   x   x                   
 AERmon/c3h6/gn         x   x   x                   
 AERmon/c3h8/gn         x   x   x                   
 AERmon/cdnc/gr         x   x   x                   
 AERmon/ch3coch3/gn     x   x   x                   
 AERmon/ch4/gn          x   x   x                   
 AERmon/cheaqpso4/gn    x   x   x                   
 AERmon/chegpso4/gn     x   x   x                   
 AERmon/co/gn           x   x   x                   
 AERmon/dms/gn          x   x   x                   
 AERmon/emilnox/gn      x   x   x                   
 AERmon/hcho/gn         x   x   x                   
 AERmon/hno3/gn         x   x   x                   
 AERmon/isop/gn         x   x   x                   
 AERmon/jno2/gn         x   x   x                   
 AERmon/lossch4/gn      x   x   x                   
 AERmon/lossco/gn       x   x   x                   
 AERmon/mmraerh2o/gn    x   x   x                   
 AERmon/mmrbc/gn        x   x   x                   
 AERmon/mmrdust/gn      x   x   x                   
 AERmon/mmrnh4/gn       x   x   x                   
 AERmon/mmrno3/gn       x   x   x                   
 AERmon/mmroa/gn        x   x   x                   
 AERmon/mmrso4/gn       x   x   x                   
 AERmon/mmrsoa/gn       x   x   x                   
 AERmon/mmrss/gn        x   x   x                   
 AERmon/no2/gn          x   x   x                   
 AERmon/no/gn           x   x   x                   
 AERmon/o3/gn           x   x   x                   
 AERmon/o3loss/gn       x   x   x                   
 AERmon/o3prod/gn       x   x   x                   
 AERmon/o3ste/gn        x   x   x                   
 AERmon/oh/gn           x   x   x                   
 AERmon/pan/gn          x   x   x                   
 AERmon/phalf/gn        x   x                       
 AERmon/so2/gn          x   x   x                   
────────────────────────────────────────────────────
 AERmon/ua/gr           x   x   x                   
 AERmon/va/gr           x   x   x                   
 AERmon/wa/gr           x   x   x                   
 AERmon/zg/gr           x   x   x                   
 Amon/cl/gr             x   x   x                   
 Amon/cli/gr            x   x   x                   
 Amon/clw/gr            x   x   x                   
 CFmon/hur/gr           x   x   x                   
 CFmon/hus/gr           x   x   x                   
 CFmon/ta/gr            x   x   x                   
────────────────────────────────────────────────────
 AERday/od550aer/gn                      x          
 AERmon/abs550aer/gn                     x          
 AERmon/od550aer/gn                      x          
 AERmon/od550aerh2o/gn                   x          
 AERmon/od550bc/gn                       x          
 AERmon/od550dust/gn                     x          
 AERmon/od550lt1aer/gn                   x          
 AERmon/od550no3/gn                      x          
 AERmon/od550oa/gn                       x          
 AERmon/od550so4/gn                      x          
 AERmon/od550soa/gn                      x          
 AERmon/od550ss/gn                       x          
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```

**Comment by plesager** [comment]
The first and most urgent step is to decide if we need to keep these extraneous variables in the cmorized data.

**Comment by noije** [comment]
I don't think I fully understand what the problem is. As Tommi said 3-D fields need vertical grid information specified by ps, ap, ap_bnds, bp, and bp_bnds.

Why does it complain about ap and ap_bnds, but not bp and bp_bnds?

For the list of "od550" variables the data request says: Needs a comment attribute "wavelength: 550nm". So, in my understanding this should be a comment rather than a dimension. But correct me if I am wrong.

**Comment by tommibergman** [comment]
Actually, The optical variables’ dimensions in data request include also lambda550, which, if I recall correctly, is translated to wavelength by cmor library.

**Comment by noije** [comment]
So, what is the problem then? Do we know how to proceed?

**Comment by plesager** [comment]
So we have a mismatch between `ece2cmor3` output and what is expected from the ESGF (CDNOT) as checked by NSC. Although it may be possible to add the problematic variables to "the official CDNOT list of variables to ignore if present in the file", I think it is better to try and understand how we got here in the first place.

**Comment by plesager** [comment]
About the pressure terms. The information is definitively needed for output on model levels, and we provide:
- ap
- b
- ps
- ap_bnds
- b_bnds

Since `b` and `b_bnds` are fine, and `ap` and `ap_bnds` are not, I first suspected incorrect naming and bet they should be called `a`
and `a_bnds`. So I checked an already published file from another model. Its content lists:
- a
- b
- p0
- ps
- a_bnds
- b_bnds

So I check the [data request site,](http://clipc-services.ceda.ac.uk/dreq/u/atmosphere_hybrid_sigma_pressure_coordinate.html) which tells us to go see ["Appendix D of the CF convention"](https://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#_atmosphere_hybrid_sigma_pressure_coordinate).  We are using the second formulation from that page, `ap` and `ap_bnds` are the correct variable names and we should tell CDNOT about it. No need for renaming and fixing attributes.

As for `ps`, I am puzzled that files from other models have been published with that extraneous variable but ours are rejected. Can it be a false positive in the checker used by NSC?

**Comment by plesager** [comment]
About the wavelength. I've downloaded a published file from the NorESM2 model (od550ss_AERmon_NorESM2-LM_piClim-aer_r1i1p1f1_gn_000101-001012.nc), and got the exact same variable names and attributes as our `od550ss` files:

```
double wavelength ;
        wavelength:units = "nm" ;
        wavelength:long_name = "Radiation Wavelength 550 nanometers" ;
        wavelength:standard_name = "radiation_wavelength" ;
float od550ss(time, lat, lon) ;
        od550ss:standard_name = "atmosphere_optical_thickness_due_to_sea_salt_ambient_aerosol_particles" ;
        od550ss:long_name = "Sea-Salt Aerosol Optical Depth at 550nm" ;
        od550ss:comment = "Total aerosol AOD due to sea salt aerosol at a wavelength of 550 nanometres." ;
        od550ss:units = "1" ;
        od550ss:original_name = "D550_SS" ;
        od550ss:cell_methods = "area: time: mean" ;
        od550ss:cell_measures = "area: areacella" ;
        od550ss:history = "...." ;
        od550ss:coordinates = "wavelength" ;
        od550ss:missing_value = 1.e+20f ;
        od550ss:_FillValue = 1.e+20f ;
``` 
There is a comment attribute being more specific than (but including) the recommended "wavelength: 550 nm".
Why has this file been published and ours cannot? Looks like similar to the `ps` case in the post above.

**Comment by plesager** [comment]
> Actually, The optical variables’ dimensions in data request include also lambda550, which, if I recall correctly, is translated to wavelength by cmor library.

Yes, it all makes sense. I think our datasets are fine, and the checker used by NSC is not working as it should. If everybody agrees I will ask to publish our data as they are.

**Comment by noije** [comment]
Yes, please do so.

**Comment by pchengi** [comment]
> About the pressure terms. The information is definitively needed for output on model levels, and we provide:
> 
> * ap
> * b
> * ps
> * ap_bnds
> * b_bnds
> 
> Since `b` and `b_bnds` are fine, and `ap` and `ap_bnds` are not, I first suspected incorrect naming and bet they should be called `a`
> and `a_bnds`. So I checked an already published file from another model. Its content lists:
> 
> * a
> * b
> * p0
> * ps
> * a_bnds
> * b_bnds
> 
> So I check the [data request site,](http://clipc-services.ceda.ac.uk/dreq/u/atmosphere_hybrid_sigma_pressure_coordinate.html) which tells us to go see ["Appendix D of the CF convention"](https://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#_atmosphere_hybrid_sigma_pressure_coordinate). We are using the second formulation from that page, `ap` and `ap_bnds` are the correct variable names and we should tell CDNOT about it. No need for renaming and fixing attributes.
> 
> As for `ps`, I am puzzled that files from other models have been published with that extraneous variable but ours are rejected. Can it be a false positive in the checker used by NSC?
It's actually not a false positive. The checker does not complain about a, b, a_bnds, and b_bnds because they are already present in the official excludes list. I'm attaching the official list of the excluded variables for your reference. 
[excl_cmip6.txt](https://github.com/EC-Earth/ece2cmor3/files/5458276/excl_cmip6.txt)

**Comment by pchengi** [comment]
I'm not sure if the inline reply above is clear enough; I've attached the list of excluded variables for your reference.

**Comment by pchengi** [comment]
A bit of background about the problem; the ESGF publication system counts each variable as a file, and all auxiliary variables present in the netcdf files are excluded. If this is not done, ESGF would misreport the number of published datasets in a manner that causes confusion. My check script ensures that this doesn't happen, by checking all of the variables that appear in an ncdump -h output, and everything other than the variable itself after the file is named ought to be present in the official excludes list. If the presence of the variables is not an issue itself, than I recommend that I contact CDNOT for the inclusion of these additional variables into the list before proceeding with the publication.  Could you let me know sites which have published these datasets as-is? I can check and let you know how things stand with them.

**Comment by plesager** [comment]
Thanks for providing the excluded variables list. Yes, CDNOT should be contacted to include  `ap`, `ap_bnds`, `ps`, and `wavelength`.

The files I checked yesterday are:
- od550ss_AERmon_NorESM2-LM_piClim-aer_r1i1p1f1_gn_000101-001012.nc, which shows the `wavelength` variable, and was published by the NCC (noresm-ncc@met.no)
- airmass_AERmon_CESM2-WACCM_ssp370SST-lowNTCF_r1i1p1f1_gn_201501-205512.nc, which includes `ps`, and is published by NCAR (cesm_cmip6@ucar.edu)

**Comment by pchengi** [comment]
The variables have been added to the official exclude_variable list now. Will proceed with data publication now!

**Comment by plesager** [comment]
Perfect. Thanks.
