### ISSUE TITLE
Update the nested CMOR tables for their updates: adding the CovidMIP experiments

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#666]
In #663 we manually added the CovidMIP experiments in the CMOR tables. However, the tables have been updated now and include the CovidMIP experiments. 

However as many of us are in the middle of the production of the CovidMIP results AND because updating the CMOR tables can not be done in a branch (if one does, the master will see the update as well, this is due to the nested CMOR table repository), I am hesitating to push this update.

I will first hold at a local commit and investigate whether all changes in our EC-Earth version and those in the CMOR tables match.

**Comment by klauswyser** [comment]
As long as EC-Earth3 is not participating in DAMIP we cannot publish the data anyway. I have asked Shuting to take the necessary steps for adding EC-Earth3 to DAMIP, this will then make another update of the tables necessary.

**Comment by treerink** [comment]
I have checked the CMOR table CovidMIP changes with our own added insertions for all of the CovidMIP experiments in which the EC-Earth consortium participates and fortunately they are 'bitwise' identical. So in principle this makes updating / replacing easy.

However, as they are identical, for the metadata this will be all the same. I though there is a CMOR table version in the metadata, but I a not sure, I see attributes like (and some are just our own specific attributes):
```
// global attributes:
		:Conventions = "CF-1.7 CMIP-6.2" ;
		:data_specs_version = "01.00.32" ;
		:ece2cmor_git_revision = "662efe555a3d7c86b3dc7e38269837d8e36fe38f-changes" ;
		:further_info_url = "https://furtherinfo.es-doc.org/CMIP6.EC-Earth-Consortium.EC-Earth3.ssp245-covid.none.r7i1p1f2" ;
			"processed by ece2cmor v1.5.0, git rev. 662efe555a3d7c86b3dc7e38269837d8e36fe38f-changes\n",
			"" ;
		:latest_applied_cmor_fixer_version = "None" ;
		:latest_ece2cmor_version = "v1.5.0" ;
		:table_info = "Creation Date:(28 May 2020) MD5:9d83976c4367ce4eb0fc4f73ad7d85ec" ;
		:cmor_version = "3.5.0" ;
}
```

Maybe we are fine as it is now, and it doesn't matter too much which data request version and which CMOR table version.

**Comment by klauswyser** [comment]
I am not sure if there is or will be a new data request for the CovidMIP experiments as it was always said "use the same data request as for ScenarioMIP ssp245." But the CMOR table version should be updated of course, I guess that's attribute ``table_info``, or?

**Comment by treerink** [comment]
> I am not sure if there is or will be a new data request for the CovidMIP experiments as it was always said "use the same data request as for ScenarioMIP ssp245." But the CMOR table version should be updated of course, I guess that's attribute `table_info`, or?

I think so, but I am not 1000% sure, and I am just not sure if when this `table_info` somehow not fully matches if this leads to trouble with these ESGF checks, maybe not and then we are making life unnecessary complicated. By the way if it is only this `table_info` we could pick it from the update later and in a late phase just before publishing change it with `cmor-fixer.`

**Comment by treerink** [comment]
They are updated but please note ec-earth portal post [847-194](https://dev.ec-earth.org/issues/847#note-194).

**Comment by treerink** [comment]
With the new release of the data request 01.00.33 (see #668), I expect another update of the CMOR tables. Currently their headers  say that they are still based on 01.00.32. Usually it takes a bit of time before the CMOR tables are updated for the latest data request version, so waiting for that.

**Comment by treerink** [comment]
The latest CMOR tables are now compatible with data request 01.00.33 according to their headers. In edfae8c I have updated our nested CMOR tables which allows to make the change to `drq`  `01.00.33` in #668.

**Comment by treerink** [comment]
Alternatively, because #668 is solved, the production of the CovidMIP control output directories and the cmorisation of the CovidMIP experiments, can be done now as well with the current latest master, i.e. without running the `./add-covidMIP-experiments.sh` script when using the updated CMOR tables. In case one decides to uses the latest CMOR tables but one has applied the  `./add-covidMIP-experiments.sh` script before, it is necessary to revert those changes first in the nested CMOR table by going into that directory and reverting all changed files. Thereafter one can follow the updates by the known:
```
git submodule update --init --recursive
```

With that, I am closing again this issue.

In #673 the production of the CovidMIP control output files will be made part of the general `genecec` script.
