### ISSUE TITLE
Add the requested fx variables to the cmorisation

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#667]
The `fx` variables are not present in the normal json data request files. They are already excepted at the level of `drq2ppt`. We want to change this, such all goes mainstream.

**Comment by treerink** [comment]
The changes in the control output files have been committed in the ec-earth repository in the `r8018-control-output-files` branch (see poral issue [895-35](https://dev.ec-earth.org/issues/895#note-35)).

**Comment by klauswyser** [comment]
Sorry for asking, it's not clear to me what the status of the fx variables ``stflf``, ``orog`` and ``areacell`` is. We have saved GRIB parameters in our ICMGG*000000 files, can we process these variables somehow with ece2cmor3? Or was this issue just about adding the variables to the data request? Thanks for clarifying.

NB: no group except BSC has published ``orog`` or ``areacell`` so far. And BSC has published ``orog`` as part of the Emon table in the DCPP experiments, not fx.

**Comment by treerink** [comment]
Hi Klaus, 

Including these `fx` variables into the EC-Earth3 output, including them on the varlists and implementing their cmorisation is ready if you would use the latest `ece2cmor3` master branch AND the latest `r8018-control-output-files` branch (see also [portal issue 895-35](https://dev.ec-earth.org/issues/895#note-36)). The goal is to merge this branch in few weeks from now into the trunk and to make an `ece2cmor3` release `v1.8.0`, which will include this item. It would be nice if we (SMHI & KNMI) would also try to finalise #676 before that release.
