### ISSUE TITLE
Impossible to CMORize msftyz and hfbasin from ORCA025 (that is EC-Earth3-HR)

### ISSUE THREAD

**Issue by krumit** [EC-Earth/ece2cmor3#669]
Hi!

I am trying to cmorize the output of the EC-Earth3-HR decadal hindcasts that we have produced at SMHI.
Now I am facing problems regarding the NEMO-output (CMORization of IFS works fine), that means data produced on the ORCA025L75-grid.

I used output-control-files/DCPP/cmip6-experiment-DCPP-dcppA-hindcast/cmip6-data-request-varlist-DCPP-dcppA-hindcast-EC-EARTH-AOGCM.json (with minor modifications).
I see that there is also a cmip6-data-request-varlist-DCPP-dcppA-hindcast-EC-EARTH-HR.json but that is identical to the former.

I am using ece2cmor v1.5.0 (commit 1f4a860be0a488bfec8abada2e1c984a03a1dbbc )

The error messages shown in the .cmor.log-file looks like this:

```
C Traceback:
! In function: cmor_check_monotonic
! called from: cmor_treat_axis_values
! called from: cmor_axis
! 

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: axis latitude (table: Omon) has non monotonic values:
! 89.707733, 89.725159 and  89.707733
!
!!!!!!!!!!!!!!!!!!!!!!!!!


C Traceback:
! In function: cmor_check_monotonic
! called from: cmor_treat_axis_values
! called from: cmor_axis
! 

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: axis latitude (table: Omon) has non monotonic
! bounds values : 89.684120, 89.716446, 89.699020
!
!!!!!!!!!!!!!!!!!!!!!!!!!


C Traceback:
! In function: cmor_check_monotonic
! called from: cmor_treat_axis_values
! called from: cmor_axis
! 

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: axis latitude (table: Omon) has overlapping bounds values:
! 89.716446, 89.699020, 89.716446 at index: 2097
!
!!!!!!!!!!!!!!!!!!!!!!!!!


C Traceback:
In function: cmor_check_monotonic
! called from: cmor_treat_axis_values
! called from: cmor_axis
! 

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Warning: axis latitude (table: Omon) has bounds values that leave gaps
! (index 2096): 89.716446, 89.716446, 89.699020
!
!!!!!!!!!!!!!!!!!!!!!!!!!


C Traceback:
! In function: cmor_check_values_inside_bounds
! called from: cmor_axis
! 

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: axis latitude has values not within bounds at indice:
! 1048: 89.725159 not within: 89.716446, 89.716446
!
!!!!!!!!!!!!!!!!!!!!!!!!!
```

I did some testing and found out that just specific variables are causing this. In my case it was as long as I tried to CMORize `msftyz` or `hfbasin`.
The above error messages are actually related to the CMORization of `hfbasin` where I can see according to the ece2cmor-logfile (just the last couple of lines):

```
2020-11-11 15:15:40 INFO:ece2cmor3.nemo2cmor: Creating NEMO grids in CMOR...
2020-11-11 15:15:41 DEBUG:urllib3.connectionpool: Starting new HTTPS connection (1): b2share.eudat.eu:443
2020-11-11 15:15:42 DEBUG:urllib3.connectionpool: https://b2share.eudat.eu:443 "GET /api/records/3ad7d5c5f1ab419297c1e02bded8d70f HTTP/1.1" 200 4860
2020-11-11 15:15:42 INFO:ece2cmor3.__load_nemo_vertices__: Downloading file nemo-vertices-ORCA025-t-grid.nc from b2share archive...
2020-11-11 15:15:42 DEBUG:urllib3.connectionpool: Starting new HTTPS connection (1): b2share.eudat.eu:443
2020-11-11 15:15:42 DEBUG:urllib3.connectionpool: https://b2share.eudat.eu:443 "GET /api/files/b700db5f-ced1-4e4d-996a-fd6fa199b22b/nemo-vertices-ORCA025-t-grid.nc HTTP/1.1" 200 48467281
2020-11-11 15:15:44 INFO:ece2cmor3.__load_nemo_vertices__: ...success, file /nobackup/rossby24/users/sm_timkr/miniconda2/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-1.5.0-py2.7.egg/
ece2cmor3/resources/nemo-vertices/nemo-vertices-ORCA025-t-grid.nc created
2020-11-11 15:15:44 INFO:ece2cmor3.nemo2cmor: Using fallback to the old midpoint calculation method for grid (1050, 1) with shape opa_grid_ptr_T_3basin_2D
```

When I eliminate `hfbasin` from the list, it also fails, now when trying to CMORize `msftyz`. The cmor.log-file looks almost identical to the first case but all instances of `latitude` are now `gridlatitude`.
The last couple of lines in the ece2cmor-logfile look like this:

```
2020-11-12 10:50:16 INFO:ece2cmor3.nemo2cmor: Creating NEMO grids in CMOR...
2020-11-12 10:50:19 INFO:ece2cmor3.nemo2cmor: Using fallback to the old midpoint calculation method for grid (1050, 1442) with shape opa_zoom_2000_sum
2020-11-12 10:50:26 INFO:ece2cmor3.nemo2cmor: Using fallback to the old midpoint calculation method for grid (1050, 1442) with shape opa_vert_sum
2020-11-12 10:50:28 INFO:ece2cmor3.nemo2cmor: Using fallback to the old midpoint calculation method for grid (1050, 1442) with shape opa_zoom_300_sum
2020-11-12 10:50:28 INFO:ece2cmor3.nemo2cmor: Using fallback to the old midpoint calculation method for grid (1050, 1) with shape opa_grid_ptr_W_3basin_3D
```

So it seems as if ece2cmor crashes whenever one of the 3basin-grids is used.
When I eliminate both `hfbasin` and `msftyz`, CMORization of all remaining NEMO-variables (all 2D lon x lat or 3D lon x lat x depth) obviously works fine.

Am I missing something or is this a bug in ece2cmor affecting ORCA025 and therefore EC-Earth3-HR.

Thanks for having a look into this, best,

Tim

**Comment by pabretonniere** [comment]
I confirm I have the same issue with msftyz for ORCA025.

**Comment by goord** [comment]
First of all, it seems as if the log message confuses the grid name and its shape...

For debugging it would be useful if you can post the output directory of a single NEMO-leg, because the file names contain the grid identifications. It may be that we are missing some vertex bound definitions files on the b2share data store...

**Comment by krumit** [comment]
There you go, the content of a single-leg output directory:
```
f900_1m_19910101_19911231_lim_grid_T_2D.nc
f900_1m_19910101_19911231_opa_grid_T_2D.nc
f900_1m_19910101_19911231_opa_grid_T_3D.nc
f900_1m_19910101_19911231_opa_grid_U_2D.nc
f900_1m_19910101_19911231_opa_grid_V_2D.nc
f900_1m_19910101_19911231_opa_grid_ptr_T_3basin_2D.nc
f900_1m_19910101_19911231_opa_grid_ptr_W_3basin_3D.nc
f900_1m_19910101_19911231_opa_vert_sum.nc
f900_1m_19910101_19911231_opa_zoom_2000_sum.nc
f900_1m_19910101_19911231_opa_zoom_300_sum.nc
f900_1m_19910101_19911231_opa_zoom_700_sum.nc
f900_1y_19910101_19911231_opa_grid_T_2D.nc
```
Thank you for digging into this!

**Comment by goord** [comment]
@treerink can you elaborate on what these vert_sum and zoom_sum files are supposed to contain? The grids seem to be the ordinary T-grid...

**Comment by goord** [comment]
@krumit and @pabretonniere can you confirm that the grid in `*_opa_vert_sum.nc`, `*_opa_zoom_(2000|300|700)_sum.nc` is identically the T-grid?

**Comment by treerink** [comment]
```
    <file id="file26" name_suffix="_opa_vert_sum" output_freq="1mo">

     <field id="id_1m_thetaot"                       name="thetaot"                 table="Emon"          field_ref="toce_pot_vmean"                         grid_ref="vert_sum"                       unit="degC"               enabled="False"   operation="average"    freq_op="1ts"  >                                                                        </field>

    </file>


    <file id="file21" name_suffix="_opa_zoom_300_sum" output_freq="1mo">

     <field id="id_1m_thetaot300"                    name="thetaot300"              table="Emon"          field_ref="toce_pot_vmean300"                      grid_ref="zoom_300_sum"                   unit="degC"               enabled="False"   operation="average"    freq_op="1ts"  >                                                                        </field>

    </file>


    <file id="file16" name_suffix="_opa_zoom_700_sum" output_freq="1mo">

     <field id="id_1m_thetaot700"                    name="thetaot700"              table="Emon"          field_ref="toce_pot_vmean700"                      grid_ref="zoom_700_sum"                   unit="degC"               enabled="False"   operation="average"    freq_op="1ts"  >                                                                        </field>

    </file>


    <file id="file29" name_suffix="_opa_zoom_2000_sum" output_freq="1mo">

     <field id="id_1m_thetaot2000"                   name="thetaot2000"             table="Emon"          field_ref="toce_pot_vmean2000"                     grid_ref="zoom_2000_sum"                  unit="degC"               enabled="False"   operation="average"    freq_op="1ts"  >                                                                        </field>

    </file>
```

**Comment by krumit** [comment]
These files contain vertical averages of `thetaot` (only one variable per file) over the full ocean water column, or only the uppermost 2000m, 300m, or 700m, respectively.
See two examples:
```
netcdf f900_1m_19910101_19911231_opa_vert_sum {
[...]
float thetaot(time_counter, y, x) ;
		thetaot:long_name = "potential temperature * e3t" ;
		thetaot:units = "degC" ;
		thetaot:online_operation = "average" ;
		thetaot:interval_operation = "900 s" ;
		thetaot:interval_write = "1 month" ;
		thetaot:cell_methods = "time: mean (interval: 900 s)" ;
		thetaot:cell_measures = "area: area" ;
		thetaot:_FillValue = 1.e+20f ;
		thetaot:missing_value = 1.e+20f ;
		thetaot:coordinates = "time_centered nav_lat nav_lon" ;

// global attributes:
		:name = "f900_1m_19910101_19911231_opa_vert_sum" ;
		:description = "Created by xios" ;
		:title = "Created by xios" ;
		:Conventions = "CF-1.6" ;
		:timeStamp = "2020-Jul-16 00:43:24 GMT" ;
		:uuid = "99df5943-c883-4af1-b83e-10df5aaa1bc9" ;
}
```
and
```
netcdf f900_1m_19910101_19911231_opa_zoom_300_sum {
[...]
float thetaot300(time_counter, y, x) ;
		thetaot300:long_name = "potential temperature * e3t" ;
		thetaot300:units = "degC" ;
		thetaot300:online_operation = "average" ;
		thetaot300:interval_operation = "900 s" ;
		thetaot300:interval_write = "1 month" ;
		thetaot300:cell_methods = "time: mean (interval: 900 s)" ;
		thetaot300:cell_measures = "area: area" ;
		thetaot300:_FillValue = 1.e+20f ;
		thetaot300:missing_value = 1.e+20f ;
		thetaot300:coordinates = "time_centered nav_lat nav_lon" ;

// global attributes:
		:name = "f900_1m_19910101_19911231_opa_zoom_300_sum" ;
		:description = "Created by xios" ;
		:title = "Created by xios" ;
		:Conventions = "CF-1.6" ;
		:timeStamp = "2020-Jul-16 00:43:22 GMT" ;
		:uuid = "b7e71521-6135-4346-8065-794d91f6126f" ;
}
```
These averages of thetaot are basically proportional to pocean heat content and that's why they are of interest. They are used to produce the CMORized variables `thetaot`, `theatot300`, `thetaot700`, `theatot2000` which are part of the `Emon`-table. And yes, that's on the standrad T-grid.

**Comment by goord** [comment]
ok, I'm still a bit confused as to why these fields can't be just part of the `opa_grid_T_2D.nc` file, but I have added them to the fields that will retrieve the cell bounds from the T-grid in the downloaded files.

For the basin files I assume that XIOS produces the zonal means after interpolation and the midpoints of the latitudes in the output actually represent the 'zone bounds' faithfully?

**Comment by goord** [comment]
I suspect the problem with the zonal means in the basins originates from this piece of code (line 657 of nemo2cmor):

```python
        # Dirty hack for lost precision in zonal grids:
        if input_lats.shape[1] == 1:
            if input_lats.shape[0] > 2 and input_lats[-1, 0] == input_lats[-2, 0]:
                input_lats[-1, 0] = input_lats[-1, 0] + (input_lats[-2, 0] - input_lats[-3, 0])
```

**Comment by goord** [comment]
@krumit I don;t have access to ORCA025 zonal grid, could you make one available to be? You can also post the list of latitudes so I can write a test in ece2cmor3

**Comment by treerink** [comment]
@goord it reminds me to commit b218737fa2cb10a7459c635f9bccf20c7c170559 https://github.com/EC-Earth/ece2cmor3/commit/b218737fa2cb10a7459c635f9bccf20c7c170559. I had to make exceptions, later you replaced it by a nicer   select of cases.

**Comment by goord** [comment]
> @goord it reminds me to commit [b218737](https://github.com/EC-Earth/ece2cmor3/commit/b218737fa2cb10a7459c635f9bccf20c7c170559) [b218737](https://github.com/EC-Earth/ece2cmor3/commit/b218737fa2cb10a7459c635f9bccf20c7c170559). I had to make exceptions, later you replaced it by a nicer select of cases.

Right we have missed these zoom/vert_sum grids and for those we are still using the wrong cell bounds.

The problem with the basin files (zonal means) is a different issue, and I suspect it has to do with the precision of the latitudes in the netcdf files for the ORCA025 grid

**Comment by krumit** [comment]
goord wrote:

> ok, I'm still a bit confused as to why these fields can't be just part of the opa_grid_T_2D.nc file, but I have added them to the fields that will retrieve the cell bounds from the T-grid in the downloaded files.

> Right we have missed these zoom/vert_sum grids and for those we are still using the wrong cell bounds.

But CMORization of these variables works. To be honest, I didn't check the outcome carefully if everything is correct. But ece2cmor is at least not complaining about it.

@goord I put the two files
```
f900_1m_19910101_19911231_opa_grid_ptr_T_3basin_2D.nc
f900_1m_19910101_19911231_opa_grid_ptr_W_3basin_3D.nc
```
on our server under

`http://exporter.nsc.liu.se/ef08da663bde42c28c53974ececd820e`

Is that sufficient for your needs?

**Comment by krumit** [comment]
goord wrote:
> The problem with the basin files (zonal means) is a different issue, and I suspect it has to do with the precision of the latitudes in the netcdf files for the ORCA025 grid

I found some reports about similar problems with CMOR in the web pointing in this direction, too.
But the error messages above, complaining about non-monotonic axes seem rather indicating that it is not about the precision but how our grid information is sent to CMOR which requires monotonic order it seems.
Sorry, if this is a stupid comment, I have no experience with the actual source code of ece2cmor. I am just writing about what I read in the respective log-files.

**Comment by goord** [comment]
@krumit ths error messages from the cmor library are always a bit difficult to read. The library requires for a 1-d zonal grid bounds a 2-dimensional array `latbnds[2,:]` with the first row the lower bounds and second row upper bounds. I downloaded your files and will check whether our calculation achieves acceptable bounds.

**Comment by krumit** [comment]
@goord Great, thanks!

**Comment by goord** [comment]
If you ncdump the latitude co-ordinate in the nc files you see the origin of the problem:
```bash
ncdump -v nav_lat f900_1m_19910101_19911231_opa_grid_ptr_T_3basin_2D.nc

netcdf f900_1m_19910101_19911231_opa_grid_ptr_T_3basin_2D {
dimensions:
	axis_nbounds = 2 ;
	x = 1 ;
	y = 1050 ;
	\3basin = 3 ;
	time_counter = UNLIMITED ; // (12 currently)
variables:
	float nav_lat(y, x) ;
		nav_lat:standard_name = "latitude" ;
		nav_lat:long_name = "Latitude" ;
		nav_lat:units = "degrees_north" ;
	float nav_lon(y, x) ;
		nav_lon:standard_name = "longitude" ;
		nav_lon:long_name = "Longitude" ;
		nav_lon:units = "degrees_east" ;
	float \3basin(\3basin) ;
		\3basin:name = "3basin" ;
		\3basin:long_name = "Sub-basin mask (1=Global 2=Atlantic 3=Indo-Pacific)" ;
		\3basin:units = "1" ;
	double time_centered(time_counter) ;
		time_centered:standard_name = "time" ;
		time_centered:long_name = "Time axis" ;
		time_centered:calendar = "gregorian" ;
		time_centered:units = "seconds since 1800-01-01 00:00:00" ;
		time_centered:time_origin = "1800-01-01 00:00:00" ;
		time_centered:bounds = "time_centered_bounds" ;
	double time_centered_bounds(time_counter, axis_nbounds) ;
	double time_counter(time_counter) ;
		time_counter:axis = "T" ;
		time_counter:standard_name = "time" ;
		time_counter:long_name = "Time axis" ;
		time_counter:calendar = "gregorian" ;
		time_counter:units = "seconds since 1800-01-01 00:00:00" ;
		time_counter:time_origin = "1800-01-01 00:00:00" ;
		time_counter:bounds = "time_counter_bounds" ;
	double time_counter_bounds(time_counter, axis_nbounds) ;
	float hfbasin(time_counter, \3basin, y, x) ;
		hfbasin:long_name = "Heat Transport : All basins" ;
		hfbasin:units = "W" ;
		hfbasin:online_operation = "average" ;
		hfbasin:interval_operation = "900 s" ;
		hfbasin:interval_write = "1 month" ;
		hfbasin:cell_methods = "time: mean (interval: 900 s)" ;
		hfbasin:_FillValue = 1.e+20f ;
		hfbasin:missing_value = 1.e+20f ;
		hfbasin:coordinates = "time_centered nav_lat nav_lon" ;

// global attributes:
		:name = "f900_1m_19910101_19911231_opa_grid_ptr_T_3basin_2D" ;
		:description = "Created by xios" ;
		:title = "Created by xios" ;
		:Conventions = "CF-1.6" ;
		:timeStamp = "2020-Jul-16 00:44:01 GMT" ;
		:uuid = "36ab0444-f503-436d-b270-4262efed9578" ;
data:

 nav_lat =
  -78.13246,
  -78.08484,
  -78.03706,
  -77.98911,
  -77.941,
  -77.89272,
  -77.84428,
  -77.79567,
  -77.74689,
  -77.69794,
...
   89.66051,
  89.70773,
  89.72516,
  89.70773 ;
}
```
again the last latitude is not larger that the previous one. I suspect this is a bug in the remapping of the NEMO grid to latitudes. I can fix it in ece2cmor3

**Comment by goord** [comment]
...but I'm not entirely sure what the last latitude should be...

**Comment by goord** [comment]
> I suspect the problem with the zonal means in the basins originates from this piece of code (line 657 of nemo2cmor):
> 
> ```python
>         # Dirty hack for lost precision in zonal grids:
>         if input_lats.shape[1] == 1:
>             if input_lats.shape[0] > 2 and input_lats[-1, 0] == input_lats[-2, 0]:
>                 input_lats[-1, 0] = input_lats[-1, 0] + (input_lats[-2, 0] - input_lats[-3, 0])
> ```

As we can see from the data, the 'dirty hack' is not applied because the last latitude is actually _smaller_ then its predecessor. I have will modify the code to repair this situation too, but note that this remains a somewhat arbitrary fix: the reported latitudes are not equidistant and the assumption that the difference can be extrapolated is only an approximation

**Comment by goord** [comment]
Fix in 0514ec867d407dc90a261021ce8ae90f1bded003

Nevertheless it would be preferable to have a look at the XIOS-interpolated zonal grid, and while we're at it, try to create a netcdf file with its cell bounds, in line with the cell bounds of the other grids.

**Comment by krumit** [comment]
@ggord Just to make sure I get you right: This last latitude is essentially wrong and probably introduced by XIOS?

**Comment by goord** [comment]
@krumit Yes, I am suspicious of both last and before-last latitudes listed in the file. I assume these fields have been computed with XIOS, since calculated zonal means is typically functionality covered by the IO server. I do wonder though where the latitudes actually come from and whether the interpolation  takes into account the skewed native ORCA grid.

**Comment by krumit** [comment]
@goord I see. Yes, this should have been done by XIOS. However, I am afraid I have no idea how that actually works...
I asked @klauswyser and @uwefladrich to have a look on this issue, too. Maybe they have further insights/ideas.

**Comment by krumit** [comment]
@goord It seems that your fix did not completely solve the problem. Independent of the potential issue with XIOS, I just tried to CMORize my output with the latest commit eaf3cc06d5a431b6b4b79347cf01e7bc171adcca expecting that it should work even if we have the suspicion that the last two latitudes are not entirely OK.
The outcome is that I get less error messages but one still exists. The log-file (last few lines) says:
```
2020-11-23 12:25:43 INFO:ece2cmor3.ece2cmorlib: Selected 28 NEMO tasks from 28 input tasks
2020-11-23 12:25:43 INFO:ece2cmor3.nemo2cmor: Looking up variables in files...
2020-11-23 12:25:50 ERROR:ece2cmor3.nemo2cmor: Variable siu                  in table SIday      was not found in the NEMO output files: task skipped.
2020-11-23 12:25:50 ERROR:ece2cmor3.nemo2cmor: Variable siv                  in table SIday      was not found in the NEMO output files: task skipped.
2020-11-23 12:25:50 ERROR:ece2cmor3.nemo2cmor: Variable siconc               in table SIday      was not found in the NEMO output files: task skipped.
2020-11-23 12:25:51 ERROR:ece2cmor3.nemo2cmor: Variable dfeos                in table Omon       was not found in the NEMO output files: task skipped.
2020-11-23 12:25:51 ERROR:ece2cmor3.nemo2cmor: Variable chlos                in table Omon       was not found in the NEMO output files: task skipped.
2020-11-23 12:25:52 ERROR:ece2cmor3.nemo2cmor: Variable thetao               in table Omon       was not found in the NEMO output files: task skipped.
2020-11-23 12:25:52 INFO:ece2cmor3.nemo2cmor: Creating NEMO grids in CMOR...
2020-11-23 12:25:54 INFO:ece2cmor3.nemo2cmor: Using fallback to the old midpoint calculation method for grid opa_grid_ptr_T_3basin_2D with shape (1050, 1)
```
The CMOR-logfile looks like this (full file content):
```
C Traceback:
! In function: cmor_check_monotonic
! called from: cmor_treat_axis_values
! called from: cmor_axis
! 

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: axis latitude (table: Omon) has non monotonic values:
! 89.707733, 89.725159 and  89.725159
!
!!!!!!!!!!!!!!!!!!!!!!!!!
```
That means the previous errors and warnings about overlapping grid cells and gaps in the data disappeared and the same is true for `Error: axis latitude has values not within bounds at indice:` as well as the second instance of the complaint about non-monotonic values. Still this one instance survived...

**Comment by krumit** [comment]
It seems as if the fix now assigns the same value for the last and second-last latitude but CMOR still complains about this.

**Comment by krumit** [comment]
@goord Please correct me if I am wrong but the current form of the fix:
`input_lats[-1, 0] = input_lats[-1, 0] + (input_lats[-2, 0] - input_lats[-3, 0])`
implicetly assumes that the last latitude shows the same value as the second last. In this case it makes sense to take the value of the last latitude and add the increment `(input_lats[-2, 0] - input_lats[-3, 0])`. But that doesn't work in this case here.
As long as we believe that the second last latitude is approximately correct, we could do:
`input_lats[-1, 0] = input_lats[-2, 0] + (input_lats[-2, 0] - input_lats[-3, 0])`
I am pretty sure that would work for my case here. Of course we still don't know for sure if the value of the second last latitude is really correct in a strict sense (you suspect otherwise). But at least the request for monotonic behaviour would be satisfied then.

**Comment by goord** [comment]
Hi @krumit sorry you're absolutely right, I was too soon with my 'fix'... Your suggestion has been pushed to the master branch

**Comment by krumit** [comment]
@goord Great, I just ran a test and it works without problems now. Hence this issue here can be closed. We will still have to discuss the problem with the raw output (coming from XIOS) and analyze if the latitudes given there are correct and if not, what's going wrong. This will be continued in https://dev.ec-earth.org/issues/918
Thank you!
