### ISSUE TITLE
Land masked IFS variables require masked regridding

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#671]
See also [ec-earth issue 922](https://dev.ec-earth.org/issues/922).

While working on #664 we discovered that land/soil IFS variables which (often or always) have a land mask, require masked regridding. The masked regridding for these variables is possible, but was not implemented in `ece2cmor3` until now. This means that many or all coastal points for these variables have incorrect values, as partly sea points with improper values have been used in the interpolation. 

In https://github.com/EC-Earth/ece2cmor3/issues/664#issuecomment-726803058 the similar problem for the outside-cmor case of `tos` on the atmosphere grid case was encountered but  with the sea mask.

An additional complication is that with the current `ece2cmor3` code the addition of the masking of monthly or yearly variables causes the BUG that these variable get dismissed, when the used mask is an `fx` variable which is for the land masking the case with `grib code 172`.

We plan to improve this masking for a next `ece2cmor3` release, as this simply gives clear better results. 

We realize that this issue also concerns the cmorised and published CMIP6 data. How to cope with this and whether we want to create errata or even want to correct published data for this should be discussed on the ec-earth portal. Correcting the data might be a hard task, as we believe this is only possible with from raw data.

**Comment by treerink** [comment]
The list of `ifspar.json` variables which have a land mask:
```
 mrros
 mrrob

 snm
 snmIs
 snw
 lwsnl
 mrro
 mrroIs
 tslsi
 tsland
 tr

 mrso
 mrsow
 clayfrac
 siltfrac
 sandfrac
 mrfso
 mrsos
 tsl
 tsl4sl
 mrsol
 hfdsl
 hfmlt
 hfsbl
 esn
 slthick
```

**Comment by etiennesky** [comment]
I think you are forgetting lai, this is quite important if you want to compute a global mean 0 values over the ocean will dillute the mean.  Or maybe I misunderstand what you mean?

**Comment by treerink** [comment]
I checked that `lai` is provided by `lpjg,` so that is not part of this issue.

**Comment by treerink** [comment]
Accidentally I mentioned the wrong issue in three commit messages (therefore the commits were not auto attached to this issue):
- Masking the tsl4sl regridding #664 & #671 d8601ff167778ec18769e36033f6f42025fa0b1c
- Masking the mrsol regridding #664 & #671 6cbb9c04191a435d7434ec2441461a60e133af06
- Masking the siconca regridding #664 & #671 4daf09aac182e961ba944ca5c0b4440d38cbab12

**Comment by klauswyser** [comment]
Sorry for coming in late in the discussion. I am a little bit puzzled about the "masked regridding" of IFS variables. The raw IFS output is on a reduced Gauss grid, and this is then mapped to a regular Gauss grid with ``cdo setgridtype,regular ...``. Where can you add the mask infromation in that cdo command?

**Comment by goord** [comment]
We divide the variable first by the mask expression , e.g. ```(var172 >= 0.5)``` which evaluates to 1 on land and 0 on sea points. This makes the sea points on the reduced grid truly masked for cdo, not zero. The regridding then discards these values, and we avoid artifacts along coast lines. So we alter the variable expression before applying regridding

**Comment by etiennesky** [comment]
Am I wrong in my understanding that all  lpjg output is also affected by this bug, because the non-land points all have values of 0 and the "cdo remapycon" remapping produces wrong values over the coastline, since there is no masking done  ?

**Comment by klauswyser** [comment]
Thanks @goord for the explanation. Pretty dangerous to divide by 0 to get missing values in my humble opinion. Another point: are we sure that ``setgridtype,regular`` works well along the coastline when some gridpoints of the *regular* grid fall between a land and an ocean point? Will all these points receive valid values because one of the neighbouring points on the reduced grids is valid? In that case the land area would become too large. If on the other hand all these gridpoints would be missing because one of the neighbours on the reduced grid is missing then we would have too little land. An easy way to check would be to compare the interpolated field with missing values against ``sftlof`` from IFS.

@etiennesky : LPJG output fields are not necessarily affected by the bug because they are saved on an unstructered grid that is not remapped with ``setgridtype,regular`` like the IFS output but a different remapping function (not sure which).

**Comment by treerink** [comment]
The division is what we found as cdo recommendation for masked regridding.

See updates -the diff figures- on the  [ec-earth issue 922](https://dev.ec-earth.org/issues/922).

**Comment by treerink** [comment]
If we fear a similar bug in the LPJG land masked regridding in the cmorisation, please open a separate issue for that.

Closing this one.

**Comment by treerink** [comment]
In 314d909 one varlist for the CMIP historical and one other for the ScenarioMIP ssp's (both AOGCM) are added with which the incorrect variables of #671 & #684 can be recmorised for those who still have the raw IFS EC-Earth3 data. In addition the fx variables are added in this varlist because of #667.
