### ISSUE TITLE
Unexpected addition of tos in ppt files

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#672]
As a consequence of #664, after the addition of `tos` to the `ifspar.json` in 449fbbe2fb3b6a4efd15ff7329645ccbc674cb3e & cee884a88e7a7eb560d9ffc9bc16970a123b0423 I face a weird behavior with `genecec` during the attempt to upgrade to the latest CMIP data request version 01.00.33 (see #668): With `tos` in the `ifspar.json` I get the `tos` grib code `34` (`34.128`) in the ppt files, without not. With `tos` I do not get them in the json data request file (which is correct because they are in these cases not asked) while for the #664 case they correctly appear both in the ppt and the json data request files.

Note that in those ppt files where `172` (`172.128`) previous was absent, that `172` is now added as well, but that is correct because `tos` on the atmos grid is masked with `172,` so once `34` is added also `172` should be there.

The problem is thus that I get the `34` in the ppt files while they are not requested on the atmos grid. Checking the messages of `drq2ppt` gives:
```
INFO:__main__: Adding grib code 34.128 to MFPPHY 3hr ppt file for variable tos in table 3hr
INFO:__main__: Adding grib code 172.128 to MFPPHY 3hr ppt file for variable tos in table 3hr
...
INFO:__main__: Adding grib code 34.128 to MFPPHY 3hr ppt file for variable tos in table Oday
INFO:__main__: Adding grib code 172.128 to MFPPHY 3hr ppt file for variable tos in table Oday
INFO:__main__: Adding grib code 34.128 to MFPPHY 3hr ppt file for variable tos in table Omon
INFO:__main__: Adding grib code 172.128 to MFPPHY 3hr ppt file for variable tos in table Omon
...
INFO:__main__: Adding grib code 34.128 to MFPPHY 6hr ppt file for variable tos in table 3hr
INFO:__main__: Adding grib code 172.128 to MFPPHY 6hr ppt file for variable tos in table 3hr
...
INFO:__main__: Adding grib code 34.128 to MFPPHY 6hr ppt file for variable tos in table Oday
INFO:__main__: Adding grib code 172.128 to MFPPHY 6hr ppt file for variable tos in table Oday
INFO:__main__: Adding grib code 34.128 to MFPPHY 6hr ppt file for variable tos in table Omon
INFO:__main__: Adding grib code 172.128 to MFPPHY 6hr ppt file for variable tos in table Omon
```
So it is clear with this messages that `drq2ppt` is adding `34` (and `172`), but why it does, is the question as these onces are not requested in the xlsx data request file (and therefore correctly also not included by `drq2varlist`).

**Comment by goord** [comment]
Hi @treerink I believe drq2ppt does not check the grid of variables, it just matches tos and adds grib code 34

**Comment by treerink** [comment]
Ok I see. It confused me because the addition of `siconca` did not do this. But probably `siconc` & `siconca` are nicely separated. So either I need to make a `tos` realm check hack in `drq2ppt` or I have to adjust the `add-variables-with-pressure-levels-for-rcm-forcing.sh` script and change `6hrPlevPt` `tos` into `6hrPlevPt` `tosa`, so also `tos` in the `ifspar.json` can be changed in `tosa`, circumventing the problem I think.

**Comment by treerink** [comment]
The `tosa` strategy works. With 757d7af the default situation is back to normal. Thus closing this issue.
