### ISSUE TITLE
Quality check for newly added cmorised fx sftlf

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#676]
With #674 `fx` `sftlf`, the _Percentage of the Grid Cell Occupied by Land (in %)_,  has been added to the cmorisation. In the current implementation this field is not masked regridded as can be seen from the `ifspar.json` has for `sftlf`:
```
    {
        "source": "172.128",
        "target": "sftlf",
        "convert": "frac2percent"
    },
```
The cmor table does not ask for masking (see at the bottom of this post), which in principle seems correct to me for such a variable. However, the unmasked regridding probably gives artefacts on the coasts. 

The[ wiki gives the recipe for sftlf](https://github.com/EC-Earth/ece2cmor3/wiki/Recommended-strategies#post-ece2cmor3-production--correction-of-ofx-sftof--fx-sftlf), this has been used until now as it was mssing from the cmorisation. A diff of a current cmorised  `fx` `sftlf`  and the one created via that recipe on the wiki looks like:

![sftlf-diff](https://user-images.githubusercontent.com/18733068/100453706-b514f800-30bb-11eb-891a-ae46575cdb22.png)

and thus shows beside differences on the coastal lines also differences land inwards.

The CMOR table has for  `fx` `sftlf`:
```
        "sftlf": {
            "frequency": "fx", 
            "modeling_realm": "atmos", 
            "standard_name": "land_area_fraction", 
            "units": "%", 
            "cell_methods": "area: mean", 
            "cell_measures": "area: areacella", 
            "long_name": "Percentage of the Grid Cell Occupied by Land (Including Lakes)", 
            "comment": "Percentage of horizontal area occupied by land.", 
            "dimensions": "longitude latitude", 
            "out_name": "sftlf", 
            "type": "real", 
            "positive": "", 
            "valid_min": "", 
            "valid_max": "", 
            "ok_min_mean_abs": "", 
            "ok_max_mean_abs": ""
        }, 
```

**Comment by goord** [comment]
Am I understanding correctly that Uwe's script interpolates the NEMO mask to sftlf?

**Comment by uwefladrich** [comment]
Hi @goord ,
I have been taking the `A128.msk` (or corresponding for other resolutions) variable from the OASIS `masks.nc` file and interpolate to a regular grid to produce `sftlf`. `A128.msk` is the land mask (only 0 or 1 values) without lakes. The reasoning was that IFS considers a cell as land whenever `lsm` (172.128) is >0.5.

**Comment by goord** [comment]
Hi @uwefladrich our implementation uses exactly 172.128 to produce the variable, so I don't see where the differences near the coasts come from. In any case @treerink this variable shouldn't be masked or have a special 'masked interpolation' because it is the very definition of the lsm

**Comment by uwefladrich** [comment]
@goord , yes, I was basically confirming that we are using the same variable.
However, do I understand correctly that the cmorisation of `sftlf` uses the values of `lsm` (172) after interpolating at regridding? That is not what I do, I am converting `lsm` to 0/1 values first, because IFS does not have fractional land.
Or am I missing something else?

**Comment by klauswyser** [comment]
@treerink: following up on the question in [667](https://github.com/EC-Earth/ece2cmor3/issues/667#issuecomment-810021970): what is the problem with the cmorisation of ``sftlf``? The lakes? Or the coastline (= use a binary mask before or after regridding ``var172``)?

Re question of lakes: the definition of ``sftlf`` clearly says ["Percentage of the grid cell occupied by land (including lakes)"](http://clipc-services.ceda.ac.uk/dreq/u/b0444e42-b096-11e6-aab6-ac72891c3257.html) so it is difficult (impossible?) to use ``var172``, the SMHI approach with A128 from the Oasis masks.nc file is simpler. But how to implement that in an automatic workflow with ece2cmor3?

**Comment by klauswyser** [comment]
Great if sftlf can be solved with the Oasis mask. Is it necessary to upload these masks to b2share? Everybody who runs the model already has them in their inidatadir already, so do we need a copy then? If we have a copy on b2share too we have to make sure that it is properly maintained, however, this is probably no big deal because these masks haven't been modified a lot over time.

**Comment by goord** [comment]
The run directory is visible to ece2cmor3, so it could get the mask from there, no need to upload it to b2share then.

**Comment by plesager** [comment]
Indeed, ec2cmor3 already relies on files (`bathy_meter.nc` and `subbasins.nc`) in the rundir. Wouldn't hurt to add another one.

**Comment by plesager** [comment]
I am trying to understand the difference between the two methods used to retrieve `sftlf`. Can someone outline the steps for each of them?

From what I've gathered, the method used so far is based on a template that has been created as follows:

- read var712
- convert to 0/1 - eg see Klaus Octave script (https://dev.ec-earth.org/issues/520)
- remove lakes
- remapped to regular gaussian grid

The method currently implemented in ece2cmor3:

- read var712
- remapped to regular gaussian grid

Do I miss something?

**Comment by klauswyser** [comment]
> * read var172
> * convert to 0/1 - eg see Klaus Octave script (https://dev.ec-earth.org/issues/520)
> * remove lakes

The  shortcut for these 3 steps is to use A128.msk (or corresponding for other resolutions) from masks.nc instead. For the Axxx.msk files used in the coupling we had to remove the lakes to ensure global conservation, that's why we can use these fields now. The steps would be:

* read Axxx.msk from grids.nc and save it as a grib file (cdo replace can do that)
* remap to regular Gauss grid and rename to sftlf

**Comment by plesager** [comment]
I produced `sftlf` from A256.msk for HiRes. The Caspian Sea is masked. It isn't in the standard resolution `sftlf` template shipped with ece2cmor3. So I reproduced the latter from A128.msk to double check:

 file:///home/sager/Pictures/Screenshot%20from%202021-04-15%2014-32-11.png

**Comment by klauswyser** [comment]
The Caspian Sea should be removed because we set

````nn_closea   =    0      !  remove (=0) or keep (=1) closed seas and lakes (ORCA)````

in namelist_ref (and no changes in namelist_cfg for various ORCA configurations). This means the ECE3 runs were made without Caspian Sea even if IFS has sent fluxes, etc over the Caspian Sea to NEMO. The update of the Caspian Sea water temperature  and ice cover is handled with L128.msk, so this doesn't matter.

If we use A128.msk (and similar) for creating ``sftlof`` then we should use a correct A128.msk without Caspian Sea, of course.

**Comment by plesager** [comment]
Ok, that means all `sftlf` published so far (all standard res) are wrong, right?

**Comment by klauswyser** [comment]
Indeed, it seems that all published sftlf files contain the Caspian Sea as water. Following the logic that we treat as lake what is not handled by the ocean model this should be changed then.

**Comment by plesager** [comment]
I fixed the `ece2cmor3/scripts/data-qa/recipes/sftlf_fx_EC-Earth3-Veg_TEMPLATE_r1i1p1f1_gr.nc`. It is available in the `fix-sftlf-tmpl` branch. See  a7e2f67

**Comment by plesager** [comment]
I just tried to create the `sftlf` for low res from the oasis A080.msk, and the Caspian Sea is also water:
![Screenshot from 2021-05-19 14-27-09](https://user-images.githubusercontent.com/11032052/118812653-9e9f6a80-b8ae-11eb-9710-ac9a421649ff.png)

Conclusion: the oasis A mask can be used to create the `sftlf` only for hires. For the other resolutions, another source or further manipulating the data is needed.

**Comment by plesager** [comment]
I ended up using the ocp-tool and EC-Earth-4 init data to get a correct low res A mask. The `sftlf` I generated from it looks correct with respect to the Caspian Sea. One can spot some small changes at high latitudes when compared to the previous plot:

![Screenshot from 2021-05-19 17-14-07](https://user-images.githubusercontent.com/11032052/118838894-58560580-b8c6-11eb-9621-431e29872c1b.png)

I suspect some differences stem from different lsm in ECE3 and ECE4 init data. I will try to carry the lake cover from ECE4 to ECE3 and repeat the procedure.

**Comment by klauswyser** [comment]
Thanks to the lake model in ECE4 there is now a proper lake mask that can be combined with the fraction of land. However, it is risky to apply this lake mask also to ECE3 for 2 reasons:
1. The land mask in IFS has changed after cy41, therefore we cannot use initial conditions created with cy41 or higher in ECE3.
2. The lake mask not only contains lake but also coastal points with less than 50% land.

All this could possibly be overcome by some clever filtering ("use lake mask only if surrounded by land") but it will need careful checks to see that you really just fill in lakes.

**Comment by plesager** [comment]
OK, I see. I'm left with the original approach: using the oasis A mask that ships with ECE3, and manually mask the Caspian Sea.

**Comment by plesager** [comment]
I have `sftlf` for the three resolutions supported in ECE3. They are all based on the oasis A mask we distribute. The Caspian Sea was manually removed from the low and standard resolutions sets, because it was still seen as water in their A mask.

If there is no objection, I propose that we use the new data sets for the next release of ece2cmor3 and cmorfixer.

**Comment by treerink** [comment]
Hi Philippe, ca you sent these files zipped by mail to me, so I can prepare a new EC-Earth b2share release?

**Comment by plesager** [comment]
You can find them on my workstation:

    /net/pc170547/nobackup_1/users/sager/sftlf-for-ece2cmor3.tar.gz

**Comment by treerink** [comment]
Thanks, got them!

**Comment by treerink** [comment]
The `fx sftlf` data for LR, standard and HR are now published as part of the [ece2cmor3-data set at b2share](https://b2share.eudat.eu/records/f979c6801d434754882cc9172c2305cb).

**Comment by treerink** [comment]
Checks done, decisions ready. Final implementation is subject #705.

Closing this issue therefore.
