### ISSUE TITLE
Addition of a basic compact request

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#678]
In order to efficiently run a spin-up or piControl run a basic compact data request is convenient. It reduces raw EC-Earth output and thus disk volume resources, it reduces cmorisation time, it reduces disk volume resources for the cmorised part. And EC-Earth is running significantly faster.

**Comment by treerink** [comment]
With this request 20 SYPD can be achieved for the AOGCM on standard resolution. Cmorised output is 2.5 GB per year (IFS+NEMO). Raw total output is 41 GB per year, where: raw IFS output is 38 GB per year. and raw NEMO output is 3.8 GB per year.

**Comment by plesager** [comment]
How does this compare to the default output? Could it simply replace it?

**Comment by treerink** [comment]
Well depends, it certainly needs some investigation. This basic compact request is as it says basic and compact and therefore rather efficient for long runs like my retune runs, it includes a lot of monthly variables which allow to judge the climatology. After cmorisation hundreds and hundreds of years only cost about 1 TB to achieve. But if you want to run for instance barakuda on this (cmorised) output, it might be there is still output missing, this is not tested / investigated yet.

So beside this one we might want to create a similar _**default**_ request which maybe is close to this one, but may include a few daily or even higher frequency variables in addition or variables needed by barakuda? If, in terms of volume, the change is very small compared to the _**basic compact**_ request we also can update that one of course. So it depends on what we want to have in the default request?

**Comment by etiennesky** [comment]
note if we replace the default output this will have some impact on some things like reproducibility test which requires the current output. Namely some ifs variables might need to be added, and the post-processing script has to be adapted for new nemo filenames. Nothing very hard to do, just worth thinking about.

**Comment by plesager** [comment]
As far as I remember, only monthly output has been used in reproducibility tests and in tuning exercises. And barakuda has been used only for monitoring. But still, we should follow Thomas suggestion and start with separate **default** (close to current, to be reviewed at some point) and **compact** requests. Then they will either merge or diverge.

We know that barakuda (or any monitoring/diagnostic tools that will supplant it) cannot run with the CMIP6 data request, so it is easy to imagine that **default** will have non-CMIP ocean diagnostic.

The crucial point here is that there are files to cmorize the default output. The first consequence is a change in variables and files name of NEMO output, as pointed out by Etienne.

**Comment by klauswyser** [comment]
The default output in the ctrl directory is based on [discussions in the HiResClim project](https://dev.ec-earth.org/projects/ecearth3/wiki/PRACE_HiRes_project/edit?section=6) about what output is useful to assess climate, biases, variability, etc. This output was later modified to also fulfill the requirements for Barakuda, EMoP, the AMWG diagnostics package, and CVDP. Reducing the output will possibly break any of the requirements.

Another important question is why should we do all this with EC-Earth3 at this stage? Do we foresee a substantial amount of new test runs, spin-up, tuning? My impression is that we will still use ECE3 for quite some time in projects but tuning or spin-up runs are not high on the list. Many projetcs have very distinct needs for output which can be copies of CMIP6 experiments, but can also be different and are most likley not just a default output. I don't really see a need for a new "general" default output option in ECE3 at this stage. And, in ECE4 things will be different anyway when we will use XIOS.

**Comment by plesager** [comment]
> The default output in the ctrl directory is based on [discussions in the HiResClim project](https://dev.ec-earth.org/projects/ecearth3/wiki/PRACE_HiRes_project/edit?section=6) about what output is useful to assess climate, biases, variability, etc. This output was later modified to also fulfill the requirements for Barakuda, EMoP, the AMWG diagnostics package, and CVDP. Reducing the output will possibly break any of the requirements.

Ok, good to know what motivated the current default output. Something to keep in mind.

> Another important question is why should we do all this with EC-Earth3 at this stage? 

Right, there is little impetus to change the default output, except it cannot be cmorized as is. Do we want to be able to cmorize the default output at the risk of breaking any post-processing tools users have been using? This has not been requested as far as I know.

As for the `compact` request, it is a good idea to record Thomas setup to minimize the output of his long tuning runs.

**Comment by treerink** [comment]
From the `ece2cmor3` / `genecec` side this issue is solved, so closing.

**Comment by plesager** [comment]
> > Another important question is why should we do all this with EC-Earth3 at this stage? Do we foresee a substantial amount of new test runs, spin-up, tuning? My impression is that we will still use ECE3 for quite some time in projects but tuning or spin-up runs are not high on the list. Many projetcs have very distinct needs for output which can be copies of CMIP6 experiments, but can also be different and are most likley not just a default output. I don't really see a need for a new "general" default output option in ECE3 at this stage. And, in ECE4 things will be different anyway when we will use XIOS.
> 
> That means we can remove the current default as it won't be used anymore and we set the `compact-request` as default because it doesn't matter anyway?

No, it does matter. The current default is still used, not for spin-up or tuning though.

**Comment by etiennesky** [comment]
IMHO it is nice to have a cmorizable compact output, but  the default output should not change at this point.  Maybe a 1-line comment in the ece-esm.sh runscript pointing to the basic compact request folder would be sufficient.

**Comment by treerink** [comment]
> No, it does matter. The current default is still used, not for spin-up or tuning though.

Ok, then the question is whether we like to have a cmorisable default, which will ensure more conversion overall (like the number of barakuda versions). If, we think it is not worth the effort we keep the default as it is. An intermediate option is to make a default which has most of what is in the current default, but maybe has not some variables which are more difficult to get in. Note that it is possible to insert some non-cmor variables in a cmor-like way (like I did for a few other projects as well), so this non-cmor variables can be included in the `genecec` output, but also can be cmorised with `ece2cmor3.`

**Comment by treerink** [comment]
Added in the `r8018-control-output-files` branch in [r8377](https://dev.ec-earth.org/projects/ecearth3/repository/revisions/8377) the ec-earth repository.
