### ISSUE TITLE
Request to add experiments to genecec

### ISSUE THREAD

**Issue by nierad** [EC-Earth/ece2cmor3#680]
Hi, 

it would be great if the following experiments could be added to genecec:

LUMIP        land-cClim                        tier-2  historical land-only constant climate
LUMIP        land-cCO2                        tier-2  historical land-only constant CO2
LUMIP        land-noShiftCultivate        tier-2  historical land-only with shifting cultivation turned off

Thanks a lot, 
Lars

**Comment by treerink** [comment]
Ok, I will add these three tier 2 LUMIP experiments with an exception to `genecec` and add them to the control output files in the current branch for that in the ec-earth repository. But earliest next week ;)

**Comment by treerink** [comment]
Hi Lars, I would have done it already, but my laptop has crashed an excellent combi with the current circumstances. I will be delayed a bit, but I will try.

**Comment by treerink** [comment]
The three tier 2 LUMIP experiments:

- land-cClim tier-2 historical land-only constant climate
- land-cCO2 tier-2 historical land-only constant CO2
- land-noShiftCultivate tier-2 historical land-only with shifting cultivation turned off

have been added to genecec and their control output files directories are added in the `r8018-control-output-files` branch (see ec-earth issue [895-38](https://dev.ec-earth.org/issues/895#note-38).
