### ISSUE TITLE
Cmorising the cordex model-level output

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#682]
- Add some description about how to cmorise the model-level output for the RCM forcing at the ece2cmor3 wiki and/or the ec-earth portal
- Add some volume numbers as info at that wiki(s)
- Add a json data request file for this
- Discuss status & quality in this issue here

**Comment by treerink** [comment]
A weird thing is that though I specify the `6hrLev` `ps` in the json data request file, `ps` is not separately cmorised but it is included in all the files with the other `6hrLev` variables. I thirst thought that this is the case because it is seen as a coordinate, but I can't see that from the `CMIP6_6hrLev.json`. @goord any idea?

**Comment by klauswyser** [comment]
Could it be a feature of the CMOR library to always include ``ps`` in all model level output? It would make sense because model level output without ``ps`` is rather useless.

**Comment by goord** [comment]
Hi @treerink, @sager, @klauswyser  the surface pressure is always included in model-level variables because it is required to interpret the hybrid model levels. ``ece2cmor3`` currently has a somewhat hacky solution to include ``ps`` as a separate 'fake' variable, even if it isn't explicitly in the request. This is also the cause of issue #655

**Comment by treerink** [comment]
Yes that was what I was thinking, but do you expect in that case to see nothing of `ps` (as coordinate or associate coordinate) in e.g. in the table for `6hrLev` `hus`? According to Erik there where a few attributes missing as well, I have to check that still.

**Comment by goord** [comment]
Ah ok, so this issue is actually identical to #655 : if ``ps`` is requested, it is not cmorized when model level variables are present. In this case the surface pressure should be both in all model level variable files and in a separate file with the correct metadata. But because of the bug #655 the latter doesn't get produced

**Comment by goord** [comment]
Hi @treerink I pushed (hopefully) a fix to the branch ``missing-ps-fix``. Can you do 2 tests: (i) the normal data request, including ``ps`` and (ii) a manually modified drq where you remove ``ps`` from the ``varlist``?

**Comment by treerink** [comment]
Including `ps` in the varlist (and after merging the latest `master` in this `missing-ps-fix` branch I got in the slurm message:
```
Traceback (most recent call last):
  File "/lustre2/projects/model_testing/reerink/miniconda2/envs/ece2cmor3/bin/ece2cmor", line 11, in <module>
    load_entry_point('ece2cmor3', 'console_scripts', 'ece2cmor')()
  File "/nfs/home/users/reerink/cmorize/ece2cmor3/ece2cmor3/ece2cmor.py", line 141, in main
    cdothreads=args.ncdo)
  File "/nfs/home/users/reerink/cmorize/ece2cmor3/ece2cmor3/ece2cmorlib.py", line 189, in perform_ifs_tasks
    ifs2cmor.execute(ifs_tasks, nthreads=taskthreads)
  File "/nfs/home/users/reerink/cmorize/ece2cmor3/ece2cmor3/ifs2cmor.py", line 210, in execute
    pool.map(cmor_worker, proctasks)
  File "/lustre2/projects/model_testing/reerink/miniconda2/envs/ece2cmor3/lib/python2.7/multiprocessing/pool.py", line 253, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/lustre2/projects/model_testing/reerink/miniconda2/envs/ece2cmor3/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
multiprocessing.pool.MaybeEncodingError: Error sending result: 'CMORError("Problem with 'cmor.variable'. Please check the logfile (if defined).",)'. Reason: 'PicklingError("Can't pickle <class '_cmor.CMORError'>: import of module _cmor failed",)'
slurmstepd: *** JOB 2036373 ON knmi357 CANCELLED AT 2021-01-16T11:03:55 ***
```

And in the cmor.log file:
```

C Traceback:
! In function: cmor_variable
! 

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: You did not define a table yet!
!
!!!!!!!!!!!!!!!!!!!!!!!!!


C Traceback:
! In function: cmor_variable
! 

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: Could not find a matching variable for name: 'ps'
!
!!!!!!!!!!!!!!!!!!!!!!!!!
```
to my surprise, so I need to have a look.

**Comment by treerink** [comment]
Hi Gijs,

I added the test varlist:
```
ece2cmor3/ece2cmor3/resources/test-data-request/cordex-model-level-output-for-rcm-forcing.json
```
in the `master,` and merged this also in the `missing-ps-fix` branch.

**Comment by treerink** [comment]
Hi @goord I saw an udate in the `missing-ps-fix` branch. Is this one also ready for a next test?

**Comment by goord** [comment]
That's right, I have tested it locally but await your approval

**Comment by treerink** [comment]
Ok thanks, will test it

**Comment by treerink** [comment]
I have merged the `missing-ps-fix` branch into the master. Both tests (with and without explicit listing `6hrLev ps`  in the varlist) passed. When `6hrLev ps` is listed in the varlist it is now also cmorised as an separate output variable.

**Comment by treerink** [comment]
Next issue to be solved for this cordex model-level output is #686.

Thereafter issue  #684 remains to be solved for this one as well.

**Comment by treerink** [comment]
Issue #686 is closed.

So for this issue #684 remains to be solved.

**Comment by treerink** [comment]
After solving #684 we seem to be able to cmorise correctly the cordex model-level output including the highly appreciated fields by RCM modellers in orderr o use this data to force their RCM with the EC-Earth output.

Finalizing this issue coincides with / is part of the pre-release #693.
