### ISSUE TITLE
Wrong horizontal interpolation in remapping for soil type related variables

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#684]
While testing #682 we discovered that the remapping/regridding for soil type related variables like soil moisture is incorrect in the cmorisation. Because of different soil types in the horizontal direction, for these variables a nearest neighbor interpolation is required which was not the case sofar. The cdo code contains some dedicated code for this for IFS (for `ISEC1_CenterID == 98`):
```
          int lveggy = (ISEC1_CodeTable == 128) && (ISEC1_CenterID == 98) &&
                      ((ISEC1_Parameter == 27) || (ISEC1_Parameter == 28) ||
                       (ISEC1_Parameter == 29) || (ISEC1_Parameter == 30) ||
                       (ISEC1_Parameter == 39) || (ISEC1_Parameter == 40) ||
                       (ISEC1_Parameter == 41) || (ISEC1_Parameter == 42) ||
                       (ISEC1_Parameter == 43))
```
where
```
grib code 27 corresponds with the IFS shortname CVL   (Low vegetation cover)
grib code 28 corresponds with the IFS shortname CVH   (High vegetation cover)
grib code 29 corresponds with the IFS shortname TVL   (Type of low vegetation)
grib code 30 corresponds with the IFS shortname TVH   (Type of high vegetation)

grib code 39 corresponds with the IFS shortname SWVL1  (Volumetric soil water layer 1)
grib code 40 corresponds with the IFS shortname SWVL2  (Volumetric soil water layer 2)
grib code 41 corresponds with the IFS shortname SWVL3  (Volumetric soil water layer 3)
grib code 42 corresponds with the IFS shortname SWVL4  (Volumetric soil water layer 4)
grib code 43 corresponds with the IFS shortname SLT    (Soil type)
```
but this is probably only applied when the `cdo` option `-t ecmwf` is used, which has been not the case so far in the cmorisation with `ece2cmor3`. See also  [Soil type](https://apps.ecmwf.int/codes/grib/param-db?id=43).

We have gone through several options how to address this issue. One of them is to add the `-t ecmwf` option to `cdo`, however this option requires a significant adjustment because by using that option the variable names in the (intermediate) cdo results will be the IFS shortname instead of the grib code, and the `ece2cmor3` flow is tailored to this file names. What could be tried is to apply this  `cdo` option `-t ecmwf` only for the soil type related variables by adding an attribute for these variables in the `ifspar.json` and to adjust the expressions for these variables or to insert for the affected grib codes another grib-code - shortname administration (note that the longest LS3MIP related expressions are subject to this issue).

This issue will trigger another bunch of errata for published data.

**Comment by goord** [comment]
This can be tested in branch [interpolate_nn](https://github.com/EC-Earth/ece2cmor3/tree/interpolate_nn)

**Comment by treerink** [comment]
Showing first the manual diff plot with the new proposed nn (nearest neighbour) interpolation using `cdo`'s `-setgridtype,regularnn` from yesterdays session:
![diff-nn-interpolation](https://user-images.githubusercontent.com/18733068/106865037-ea951d80-66ca-11eb-910d-50bc51190fad.png)
Between -15.6 & 15.6 degrees around the equator the grid center points probably coincide for both the gaussian reduced and the gaussian regular grid, which has the effect that there is no difference in this band with the nearest neighbour interpolation

**Comment by treerink** [comment]
I have run various tests with the branch. A positive confirming result is that I found correct looking corrections for Lmon mrso:
![diff-Lmon-mrso](https://user-images.githubusercontent.com/18733068/106865981-33010b00-66cc-11eb-889e-3a5745b9ca53.png)

However, strange enough, for 6hrPlevPt mrsol I did not see any differences. So first I will check whether something went wrong in my check.

**Comment by goord** [comment]
Do you have the cdo command from the log file?

**Comment by treerink** [comment]
Both logs look correct to me:
```
Post-processing target mrsol in table 6hrPlevPt from file /lustre2/projects/dutch_scen/reerink/temp-cmor-dir/ds23/ifs/801/ds23-ifs-2650/42.128.111_41.128.111_40.128.111_39.128.111_172.128.1.6 with cdo command -setgridtype,regularnn -setcode,118          -expr,'var1=(70*var39)/(var172>0.5);var2=(210*var40)/(var172>0.5);var3=(720*var41)/(var172>0.5);var4=(1890*var42)/(var172>0.5)' -selhour,0,6,12,18 -selcode,39,40,41,42,172
Post-processing target mrsol in table Emon      from file /lustre2/projects/dutch_scen/reerink/temp-cmor-dir/ds23/ifs/801/ds23-ifs-2650/42.128.111_41.128.111_40.128.111_39.128.111_172.128.1.6 with cdo command -setgridtype,regularnn -setcode,118 -monmean -expr,'var1=(70*var39)/(var172>0.5);var2=(210*var40)/(var172>0.5);var3=(720*var41)/(var172>0.5);var4=(1890*var42)/(var172>0.5)'                    -selcode,39,40,41,42,172
```
I will have a look whether something went wrong with the ncdiff.

**Comment by treerink** [comment]
It is ok, I had some displaying issue. I have also made a confirming diff for `6hrPlevPt` `mrsol` in  the model level cmorisation set (#682).

I will now ask Erik to judge whether the erroneous features he spotted before with the soil type related variables are gone with this fix.

**Comment by treerink** [comment]
The following variables are affected (a grep on `nn` in the current `ifspar.json`):
```
mrso
mrsow
siltfrac
sandfrac
mrfso
mrsol
```

**Comment by treerink** [comment]
Checking whether we catched all soil related variables in the `ifspar.json` in db6479c5d42f1d1c8fb8b51332951470320f1d39:



```
for i in {39..43}; do grep -B 5 var$i ../resources/ifspar.json |grep target; done > soiltype-related-vars.txt ; sort soiltype-related-vars.txt | uniq
```
```
        x "target": "clayfrac",
        v "target": "mrfso",
        v "target": "mrso",
        v "target": "mrsol",
        x "target": "mrsos",
        v "target": "mrsow",
        v "target": "sandfrac",
        v "target": "siltfrac",
```

The other check:
```
for i in {27..30}; do grep -B 5 var$i ../resources/ifspar.json |grep target; done > soiltype-related-vars.txt ; sort soiltype-related-vars.txt | uniq
```
does not have any hit.

Thus, the `"interpolate": "nn"` attribute should be added for `clayfrac` & `mrsos` as well.

**Comment by treerink** [comment]
Solved, merged into the master branch.

**Comment by treerink** [comment]
The following variables are affected by this fix:
```
mrfso
mrso
mrsol
mrsos
mrsow
clayfrac
sandfrac
siltfrac
```

**Comment by treerink** [comment]
In 314d909 one varlist for the CMIP historical and one other for the ScenarioMIP ssp's (both AOGCM) are added with which the incorrect variables of #671 & 684 can be recmorised for those who still have the raw IFS EC-Earth3 data. In addition the fx variables are added in this varlist because of #667.

**Comment by treerink** [comment]
See also [ec-earth portal issue 954](https://dev.ec-earth.org/issues/954), also for errata proposals.
