### ISSUE TITLE
ece2cmor3 crashes with "ImportError: No module named dateutil.parser" 

### ISSUE THREAD

**Issue by nierad** [EC-Earth/ece2cmor3#685]
Hi all, 

I am not sure whether this is related to ece2cmor3 or my installation. After some modifications to lpjg2cmor.py I got the following error: 
```
Processing lpjg leg 001 of experiment CCO2
Traceback (most recent call last):
  File "/home/x_larni/miniconda2/bin/ece2cmor", line 11, in <module>
    load_entry_point('ece2cmor3', 'console_scripts', 'ece2cmor')()
  File "/home/x_larni/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/x_larni/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/home/x_larni/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/home/x_larni/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/x_larni/cmorize/ece2cmor3/ece2cmor3/ece2cmor.py", line 6, in <module>
    import dateutil.parser
ImportError: No module named dateutil.parser
leg 001 for lpjg of experiment CCO2 failed.
```
I then moved the whole directory and re-installed ece2cmor3 from scratch as many times before. However, I got the same error. Even if I go back to older releases. 
I also seem not to be able to update conda itself. I get this when trying:
```
[x_larni@tetralith1 ece2cmor3]$ conda update -n base -c defaults conda
Collecting package metadata (current_repodata.json): done
Solving environment: done

==> WARNING: A newer version of conda exists. <==
  current version: 4.8.3
  latest version: 4.9.2

Please update conda by running

    $ conda update -n base -c defaults conda


# All requested packages already installed.
```

Any idea anybody?

**Comment by treerink** [comment]
Can you first try in your conda environment (i.e. in a shell where miniconda2 is active or the ece2cmor3 environment is active):
```
sudo pip install python-dateutil
```
Let's see if this is the only problem.

**Comment by nierad** [comment]
Hi Thomas!
This is what I get. Do I have to switch to Python3?
```
[x_larni@tetralith1 ece2cmor3]$ pip install python-dateutil
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Requirement already satisfied: python-dateutil in /proj/s-cmip/users/lu/x_larni/rossby15/miniconda2/envs/ece2cmor3/lib/python2.7/site-packages (2.8.1)
Requirement already satisfied: six>=1.5 in /proj/s-cmip/users/lu/x_larni/rossby15/miniconda2/envs/ece2cmor3/lib/python2.7/site-packages (from python-dateutil) (1.15.0)
```

**Comment by etiennesky** [comment]
FYI @nierad if you want to cmorize the special variables for c4mip (cLandYr, cFluxYr), you should use my ece2cmor3 fork.

However, official ece2cmor3 sill be fine for the standard variables, even fco2nat which also contains the co2 flues from pisces (fgco2).

**Comment by nierad** [comment]
Thanks Etienne, 
unfortunately, this is just an every-day-cmorization which suddenly doesn't work anymore...

**Comment by goord** [comment]
Hi @nierad, in your ``ece2cmor3`` conda environment you can either:

- type ``pip install python-dateutil``
- type ``conda install python-dateutil``

or checkout the latest version of the master branch, I have added the dependency to the list of packages. This slipped our attention because on most systems this package is already installed and the conda python silently uses the system-installed python-dateutil I guess. I do not know why it suddenly appeared on your system, maybe upon migration to python 3, the package list was changed or so

**Comment by nierad** [comment]
Hi Gijs, 
it doesn't work. I get this when installing everything from scratch (including miniconda2 or 3: https://github.com/EC-Earth/ece2cmor3/issues/685#issuecomment-763602852
Why is there a reference to python2.7? I thought, we had moved to Python 3...

**Comment by goord** [comment]
No python3 is still in a separate branch, yet to be merged

**Comment by nierad** [comment]
Hmmm... could some other settings interfere with it?

**Comment by goord** [comment]
It's a strange error,  because anaconda says dateutil is already installed on your system

**Comment by nierad** [comment]
Also, the fact that I can't update conda itself is strange. I will try this afternoon with David to see whether it is something with my account/settings only. If that test is negative, I think I'll contact our HPC-support.

**Comment by goord** [comment]
Hi Lars, what happens if you type
```
conda activate ece2cmor3
python
import dateutil.parser
```

**Comment by nierad** [comment]
Hi Gijs, 
no Problems. That works. 
I just replaced 
```
ìmport dateutil.parser
```
by
```
import dateutil
```
in ece2cmor.py. It runs. Let's see what happens if we get to where the parser is used...

**Comment by nierad** [comment]
Yes! That solved it.... 
It's not that I undersand what is going on here...

Btw, there is also a 
```
import dateutil.relativedelta
```
that is never used.

**Comment by goord** [comment]
That relativedelta was probably used in the past and import statement was never removed...

The only thing I can think of is that the parser is no longer a module within the dateutil package. You can check in your solution to the master branch if you wish

**Comment by treerink** [comment]
But be sure you do not have other changes. Can you please wait a second, I am just halfway a merge.

**Comment by nierad** [comment]
No worries. I'll wait. Let me know when you're ready.

**Comment by nierad** [comment]
@treerink has commited change to master
