### ISSUE TITLE
Removing the second masking for ifs land-masked variables

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#686]
As a remnant from the earlier method a mask is applied after the regridding while the latest method does the masking before regridding by not taking the invalid values into account. The second masking after the regridding should be removed for the  ifs land-masked variables because it could lead to unnecessary masking of a few additional points.

The proposed fix adds to the recent improvement done in #671.

**Comment by treerink** [comment]
The `remove-2nd-masking` branch has been created for this issue.

**Comment by goord** [comment]
Hi @treerink this can be tested

**Comment by treerink** [comment]
I have been testing the `remove-2nd-masking` branch  with the ec985bd9763c36e7f55c084092b4034fa6de6494 commit, but I do not see any difference in `tsl` or `mrsol` for instance after comparing the new result and the previous result which includes the second masking step. So does it really make no difference, contrary to the believed findings of SMHI, or did we not disable (in all cases for instance) the second masking step?

```
# logging some diffs I made:

cd /lustre2/projects/dutch_scen/reerink/cmorised-results/to-be-approved-by-erik-v09/cmor-cmip-ds23/ds23/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p2f1/6hrPlevPt/tsl/gr/v20210126
ncdiff tsl_6hrPlevPt_EC-Earth3_historical_r1i1p2f1_gr_265001010000-265012311800.nc /lustre2/projects/dutch_scen/reerink/cmorised-results/to-be-approved-by-erik-v08/cmor-cmip-ds23/ds23/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p2f1/6hrPlevPt/tsl/gr/v20201204/tsl_6hrPlevPt_EC-Earth3_historical_r1i1p2f1_gr_265001010000-265012311800.nc diff-tsl-v09-v08.nc

cd /lustre2/projects/dutch_scen/reerink/cmorised-results/to-be-approved-by-erik-v09/cmor-cmip-ds23/ds23/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p2f1/6hrPlevPt/mrsol/gr/v20210126
ncdiff mrsol_6hrPlevPt_EC-Earth3_historical_r1i1p2f1_gr_265101010000-265112311800.nc /lustre2/projects/dutch_scen/reerink/cmorised-results/to-be-approved-by-erik-v08/cmor-cmip-ds23/ds23/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p2f1/6hrPlevPt/mrsol/gr/v20201204/mrsol_6hrPlevPt_EC-Earth3_historical_r1i1p2f1_gr_265101010000-265112311800.nc diff-mrsol-v09-v08.nc

cd /lustre3/projects/CMIP6/reerink/cmorised-results/cmor-cmip-test-all-branch-r8018-control-output-files-t004-remove-2nd-masking-a/t004/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/piControl/r1i1p1f1/Lmon/tsl/gr/v20210126
ncdiff tsl_Lmon_EC-Earth3_piControl_r1i1p1f1_gr_199101-199112.nc /lustre3/projects/CMIP6/reerink/cmorised-results/cmor-cmip-test-all-branch-r8018-control-output-files-t004/t004/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/piControl/r1i1p1f1/Lmon/tsl/gr/v20201203/tsl_Lmon_EC-Earth3_piControl_r1i1p1f1_gr_199101-199112.nc diff-tsl-t004a-t004.nc
```

**Comment by klauswyser** [comment]
Hej @treerink, could you make a sample output available? One file with one filtered variable is sufficient. Thanks.

**Comment by treerink** [comment]
Well, I overlooked one thing: that `ncdiff` doesn't show a difference as soon one of the points in both files has a missing value, in that case in the resulting file it gives a missing value in any case. And that matters here. So with setting the missing values to different values and taking the `ncdiff` on those files the mask differences become visible after removing the second masking step:

![diff-tsl-mod-vt004a-t004](https://user-images.githubusercontent.com/18733068/106134015-478e5200-6166-11eb-88c7-c3b02d78c9bd.png)

**Comment by treerink** [comment]
The `remove-2nd-masking` has been merged into the master, solving this issue.
