### ISSUE TITLE
Add an ignore mask for erroneous points in versions < v1.7.0  for ifs land-masked variables  

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#691]
In #671 and #686 two fixes have been applied for ifs land-masked variables. Without the raw EC-Earth3 data it is not possible to correct these data.  Because a lot of published data on the ESGF nodes can not be fixed, as their raw data is not longer available, it is asked whether a mask can be constructed which marks the erroneous points.

We intend to provide a mask which marks all points which are incorrect in `ece2cmor3` versions < `1.7.0` compared to the cmorised  ifs land-masked results with a version >= v1.7, and thus includes both the changes due to #671 and #686.

**Comment by treerink** [comment]
A neat `omit_mask` has been produced and published [here on b2share](https://b2share.eudat.eu/records/5692faf1b52f446887f191ddd32a1381). The file with the `omit_mask` can be downloaded by this [direct download link](http://hdl.handle.net/11304/ccb20fb4-fc11-46ef-ab18-7975d6de84bc).

**Comment by treerink** [comment]
Currently we only provided the `omit_mask` for the EC-Earth3 standard resolution, i.e. for IFS T255. For the EC-Earth3 LR variants and the EC-Earth3 HR variants the `omit_mask` has not been produced yet. Therefore I need for each resolution two `Lmon` `tsl` files based on the identical EC-Earth output for each of these resolutions: 

1. using `ece2cmor3` `v1.5.0`  # git checkout 0e9c8f0d4efe956627d5dee9cd3ae6d26a995191
2. using `ece2cmor3` `v1.7.0`  # git checkout c9063184d7c8314349d4a99a737ad290ef0e97ac

Who can provide them for EC-Earth3 LR?

And who can provide them for EC-Earth3 HR?

**Comment by krumit** [comment]
I guess, I could do that for HR. For clarification: You just need two of these Lmon tsl files (with ece2cmor3 v1.5.0 and v1.7.0), no matter which actual simulation they are coming from and which timesteps (years) they contain?

I have produced a number of DCPP-A-hindcasts in HR that have been cmorized already. I think I wrote the necessary output to additionally cmorize tsl. I will check and come back to you.

**Comment by treerink** [comment]
Hi Tim,

That would be great, thanks! Yes indeed I do not mind which time step and which simulation, as long you use the same raw data for running both ece2cmor3 versions on it of course. Please do not upload these files here at this Github. I think at SMHI you can easily provide me a link from where I can download it, so if you can post the link here, that would be great

Thanks,
Thomas

**Comment by krumit** [comment]
Hi Thomas,

You should be able to download the two files from
http://exporter.nsc.liu.se/8e9344127f27457a96c4e276d738078a
or
rsync://exporter.nsc.liu.se/8e9344127f27457a96c4e276d738078a

Please let me know if you encounter problems.

Best,

Tim

**Comment by treerink** [comment]
Hi Tim,

I got them and the checksums are fine (the rsync did not work for me). Thanks, I will work on the `omit_mask` for HR with this.

Regards, Thomas

**Comment by treerink** [comment]
It was asked in the EC-Earth CMIP6 WG also to provide the script: Adding the script which produces for the EC-Earth3 LR, standard & HR resolutions the omit_mask for the BUG in the ifs land masked variables in `ece2cmor3` versions < `v1.7.0`. See #691, #671, #686.

**Comment by treerink** [comment]
The `omit_mask`'s for the EC-Earth3 `LR`, `standard` & `HR` resolutions have been created and their latest versions will be uploaded to b2share.

**Comment by treerink** [comment]
The `omit_mask`'s for the EC-Earth3 `LR`, `standard` & `HR` resolutions have been published on b2share [here](https://b2share.eudat.eu/records/f674000ecf3e4510a25960a4b7d77ee3).

**Comment by treerink** [comment]
In 2c46272 the script is extended for the LR-pliocene case. I have locally created the `omit_mask` for the LR pliocene case, but it is not uploaded to the b2share dataset yet.
