### ISSUE TITLE
Publish the omit_mask for the EC-Earth3-LR pliocene case

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#706]
The omit_mask for the EC-Earth3-LR Pliocene case is reproduced and can be published on b2share as well.

**Comment by treerink** [comment]
Hi Gijs, I see a new release date, but I do not see the new omit_mask for LR-pliocene?

**Comment by goord** [comment]
oops. Where are the masks Thomas?

**Comment by treerink** [comment]
Thanks Gijs!
