### ISSUE TITLE
The download-b2share-dataset.sh script fails on cca

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#712]
The `download-b2share-dataset.sh` script which has been added to overcome the two issues mentioned in #710, fails on `cca`. On cca it is not `wget` which is the show stopper but it appeared to be a difference in the bash interpreter. The main problem with bash on cca with this script appears to be that obviously [indirect expansion](https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html) does simply not work. I guess it is related to gnu / no gnu. Another problem appears to be the `for & ls -1` combination in the md5 check.

I have written a replacement script which now works well on cca. Before committing I will first test it on my ubuntu laptop, on the KNMI HPC and on KNMI workstation environment.

**Comment by treerink** [comment]
Solved in 412613b. The updated script has been successfully tested on four platforms.

**Comment by aearamos** [comment]
I can confirm It's also working in my local machine and I was able to download the files properly.
