### ISSUE TITLE
git revision missing for DynVar processing

### ISSUE THREAD

**Issue by fserva** [EC-Earth/ece2cmor3#714]
Hi @goord @treerink 

I am now using the ece2cmor3 master branch to process some data for DynVar. 
In order to use it, I use the command  `./switch-on-off-DynVarMIP-mode.sh` `activate-DynVarMIP-mode`. 
It seems to be working well.

As you see below there may be a problem with the revision information (already noted during implementation). 
It seems the version I am using is 1 commit ahead, and presumably this commit is related with the step 'Updating the nested CMOR table repository by maintainers' which requires a commit.

```
// global attributes:
		:Conventions = "CF-1.7 CMIP-6.2" ;
		:activity_id = "CMIP" ;
		:branch_method = "no parent" ;
		:contact = "cmip6-data@ec-earth.org" ;
		:creation_date = "2021-07-13T02:49:33Z" ;
		:data_specs_version = "01.00.33" ;
		:ece2cmor_git_revision = "local unknown branch" ;
		:experiment = "AMIP" ;
		:experiment_id = "amip" ;
		:forcing_index = 1 ;
		:frequency = "mon" ;
		:further_info_url = "https://furtherinfo.es-doc.org/CMIP6.EC-Earth-Consortium.EC-Earth3.amip.none.r10i1p1f1" ;
		:grid = "T255L91" ;
		:grid_label = "gr" ;
		:history = "2021-07-13T02:49:13Z ; CMOR rewrote data to be consistent with CMIP6, CF-1.7 CMIP-6.2 and CF standards.;\n",
			"processed by ece2cmor v1.8.0, git rev. local unknown branch\n",
```

Do you think this would be a problem? Suggestions on how to solve it in case?

Thanks

**Comment by fserva** [comment]
An update: I've repeated the procedure without tables update, but only doing `./switch-on-off-DynVarMIP-mode.sh activate-DynVarMIP-mode`. This caused the changes:
```
#	modified:   ece2cmor3/resources/list-of-identified-missing-cmip6-requested-variables.xlsx
#	modified:   ece2cmor3/resources/list-of-ignored-cmip6-requested-variables.xlsx
#	modified:   ece2cmor3/scripts/drq2ppt.py
```
but git revision is still `local unknown branch`. Does this happen also with other  `switch-on-off` scripts?

**Comment by goord** [comment]
Hi @fserva, this is because the git-python package that writes the attribute detects local changes when you run that script. It's not a great deal, since the attribute is not standard, it's for internal tracking be the EC-Earth community. But as long as you remember how you produced the data, I wouldn't worry about this.

**Comment by fserva** [comment]
Thanks @goord, I will take a note about it. It's fine as long as we know what's going on. Closing this issue then.
