### ISSUE TITLE
Problems with CORDEX Cmorization

### ISSUE THREAD

**Issue by LaKenLin** [EC-Earth/ece2cmor3#718]
I am having some trouble using ece2cmor3 for CORDEX data. I used that executable previously for some standard cmorization and it worked. It would be great to get some insight on how to do it properly and if these are problems with ece2cmor or in my use of it.

The following classes of errors occurred:

Dismissed variables: va, hus, us, ta
Typical message: INFO:ece2cmor3.taskloader: Dismissing model level target variable ta in table 6hrLev for component ifs...
These variables are in the corresponding table (/home/laulin/.conda/envs/ece2cmor3_v1.8/ece2cmor3/resources/tables/CMIP6_6hrLev.json) therefore these are either dismissed by default for some reason or there is a problem in the data. However, I think it is unlikely that the problem is in the data since they are dismissed before the GRIB files are even filtered.
Is there any other location you are aware of, where the cmorization of these variables would have to be declared/activated, outside of the variable list and the CMOR table?

Variable not in table (dismissed): tosa, tsl4sl, siconca
Typical message: ERROR:ece2cmor3.taskloader: The tosa variable does not appear in the CMOR table file 6hrPlevPt
These variables are not in the table and I can neither see them in the CMIP6 data request (http://clipc-services.ceda.ac.uk/dreq/u/MIPtable::6hrPlevPt.html).

Field missing in first day (dismissed): land (172), sftlf (172)
Typical message: ERROR:ece2cmor3.grib_filter: Field missing in the first day of file: code 172.128, level type 1, level 0. Dismissing task land in table fx
Seems to be missing in the data.

Field missing in initial state (dismissed): mrsol (172)
Typical message: ERROR:ece2cmor3.grib_filter: Field missing in the initial state files: code 172.128, level type 1, level 0. Dismissing task mrsol in table 6hrPlevPt
It is strange that variable 172 is used for mrsol to my eyes. Nonetheless, I linked the previous file ICMGGdhi1+197912 which I suppose is the initial state. WGRIB finds code 172 neither in this file nor in ICMGGdhi1+198001.

Cmorized: orog (GRIB: 129), areacella (129), tas (167), ps (134)
These 4 variables are cmorized without problems.

I would appreciate any and all feedback. Thank you!

**Comment by treerink** [comment]
Hi Laurent, 

Here my inline-reply of a few weeks ago which you didn't receive or found:

> I am having some trouble using ece2cmor3 for CORDEX data. I used that executable previously for some standard cmorization and it worked. It would be great to get some insight on how to do it properly and if these are problems with ece2cmor or in my use of it.
> 
> The following classes of errors occurred:
> 
> Dismissed variables: va, hus, us, ta Typical message: INFO:ece2cmor3.taskloader: Dismissing model level target variable ta in table 6hrLev for component ifs... These variables are in the corresponding table (/home/laulin/.conda/envs/ece2cmor3_v1.8/ece2cmor3/resources/tables/CMIP6_6hrLev.json) therefore these are either dismissed by default for some reason or there is a problem in the data. However, I think it is unlikely that the problem is in the data since they are dismissed before the GRIB files are even filtered. Is there any other location you are aware of, where the cmorization of these variables would have to be declared/activated, outside of the variable list and the CMOR table?

This are of course the essential variables which you want to cmorise on model levels. Could it be that you have still the flag --skip_alevel_vars activated in your submit script? This is usually strongly recommended if you cmorise data for which you do not use the model levels, but for this case you of course need to take off this option.

> 
> Variable not in table (dismissed): tosa, tsl4sl, siconca Typical message: ERROR:ece2cmor3.taskloader: The tosa variable does not appear in the CMOR table file 6hrPlevPt These variables are not in the table and I can neither see them in the CMIP6 data request (http://clipc-services.ceda.ac.uk/dreq/u/MIPtable::6hrPlevPt.html).

That is correctly observed. However, these are typically variables which RCM people really want to have when they do their dynamic downscaling. So what I have made is an additional script which injects  the required CMOR table stuff into the CMOR tables and activates its use. The script for this actually serves another goal as well, namely the addition of the 23 & 36 pressure level stuff in the tables, which is an cheaper alternative to the model level output approach, but that's not the topic here, and important to know is that this additional injections do not harm in any way our goal here. So what you can do is: 
```
  cd ${HOME}/cmorize/ece2cmor3/ece2cmor3/scripts
 ./add-variables-with-pressure-levels-for-rcm-forcing.sh                    # insert the relevant tosa, tsl4sl, siconca frequencies in the CMOR tables
 cd ${HOME}/cmorize/ece2cmor3/; python setup.py develop; cd -    # in order to activate the changes
 git status                                                                                            # To check it changed the tables
```
In case you want to cancel these changes (for instance before an ece2cmor3 update) you can use the script:
```
./revert-nested-cmor-table-branch.sh
```
With this you can cmorise the additional variables which are very handy for the RCM people and which is in terms of additional data volume negligible. A few other existing small variables for this purpose are also added, so this additional set is a mixture of existing and non-existing CMOR variables.

> 
> Field missing in first day (dismissed): land (172), sftlf (172) Typical message: ERROR:ece2cmor3.grib_filter: Field missing in the first day of file: code 172.128, level type 1, level 0. Dismissing task land in table fx Seems to be missing in the data.

The latest `ece2cmor3` version (> `v1.8`) needs grib code 172.128 in the `ICMGG????+000000` grib file which are in your first leg. Did you link them correctly. Theoretically it is possible 172 is not in the `ICMGG????+000000` file, but I think it will be there. It is more likely the `ICMGG????+000000` is not in your first leg or not correctly linked, such that `ece2cmor3` can find it.

> 
> Field missing in initial state (dismissed): mrsol (172) Typical message: ERROR:ece2cmor3.grib_filter: Field missing in the initial state files: code 172.128, level type 1, level 0. Dismissing task mrsol in table 6hrPlevPt It is strange that variable 172 is used for mrsol to my eyes. Nonetheless, I linked the previous file ICMGGdhi1+197912 which I suppose is the initial state. WGRIB finds code 172 neither in this file nor in ICMGGdhi1+198001.

Same point as above. It is a land masked remapping that is way the 172 mask is needed.

> 
> Cmorized: orog (GRIB: 129), areacella (129), tas (167), ps (134) These 4 variables are cmorized without problems.
> 
> I would appreciate any and all feedback. Thank you!

Note that in the latest EC-Earth3 - ece2cmor3 matching releases we changed the way in ece2cmor3 how we get 172, it has been made easier and more reliable now, so now we always write and tke 172 from the ICMGG????+000000 file. This was not the case at the time these runs have been done. However, ece2cmor3 is kind of backward compatible in this respect. I have cmorised the model levels of our KNMI r1 runs from that time, last July 2021 with the latest ece2cmor3 successfully, so I am pretty sure we must be able to cmorise the DMI ones as well.

Hope you come closer with this, let me know how it goes.

Regards,
Thomas

**Comment by treerink** [comment]
As I understood the cmorisation of the model levels on DMI has finished I am closing this issue. Please reopen if needed.
