### ISSUE TITLE
Data downloaded from b2share not installed with package data

### ISSUE THREAD

**Issue by jmrgonza** [EC-Earth/ece2cmor3#721]
I'm not sure if this is on purpose, but the data that is collected with the download-b2share-dataset.sh and stored in the resources/b2share-data is not installed in the same way as other package data. I think that to do so, the b2share-data directory should be added to the list given in the package_data argument in setup.py.
In my installation, when I install the package with "python setup.py develop", the ece2cmor executable is able to find this external files that I previously downloaded with the download-b2share-dataset.sh script. However, when I install it with "python setup.py install" the files are missing, and in my platform this leads to some problem when the ece2cmor script tries to download them (and fails).

**Comment by treerink** [comment]
Yes the previous used:
```
-                                  "resources/nemo-vertices/*.txt",
-                                  "resources/nemo-vertices/*.nc",
```
are replaced by:
```
+                                  "resources/b2share-data/nemo-vertices-ORCA*.nc",
+                                  "resources/b2share-data/fx-sftlf-EC-Earth3-T*.nc",
```
in the `setup.py`. Also some other `genecec` related data files have been added.
