### ISSUE TITLE
Dangerous situation possible in which unintended backups in the output/ifs dir are selected & filtered

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#725]
A rather nasty situation can be encountered in which wrong grib files are selected / filtered by the `ifs` component of `ece2cmor3`. If one never has saved copies of grib files (or sub directories with grib files in them) within the `output/ifs/` directory one is safe for this issue. However, if you have copies of grib files inside your  `output/ifs/` directory there is a large change something went wrong in the cmorisation. 

In my case I had to switch on the large volume CORDEX model level output for the historical run from 1949 onwards. Therefore I restarted EC-Earth3 after configuring this model level output, but because december files are modified by EC-Earth I made some copies of two legs inside the  `output/ifs/`, for instance  `output/ifs/backup-leg-x`. If I would have saved them like `output/backup-ifs-leg-x` nothing would have gone wrong. However if the copies are inside the `output/ifs/` they are selected by a `find` and it is thus even possible several grib files with the same time are selected. One can check the filter message in the ece2cmor3 `????-ifs-???-*.log` files.

We need to implement the minimum error with an abort in case grib files with the same time slices are encountered. Further we need to communicate this situation clearly to the users.

**Comment by goord** [comment]
In the ifs-paths-fix branch, I have refactored the file-finding functions and put them all in ifs2cmor. ece2cmor3 should not descend down into other directories then the previous leg when searching initial month fields. This should fix the situation even when you have backup directories etc. 

I have added tests and tested on the osm output without issues, but it would be useful to have a second pair of eyes testing the solution @treerink

**Comment by treerink** [comment]
Branch tested (also the extended test which checks on all field values). A test with an aded backup folder of a different run in the `output/ifs` dir  gave equal results. It is a bit hard to test for any case / combination, but normal runs give identical results and a former trouble case as well.

The `ifs-paths-fix` branch is merged.
