### ISSUE TITLE
dreqPy broken for recent python version

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#741]
The `genecec` part of the code depends on `dreqPy` and used python3 (but until recent a python3.4 or close version was used for `genecec).` However, when using a recent python version like python3.10.6 `dreqPy` appears to be broken due to the deprication of getiterator() which is replaced by iter() in ElementTree (see [here](https://github.com/cmip6dr/dreqPy1.2/issues/1)). Until this has been fixed a workaround for `genecec` is to build a separate python3.4 dreqPy environment and use the python3.4 from that environment in `genecec.` 

This workaround is inconvenient and ugly but allows to run genecec for both the ece2cmor3 python2 & ece2cmor3 python3 case (note that genecec itself always has been run with python3 (python3.4) where `genecec` calls various `drq2*.py`  python scripts which rely on the ece2cmor3 python2 or ece2cmor3 python3 version. This workaround thus allows to continue working on the python2 to python3 porting of ece2cmor3 #732 #403.

The workaround uses an separate _environment.yml_ like this:
```
name: python34
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.4
  - dreqpy==01.00.33
 ```

**Comment by treerink** [comment]
The workaround has been removed, now the latest `dreqPy` `01.02.00` version has been released which has the `iter` issue fixed. `Genecec` can be run again for the master and the python3 branch.

**Comment by zklaus** [comment]
This should not have been an issue, because that problem was solved in the Conda-forge package via a patch. But happy to see the new release of Dreqpy on Pypi, which I have now also released on Conda-forge.
