### ISSUE TITLE
Cmorising of day/zg and day/ta broken

### ISSUE THREAD

**Issue by uwefladrich** [EC-Earth/ece2cmor3#743]
Hi,

I have difficulties to cmorise `day/zg` for an ECE3-Veg historical run. When using the minimal varlist request of
```json
{
    "ifs": {
        "day": [
            "zg"
        ]
    },
    "lpjg": {},
    "nemo": {},
    "tm5": {}
}
```
I get `*.cmor.log` files including an error similar to
```
Error: NetCDF Error (-101: NetCDF: HDF error) closing variable ta (table: day)
```
or
```
Error: NetCDF Error (-101: NetCDF: HDF error), writing variable 'ta' (table day) to file
```
and an `ece2cmor` traceback like
```
 Traceback (most recent call last):
   File "[...]/bin/ece2cmor", line 11, in <module>
     load_entry_point('ece2cmor3==1.8.1', 'console_scripts', 'ece2cmor')()
   File "[...]/lib/python2.7/site-packages/ece2cmor3-1.8.1-py2.7.egg/ece2cmor3/ece2cmor.py", line 140, in main
     cdothreads=args.ncdo)
   File "[...]/lib/python2.7/site-packages/ece2cmor3-1.8.1-py2.7.egg/ece2cmor3/ece2cmorlib.py", line 198, in perform_ifs_tasks
     ifs2cmor.execute(ifs_tasks, nthreads=taskthreads)
   File "[...]/lib/python2.7/site-packages/ece2cmor3-1.8.1-py2.7.egg/ece2cmor3/ifs2cmor.py", line 251, in execute
     pool.map(cmor_worker, proctasks)
   File "[...]/lib/python2.7/multiprocessing/pool.py", line 253, in map
     return self.map_async(func, iterable, chunksize).get()
   File "[...]/lib/python2.7/multiprocessing/pool.py", line 572, in get
     raise self._value
 multiprocessing.pool.MaybeEncodingError: Error sending result: 'CMORError("Problem with 'cmor.close'. Please check the logfile (if defined).",)'. Reason: 'PicklingError("Can't pickle <class '_cmor.CMORError'>: import of module _cmor failed",)'
```
In the output directory, I find the temporary files like `zg_day_EC-Earth3-Veg_historical_r1i1p1f1_gr9p3TFg119396.nc`.

I checked with `day/ta` instead of `day/zg` because I know that we cmorised and published this variable quite some time ago, but it results in the same error. Both variables are in the same table and both are 3d based on plev8.

Any idea what is going on?

**Comment by goord** [comment]
Hi @uwefladrich can you do the test with a single process? The process pool tends to hide the real exception message.

**Comment by goord** [comment]
maybe the request is **too** simple for multiple processes to handle? I suspect some bug in the scheduling of dependent variables, but I'll have to take a closer look to see what the root cause is

**Comment by uwefladrich** [comment]
> maybe the request is **too** simple for multiple processes to handle?

Do you mean in the sense that there is only one variable? I do not think so, because I had originally a number of other variables in the list and got the same error. I only simplified for the sake for the issue.

**Comment by klauswyser** [comment]
This note may be unrelated, but there could be similarities with the actual problem. Recent versions of CDO often produce warnings about non thread-safe netCDF/HDF5 libraries. Sometimes the cdo command works despite the warning, but sometimes not. Could it be something similar with the CMOR library? Are you using a thread-safe netCDF/HDF library? Maybe worth trying if there is a thread-safe library available.

**Comment by goord** [comment]
Could be the case Klaus, @uwefladrich could you post the log files of both single and multiprocess runs?

**Comment by uwefladrich** [comment]
Unfortunately, `-npp 1` does not seem to solve the problem reliably. I started a new test this morning with the full varlist and the problem reappeared. Here are the logs for the single-threaded run:

Job output:
```
 Error in calling operator setgridtype with:
 >>> cdo -O -f nc -P 4 setgridtype,regular -monmean -expr,'var141=(var141)/(var172>0.5)' -selcode,141,141,172 /scratch/local/ece2cmor/t607-ifs-1850/141.128.1_172.128.1.3 /scratch/local/ece2cmor/t607-ifs-1850/lwsnl_LImon.nc<<<
 STDOUT:
 STDERR:cdo(1) monmean: Process started
 cdo(2) expr: Process started
 cdo(3) selcode: Process started
 
 cdo(2) expr (Abort): Variable >var141< not found!
 terminate called without an active exception
 
 Error in calling operator setgridtype with:
 >>> cdo -O -f nc -P 4 setgridtype,regular -monmean -expr,'var141=(var141)/(var172>0.5)' -selcode,141,141,172 /scratch/local/ece2cmor/t607-ifs-1850/141.128.1_172.128.1.3 /scratch/local/ece2cmor/t607-ifs-1850/lwsnl_LImon.nc<<<
 STDOUT:
 STDERR:cdo(1) monmean: Process started
 cdo(2) expr: Process started
 cdo(3) selcode: Process started
 
 cdo(2) expr (Abort): Variable >var141< not found!
 terminate called without an active exception
 
 Error in calling operator setgridtype with:
 >>> cdo -O -f nc -P 4 setgridtype,regular -monmean -expr,'var141=(var141)/(var172>0.5)' -selcode,141,141,172 /scratch/local/ece2cmor/t607-ifs-1850/141.128.1_172.128.1.3 /scratch/local/ece2cmor/t607-ifs-1850/lwsnl_LImon.nc<<<
 STDOUT:
 STDERR:cdo(1) monmean: Process started
 cdo(2) expr: Process started
 cdo(3) selcode: Process started
 
 cdo(2) expr (Abort): Variable >var141< not found!
 terminate called without an active exception
 
 Error in calling operator setgridtype with:
 >>> cdo -O -f nc -P 4 setgridtype,regular -monmean -expr,'var141=(var141)/(var172>0.5)' -selcode,141,141,172 /scratch/local/ece2cmor/t607-ifs-1850/141.128.1_172.128.1.3 /scratch/local/ece2cmor/t607-ifs-1850/lwsnl_LImon.nc<<<
 STDOUT:
 STDERR:cdo(1) monmean: Process started
 cdo(2) expr: Process started
 cdo(3) selcode: Process started
 
 cdo(2) expr (Abort): Variable >var141< not found!
 terminate called without an active exception
 
 Traceback (most recent call last):
   File "[...]/bin/ece2cmor", line 11, in <module>
     load_entry_point('ece2cmor3==1.8.1', 'console_scripts', 'ece2cmor')()
   File "[...]/lib/python2.7/site-packages/ece2cmor3-1.8.1-py2.7.egg/ece2cmor3/ece2cmor.py", line 140, in main
     cdothreads=args.ncdo)
   File "[...]/lib/python2.7/site-packages/ece2cmor3-1.8.1-py2.7.egg/ece2cmor3/ece2cmorlib.py", line 198, in perform_ifs_tasks
     ifs2cmor.execute(ifs_tasks, nthreads=taskthreads)
   File "[...]/lib/python2.7/site-packages/ece2cmor3-1.8.1-py2.7.egg/ece2cmor3/ifs2cmor.py", line 248, in execute
     cmor_worker(task)
   File "[...]/lib/python2.7/site-packages/ece2cmor3-1.8.1-py2.7.egg/ece2cmor3/ifs2cmor.py", line 294, in cmor_worker
     execute_netcdf_task(task)
   File "[...]/lib/python2.7/site-packages/ece2cmor3-1.8.1-py2.7.egg/ece2cmor3/ifs2cmor.py", line 656, in execute_netcdf_task
     time_selection=time_selection, force_fx=(cmor_target.get_freq(task.target) == 0))
   File "[...]/lib/python2.7/site-packages/ece2cmor3-1.8.1-py2.7.egg/ece2cmor3/cmor_utils.py", line 410, in netcdf2cmor
     cmor.write(varid, vals, ntimes_passed=ntimes_passed)
   File "[...]/lib/python2.7/site-packages/cmor/pywrapper.py", line 850, in write
     time_vals, time_bnds, store_with)
 _cmor.CMORError: Problem with 'cmor.write'. Please check the logfile (if defined).
 /home/sm_uflad/bin/ece2cmor.mamba: line 26: 223704 Segmentation fault      ece2cmor $@
 Command returned error code 139
```
[t607-ifs-001-20230302071959.cmor.log](https://github.com/EC-Earth/ece2cmor3/files/10868974/t607-ifs-001-20230302071959.cmor.log)
[t607-ifs-001-20230302071959.log](https://github.com/EC-Earth/ece2cmor3/files/10868976/t607-ifs-001-20230302071959.log)

**Comment by uwefladrich** [comment]
Note that the there is a lot of noise about 141 not found, which I think comes from the attempt to cmorise `Limon/lwsnl` and which I think is unrelated to the `zg` problem. Nevertheless, I started another test without `lwsnl` just to be sure it does not contribute to the problem.

**Comment by uwefladrich** [comment]
> [...] Recent versions of CDO often produce warnings about non thread-safe netCDF/HDF5 libraries. Sometimes the cdo command works despite the warning, but sometimes not. Could it be something similar with the CMOR library? Are you using a thread-safe netCDF/HDF library? Maybe worth trying if there is a thread-safe library available.

Could indeed be a good guess! However, it should not matter as long as I use `--npp 1` with ece2cmor, right?

It is a bit difficult to know on our system whether the netCDF/HDF libraries are meant to be thread-safe or not. There are many modules, some have "serial" in their name, some not. Then there is one module that has "parallel" explicit in its name. But that's of course not build with the correct compiler ...

**Comment by goord** [comment]
In ece2cmor3 all processes are supposed to write to separate files, because they never share variables. As for cdo, we assign multiple threads per process but it is my understanding that these also write to different temp files in the processing chain.

So in that sense I would think thread-safety is not an issue here.

**Comment by goord** [comment]
So the CMOR error message is not very instructive (as usual). Still, the var141 issue needs to be resolved first, it can cause the application to crash at a later stage.

**Comment by uwefladrich** [comment]
Here is a new set of log files. I add logs ece2cmor and cmor logs from cmorisation of two legs, since the errors differ slightly.

The 141-related errors are gone, the `zg` errors are still there.

[job-24422198-1.log](https://github.com/EC-Earth/ece2cmor3/files/10869905/job-24422198-1.log)
[t607-ifs-001-20230302082351.cmor.log](https://github.com/EC-Earth/ece2cmor3/files/10869906/t607-ifs-001-20230302082351.cmor.log)
[t607-ifs-001-20230302082351.log](https://github.com/EC-Earth/ece2cmor3/files/10869908/t607-ifs-001-20230302082351.log)
[t607-ifs-002-20230302082351.cmor.log](https://github.com/EC-Earth/ece2cmor3/files/10869909/t607-ifs-002-20230302082351.cmor.log)
[t607-ifs-002-20230302082351.log](https://github.com/EC-Earth/ece2cmor3/files/10869911/t607-ifs-002-20230302082351.log)

**Comment by treerink** [comment]
I encountered the last days netcdf / hdf5 errors when combining versions of {python, cmor, cdo} which are too far from each other. You could try the latest checkout of the `python-3.11` branch (there in the last update cdo 2.1.1 is used and I am right now validating the effect, so far seems good, but takes a few hours more). Of course this requires that you recreate the  ece2cmor3 environment (I used the latest mamba for that, which might matter is if it includes the latest python 3.11 version).

**Comment by uwefladrich** [comment]
Hm, changing the group allowed indeed to run the test successfully (with `--npp 1`). I do not really understand this, because I was able to make a test in this directory that wrote a lot of data before, but who knows.

I also cross-checked and run another test with `--npp 32`, also successful!

So, a very good guess @klauswyser !!

So it seems that while I have no good explanation why this happens with just this variable, there is not really a point to follow up further at the moment. If it happens again, we can return to this issue.
