### ISSUE TITLE
Add MODIS cloud fraction to ece2cmor3

### ISSUE THREAD

**Issue by klauswyser** [EC-Earth/ece2cmor3#746]
With COSP activated IFS saves a few variables from CALIPSO, ISCCP and MODIS. ece2cmor currently can process CALIPSO and ISCCP but not MODIS. Can we add the MODIS variables 47.126 - 49.129 to ifs-par.json? Including the filtering of missing values (#745 ), of course.

**Comment by klauswyser** [comment]
The MODIS variables have been added in the same go as #745, see PR #755

**Comment by klauswyser** [comment]
There is still an issue with climodis (var126049). ece2cmor complains
````
ERROR:ece2cmor3.grib_filter: Field missing in the first day of file: code 49.126, level type 1, level 0.
Dismissing task climodis in table Emon
````
It's not clear where this error comes from, the variable is in the IFS output, and it looks very similar to any other MODIS variable (var126047 or var126048) that are correctly processed. Could it be that variable 49 is in use somewhere for something else?

**Comment by klauswyser** [comment]
The problem is that parameter 49 from table 128 (10m wind gust) is a special case, but the check tests only the parameter and not the table, therefore even 49.126 triggers the special case which then leads to failure. I have added a table check for this case in #755.

**Comment by treerink** [comment]
In 3ecb24e the situation for newly added MODIS pextra variables `47, 48 & 49` with `table 126` are fixed for the `genecec` side.
