### ISSUE TITLE
Wrong mask for tslsi?

### ISSUE THREAD

**Issue by plesager** [EC-Earth/ece2cmor3#750]
The tslsi (skin temperature over land and sea-ice only) seems incorrect. See discussion in https://dev.ec-earth.org/issues/1188#note-8. The correct grib code is picked up. Could you tell us which mask is being currently applied? Is land only or land+sea_ice?

**Comment by treerink** [comment]
According to the `ifspar.json` currently a `land` mask is applied.

**Comment by plesager** [comment]
Ok, thanks. A fix is needed to include sea-ice, but this is not as urgent as #744.

**Comment by treerink** [comment]
The `tslsi` mask is adjusted in the `issue-750-tslsi-mask` branch and can be tested. The `tr` is removed, because it was wrong and we cannot provide it correctly.

**Comment by treerink** [comment]
As far I trace back there are only `Eday` `tr` requests for `LSMIP`. So I will aim for taking up `Eday` `tr` in the ignore list at the `genecec` side.

**Comment by treerink** [comment]
Done, `land + sea-ice mask` looks now ok for `tslsi`. And `tr` has been removed.
