### ISSUE TITLE
pytest issues

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#751]
Two `pytest` tests fail in the `python-3.11` branch:

In test/nemo2cmor_test.py
- `test_cmor_single_task`
- `test_cmor_single_task3d`

And one deprecation warning:
```
${mambapath}/envs/ece2cmor3-python-3/lib/python3.11/site-packages/pkg_resources/__init__.py:121
  ${mambapath}/envs/ece2cmor3-python-3/lib/python3.11/site-packages/pkg_resources/__init__.py:121: DeprecationWarning: pkg_resources is deprecated as an API
    warnings.warn("pkg_resources is deprecated as an API", DeprecationWarning)
```
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html

**Comment by treerink** [comment]
With deactivating the two aforementioned pytests the pytest on the github platform succeed for the `python-3.11` branch. It means the rest is fine, but this issue needs a fix still.

**Comment by treerink** [comment]
Yes, thanks @zklaus  ! Obviously in the last 14 days the numpy version went from 1.23.5 to 1.24.2 in the conda-forge channel, and the cmor package takes numpy >=1.23.5 (so they should limit for cmor 3.7.1 numpy to >=1.23.5 and <1.24.

I have made a short test in which I have limited numpy <1.24 for ece2cmor3 for the python3.11 branch and this wnet fine again.

Ok, as soon I can take off the numpy limitation again because 'they' have fixed the dependency limits, I am eager to be updated on that!

**Comment by treerink** [comment]
The `numpy.float` & `numpy.int` aliases deprecation warnings remain until the changes (which have been made already in their repository) in the `CMOR` lib are in a next `CMOR 3.7.2` conda release:
```
test/nemo2cmor_test.py::nemo2cmor_tests::test_cmor_single_task3d
  ${mambapath}/envs/ece2cmor3/lib/python3.11/site-packages/cmor/pywrapper.py:539: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    numpy.float, numpy.float32, numpy.float64,

```
because they come from the `CMOR` `pywrapper.py.`

The rest is solved with the limitation to pin numpy < 1.24.

**Comment by zklaus** [comment]
The cmor issues are now fixed on conda-forge, see conda-forge/cmor-feedstock#59 and links therein, so you should be able to remove the pin in `environment.yml` again.

**Comment by treerink** [comment]
> The cmor issues are now fixed on conda-forge, see [conda-forge/cmor-feedstock#59](https://github.com/conda-forge/cmor-feedstock/issues/59) and links therein, so you should be able to remove the pin in `environment.yml` again.

Thanks, yes works fine now!
