### ISSUE TITLE
add cmorization of co2box model output

### ISSUE THREAD

**Issue by etiennesky** [EC-Earth/ece2cmor3#785]
I am starting to add support for co2box model output. As this model replaces TM5 CO2-only configuration, it outputs some variables already supported by tm5 : co2, co2s and co2mass.

**Comment by treerink** [comment]
See pull request #792.

**Comment by treerink** [comment]
Actually we face a same issue with _co2mass_ in table Amon for the co2box branch as in #801.

Test case:
```
 mkdir -p ${HOME}/cmorize/control-output-files/output-control-files-v536/cmip6/
 cd ${HOME}/cmorize/ece2cmor3/ece2cmor3/scripts/
 ./genecec-per-mip-experiment.sh ${HOME}/cmorize/control-output-files/output-control-files-v536/cmip6/ C4MIP 1pctCO2-bgc 1 1

 drq2varlist --drq cmip6-data-request/cmip6-data-request-C4MIP-1pctCO2-bgc-t1-p1/cmvme_C4MIP_1pctCO2-bgc_1_1.xlsx --ececonf EC-EARTH-CC --varlist ${HOME}/cmorize/control-output-files/output-control-files-v536/cmip6/C4MIP/cmip6-experiment-C4MIP-1pctCO2-bgc/cmip6-data-request-varlist-C4MIP-1pctCO2-bgc-EC-EARTH-CC.json
 convert_component_to_flat_json ${HOME}/cmorize/control-output-files/output-control-files-v536/cmip6/C4MIP/cmip6-experiment-C4MIP-1pctCO2-bgc/cmip6-data-request-varlist-C4MIP-1pctCO2-bgc-EC-EARTH-CC.json
 checkvars --asciionly -v --drq cmip6-data-request-varlist-C4MIP-1pctCO2-bgc-EC-EARTH-CC-flat.json --output ${HOME}/cmorize/control-output-files/output-control-files-v536/cmip6/C4MIP/cmip6-experiment-C4MIP-1pctCO2-bgc/request-overview
```

I run a test with a local modification in which the crash technically is solved and the results for the optimesm project are still good, but the the usual output-control-files for trunk are affected (and probably not fully correctly). This needs further tweaking and knowing our aim.

I think this is the last issue to be solved before the `co2box` branch can be merged into the master.

**Comment by treerink** [comment]
You can't, this are the minimalized test lines for a subtest to repeat the error and to quickly test a solution. I am busy with this.

Actually my question is what should I do with `Amon co2mass` in which situation: Clear, for the optimesm case with ECE3-CC (=> ECE3-ESM) the preference is set to the `co2box` component of ece2cmor. But in the regular output-control-files (in trunk) often `Amon co2mass` is assigned to the TM5 component for ECE3-CC and maybe other ECE configurations, I guess that should remain the same right? With my current locally tested solution it tuned out it now takes in all those cases the co2box component, so I have to modify this preference rule a bit.

So one of my questions is, in the original ECE3-CC, and other configurations, all should stay the same, this `co2box` model won't be included there?

Note, as soon we decide to call the new configuration `EC-Earth3-ESM`, this problem is very easy to solve ...

**Comment by treerink** [comment]
@etiennesky: From the [co2box wiki](https://dev.ec-earth.org/projects/ecearth3/wiki/CO2_box_model) I understand that the output of the `co2box` model is on the `3x2 degree TM5 grid`, so would this all apply for the co2box output as well:
```
    "grid":                         "native regular 2x3 degree latxlon grid L10",
    "grid_label":                   "gn",
    "nominal_resolution":           "250 km",
```
Also the layer L10 info is correct?

**Comment by etiennesky** [comment]
Hi @treerink sorry for the delay. I would say that going forward I would like to have co2box instead of tm5 for co2s and co2mass in EC-Earth3-CC as well as EC-Earth3-ESM.  But how hard can it be to manually set the preference to use tm5 instead, if someone want to run EC-Earth3-CC with ctm5 instead of co2box?

**Comment by etiennesky** [comment]
> @etiennesky: From the [co2box wiki](https://dev.ec-earth.org/projects/ecearth3/wiki/CO2_box_model) I understand that the output of the `co2box` model is on the `3x2 degree TM5 grid`, so would this all apply for the co2box output as well:
>
> ```
>     "grid":                         "native regular 2x3 degree latxlon grid L10",
>     "grid_label":                   "gn",
>     "nominal_resolution":           "250 km",
> ```
> 
> Also the layer L10 info is correct?

**Comment by treerink** [comment]
> > @etiennesky: From the [co2box wiki](https://dev.ec-earth.org/projects/ecearth3/wiki/CO2_box_model) I understand that the output of the `co2box` model is on the `3x2 degree TM5 grid`, so would this all apply for the co2box output as well:
> 
> sorry, perhaps there is a confusion in the wiki you posted. The EXCHANGES are done on the TM5 grid, but the actual co2box model itself is on a global point grid, and only one vertical level (the surface). So I am not sure that to put but this is NOT correct.. are there any examples of a point-grid in CMIP6 CV ?

Ok, so no vertical grid resolution, clear. Ok the rest requires some investigation. However, before I first planned to include a metadata template for the co2box component as well, but this is in the current state not ideal: I wait until we have registered the `EC-Earth3-ESM` configuration, else it becomes rather error prone.

**Comment by etiennesky** [comment]
> Ok, so no vertical grid resolution, clear. Ok the rest requires some investigation. However, before I first planned to include a metadata template for the co2box component as well, but this is in the current state not ideal: I wait until we have registered the `EC-Earth3-ESM` configuration, else it becomes rather error prone.

can you point me to a resources where all the possible resolutions are available ?

**Comment by etiennesky** [comment]
> can you point me to a resources where all the possible resolutions are available ?

I see there is nothing compatible in https://github.com/WCRP-CMIP/CMIP6_CVs/blob/main/CMIP6_nominal_resolution.json

Also, it seems that "none" is a valid key, but this is usually used when a realm is not used in a configuration, see CMIP6_source_id.json

**Comment by klauswyser** [comment]
There is some information about nominal resolution in the [CMIP6 attributes and DRS](https://docs.google.com/document/d/1h0r8RZr_f3-8egBMMh7aqLwy3snpD6_MrDz1q8n5XUk/edit#bookmark=id.ibeh7ad2gpdi) document.
