### ISSUE TITLE
error when processing mrro for lpjg

### ISSUE THREAD

**Issue by klauswyser** [EC-Earth/ece2cmor3#820]
While testing the cmorisation of the esm-piCOntrol experiment fro OptimESM I encountered a new error:
````
INFO:ece2cmor3.lpjg2cmor: Processing file /nobackup/rossby27/proj/optimesm/sm_wyser/ece-run/CD11/output/lpjg/001/mrro_daily.out
INFO:ece2cmor3.lpjg2cmor: Creating lpjg netcdf file for variable mrro for year 1850
/home/sm_wyser/cmorize/ece2cmor3/ece2cmor3/lpjg2cmor.py:498: RuntimeWarning: overflow encountered in cast
  variable[:] = np.where(dumvar < 1.e+20, dumvar, 0.)   # TODO: see out2nc for what to do here if you have the LPJG regular grid
Error in calling operator remapycon with:
>>> cdo -O -s -remapycon,n128 -setgrid,/home/sm_wyser/cmorize/ece2cmor3/ece2cmor3/resources/lpjg-grid-content/ingrid_T255_unstructured.txt /scratch/local/LPJGtemp.nc /scratch/local/mrro_day_1850.nc<<<
STDOUT:cdi  cdf_put_vara_double: name=mrro  type=NC_FLOAT  minval=-inf  maxval=0.001429
````
I did test cmorisation a few weeks ago and everything worked fine. There may have been changes in model output or data request, but I don't think so. I had to move to a new platform and this was the first cmorisation test. I updated ece2cmor, then installed a completely fresh mamab environment. I was able to successfully process ifs, nemo and the co2box model, but got this error from lpjg (tested different years of output, same same)

A usual suspect is cdo - I had problems with it before - but I explicietly unload all modules before activating the mamba env that includes cdo so I get the proper cdo from the environment.

Any idea?

Pinging @treerink and @nierad

**Comment by nierad** [comment]
@klauswyser This is the same LPJG-output error we have fixed earlier for other variables. There is an `-inf` in the output files which it shouldn't. Can we find the original output somewhere? Or could you make the `mrro_daily.out`-file available available?

**Comment by klauswyser** [comment]
Sure: /nobackup/rossby27/proj/optimesm/sm_wyser/ece-run/CD11/output/lpjg/001/mrro_daily.out

**Comment by nierad** [comment]
There are some NaNs in there. I will have a look and get back to you asap.

**Comment by nierad** [comment]
Great,  just found it myself. The bugfix was committed in r10110.
