### ISSUE TITLE
Add EC-Earth3-ESM-1

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#825]
Add the EC-Earth3-ESM-1 configuration.

See also [ECE portal issue 1312-226](https://dev.ec-earth.org/issues/1312#note-226).

**Comment by treerink** [comment]
Changes in the `add-esm-configuration` branch for both testing `genecec` & `ece2cmor3`.

**Comment by etiennesky** [comment]
Is there anything blocking the merge of this branch? It has been open for a few months and we are in the middle of production with this model version.

**Comment by etiennesky** [comment]
I think there is missing the required changes to modify ece2cmor3/scripts/modify-metadata-template.sh  ?

**Comment by treerink** [comment]
> I think there is missing the required changes to modify ece2cmor3/scripts/modify-metadata-template.sh ?

Yes, see 0bd5e26. Sorry this took so long.

**Comment by treerink** [comment]
I will start testing this branch with running `genecec` and see how well it goes and how many changes it gives.

For co2box I took: `grid_label = gn`  From [CMIP6_CVs /CMIP6_grid_label.json](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/main/CMIP6_grid_label.json) one could also consider `grid_label = gm`, but if I have the good understanding of the `co2box` model `gn` is most appropiate.

**Comment by treerink** [comment]
For the nominal resolution for the `co2box` model I took `10000 km` according to the general description in this [Appendix 2](https://docs.google.com/document/d/1h0r8RZr_f3-8egBMMh7aqLwy3snpD6_MrDz1q8n5XUk/edit)
`else 				nominal_resolution = “10000 km”`
But I fear for the CMIP6 case it will give trouble because [CMIP6_CVs/CMIP6_nominal_resolution.json](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/main/CMIP6_nominal_resolution.json) shows only this definition:
```
"nominal_resolution":[
        "0.5 km",
        "1 km",
        "10 km",
        "100 km",
        "1000 km",
        "10000 km",
        "1x1 degree",
        "2.5 km",
        "25 km",
        "250 km",
        "2500 km",
        "5 km",
        "50 km",
        "500 km",
        "5000 km"
    ],
```
and thus lacking the `10000 km` one.

**Comment by treerink** [comment]
I have added the PISM component for the metadata part already here, though the PISM cmorisation component is not implemented yet.

**Comment by etiennesky** [comment]
> I will start testing this branch with running `genecec` and see how well it goes and how many changes it gives.
> 
> For co2box I took: `grid_label = gn` From [CMIP6_CVs /CMIP6_grid_label.json](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/main/CMIP6_grid_label.json) one could also consider `grid_label = gm`, but if I have the good understanding of the `co2box` model `gn` is most appropiate.

the grid of the co2box moel is a global (0D) one, so it could be gm, but that means a processing from some spatial data to a global average, so gn is fine!

**Comment by etiennesky** [comment]
> For the nominal resolution for the `co2box` model (see also #785) I took `10000 km` according to the general description in this [Appendix 2](https://docs.google.com/document/d/1h0r8RZr_f3-8egBMMh7aqLwy3snpD6_MrDz1q8n5XUk/edit): `else nominal_resolution = “10000 km”`

thats is not quite exact since it's a global grid, but I don't think there is something that fits well, but this works because 

`else 				nominal_resolution = “10000 km” `

**Comment by klauswyser** [comment]
I processed many experiments for OptimESM, including output from the co2box model, always setting ``nominal_resolution = "10000 km"``. This worked well, no problem encountered.

**Comment by treerink** [comment]
PISM <=> PISCES ?
Pisces should be fine, I am talking about the ISM PISM ... (?)

**Comment by treerink** [comment]
So far I witness only expected changes with running the full `genecec`, so with a bit of luck I will merge this branch at the end of the day into the master.

**Comment by treerink** [comment]
Then I have to change from:
```
./genecec-for-individual-experiments.sh ../resources/miscellaneous-data-requests/optimesm-request/optimesm-request-EC-EARTH-CC-varlist.json        CMIP        historical               EC-EARTH-CC      optimesm
```
to
```
./genecec-for-individual-experiments.sh ../resources/miscellaneous-data-requests/optimesm-request/optimesm-request-EC-EARTH-ESM-1-varlist.json        CMIP        historical               EC-EARTH-ESM-1      optimesm
```
and see whether updating the optimism ECE output control files will go smooth or current manual commits have to be sorted out.

Other experiments to be added there? Or is the experiment naming still under discussion  - I lost the status on that.
Probably not so relevant and necessary because we use the same request everywhere. Only for the experiment metadata it matters, but one or the other way does not differ much in work (i.e. manually adjusting it in the current historical one).

**Comment by treerink** [comment]
I see Klaus that in [r10143](https://dev.ec-earth.org/projects/ecearth3/repository/revisions/10143) you chose in [metadata-*-co2box-template.json](https://dev.ec-earth.org/projects/ecearth3/repository/revisions/10143/entry/ecearth3/branches/projects/optimesm/runtime/classic/ctrl/output-control-files/optimesm/metadata-cmip6-CMIP-historical-EC-EARTH-ESM-co2box-template.json) `grid_label = gm` and for grid you used `box model` where I used `global grid` now from another suggestion. What should I do, keep what I have and overwrite the optimesm branch or adjust one or both cases such that it matches the current optimesm branch?

**Comment by treerink** [comment]
(the comment attribute you added I will take over)

**Comment by treerink** [comment]
For co2box grid I used now `global box model`.

**Comment by treerink** [comment]
Branch merged into master with #831

**Comment by treerink** [comment]
I just chose something which looked clear to me ;)

Same applies to `grid_label = gm` vs  `grid_label = gn`

I am fine with any choice, I just want to finish it :)

**Comment by klauswyser** [comment]
Sure, no problem. However, changing metadata violates backward compatibility, something we should avoid if not necessary. Several experiments and members from OptimESM have already been cmorised, so I suggest we stick with the metadata that we used there.

**Comment by treerink** [comment]
Adjusted in e5d732b
