### ISSUE TITLE
! Error: axis time has non monotonic values

### ISSUE THREAD

**Issue by vmeccia** [EC-Earth/ece2cmor3#826]
I am having problems to cmorize the outputs of ifs related to the time axis:

```
! Error: axis time (table: CFmon) has non monotonic values:
! 913.000000, 745.500000 and  775.500000
```

I am having this issue for different variables at different years in a random way. It seems that the responsible is the grib filtering, because after filtering, sometimes (it is not always happening), the data from January of the following year is put at the beginning of the file instead of at the end.

Did anybody have this problem before? Some tips to solve it?

**Comment by treerink** [comment]
I don't remember an issue which fits with your description. You are using the latest master of `ece2cmor3`? Which EC-Earth3 configuration, the AOGCM? With which variables for instance do you experience this issue? You say random, but if you repeat the cmorisation for the same years of the same variable, does the issue repeat at the same points, or is this also random? In other words is the issue easily reproducible given you grib output?

**Comment by vmeccia** [comment]
Many thanks for answering! I finally could cmorize everything after updating ece2cmor3 ;)
