### ISSUE TITLE
ece2cmor3 causes a "fatal: not a git repository (or any parent up to mount point /)" error when run outside of .../cmorize/ece2cmor3/

### ISSUE THREAD

**Issue by nierad** [EC-Earth/ece2cmor3#827]
Hi @treerink, 

When running ece2cmor3 outside of `.../cmorize/ece2cmor3/` I get the following error because I am not in the directory of the git-repo:

```shell
+ ece2cmor /proj/rescue/optimesm/run/OPr5/output/ifs/001 --exp OPr5 --varlist /proj/rescue/cmorisation/OPr5/optimesm-request-EC-EARTH-ESM-varlist.json --meta /proj/rescue/cmorisation/OPr5/metadata-cmip6-CMIP-historical-EC-EARTH-ESM-ifs-template.json --ececonf EC-EARTH3-VEG --ifs --tmpdir /tmp/cmorize/OPr5/ifs/001 --odir /proj/rescue/optimesm/cmorized/OPr5 --npp 32 --skip_alevel_vars --log
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Traceback (most recent call last):
  File "/home/x_larni/mamba/envs/ece2cmor3/bin/ece2cmor", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/x_larni/mamba/envs/ece2cmor3/lib/python3.11/site-packages/ece2cmor3/ece2cmor.py", line 106, in main
    ece2cmorlib.initialize(args.meta, mode=modedict[args.overwritemode], tabledir=args.tabledir,
  File "/home/x_larni/mamba/envs/ece2cmor3/lib/python3.11/site-packages/ece2cmor3/ece2cmorlib.py", line 85, in initialize
    log.info('ece2cmor3 version {} based on the {} branch'.format(__version__.version, get_git_branch_name()))
                                                                                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/x_larni/mamba/envs/ece2cmor3/lib/python3.11/site-packages/ece2cmor3/ece2cmorlib.py", line 53, in get_git_branch_name
    return subprocess.check_output(['git', 'rev-parse', '--abbrev-ref', 'HEAD']).decode('ascii').strip()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x_larni/mamba/envs/ece2cmor3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x_larni/mamba/envs/ece2cmor3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'rev-parse', '--abbrev-ref', 'HEAD']' returned non-zero exit status 128.
+ '[' 1 -ne 0 ']'
+ echo 'leg 001 for ifs of experiment OPr5 failed.'
leg 001 for ifs of experiment OPr5 failed.
+ exit -1

``` 

It runs when starting it inside the repo.
This change has only recently been made to [ece2cmorlib.py](https://github.com/EC-Earth/ece2cmor3/commit/ae2b16562e1186a513f1300126ffe62d1542c71f).

Not sure whether I made a mistake here or if I missed something.  
Thanks, Lars

**Comment by treerink** [comment]
hi @nierad with this change the exact git hash of the used version has been added to the metadata of the cmorised output in order to log as precisely as possible the ece2cmor3 status which is used (a good thing). Though I did not test it yet myself, it sounds logical that you fase this error when you are fully outside the git tree when starting `ece2cmor3`. Do you need to start outside the ece2cmor git tree, or you are just used to sometimes do so and sometimes not? The advantage of the current situation is that one can easily switch between two checkouts and no general `ece2cmor` root has to be set.

**Comment by nierad** [comment]
Hi @treerink, 
yes, it definitely is a good thing. It is just the way we set it up here in Lund, first of all the log files don't jam the repository and, because we have rather little /home/ allocations we tend to keep everything none-code outside. But, obviously, no-one else has this problem:) Just wanted to know, whether there is a good fix to it.  Happy to close this issue again:)

**Comment by treerink** [comment]
Hi Lars, and following the submit example like:
`~/cmorize/ece2cmor3/ece2cmor3/scripts/submit-script-examples/submit-at-hpc2020-ece2cmor-leg-job-test-all.sh`
in which as soon one cmorise job is finished the log files are moved to a log dir in the output dir, would that be sufficient to stay clean and within bounds?

**Comment by nierad** [comment]
Hi Thomas,

I use that already, thanks. It was just the old habit. I'll close the issue😉
________________________________
Von: Thomas Reerink ***@***.***>
Gesendet: Freitag, 16. August 2024 15:14
An: EC-Earth/ece2cmor3 ***@***.***>
Cc: Lars Nieradzik ***@***.***>; Mention ***@***.***>
Betreff: Re: [EC-Earth/ece2cmor3] ece2cmor3 causes a "fatal: not a git repository (or any parent up to mount point /)" error when run outside of .../cmorize/ece2cmor3/ (Issue #827)


Hi Lars, and following the submit example like:
~/cmorize/ece2cmor3/ece2cmor3/scripts/submit-script-examples/submit-at-hpc2020-ece2cmor-leg-job-test-all.sh
in which as soon one cmorise job is finished the log files are moved to a log dir in the output dir, would that be sufficient to stay clean and within bounds?
